Composition {
	CurrentTime = 24,
	RenderRange = { 0, 64 },
	GlobalRange = { 0, 64 },
	CurrentID = 4019,
	HiQ = true,
	Proxy = true,
	PlaybackUpdateMode = 0,
	Version = "Fusion Studio 8.2.1 build 6",
	SavedOutputs = 2,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	Resumable = true,
	OutputClips = {
	},
	Tools = {
		CookTorrance1 = MtlCookTorrance {
			Inputs = {
				MaterialIDNest = Input { Value = 1, },
				MaterialID = Input { Value = 6, },
			},
			ViewInfo = OperatorInfo { Pos = { 55, 115.5 } },
		},
		FBXMesh3D1 = SurfaceFBXMesh {
			CtrlWZoom = false,
			Inputs = {
				ImportFile = Input { Value = "Macros:\\KartaVR\\Images\\boxworld.fbx", },
				TransformToWorld = Input { Value = 0, },
				["ObjectID.Nest"] = Input { Value = 1, },
				["ObjectID.ObjectID"] = Input { Value = 4, },
				MaterialInput = Input {
					SourceOp = "CookTorrance1",
					Source = "MaterialOutput",
				},
				["MtlStdInputs.MaterialID"] = Input { Value = 5, },
			},
			ViewInfo = OperatorInfo { Pos = { 165, 115.5 } },
		},
		WarmDirectionalLight = LightDirectional {
			NameSet = true,
			Inputs = {
				["Transform3DOp.Translate.X"] = Input { Value = -37, },
				["Transform3DOp.Translate.Y"] = Input { Value = 96, },
				["Transform3DOp.Translate.Z"] = Input { Value = -27, },
				["Transform3DOp.Rotate.X"] = Input { Value = 58.1650225943886, },
				["Transform3DOp.Rotate.Y"] = Input { Value = -64.8353715026751, },
				["Transform3DOp.Rotate.Z"] = Input { Value = -91.4079946666025, },
				Green = Input { Value = 0.925490196078431, },
				Blue = Input { Value = 0.776470588235294, },
				Intensity = Input { Value = 0.8, },
			},
			ViewInfo = OperatorInfo { Pos = { 165, 148.5 } },
		},
		CoolDirectionalLight = LightDirectional {
			NameSet = true,
			Inputs = {
				["Transform3DOp.Translate.X"] = Input { Value = 58.3879784519737, },
				["Transform3DOp.Translate.Y"] = Input { Value = 95.1104338268553, },
				["Transform3DOp.Translate.Z"] = Input { Value = -26.3166398889364, },
				["Transform3DOp.Rotate.X"] = Input { Value = 137.656114007812, },
				["Transform3DOp.Rotate.Y"] = Input { Value = 31.7768835327588, },
				["Transform3DOp.Rotate.Z"] = Input { Value = 130.256588513497, },
				Red = Input { Value = 0.811764705882353, },
				Green = Input { Value = 0.917647058823529, },
				Intensity = Input { Value = 0.8, },
			},
			ViewInfo = OperatorInfo { Pos = { 165, 181.5 } },
		},
		PointLight1 = LightPoint {
			Inputs = {
				["Transform3DOp.Translate.X"] = Input { Value = -161.856563476427, },
				["Transform3DOp.Translate.Y"] = Input { Value = 347.254927143773, },
				["Transform3DOp.Translate.Z"] = Input { Value = -32.0346642872779, },
				Intensity = Input { Value = 0.243373493975904, },
				DecayRate = Input { Value = 25000, },
			},
			ViewInfo = OperatorInfo { Pos = { 165, 214.5 } },
		},
		LightMerge3D = Merge3D {
			NameSet = true,
			Inputs = {
				PassThroughLights = Input { Value = 1, },
				SceneInput1 = Input {
					SourceOp = "FBXMesh3D1",
					Source = "Output",
				},
				SceneInput2 = Input {
					SourceOp = "WarmDirectionalLight",
					Source = "Output",
				},
				SceneInput3 = Input {
					SourceOp = "CoolDirectionalLight",
					Source = "Output",
				},
				SceneInput4 = Input {
					SourceOp = "PointLight1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 275, 181.5 } },
		},
		SkyGradient = Background {
			NameSet = true,
			Inputs = {
				GlobalOut = Input { Value = 64, },
				Width = Input { Value = 640, },
				Height = Input { Value = 640, },
				Depth = Input { Value = 4, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Type = Input { Value = FuID { "Vertical" }, },
				TopLeftRed = Input { Value = 0.16078431372549, },
				TopLeftGreen = Input { Value = 0.294117647058824, },
				TopLeftBlue = Input { Value = 0.423529411764706, },
				BottomLeftRed = Input { Value = 0.858823529411765, },
				BottomLeftGreen = Input { Value = 0.882352941176471, },
				BottomLeftBlue = Input { Value = 0.898039215686275, },
				Gradient = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 55, 49.5 } },
		},
		SkyMirrorTransform = Transform {
			NameSet = true,
			Inputs = {
				Center = Input { Value = { 0.5, 0.9 }, },
				Pivot = Input { Value = { 0.5, 0 }, },
				UseSizeAndAspect = Input { Value = 0, },
				YSize = Input { Value = 0.6, },
				Edges = Input { Value = 3, },
				Input = Input {
					SourceOp = "SkyGradient",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 165, 49.5 } },
		},
		SkyWard = MtlWard {
			NameSet = true,
			Inputs = {
				["Diffuse.Color.Material"] = Input {
					SourceOp = "SkyMirrorTransform",
					Source = "Output",
				},
				["Specular.Nest"] = Input { Value = 1, },
				["Specular.Intensity"] = Input { Value = 0, },
				["Transmittance.Nest"] = Input { Value = 1, },
				ReceivesLighting = Input { Value = 0, },
				ReceivesShadows = Input { Value = 0, },
				MaterialIDNest = Input { Value = 1, },
				MaterialID = Input { Value = 7, },
			},
			ViewInfo = OperatorInfo { Pos = { 275, 49.5 } },
		},
		SkyEnvrionment = Shape3D {
			NameSet = true,
			Inputs = {
				["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 2, },
				Shape = Input { Value = FuID { "SurfaceSphereInputs" }, },
				MaterialInput = Input {
					SourceOp = "SkyWard",
					Source = "MaterialOutput",
				},
				["MtlStdInputs.Diffuse.Color.Red"] = Input { Value = 0.141728395061728, },
				["MtlStdInputs.Diffuse.Color.Green"] = Input { Value = 0.262716049382716, },
				["MtlStdInputs.Diffuse.Color.Blue"] = Input { Value = 0.373333333333333, },
				["MtlStdInputs.MaterialID"] = Input { Value = 4, },
				["SurfaceSphereInputs.Radius"] = Input { Value = 400, },
				["SurfaceSphereInputs.Lighting.Nest"] = Input { Value = 1, },
				["SurfaceSphereInputs.Lighting.IsAffectedByLights"] = Input { Value = 0, },
				["SurfaceSphereInputs.ObjectID.Nest"] = Input { Value = 1, },
				["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 5, }
			},
			ViewInfo = OperatorInfo { Pos = { 440, 49.5 } },
		},
		SkyMerge3D = Merge3D {
			NameSet = true,
			Inputs = {
				["Transform3DOp.Translate.X"] = Input { Value = 8.63457423928764, },
				["Transform3DOp.Translate.Y"] = Input { Value = 32.5640361436439, },
				["Transform3DOp.Translate.Z"] = Input { Value = -18.7989914433103, },
				PassThroughLights = Input { Value = 1, },
				SceneInput1 = Input {
					SourceOp = "LightMerge3D",
					Source = "Output",
				},
				SceneInput2 = Input {
					SourceOp = "SkyEnvrionment",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 440, 181.5 } },
		},
		Transform3D1 = Transform3D {
			Inputs = {
				SceneInput = Input {
					SourceOp = "SkyMerge3D",
					Source = "Output",
				},
				["Transform3DOp.Translate.X"] = Input {
					SourceOp = "Transform3D1XOffset",
					Source = "Value",
				},
				["Transform3DOp.Translate.Y"] = Input {
					SourceOp = "Transform3D1YOffset",
					Source = "Value",
				},
				["Transform3DOp.Translate.Z"] = Input {
					SourceOp = "Transform3D1ZOffset",
					Source = "Value",
				},
				["Transform3DOp.Rotate.X"] = Input {
					SourceOp = "Transform3D1XRotation",
					Source = "Value",
				},
				["Transform3DOp.Rotate.Y"] = Input {
					SourceOp = "Transform3D1YRotation",
					Source = "Value",
				},
				["Transform3DOp.InvertTransform"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 660, 181.5 } },
		},
		Transform3D1XOffset = BezierSpline {
			SplineColor = { Red = 250, Green = 59, Blue = 49 },
			NameSet = true,
			KeyFrames = {
				[0] = { 0, RH = { 21.3333333333333, 0 }, Flags = { Linear = true } },
				[64] = { 0, LH = { 42.6666666666667, 0 }, Flags = { Linear = true } }
			}
		},
		Transform3D1YOffset = BezierSpline {
			SplineColor = { Red = 252, Green = 131, Blue = 47 },
			NameSet = true,
			KeyFrames = {
				[0] = { 54, RH = { 21.3333333333333, 54 }, Flags = { Linear = true } },
				[64] = { 54, LH = { 42.6666666666667, 54 }, Flags = { Linear = true } }
			}
		},
		Transform3D1ZOffset = BezierSpline {
			SplineColor = { Red = 254, Green = 207, Blue = 46 },
			NameSet = true,
			KeyFrames = {
				[0] = { -44, RH = { 21.3333333333333, -68.2239185666667 }, Flags = { Linear = true } },
				[64] = { -116.6717557, LH = { 42.6666666666667, -92.4478371333333 }, Flags = { Linear = true } }
			}
		},
		Transform3D1XRotation = BezierSpline {
			SplineColor = { Red = 255, Green = 128, Blue = 128 },
			NameSet = true,
			KeyFrames = {
				[0] = { 90, RH = { 21.3333333333333, 90 }, Flags = { Linear = true } },
				[64] = { 90, LH = { 42.6666666666667, 90 }, Flags = { Linear = true } }
			}
		},
		Transform3D1YRotation = BezierSpline {
			SplineColor = { Red = 128, Green = 255, Blue = 128 },
			NameSet = true,
			KeyFrames = {
				[0] = { 180, RH = { 21.3333333333333, 180 }, Flags = { Linear = true } },
				[64] = { 180, LH = { 42.6666666666667, 180 }, Flags = { Linear = true } }
			}
		},
		Z360Stereo = GroupOperator {
			CtrlWZoom = false,
			NameSet = true,
			CustomData = {
				HelpPage = "http://www.andrewhazelden.com/projects/kartavr/docs/macros-guide-z360.html#Z360Stereo",
			},
			Inputs = ordered() {
				MainInput1 = InstanceInput {
					SourceOp = "PanoMerge",
					Source = "Background",
				},
				Input1 = InstanceInput {
					SourceOp = "StereoDisplaceRight",
					Source = "XChannel",
					Name = "Depth Input Channel",
					Default = 4,
				},
				Input2 = InstanceInput {
					SourceOp = "StereoDisplaceRight",
					Source = "XOffset",
					Name = "Stereo Displace Convergence",
					MinScale = -2,
					MaxScale = -2,
					Default = 0,
				},
				Input3 = InstanceInput {
					SourceOp = "StereoDisplaceRight",
					Source = "XRefraction",
					Name = "Stereo Depth Displacement",
					Default = -0.003,
				},
				Input4 = InstanceInput {
					SourceOp = "CustomToolOffsetControl",
					Source = "NumberIn1",
					Default = 0.495,
				},
				Input5 = InstanceInput {
					SourceOp = "DepthBlur",
					Source = "Filter",
					Name = "ZDepth - Blur Filter",
				},
				Input6 = InstanceInput {
					SourceOp = "DepthBlur",
					Source = "XBlurSize",
					Name = "ZDepth - Blur Size",
					Default = 8,
				},
				Input7 = InstanceInput {
					SourceOp = "ZDepthColorCorrector",
					Source = "MasterRGBContrast",
					Name = "ZDepth - Contrast",
					Default = 1,
				},
				Input8 = InstanceInput {
					SourceOp = "ZDepthColorCorrector",
					Source = "MasterRGBGain",
					Name = "ZDepth - Gain",
					Default = 1,
				},
				Input9 = InstanceInput {
					SourceOp = "ZDepthColorCorrector",
					Source = "MasterRGBLift",
					Name = "ZDepth - Lift",
					Default = 0,
				},
				Input10 = InstanceInput {
					SourceOp = "ZDepthColorCorrector",
					Source = "MasterRGBGamma",
					Name = "ZDepth - Gamma",
					Default = 0.6,
				},
				Input11 = InstanceInput {
					SourceOp = "RGBColorCorrector",
					Source = "Saturation1",
					Name = "RGB - Saturation",
					Default = 1,
				},
				Input12 = InstanceInput {
					SourceOp = "RGBColorCorrector",
					Source = "MasterRGBContrast",
					Name = "RGB - Contrast",
					Default = 1,
				},
				Input13 = InstanceInput {
					SourceOp = "RGBColorCorrector",
					Source = "MasterRGBGain",
					Name = "RGB - Gain",
					Default = 1,
				},
				Input14 = InstanceInput {
					SourceOp = "RGBColorCorrector",
					Source = "MasterRGBLift",
					Name = "RGB - Lift",
					Default = 0,
				},
				Input15 = InstanceInput {
					SourceOp = "RGBColorCorrector",
					Source = "MasterRGBGamma",
					Name = "RGB - Gamma",
					Default = 1,
				},
				Input16 = InstanceInput {
					SourceOp = "SetMetadataStereoMethod",
					Source = "EnableStereoMetadata",
					Page = "Controls",
				}
			},
			Outputs = {
				MainOutput1 = InstanceOutput {
					SourceOp = "SetMetadataStereoMethod",
					Source = "Output",
				}
			},
			ViewInfo = GroupInfo {
				Pos = { 990, 181.5 },
				Flags = {
					AllowPan = false,
					AutoSnap = true,
					RemoveRouters = true
				},
				Size = { 3041, 1055.2, 1520.5, 22 },
				Direction = "Horizontal",
				PipeStyle = "Direct",
				Scale = 1,
				Offset = { -134.73, 0 }
			},
			Tools = ordered() {
				ViewTransformLeft_1 = Transform {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Center = Input { Value = { 0.5, 1.5 }, },
						Input = Input {
							SourceOp = "SlideTransformLeft",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 1182.5, 769.6 } },
				},
				SlideTransformLeft = Transform {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Center = Input {
							Value = { 0, 0 },
							Expression = "Point(-CustomToolOffsetControl.NumberIn1, 0.5)",
						},
						Edges = Input { Value = 1, },
						FilterMethod = Input { Value = 6, },
						Input = Input {
							SourceOp = "CanvasShrink",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 1017.5, 769.6 } },
				},
				CanvasShrink = Crop {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						XOffset = Input {
							Value = 3840,
							Expression = "PanoMerge.Background.OriginalWidth",
						},
						XSize = Input {
							Value = 3840,
							Expression = "PanoMerge.Background.OriginalWidth",
						},
						YSize = Input {
							Value = 1920,
							Expression = "PanoMerge.Background.OriginalHeight/2",
						},
						Input = Input {
							SourceOp = "StereoDisplaceLeft",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 467.5, 769.6 } },
				},
				StereoDisplaceLeft = Displace {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Type = Input { Value = 1, },
						XChannel = Input {
							Value = 4,
							Expression = "StereoDisplaceRight.XChannel",
						},
						XOffset = Input { Expression = "StereoDisplaceRight.XOffset", },
						XRefraction = Input {
							Value = 0.003,
							Expression = "-StereoDisplaceRight.XRefraction",
						},
						YChannel = Input { Value = 4, },
						Input = Input {
							SourceOp = "Instance_ImageCanvasCrop",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "Instance_DepthBlur",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 357.5, 769.6 } },
				},
				Instance_DepthBlur = Blur {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "DepthBlur",
					Inputs = {
						Input = Input {
							SourceOp = "Instance_CanvasExpand",
							Source = "Output",
						},
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { 192.5, 769.6 } },
				},
				OverUnderCrop_1 = Crop {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						XSize = Input {
							Value = 3840,
							Expression = "PanoMerge.Background.OriginalWidth",
						},
						YSize = Input {
							Value = 3840,
							Expression = "PanoMerge.Background.OriginalHeight",
						},
						Input = Input {
							SourceOp = "ViewMerge_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 1457.5, 439.6 } },
				},
				ViewMerge_1 = Merge {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Background = Input {
							SourceOp = "ViewTransformLeft_1",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "ViewTransformRight_1",
							Source = "Output",
						},
						PerformDepthMerge = Input { Value = 0, },
					},
					ViewInfo = OperatorInfo { Pos = { 1182.5, 439.6 } },
				},
				Instance_CanvasExpand = Crop {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CanvasExpand",
					Inputs = {
						XOffset = Input {
							Value = -3840,
							Expression = "-PanoMerge.Background.OriginalWidth"
						},
						XSize = Input {
							Value = 11520,
							Expression = "PanoMerge.Background.OriginalWidth*3"
						},
						YSize = Input {
							Value = 1920,
							Expression = "PanoMerge.Background.OriginalHeight/2"
						},
						ResetSize = Input { },
						ResetOffset = Input { },
						Input = Input {
							SourceOp = "Instance_RightMerge",
							Source = "Output",
						},
						AutoCrop = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 769.6 } },
				},
				Instance_ImageCanvasCrop = Crop {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Instance_CanvasExpand",
					Inputs = {
						XOffset = Input {
							Value = -3840,
							Expression = "-PanoMerge.Background.OriginalWidth"
						},
						XSize = Input {
							Value = 11520,
							Expression = "PanoMerge.Background.OriginalWidth*3"
						},
						YSize = Input {
							Value = 1920,
							Expression = "PanoMerge.Background.OriginalHeight/2"
						},
						ResetSize = Input { },
						ResetOffset = Input { },
						Input = Input {
							SourceOp = "Instance_ImageRightMerge",
							Source = "Output",
						},
						AutoCrop = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 1000.6 } },
				},
				Instance_ImageLeftMerge = Merge {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Instance_LeftMerge",
					Inputs = {
						Background = Input {
							SourceOp = "Instance_ImagePipeRouter3",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "Instance_PipeRouter1",
							Source = "Output",
						},
						ReferenceSize = Input { Value = 1, },
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 934.6 } },
				},
				Instance_ImageRightMerge = Merge {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Instance_RightMerge",
					Inputs = {
						Background = Input {
							SourceOp = "Instance_ImageRightTransform",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "Instance_ImageLeftMerge",
							Source = "Output",
						},
						ReferenceSize = Input { Value = 1, },
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 1000.6 } },
				},
				ImageCanvasCrop = Crop {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CanvasExpand",
					Inputs = {
						XOffset = Input {
							Value = -3840,
							Expression = "-PanoMerge.Background.OriginalWidth"
						},
						XSize = Input {
							Value = 11520,
							Expression = "PanoMerge.Background.OriginalWidth*3"
						},
						YSize = Input {
							Value = 1920,
							Expression = "PanoMerge.Background.OriginalHeight/2"
						},
						ResetSize = Input { },
						ResetOffset = Input { },
						Input = Input {
							SourceOp = "ImageRightMerge",
							Source = "Output",
						},
						AutoCrop = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 373.6 } },
				},
				Instance_LeftMerge = Merge {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "LeftMerge",
					Inputs = {
						Background = Input {
							SourceOp = "Instance_DepthPipeRouter3",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "PipeRouter2",
							Source = "Output",
						},
						ReferenceSize = Input { Value = 1, },
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 703.6 } },
				},
				ImageRightMerge = Merge {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "RightMerge",
					Inputs = {
						Background = Input {
							SourceOp = "ImageRightTransform",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "ImageLeftMerge",
							Source = "Output",
						},
						ReferenceSize = Input { Value = 1, },
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 373.6 } },
				},
				Instance_RightMerge = Merge {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "RightMerge",
					Inputs = {
						Background = Input {
							SourceOp = "Instance_RightTransform",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "Instance_LeftMerge",
							Source = "Output",
						},
						ReferenceSize = Input { Value = 1, },
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 769.6 } },
				},
				ImagePipeRouterLeft = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "ImageCanvasCrop",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 357.5, 373.6 } },
				},
				Instance_DepthPipeRouter3 = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "DepthPipeRouter3",
					Inputs = {
						Input = Input {
							SourceOp = "Instance_LeftTransform",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -27.5, 637.6 } },
				},
				Instance_ImagePipeRouter3 = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Instance_DepthPipeRouter3",
					Inputs = {
						Input = Input {
							SourceOp = "Instance_ImageLeftTransform",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -27.5, 868.6 } },
				},
				ImageLeftMerge = Merge {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "LeftMerge",
					Inputs = {
						Background = Input {
							SourceOp = "ImagePipeRouter3",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "PipeRouter1Left",
							Source = "Output",
						},
						ReferenceSize = Input { Value = 1, },
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 307.6 } },
				},
				Instance_LeftTransform = Transform {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "LeftTransform",
					Inputs = {
						ReferenceSize = Input { },
						Input = Input {
							SourceOp = "Instance_DepthPipeRouter1",
							Source = "Output",
						},
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { -247.5, 637.6 } },
				},
				Instance_ImageRightTransform = Transform {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Instance_RightTransform",
					Inputs = {
						ReferenceSize = Input { },
						Input = Input {
							SourceOp = "Instance_ImagePipeRouter2",
							Source = "Output",
						},
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { -247.5, 1000.6 } },
				},
				ImageRightTransform = Transform {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "RightTransform",
					Inputs = {
						ReferenceSize = Input { },
						Input = Input {
							SourceOp = "ImagePipeRouter2",
							Source = "Output",
						},
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { -247.5, 373.6 } },
				},
				Instance_RightTransform = Transform {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "RightTransform",
					Inputs = {
						ReferenceSize = Input { },
						Input = Input {
							SourceOp = "Instance_DepthPipeRouter2",
							Source = "Output",
						},
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { -247.5, 769.6 } },
				},
				Instance_ImageLeftTransform = Transform {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Instance_LeftTransform",
					Inputs = {
						ReferenceSize = Input { },
						Input = Input {
							SourceOp = "Instance_ImagePipeRouter1",
							Source = "Output",
						},
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { -247.5, 868.6 } },
				},
				ImageLeftTransform = Transform {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "LeftTransform",
					Inputs = {
						ReferenceSize = Input { },
						Input = Input {
							SourceOp = "ImagePipeRouter1",
							Source = "Output",
						},
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { -247.5, 241.6 } },
				},
				ImagePipeRouter3 = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "DepthPipeRouter3",
					Inputs = {
						Input = Input {
							SourceOp = "ImageLeftTransform",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -27.5, 241.6 } },
				},
				Instance_DepthPipeRouter2 = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "DepthPipeRouter2",
					Inputs = {
						Input = Input {
							SourceOp = "PipeRouter2",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -467.5, 769.6 } },
				},
				ImagePipeRouter1 = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "DepthPipeRouter1",
					Inputs = {
						Input = Input {
							SourceOp = "PipeRouter1Left",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -467.5, 241.6 } },
				},
				Instance_ImagePipeRouter2 = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Instance_DepthPipeRouter2",
					Inputs = {
						Input = Input {
							SourceOp = "Instance_PipeRouter1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -467.5, 1000.6 } },
				},
				Instance_DepthPipeRouter1 = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "DepthPipeRouter1",
					Inputs = {
						Input = Input {
							SourceOp = "PipeRouter2",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -467.5, 637.6 } },
				},
				ImagePipeRouter2 = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "DepthPipeRouter2",
					Inputs = {
						Input = Input {
							SourceOp = "PipeRouter1Left",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -467.5, 373.6 } },
				},
				Instance_ImagePipeRouter1 = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Instance_DepthPipeRouter1",
					Inputs = {
						Input = Input {
							SourceOp = "Instance_PipeRouter1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -467.5, 868.6 } },
				},
				PipeRouter2 = PipeRouter {
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "ZDepthColorCorrector",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -577.5, 703.6 } },
				},
				ViewTransformRight_1 = Transform {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "SlideTransformRight",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 1182.5, 142.6 } },
				},
				SlideTransformRight = Transform {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Center = Input {
							Value = { 0.495, 0.5 },
							Expression = "Point(CustomToolOffsetControl.NumberIn1, 0.5)",
						},
						Edges = Input { Value = 1, },
						FilterMethod = Input { Value = 6, },
						Input = Input {
							SourceOp = "CanvasShrink_2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 1017.5, 142.6 } },
				},
				CanvasShrink_2 = Crop {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						XOffset = Input {
							Value = 3840,
							Expression = "PanoMerge.Background.OriginalWidth",
						},
						XSize = Input {
							Value = 3840,
							Expression = "PanoMerge.Background.OriginalWidth",
						},
						YSize = Input {
							Value = 1920,
							Expression = "PanoMerge.Background.OriginalHeight/2",
						},
						Input = Input {
							SourceOp = "StereoDisplaceRight",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 467.5, 142.6 } },
				},
				StereoDisplaceRight = Displace {
					CtrlWShown = false,
					NameSet = true,
					CurrentSettings = 2,
					CustomData = {
						Settings = {
							[1] = {
								Tools = ordered() {
									StereoDisplaceRight = Displace {
										Inputs = {
											YChannel = Input { Value = 4 },
											Type = Input { Value = 1 },
											Input = Input {
												SourceOp = "ImagePipeRouterLeft",
												Source = "Output"
											},
											Foreground = Input {
												SourceOp = "DepthBlur",
												Source = "Output"
											},
											XChannel = Input { Value = 4 }
										},
										CtrlWZoom = false,
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 4290, 1732.5 } },
										CustomData = {
										}
									}
								}
							}
						}
					},
					Inputs = {
						Type = Input { Value = 1, },
						XChannel = Input { Value = 4, },
						XRefraction = Input { Value = -0.003, },
						YChannel = Input { Value = 4, },
						Input = Input {
							SourceOp = "ImagePipeRouterLeft",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "DepthBlur",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 357.5, 142.6 } },
				},
				DepthBlur = Blur {
					CtrlWShown = false,
					NameSet = true,
					CurrentSettings = 2,
					CustomData = {
						Settings = {
							[1] = {
								Tools = ordered() {
									DepthBlur = Blur {
										Inputs = {
											XBlurSize = Input { Value = 0 },
											Input = Input {
												SourceOp = "CanvasExpand",
												Source = "Output"
											}
										},
										CtrlWZoom = false,
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 4125, 1732.5 } },
										CustomData = {
										}
									}
								}
							}
						}
					},
					Inputs = {
						XBlurSize = Input { Value = 8, },
						Input = Input {
							SourceOp = "CanvasExpand",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 192.5, 142.6 } },
				},
				RightMerge = Merge {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Background = Input {
							SourceOp = "RightTransform",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "LeftMerge",
							Source = "Output",
						},
						PerformDepthMerge = Input { Value = 0, },
						ReferenceSize = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 142.6 } },
				},
				CanvasExpand = Crop {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						XOffset = Input {
							Value = -3840,
							Expression = "-PanoMerge.Background.OriginalWidth",
						},
						XSize = Input {
							Value = 11520,
							Expression = "PanoMerge.Background.OriginalWidth*3",
						},
						YSize = Input {
							Value = 1920,
							Expression = "PanoMerge.Background.OriginalHeight/2",
						},
						Input = Input {
							SourceOp = "RightMerge",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 142.6 } },
				},
				RightTransform = Transform {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Center = Input { Value = { 1.5, 0.5 }, },
						Input = Input {
							SourceOp = "DepthPipeRouter2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -247.5, 142.6 } },
				},
				Instance_PipeRouter1 = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "PipeRouter1Left",
					Inputs = {
						Input = Input {
							SourceOp = "RGBColorCorrector",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -632.5, 934.6 } },
				},
				PipeRouter1Left = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "RGBColorCorrector",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -632.5, 307.6 } },
				},
				DepthPipeRouter2 = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "PipeRouter1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -467.5, 142.6 } },
				},
				ZDepthColorCorrector = ColorCorrector {
					CtrlWShown = false,
					NameSet = true,
					CurrentSettings = 2,
					CustomData = {
						Settings = {
							[1] = {
								Tools = ordered() {
									ZDepthColorCorrector = ColorCorrector {
										Inputs = {
											HistogramIgnoreTransparent = Input { Value = 1 },
											ColorRanges = Input {
												Value = ColorCurves {
													Curves = {
														{
															Points = {
																{ 0, 1 },
																{ 0.4, 0.2 },
																{ 0.6, 0 },
																{ 1, 0 }
															}
														},
														{
															Points = {
																{ 0, 0 },
																{ 0.4, 0 },
																{ 0.6, 0.2 },
																{ 1, 1 }
															}
														}
													}
												}
											},
											Input = Input {
												SourceOp = "RGBCropTop",
												Source = "Output"
											}
										},
										CtrlWZoom = false,
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 2805, 2293.5 } },
										CustomData = {
										}
									}
								}
							}
						}
					},
					Inputs = {
						MasterRGBGamma = Input { Value = 0.6, },
						ColorRanges = Input {
							Value = ColorCurves {
								Curves = {
									{
										Points = {
											{ 0, 1 },
											{ 0.4, 0.2 },
											{ 0.6, 0 },
											{ 1, 0 }
										}
									},
									{
										Points = {
											{ 0, 0 },
											{ 0.4, 0 },
											{ 0.6, 0.2 },
											{ 1, 1 }
										}
									}
								}
							},
						},
						PreDividePostMultiply = Input { Value = 1, },
						HistogramIgnoreTransparent = Input { Value = 1, },
						Input = Input {
							SourceOp = "RGBCropTop",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -1127.5, 703.6 } },
				},
				RGBColorCorrector = ColorCorrector {
					CtrlWShown = false,
					NameSet = true,
					CustomData = {
						Settings = {
							[1] = {
								Tools = ordered() {
									RGBColorCorrector = ColorCorrector {
										Inputs = {
											WheelSaturation1 = Input { Value = 1.3 },
											ColorRanges = Input {
												Value = ColorCurves {
													Curves = {
														{
															Points = {
																{ 0, 1 },
																{ 0.4, 0.2 },
																{ 0.6, 0 },
																{ 1, 0 }
															}
														},
														{
															Points = {
																{ 0, 0 },
																{ 0.4, 0 },
																{ 0.6, 0.2 },
																{ 1, 1 }
															}
														}
													}
												}
											},
											HistogramIgnoreTransparent = Input { Value = 1 },
											Input = Input {
												SourceOp = "ZDepthCropBottom",
												Source = "Output"
											}
										},
										Name = "RGBColorCorrector",
										CtrlWZoom = false,
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 2805, 1897.5 } },
										CustomData = {
										}
									}
								}
							},
							[2] = {
								Tools = ordered() {
									RGBColorCorrector = ColorCorrector {
										Inputs = {
											WheelSaturation1 = Input { Value = 1.3 },
											ColorRanges = Input {
												Value = ColorCurves {
													Curves = {
														{
															Points = {
																{ 0, 1 },
																{ 0.4, 0.2 },
																{ 0.6, 0 },
																{ 1, 0 }
															}
														},
														{
															Points = {
																{ 0, 0 },
																{ 0.4, 0 },
																{ 0.6, 0.2 },
																{ 1, 1 }
															}
														}
													}
												}
											},
											HistogramIgnoreTransparent = Input { Value = 1 },
											Input = Input {
												SourceOp = "ZDepthCropBottom",
												Source = "Output"
											}
										},
										CtrlWZoom = false,
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 2805, 1897.5 } },
										CustomData = {
										}
									}
								}
							}
						}
					},
					Inputs = {
						ColorRanges = Input {
							Value = ColorCurves {
								Curves = {
									{
										Points = {
											{ 0, 1 },
											{ 0.4, 0.2 },
											{ 0.6, 0 },
											{ 1, 0 }
										}
									},
									{
										Points = {
											{ 0, 0 },
											{ 0.4, 0 },
											{ 0.6, 0.2 },
											{ 1, 1 }
										}
									}
								}
							},
						},
						PreDividePostMultiply = Input { Value = 1, },
						HistogramIgnoreTransparent = Input { Value = 1, },
						Input = Input {
							SourceOp = "ZDepthCropBottom",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -1127.5, 307.6 } },
				},
				RGBCropTop = Crop {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						XSize = Input {
							Value = 3840,
							Expression = "PanoMerge.Background.OriginalWidth",
						},
						YSize = Input {
							Value = 1920,
							Expression = "PanoMerge.Background.OriginalHeight/2",
						},
						Input = Input {
							SourceOp = "PipeRouter3_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -1292.5, 703.6 } },
				},
				ZDepthCropBottom = Crop {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						YOffset = Input {
							Value = 1920,
							Expression = "PanoMerge.Background.OriginalHeight/2",
						},
						XSize = Input {
							Value = 3840,
							Expression = "PanoMerge.Background.OriginalWidth",
						},
						YSize = Input {
							Value = 1920,
							Expression = "PanoMerge.Background.OriginalHeight/2",
						},
						Input = Input {
							SourceOp = "PipeRouter3_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -1292.5, 307.6 } },
				},
				LeftMerge = Merge {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Background = Input {
							SourceOp = "DepthPipeRouter3",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "PipeRouter1",
							Source = "Output",
						},
						PerformDepthMerge = Input { Value = 0, },
						ReferenceSize = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 76.6 } },
				},
				CustomToolOffsetControl = Custom {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						NumberIn1 = Input { Value = 0.495, },
						LUTIn1 = Input {
							SourceOp = "CustomToolOffsetControlLUTIn1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "CustomToolOffsetControlLUTIn2",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "CustomToolOffsetControlLUTIn3",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "CustomToolOffsetControlLUTIn4",
							Source = "Value",
						},
						NumberControls = Input { Value = 1, },
						NameforNumber1 = Input { Value = "Stereo Offset Convergence", },
						ShowNumber2 = Input { Value = 0, },
						ShowNumber3 = Input { Value = 0, },
						ShowNumber4 = Input { Value = 0, },
						ShowNumber5 = Input { Value = 0, },
						ShowNumber6 = Input { Value = 0, },
						ShowNumber7 = Input { Value = 0, },
						ShowNumber8 = Input { Value = 0, },
						ShowPoint1 = Input { Value = 0, },
						ShowPoint2 = Input { Value = 0, },
						ShowPoint3 = Input { Value = 0, },
						ShowPoint4 = Input { Value = 0, },
						ShowLUT1 = Input { Value = 0, },
						ShowLUT2 = Input { Value = 0, },
						ShowLUT3 = Input { Value = 0, },
						ShowLUT4 = Input { Value = 0, },
					},
					ViewInfo = OperatorInfo { Pos = { 1014.68, 73.0599 } },
				},
				CustomToolOffsetControlLUTIn1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
				},
				CustomToolOffsetControlLUTIn2 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
				},
				CustomToolOffsetControlLUTIn3 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
				},
				CustomToolOffsetControlLUTIn4 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
				},
				PipeRouter1 = PipeRouter {
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "ZDepthColorCorrector",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -632.5, 76.6 } },
				},
				PipeRouter3_1 = PipeRouter {
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "PanoMerge",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -1347.5, 505.6 } },
				},
				PanoMerge = Merge {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Background = Input {
							SourceOp = "OverUnderCrop",
							Source = "Output",
						},
						PerformDepthMerge = Input { Value = 0, },
					},
					ViewInfo = OperatorInfo { Pos = { -1457.5, 505.6 } },
				},
				LeftTransform = Transform {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Center = Input { Value = { -0.5, 0.5 }, },
						Input = Input {
							SourceOp = "DepthPipeRouter1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -247.5, 10.6 } },
				},
				DepthPipeRouter1 = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "PipeRouter1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -467.5, 10.6 } },
				},
				DepthPipeRouter3 = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "LeftTransform",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -27.5, 10.6 } },
				},
				SetMetadataStereoMethod = Fuse.SetMetaData {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						FieldName = Input { Value = "Stereo", },
						FieldValue = Input { Expression = "iif(EnableStereoMetadata == 1, \"{Method  = \\\"vstack\\\"}\", \"\")", },
						Input = Input {
							SourceOp = "OverUnderCrop_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 1596, 439.5 } },
					UserControls = ordered() {
						EnableStereoMetadata = {
							CBC_TriState = false,
							INP_Integer = false,
							LINKID_DataType = "Number",
							ICS_ControlPage = "Controls",
							INPID_InputControl = "CheckboxControl",
							LINKS_Name = "Enable Stereo Metadata"
						}
					}
				}
			},
		},
		Note1 = Note {
			Inputs = {
				Comments = Input { Value = "This example shows how to render elements from Fusion's 3D animation system to an Equirectangular/LatLong/Spherical Over/Under Z360 Stereo format output.", }
			},
			ViewInfo = StickyNoteInfo {
				Pos = { 605, 49.5 },
				Flags = {
					Expanded = true
				},
				Size = { 619.498, 68.6028 }
			},
		},
		Z360Renderer3D = GroupOperator {
			CustomData = {
				HelpPage = "http://www.andrewhazelden.com/projects/kartavr/docs/macros-guide.html#Z360Renderer3D",
			},
			Inputs = ordered() {
				MainInput1 = InstanceInput {
					SourceOp = "CameraViewInput",
					Source = "SceneInput1",
				},
				Input1 = InstanceInput {
					SourceOp = "UVRenderer3DColor",
					Source = "Height",
					MaxScale = 8192,
					Default = 1920,
				},
				Input2 = InstanceInput {
					SourceOp = "UVRenderer3DColor",
					Source = "Depth",
					Default = 4,
				},
				Input3 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "RendererSoftware.LightingEnabled",
					Default = 1,
				},
				Input4 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "RendererSoftware.ShadowsEnabled",
					Default = 1,
				},
				Input5 = InstanceInput {
					SourceOp = "Camera3DFront",
					Source = "Transform3DOp.Translate.X",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input6 = InstanceInput {
					SourceOp = "Camera3DFront",
					Source = "Transform3DOp.Translate.Y",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input7 = InstanceInput {
					SourceOp = "Camera3DFront",
					Source = "Transform3DOp.Translate.Z",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input8 = InstanceInput {
					SourceOp = "CubeMapColor",
					Source = "Rotate.RotOrder",
				},
				Input9 = InstanceInput {
					SourceOp = "CubeMapColor",
					Source = "Rotate.X",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				Input10 = InstanceInput {
					SourceOp = "CubeMapColor",
					Source = "Rotate.Y",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				Input11 = InstanceInput {
					SourceOp = "CubeMapColor",
					Source = "Rotate.Z",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				}
			},
			Outputs = {
				MainOutput1 = InstanceOutput {
					SourceOp = "OverUnderCrop",
					Source = "Output",
				}
			},
			ViewInfo = GroupInfo {
				Pos = { 880, 181.5 },
				Flags = {
					AllowPan = false,
					AutoSnap = true,
					RemoveRouters = true
				},
				Size = { 2106, 494.2, 1053, 22 },
				Direction = "Horizontal",
				PipeStyle = "Direct",
				Scale = 1,
				Offset = { 0, 0 }
			},
			Tools = ordered() {
				OverUnderCrop = Crop {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						XSize = Input {
							Value = 3840,
							Expression = "UVRenderer3DColor.Width",
						},
						YSize = Input {
							Value = 3840,
							Expression = "UVRenderer3DColor.Height*2",
						},
						Input = Input {
							SourceOp = "ViewMerge",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 990, 439.6 } },
				},
				ViewMerge = Merge {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Background = Input {
							SourceOp = "ViewTransformRight",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "PipeRouter3",
							Source = "Output",
						},
						PerformDepthMerge = Input { Value = 0, },
					},
					ViewInfo = OperatorInfo { Pos = { 880, 439.6 } },
				},
				ViewTransformRight = Transform {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "UVRenderer3DDepth",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 770, 439.6 } },
				},
				ViewTransformLeft = Transform {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Center = Input { Value = { 0.5, 1.5 }, },
						Input = Input {
							SourceOp = "UVRenderer3DColor",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 770, 142.6 } },
				},
				PipeRouter3 = PipeRouter {
					CtrlWShown = false,
					Inputs = {
						Input = Input {
							SourceOp = "ViewTransformLeft",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 880, 142.6 } },
				},
				Note3 = Note {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Comments = Input { Value = "Z-Depth Channel Merge", }
					},
					ViewInfo = StickyNoteInfo {
						Pos = { 715, 43.6 },
						Flags = {
							Expanded = true
						},
						Size = { 317.376, 63.6531 }
					},
				},
				UVRenderer3DDepth = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 64, },
						Width = Input {
							Value = 3840,
							Expression = "UVRenderer3DColor.Height*2",
						},
						Height = Input {
							Value = 1920,
							Expression = "UVRenderer3DColor.Height",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "Shape3DSphereDepth",
							Source = "Output",
						},
						RendererType = Input { Value = FuID { "RendererOpenGLUV" }, },
						["RendererOpenGLUV.UVGutterSize"] = Input { Value = 0, },
						["RendererOpenGLUV.Texturing"] = Input { Value = 1, },
						["RendererOpenGLUV.TextureDepth"] = Input { Value = 4, },
					},
					ViewInfo = OperatorInfo { Pos = { 440, 439.6 } },
				},
				UVRenderer3DColor = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 64, },
						Width = Input {
							Value = 3840,
							Expression = "Height*2",
						},
						Height = Input { Value = 1920, },
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "Shape3DSphereColor",
							Source = "Output",
						},
						RendererType = Input { Value = FuID { "RendererOpenGLUV" }, },
						["RendererOpenGLUV.UVGutterSize"] = Input { Value = 0, },
						["RendererOpenGLUV.Texturing"] = Input { Value = 1, },
						["RendererOpenGLUV.TextureDepth"] = Input { Value = 0, },
					},
					ViewInfo = OperatorInfo { Pos = { 440, 142.6 } },
				},
				Shape3DSphereDepth = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 7, },
						["Transform3DOp.Rotate.Y"] = Input { Value = 270, },
						["Transform3DOp.ScaleLock"] = Input { Value = 0, },
						["Transform3DOp.Scale.X"] = Input { Value = -1000, },
						["Transform3DOp.Scale.Y"] = Input { Value = 1000, },
						["Transform3DOp.Scale.Z"] = Input { Value = 1000, },
						Shape = Input { Value = FuID { "SurfaceSphereInputs" }, },
						MaterialInput = Input {
							SourceOp = "CubeMapDepth",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.MaterialID"] = Input { Value = 6, },
						["SurfaceSphereInputs.Radius"] = Input { Value = 500, },
						["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 8, }
					},
					ViewInfo = OperatorInfo { Pos = { 330, 439.6 } },
				},
				Shape3DSphereColor = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 7, },
						["Transform3DOp.Rotate.Y"] = Input { Value = 270, },
						["Transform3DOp.ScaleLock"] = Input { Value = 0, },
						["Transform3DOp.Scale.X"] = Input { Value = -1000, },
						["Transform3DOp.Scale.Y"] = Input { Value = 1000, },
						["Transform3DOp.Scale.Z"] = Input { Value = 1000, },
						Shape = Input { Value = FuID { "SurfaceSphereInputs" }, },
						MaterialInput = Input {
							SourceOp = "CubeMapColor",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.MaterialID"] = Input { Value = 6, },
						["SurfaceSphereInputs.Radius"] = Input { Value = 500, },
						["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 8, }
					},
					ViewInfo = OperatorInfo { Pos = { 330, 142.6 } },
				},
				CubeMapDepth = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CubeMapColor",
					Inputs = {
						Rotation = Input { Value = 1, },
						["FilterMode.Nest"] = Input { Value = 1, },
						CrossImage = Input { },
						Left = Input {
							SourceOp = "ZDepthCustomToolLeft",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "ZDepthCustomToolRight",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "ZDepthCustomToolTop",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "ZDepthCustomToolBottom",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "ZDepthCustomToolFront",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "ZDepthCustomToolBack",
							Source = "Output",
						},
						MaterialIDNest = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 220, 439.6 } },
				},
				CubeMapColor = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Orientation = Input { Value = 0, },
						Rotation = Input { Value = 1, },
						["FilterMode.Nest"] = Input { Value = 1, },
						["FilterMode.SW.LowQ"] = Input { Value = FuID { "Bilinear" }, },
						Left = Input {
							SourceOp = "PipeRouterLeft",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "PipeRouterRight",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "PipeRouterTop",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "PipeRouterBottom",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "PipeRouterFront",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "PipeRouterBack",
							Source = "Output",
						},
						MaterialID = Input { Value = 3, },
					},
					ViewInfo = OperatorInfo { Pos = { 220, 142.6 } },
				},
				Note2 = Note {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Comments = Input { Value = "The ZDepthCustomToolFront node's RGB expressions set the visible range for the depth data", }
					},
					ViewInfo = StickyNoteInfo {
						Pos = { -330, 43.6 },
						Flags = {
							Expanded = true
						},
						Size = { 504.111, 69.0964 }
					},
				},
				ZDepthCustomToolFront = Custom {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						LUTIn1 = Input {
							SourceOp = "ZDepthCustomToolFrontLUTIn1",
							Source = "Value",
						},
						LUTIn2 = Input {
							SourceOp = "ZDepthCustomToolFrontLUTIn2",
							Source = "Value",
						},
						LUTIn3 = Input {
							SourceOp = "ZDepthCustomToolFrontLUTIn3",
							Source = "Value",
						},
						LUTIn4 = Input {
							SourceOp = "ZDepthCustomToolFrontLUTIn4",
							Source = "Value",
						},
						RedExpression = Input { Value = "(z1*0.002)*-1", },
						GreenExpression = Input { Value = "(z1*0.002)*-1", },
						BlueExpression = Input { Value = "(z1*0.002)*-1", },
						AuxChannelNest = Input { Value = 1, },
						Image1 = Input {
							SourceOp = "ChangeDepthFront",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -110, 274.6 } },
				},
				ZDepthCustomToolFrontLUTIn1 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 0, Blue = 0 },
					CtrlWShown = false,
					NameSet = true,
				},
				ZDepthCustomToolFrontLUTIn2 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 204, Blue = 0 },
					CtrlWShown = false,
					NameSet = true,
				},
				ZDepthCustomToolFrontLUTIn3 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 0, Green = 0, Blue = 204 },
					CtrlWShown = false,
					NameSet = true,
				},
				ZDepthCustomToolFrontLUTIn4 = LUTBezier {
					KeyColorSplines = {
						[0] = {
							[0] = { 0, RH = { 0.333333333333333, 0.333333333333333 }, Flags = { Linear = true } },
							[1] = { 1, LH = { 0.666666666666667, 0.666666666666667 }, Flags = { Linear = true } }
						}
					},
					SplineColor = { Red = 204, Green = 204, Blue = 204 },
					CtrlWShown = false,
					NameSet = true,
				},
				ZDepthCustomToolRight = Custom {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "ZDepthCustomToolFront",
					Inputs = {
						LUTControlsNest = Input { },
						AuxChannelNest = Input { Value = 1, },
						Randomize = Input { },
						NumberControls = Input { },
						PointControls = Input { },
						LUTControls = Input { },
						Image1 = Input {
							SourceOp = "ChangeDepthRight",
							Source = "Output",
						},
						Image2 = Input { },
						Image3 = Input { },
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { -110, 307.6 } },
				},
				ZDepthCustomToolBack = Custom {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "ZDepthCustomToolFront",
					Inputs = {
						LUTControlsNest = Input { },
						AuxChannelNest = Input { Value = 1, },
						Randomize = Input { },
						NumberControls = Input { },
						PointControls = Input { },
						LUTControls = Input { },
						Image1 = Input {
							SourceOp = "ChangeDepthBack",
							Source = "Output",
						},
						Image2 = Input { },
						Image3 = Input { },
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { -110, 340.6 } },
				},
				ZDepthCustomToolBottom = Custom {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "ZDepthCustomToolFront",
					Inputs = {
						LUTControlsNest = Input { },
						AuxChannelNest = Input { Value = 1, },
						Randomize = Input { },
						NumberControls = Input { },
						PointControls = Input { },
						LUTControls = Input { },
						Image1 = Input {
							SourceOp = "ChangeDepthBottom",
							Source = "Output",
						},
						Image2 = Input { },
						Image3 = Input { },
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { -110, 439.6 } },
				},
				ZDepthCustomToolTop = Custom {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "ZDepthCustomToolFront",
					Inputs = {
						LUTControlsNest = Input { },
						AuxChannelNest = Input { Value = 1, },
						Randomize = Input { },
						NumberControls = Input { },
						PointControls = Input { },
						LUTControls = Input { },
						Image1 = Input {
							SourceOp = "ChangeDepthTop",
							Source = "Output",
						},
						Image2 = Input { },
						Image3 = Input { },
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { -110, 406.6 } },
				},
				ZDepthCustomToolLeft = Custom {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "ZDepthCustomToolFront",
					Inputs = {
						LUTControlsNest = Input { },
						AuxChannelNest = Input { Value = 1, },
						Randomize = Input { },
						NumberControls = Input { },
						PointControls = Input { },
						LUTControls = Input { },
						Image1 = Input {
							SourceOp = "ChangeDepthLeft",
							Source = "Output",
						},
						Image2 = Input { },
						Image3 = Input { },
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { -110, 373.6 } },
				},
				ChangeDepthFront = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterFront",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -220, 274.6 } },
				},
				ChangeDepthBottom = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBottom",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -220, 439.6 } },
				},
				ChangeDepthRight = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterRight",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -220, 307.6 } },
				},
				ChangeDepthTop = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterTop",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -220, 406.6 } },
				},
				ChangeDepthBack = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBack",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -220, 340.6 } },
				},
				ChangeDepthLeft = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterLeft",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -220, 373.6 } },
				},
				Renderer3DTop = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["RendererOpenGL.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Vector", },
						["RendererOpenGL.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.ObjectID", },
						["RendererOpenGL.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.BackVector", },
						["RendererOpenGL.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.TexCoord0", },
						["RendererOpenGL.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Z", },
						["RendererOpenGL.Channels.Nest"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Nest", },
						["RendererOpenGL.LightingEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.LightingEnabled", },
						["RendererOpenGL.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Normal", },
						["RendererOpenGL.ShadowsEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.ShadowsEnabled", },
						["RendererOpenGL.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.WorldCoord", },
						["RendererOpenGL.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.MaterialID", },
						["RendererOpenGL.Supersampling"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Supersampling", },
						GlobalOut = Input { Value = 64, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3DColor.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3DColor.Height*0.5",
						},
						Depth = Input {
							Value = 4,
							Expression = "UVRenderer3DColor.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DTop" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.Z",
						},
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.BgColor"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BgColor", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -605, 406.6 } },
				},
				Renderer3DRight = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["RendererOpenGL.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Vector", },
						["RendererOpenGL.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.ObjectID", },
						["RendererOpenGL.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.BackVector", },
						["RendererOpenGL.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.TexCoord0", },
						["RendererOpenGL.Channels.Z"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererOpenGL.Channels.Z",
						},
						["RendererOpenGL.Channels.Nest"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Nest", },
						["RendererOpenGL.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererOpenGL.LightingEnabled",
						},
						["RendererOpenGL.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Normal", },
						["RendererOpenGL.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererOpenGL.ShadowsEnabled",
						},
						["RendererOpenGL.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.WorldCoord", },
						["RendererOpenGL.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.MaterialID", },
						["RendererOpenGL.Supersampling"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Supersampling", },
						GlobalOut = Input { Value = 64, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3DColor.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3DColor.Height*0.5",
						},
						Depth = Input {
							Value = 4,
							Expression = "UVRenderer3DColor.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DRight" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.Z",
						},
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.BgColor"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BgColor", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -605, 307.6 } },
				},
				Renderer3DBack = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["RendererOpenGL.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Vector", },
						["RendererOpenGL.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.ObjectID", },
						["RendererOpenGL.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.BackVector", },
						["RendererOpenGL.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.TexCoord0", },
						["RendererOpenGL.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Z", },
						["RendererOpenGL.Channels.Nest"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Nest", },
						["RendererOpenGL.LightingEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.LightingEnabled", },
						["RendererOpenGL.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Normal", },
						["RendererOpenGL.ShadowsEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.ShadowsEnabled", },
						["RendererOpenGL.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.WorldCoord", },
						["RendererOpenGL.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.MaterialID", },
						["RendererOpenGL.Supersampling"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Supersampling", },
						GlobalOut = Input { Value = 64, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3DColor.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3DColor.Height*0.5",
						},
						Depth = Input {
							Value = 4,
							Expression = "UVRenderer3DColor.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DBack" }, },
						RendererType = Input { Expression = "Renderer3DFront.RendererType", },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.Z",
						},
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.BgColor"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BgColor", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -605, 340.6 } },
				},
				Renderer3DFront = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["RendererOpenGL.Channels.Z"] = Input { Value = 1, },
						["RendererOpenGL.LightingEnabled"] = Input { Value = 1, },
						["RendererOpenGL.ShadowsEnabled"] = Input { Value = 1, },
						["RendererOpenGL.Channels.Nest"] = Input { Value = 1, },
						GlobalOut = Input { Value = 64, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3DColor.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3DColor.Height*0.5",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DFront" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.Z"] = Input { Value = 1, },
						["RendererSoftware.LightingEnabled"] = Input { Value = 1, },
						["RendererSoftware.ShadowsEnabled"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -605, 274.6 } },
				},
				Renderer3DBottom = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["RendererOpenGL.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Vector", },
						["RendererOpenGL.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.ObjectID", },
						["RendererOpenGL.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.BackVector", },
						["RendererOpenGL.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.TexCoord0", },
						["RendererOpenGL.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Z", },
						["RendererOpenGL.Channels.Nest"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Nest", },
						["RendererOpenGL.LightingEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.LightingEnabled", },
						["RendererOpenGL.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Normal", },
						["RendererOpenGL.ShadowsEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.ShadowsEnabled", },
						["RendererOpenGL.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.WorldCoord", },
						["RendererOpenGL.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.MaterialID", },
						["RendererOpenGL.Supersampling"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Supersampling", },
						GlobalOut = Input { Value = 64, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3DColor.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3DColor.Height*0.5",
						},
						Depth = Input {
							Value = 4,
							Expression = "UVRenderer3DColor.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DBottom" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.Z",
						},
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.BgColor"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BgColor", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -605, 439.6 } },
				},
				Renderer3DLeft = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["RendererOpenGL.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Vector", },
						["RendererOpenGL.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.ObjectID", },
						["RendererOpenGL.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.BackVector", },
						["RendererOpenGL.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.TexCoord0", },
						["RendererOpenGL.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Z", },
						["RendererOpenGL.Channels.Nest"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Nest", },
						["RendererOpenGL.LightingEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.LightingEnabled", },
						["RendererOpenGL.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Normal", },
						["RendererOpenGL.ShadowsEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.ShadowsEnabled", },
						["RendererOpenGL.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.WorldCoord", },
						["RendererOpenGL.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.MaterialID", },
						["RendererOpenGL.Supersampling"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Supersampling", },
						GlobalOut = Input { Value = 64, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3DColor.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3DColor.Height*0.5",
						},
						Depth = Input {
							Value = 4,
							Expression = "UVRenderer3DColor.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DLeft" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.Z",
						},
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.BgColor"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BgColor", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -605, 373.6 } },
				},
				PipeRouterBack = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DBack",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -495, 340.6 } },
				},
				PipeRouterTop = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DTop",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -495, 406.6 } },
				},
				PipeRouterLeft = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DLeft",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -495, 373.6 } },
				},
				PipeRouterBottom = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DBottom",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -495, 439.6 } },
				},
				PipeRouterRight = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DRight",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -495, 307.6 } },
				},
				PipeRouterFront = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DFront",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -495, 274.6 } },
				},
				CameraViewInput = Merge3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						PassThroughLights = Input { Value = 1, },
						SceneInput1 = Input {
							SourceOp = "Transform3D1",
							Source = "Output",
						},
						SceneInput2 = Input {
							SourceOp = "Camera3DFront",
							Source = "Output",
						},
						SceneInput3 = Input {
							SourceOp = "Camera3DRight",
							Source = "Output",
						},
						SceneInput5 = Input {
							SourceOp = "Camera3DLeft",
							Source = "Output",
						},
						SceneInput4 = Input {
							SourceOp = "Camera3DBack",
							Source = "Output",
						},
						SceneInput7 = Input {
							SourceOp = "Camera3DBottom",
							Source = "Output",
						},
						SceneInput6 = Input {
							SourceOp = "Camera3DTop",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -825, 274.6 } },
				},
				Camera3DTop = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.X+90", },
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Z", },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -990, 142.6 } },
				},
				Camera3DLeft = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = -90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.Z-90.0",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -990, 109.6 } },
				},
				Camera3DBack = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = 180,
							Expression = "Camera3DFront.Transform3DOp.Rotate.Z+180.0",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -990, 76.6 } },
				},
				Camera3DFront = Camera3D {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Rotate.X"] = Input { Value = -90, },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -990, 10.6 } },
				},
				Camera3DRight = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = 90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.Z+90",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -990, 43.6 } },
				},
				Camera3DBottom = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -180,
							Expression = "Camera3DFront.Transform3DOp.Rotate.X-90",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Z", },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -990, 175.6 } },
				}
			},
		}
	},
	Views = {
		{
			FrameTypeID = "ChildFrame",
			Mode = 3,
			LayoutPreset = 0,
			Left = 0,
			Top = 27,
			Width = 3440,
			Height = 1197,
			Views = ordered() {
				Main = MultiView {
					Active = "Flow",
					ViewList = ordered() {
						Flow = "FlowView",
						Console = "ConsoleView",
						Timeline = "TimelineView",
						Spline = "SplineEditorView",
						Info = "InfoView",
						Chat = "ChatView"
					},
					Flow = FlowView {
						Flags = {
							Navigator = true,
							AutoHideNavigator = true,
							AutoSnap = true,
							RemoveRouters = true
						},
						NavigatorSize = { 200, 140 },
						Direction = "Horizontal",
						PipeStyle = "Direct",
						Scale = 1.23307,
						Offset = { -92.6453, 42.3472 }
					},
					Timeline = TimelineView {
						TreeControlState = {
						},
						DisplayMode = "All Tools",
						ShowCurrentTimeTools = false,
						Filter = "Show All",
						ShowSelectedTools = false,
						ShowAnimatedToolsOnly = false,
						ShowEditBoxes = false,
						KeyFrameView = {
							Position = { Left = 150, Bottom = 279 },
							ScaleX = 0.137231968810916,
							OffsetX = -3.29356725146199,
							OffsetY = 0,
							AutoScaling = "scroll",
							AutoSnapTo = "frame",
							AutoSnapToGuidelines = false,
							GuidelinesGrabEnabled = true,
							GuidelinesSnapTo = "frame"
						},
						Spreadsheet = { LeftPos = 150, Visible = false }
					},
					Spline = SplineEditorView {
						LeftPos = 256,
						ScaleX = 0.2,
						ScaleY = 0.00338983050847458,
						OffsetX = -4,
						OffsetY = 0,
						AutoScaling = "scroll",
						AutoSnapTo = "frame",
						AutoSnapToGuidelines = false,
						GuidelinesSnapTo = "frame",
						ShowKeyMarkers = false,
						IndependentHandles = false,
						ShowNonSplineModifiers = false,
						GuidelinesGrabEnabled = true,
						ShowOneToolOnly = false,
						ShowSelectedTools = false,
						ShowAllInputs = false,
						Filter = "Show All"
					},
				},
				Controls = MultiView {
					Active = "Tools",
					ViewList = ordered() {
						Tools = "ControlView",
						Modifiers = "ModifierView"
					},
				},
				Left = "PreviewContainer",
				Right = "PreviewContainer",
				Transport = "TransportView",
				Time = "TimeView"
			},
			Layout = {
				Columns = 2,
				RatioX = 1,
				RatioY = 1,
				{
					Rows = 3,
					RatioX = 0.761572052401747,
					RatioY = 1,
					{
						Columns = 2,
						RatioX = 1,
						RatioY = 0.617325483599664,
						{ ID = "Left", RatioX = 1, RatioY = 0.00953678474114441, Pop = true },
						{ ID = "Right", RatioX = -2, Pop = true },
						Pop = true
					},
					{ ID = "Main", RatioY = 0.333894028595458, Pop = true },
					{ ID = "Time", SnapY = 56, Flat = true }
				},
				{
					Rows = 2,
					PixelX = 817,
					{ ID = "Controls", RatioX = 1, RatioY = 1 },
					{ ID = "Transport", FixedY = -2 }
				}
			}
		}
	},
	Prefs = {
		Comp = {
			Interactive = {
				Proxy = {
					Scale = 4,
					AutoScale = 4,
				},
			},
			Views = {
				Right = {
					Viewer = {
						Normalise = false,
						ScaleMode = 1
					},
					View3D = {
						CamFront = {
							Rotation = {
								Y = 0,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamLeft = {
							Rotation = {
								Y = 90,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamPersp = {
							Rotation = {
								Y = 0,
								X = 30,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamRight = {
							Rotation = {
								Y = -90,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamTop = {
							Rotation = {
								Y = 0,
								X = 90,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						}
					},
				},
				Left = {
					Viewer = {
						ScaleMode = 1,
						Normalise = false,
						Channel = 4294967295,
					},
					MaterialViewer = {
						Camera = {
							Rotation = {
								Y = -20,
								X = 15,
								Z = 0
							}
						}
					},
					SubView = {
						Enabled = false,
						GLHistogramViewer = {
							AutoBounds = true
						},
					},
					Stereo = {
						Enabled = false,
						Swap = true,
						DisplayMethod = "Anaglyph",
						Stack = true,
						StackMethod = "Vertical",
						AnaglyphMethod = "Half-color",
					},
					Controls = {
						SnapPixel = false,
					},
					View3D = {
						CamFront = {
							Rotation = {
								Y = 0,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						Options = {
							Lighting = true,
							Shadows = false,
							Wireframe = false
						},
						CamRight = {
							Rotation = {
								Y = -90,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamLeft = {
							Rotation = {
								Y = 90,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamTop = {
							Rotation = {
								Y = 0,
								X = 90,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamPersp = {
							Rotation = {
								Y = 86.7999572753906,
								X = 18.4000244140625,
								Z = 0
							},
							Scale = 0.00213574361987412,
							Position = {
								Y = 184.447494506836,
								X = -553.604309082031,
								Z = 30.9517059326172
							}
						},
						SortMethod = "QuickBSP",
						CameraName = "Perspective"
					},
				},
				View1 = {
				},
			},
			FrameFormat = {
				Name = "2K Full Aperture (Super 35)",
				Width = 2048,
				Height = 1556,
				Rate = 24,
				PerFeet = 16,
				GuideRatio = 1.77778,
			},
			LastFile = "",
			Unsorted = {
				GlobalEnd = 64,
				RenderSettings = {
					Configs = {
						Preview = {
							StepRender = false,
							PriorityClasses = "all",
							CustomAspect = true,
							StepSize = 5,
							SizeType = 1,
							CustomHeight = 160,
							ShowSlaves = false,
							CustomWidth = 200,
							MotionBlur = true,
							UpdateMode = "Some",
							UseNetwork = false,
							Quality = false
						},
						Final = {
							StepRender = false,
							PriorityClasses = "all",
							CustomAspect = true,
							StepSize = 5,
							SizeType = 1,
							CustomHeight = 160,
							ShowSlaves = false,
							CustomWidth = 200,
							MotionBlur = true,
							UpdateMode = "Some",
							UseNetwork = false,
							Quality = true
						}
					},
					PreviewConfig = "Preview",
					CurrentConfig = "Final"
				}
			},
			Paths = {
			},
			QuickTime = {
			},
		}
	}
}

 