Composition {
	CurrentTime = 0,
	RenderRange = { 0, 0 },
	GlobalRange = { 0, 1 },
	CurrentID = 154,
	PlaybackUpdateMode = 0,
	Version = "Fusion 8.2.1 build 6",
	SavedOutputs = 0,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	Resumable = true,
	OutputClips = {
		"Temp:\\KartaVR\\latlong-color-corrected-horizontal-gradient.0000.png",
		"Temp:\\KartaVR\\latlong-color-corrected-vertical.0000.png",
		"Temp:\\KartaVR\\latlong-color-corrected-horizontal.0000.png"
	},
	Tools = {
		Loader1_1_1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "Macros:/KartaVR/Images/latlong_fall_colors_with_tripod.jpg",
					FormatID = "JpegFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 165, 247.5 } },
		},
		Loader1_1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "Macros:/KartaVR/Images/latlong_fall_colors_with_tripod.jpg",
					FormatID = "JpegFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 165, 148.5 } },
		},
		Loader1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "Macros:/KartaVR/Images/latlong_fall_colors_with_tripod.jpg",
					FormatID = "JpegFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 165, 49.5 } },
		},
		ColorCorrectorMasked2 = GroupOperator {
			NameSet = true,
			Inputs = ordered() {
				Input251 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "Width",
					Default = 3840,
				},
				Input252 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "Height",
					Default = 1920,
				},
				Input253 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "Depth",
					Default = 0,
				},
				Input254 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "Type",
				},
				Input255 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "TopLeftRed",
					Name = "Top Left",
					ControlGroup = 164,
					Default = 0,
				},
				Input256 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "TopLeftGreen",
					ControlGroup = 164,
					Default = 0,
				},
				Input257 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "TopLeftBlue",
					ControlGroup = 164,
					Default = 0,
				},
				Input258 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "TopLeftAlpha",
					ControlGroup = 164,
					Default = 1,
				},
				Input259 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "TopRightRed",
					Name = "Top Right",
					ControlGroup = 165,
					Default = 0,
				},
				Input260 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "TopRightGreen",
					ControlGroup = 165,
					Default = 0,
				},
				Input261 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "TopRightBlue",
					ControlGroup = 165,
					Default = 0,
				},
				Input262 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "TopRightAlpha",
					ControlGroup = 165,
					Default = 1,
				},
				Input263 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "BottomLeftRed",
					Name = "Bottom Left",
					ControlGroup = 166,
					Default = 0,
				},
				Input264 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "BottomLeftGreen",
					ControlGroup = 166,
					Default = 0,
				},
				Input265 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "BottomLeftBlue",
					ControlGroup = 166,
					Default = 0,
				},
				Input266 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "BottomLeftAlpha",
					ControlGroup = 166,
					Default = 1,
				},
				Input267 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "BottomRightRed",
					Name = "Bottom Right",
					ControlGroup = 167,
					Default = 0,
				},
				Input268 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "BottomRightGreen",
					ControlGroup = 167,
					Default = 0,
				},
				Input269 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "BottomRightBlue",
					ControlGroup = 167,
					Default = 0,
				},
				Input270 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "BottomRightAlpha",
					ControlGroup = 167,
					Default = 1,
				},
				Input271 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "GradientType",
				},
				Input272 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "Start",
					DefaultX = 0.5,
					DefaultY = 1,
				},
				Input273 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "End",
					DefaultX = 0.5,
					DefaultY = 0.5,
				},
				Input274 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "Gradient",
				},
				Input275 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "GradientInterpolationMethod",
				},
				Input276 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "Offset",
					Default = 0,
				},
				Input277 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "Repeat",
				},
				Input278 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "SubPixel",
				},
				Input279 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "MotionBlur",
					Default = 0,
				},
				Input280 = InstanceInput {
					SourceOp = "GradientMaskBackground_1",
					Source = "Quality",
					Default = 2,
				},
				MainInput1 = InstanceInput {
					SourceOp = "AlphaDivideMask_1",
					Source = "Input",
				},
				Input1 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Menu",
				},
				Input2 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "CorrectionRange",
				},
				Input3 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "WheelHue1",
					ControlGroup = 3,
				},
				Input4 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "WheelSaturation1",
					ControlGroup = 3,
					Default = 1,
				},
				Input5 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "WheelTintAngle1",
					ControlGroup = 3,
				},
				Input6 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "WheelTintLength1",
					ControlGroup = 3,
				},
				Input7 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "WheelRangeDummy1",
					ControlGroup = 3,
					Default = 0,
				},
				Input8 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "WheelHue2",
					ControlGroup = 3,
				},
				Input9 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "WheelSaturation2",
					ControlGroup = 3,
					Default = 1,
				},
				Input10 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "WheelTintAngle2",
					ControlGroup = 3,
				},
				Input11 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "WheelTintLength2",
					ControlGroup = 3,
				},
				Input12 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "WheelHue3",
					ControlGroup = 3,
				},
				Input13 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "WheelSaturation3",
					ControlGroup = 3,
					Default = 1,
				},
				Input14 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "WheelTintAngle3",
					ControlGroup = 3,
				},
				Input15 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "WheelTintLength3",
					ControlGroup = 3,
				},
				Input16 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "WheelHue4",
					ControlGroup = 3,
				},
				Input17 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "WheelSaturation4",
					ControlGroup = 3,
					Default = 1,
				},
				Input18 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "WheelTintAngle4",
					ControlGroup = 3,
				},
				Input19 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "WheelTintLength4",
					ControlGroup = 3,
				},
				Input20 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "TintMode",
					Default = 2,
				},
				Input21 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Hue1",
				},
				Input22 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Saturation1",
					Default = 1,
				},
				Input23 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Hue2",
				},
				Input24 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Saturation2",
					Default = 1,
				},
				Input25 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Hue3",
				},
				Input26 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Saturation3",
					Default = 1,
				},
				Input27 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Hue4",
				},
				Input28 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Saturation4",
					Default = 1,
				},
				Input29 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Channel",
				},
				Input30 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Histogram",
					ControlGroup = 14,
				},
				Input31 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HistogramReference",
					ControlGroup = 14,
				},
				Input32 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HistogramOutput",
					ControlGroup = 14,
				},
				Input33 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HistogramCurve",
					ControlGroup = 14,
				},
				Input34 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HistogramType",
				},
				Input35 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "EqualizeLuminance",
					Default = 0,
				},
				Input36 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "LockRedGreenBlue",
					Default = 1,
				},
				Input37 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "EqualizeRed",
					Default = 1,
				},
				Input38 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "EqualizeGreen",
					Default = 1,
				},
				Input39 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "EqualizeBlue",
					Default = 1,
				},
				Input40 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Precision",
					Default = 2,
				},
				Input41 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "SmoothOutCorrectionCurve",
					Default = 0,
				},
				Input42 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "SnapshotMatch",
				},
				Input43 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ReleaseMatch",
				},
				Input44 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MatchShow",
					Default = 0,
				},
				Input45 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MatchCenter",
					DefaultX = 0.5,
					DefaultY = 0.5,
				},
				Input46 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MatchWidth",
					Default = 1,
				},
				Input47 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MatchHeight",
					Default = 1,
				},
				Input48 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ResetAllHistogramChanges",
				},
				Input49 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRGBContrast",
					Default = 1,
				},
				Input50 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRGBGain",
					Default = 1,
				},
				Input51 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRGBLift",
					Default = 0,
				},
				Input52 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRGBGamma",
					Default = 1,
				},
				Input53 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRGBBrightness",
					Default = 0,
				},
				Input54 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRGBLow",
					ControlGroup = 35,
					Default = 0,
				},
				Input55 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRGBMid",
					ControlGroup = 35,
					Default = 1,
				},
				Input56 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRGBHigh",
					ControlGroup = 35,
					Default = 1,
				},
				Input57 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRGBOutputLow",
					ControlGroup = 36,
					Default = 0,
				},
				Input58 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRGBOutputHigh",
					ControlGroup = 36,
					Default = 1,
				},
				Input59 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRedContrast",
					Default = 1,
				},
				Input60 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRedGain",
					Default = 1,
				},
				Input61 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRedLift",
					Default = 0,
				},
				Input62 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRedGamma",
					Default = 1,
				},
				Input63 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRedBrightness",
					Default = 0,
				},
				Input64 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRedLow",
					ControlGroup = 42,
					Default = 0,
				},
				Input65 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRedMid",
					ControlGroup = 42,
					Default = 1,
				},
				Input66 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRedHigh",
					ControlGroup = 42,
					Default = 1,
				},
				Input67 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRedOutputLow",
					ControlGroup = 43,
					Default = 0,
				},
				Input68 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterRedOutputHigh",
					ControlGroup = 43,
					Default = 1,
				},
				Input69 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterGreenContrast",
					Default = 1,
				},
				Input70 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterGreenGain",
					Default = 1,
				},
				Input71 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterGreenLift",
					Default = 0,
				},
				Input72 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterGreenGamma",
					Default = 1,
				},
				Input73 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterGreenBrightness",
					Default = 0,
				},
				Input74 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterGreenLow",
					ControlGroup = 49,
					Default = 0,
				},
				Input75 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterGreenMid",
					ControlGroup = 49,
					Default = 1,
				},
				Input76 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterGreenHigh",
					ControlGroup = 49,
					Default = 1,
				},
				Input77 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterGreenOutputLow",
					ControlGroup = 50,
					Default = 0,
				},
				Input78 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterGreenOutputHigh",
					ControlGroup = 50,
					Default = 1,
				},
				Input79 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterBlueContrast",
					Default = 1,
				},
				Input80 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterBlueGain",
					Default = 1,
				},
				Input81 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterBlueLift",
					Default = 0,
				},
				Input82 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterBlueGamma",
					Default = 1,
				},
				Input83 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterBlueBrightness",
					Default = 0,
				},
				Input84 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterBlueLow",
					ControlGroup = 56,
					Default = 0,
				},
				Input85 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterBlueMid",
					ControlGroup = 56,
					Default = 1,
				},
				Input86 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterBlueHigh",
					ControlGroup = 56,
					Default = 1,
				},
				Input87 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterBlueOutputLow",
					ControlGroup = 57,
					Default = 0,
				},
				Input88 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MasterBlueOutputHigh",
					ControlGroup = 57,
					Default = 1,
				},
				Input89 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRGBContrast",
					Default = 1,
				},
				Input90 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRGBGain",
					Default = 1,
				},
				Input91 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRGBLift",
					Default = 0,
				},
				Input92 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRGBGamma",
					Default = 1,
				},
				Input93 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRGBBrightness",
					Default = 0,
				},
				Input94 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRGBLow",
					ControlGroup = 63,
					Default = 0,
				},
				Input95 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRGBMid",
					ControlGroup = 63,
					Default = 1,
				},
				Input96 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRGBHigh",
					ControlGroup = 63,
					Default = 1,
				},
				Input97 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRGBOutputLow",
					ControlGroup = 64,
					Default = 0,
				},
				Input98 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRGBOutputHigh",
					ControlGroup = 64,
					Default = 1,
				},
				Input99 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRedContrast",
					Default = 1,
				},
				Input100 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRedGain",
					Default = 1,
				},
				Input101 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRedLift",
					Default = 0,
				},
				Input102 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRedGamma",
					Default = 1,
				},
				Input103 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRedBrightness",
					Default = 0,
				},
				Input104 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRedLow",
					ControlGroup = 70,
					Default = 0,
				},
				Input105 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRedMid",
					ControlGroup = 70,
					Default = 1,
				},
				Input106 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRedHigh",
					ControlGroup = 70,
					Default = 1,
				},
				Input107 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRedOutputLow",
					ControlGroup = 71,
					Default = 0,
				},
				Input108 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsRedOutputHigh",
					ControlGroup = 71,
					Default = 1,
				},
				Input109 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsGreenContrast",
					Default = 1,
				},
				Input110 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsGreenGain",
					Default = 1,
				},
				Input111 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsGreenLift",
					Default = 0,
				},
				Input112 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsGreenGamma",
					Default = 1,
				},
				Input113 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsGreenBrightness",
					Default = 0,
				},
				Input114 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsGreenLow",
					ControlGroup = 77,
					Default = 0,
				},
				Input115 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsGreenMid",
					ControlGroup = 77,
					Default = 1,
				},
				Input116 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsGreenHigh",
					ControlGroup = 77,
					Default = 1,
				},
				Input117 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsGreenOutputLow",
					ControlGroup = 78,
					Default = 0,
				},
				Input118 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsGreenOutputHigh",
					ControlGroup = 78,
					Default = 1,
				},
				Input119 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsBlueContrast",
					Default = 1,
				},
				Input120 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsBlueGain",
					Default = 1,
				},
				Input121 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsBlueLift",
					Default = 0,
				},
				Input122 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsBlueGamma",
					Default = 1,
				},
				Input123 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsBlueBrightness",
					Default = 0,
				},
				Input124 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsBlueLow",
					ControlGroup = 84,
					Default = 0,
				},
				Input125 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsBlueMid",
					ControlGroup = 84,
					Default = 1,
				},
				Input126 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsBlueHigh",
					ControlGroup = 84,
					Default = 1,
				},
				Input127 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsBlueOutputLow",
					ControlGroup = 85,
					Default = 0,
				},
				Input128 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ShadowsBlueOutputHigh",
					ControlGroup = 85,
					Default = 1,
				},
				Input129 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRGBContrast",
					Default = 1,
				},
				Input130 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRGBGain",
					Default = 1,
				},
				Input131 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRGBLift",
					Default = 0,
				},
				Input132 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRGBGamma",
					Default = 1,
				},
				Input133 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRGBBrightness",
					Default = 0,
				},
				Input134 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRGBLow",
					ControlGroup = 91,
					Default = 0,
				},
				Input135 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRGBMid",
					ControlGroup = 91,
					Default = 1,
				},
				Input136 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRGBHigh",
					ControlGroup = 91,
					Default = 1,
				},
				Input137 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRGBOutputLow",
					ControlGroup = 92,
					Default = 0,
				},
				Input138 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRGBOutputHigh",
					ControlGroup = 92,
					Default = 1,
				},
				Input139 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRedContrast",
					Default = 1,
				},
				Input140 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRedGain",
					Default = 1,
				},
				Input141 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRedLift",
					Default = 0,
				},
				Input142 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRedGamma",
					Default = 1,
				},
				Input143 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRedBrightness",
					Default = 0,
				},
				Input144 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRedLow",
					ControlGroup = 98,
					Default = 0,
				},
				Input145 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRedMid",
					ControlGroup = 98,
					Default = 1,
				},
				Input146 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRedHigh",
					ControlGroup = 98,
					Default = 1,
				},
				Input147 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRedOutputLow",
					ControlGroup = 99,
					Default = 0,
				},
				Input148 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesRedOutputHigh",
					ControlGroup = 99,
					Default = 1,
				},
				Input149 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesGreenContrast",
					Default = 1,
				},
				Input150 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesGreenGain",
					Default = 1,
				},
				Input151 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesGreenLift",
					Default = 0,
				},
				Input152 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesGreenGamma",
					Default = 1,
				},
				Input153 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesGreenBrightness",
					Default = 0,
				},
				Input154 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesGreenLow",
					ControlGroup = 105,
					Default = 0,
				},
				Input155 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesGreenMid",
					ControlGroup = 105,
					Default = 1,
				},
				Input156 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesGreenHigh",
					ControlGroup = 105,
					Default = 1,
				},
				Input157 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesGreenOutputLow",
					ControlGroup = 106,
					Default = 0,
				},
				Input158 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesGreenOutputHigh",
					ControlGroup = 106,
					Default = 1,
				},
				Input159 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesBlueContrast",
					Default = 1,
				},
				Input160 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesBlueGain",
					Default = 1,
				},
				Input161 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesBlueLift",
					Default = 0,
				},
				Input162 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesBlueGamma",
					Default = 1,
				},
				Input163 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesBlueBrightness",
					Default = 0,
				},
				Input164 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesBlueLow",
					ControlGroup = 112,
					Default = 0,
				},
				Input165 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesBlueMid",
					ControlGroup = 112,
					Default = 1,
				},
				Input166 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesBlueHigh",
					ControlGroup = 112,
					Default = 1,
				},
				Input167 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesBlueOutputLow",
					ControlGroup = 113,
					Default = 0,
				},
				Input168 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "MidTonesBlueOutputHigh",
					ControlGroup = 113,
					Default = 1,
				},
				Input169 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRGBContrast",
					Default = 1,
				},
				Input170 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRGBGain",
					Default = 1,
				},
				Input171 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRGBLift",
					Default = 0,
				},
				Input172 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRGBGamma",
					Default = 1,
				},
				Input173 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRGBBrightness",
					Default = 0,
				},
				Input174 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRGBLow",
					ControlGroup = 119,
					Default = 0,
				},
				Input175 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRGBMid",
					ControlGroup = 119,
					Default = 1,
				},
				Input176 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRGBHigh",
					ControlGroup = 119,
					Default = 1,
				},
				Input177 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRGBOutputLow",
					ControlGroup = 120,
					Default = 0,
				},
				Input178 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRGBOutputHigh",
					ControlGroup = 120,
					Default = 1,
				},
				Input179 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRedContrast",
					Default = 1,
				},
				Input180 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRedGain",
					Default = 1,
				},
				Input181 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRedLift",
					Default = 0,
				},
				Input182 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRedGamma",
					Default = 1,
				},
				Input183 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRedBrightness",
					Default = 0,
				},
				Input184 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRedLow",
					ControlGroup = 126,
					Default = 0,
				},
				Input185 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRedMid",
					ControlGroup = 126,
					Default = 1,
				},
				Input186 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRedHigh",
					ControlGroup = 126,
					Default = 1,
				},
				Input187 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRedOutputLow",
					ControlGroup = 127,
					Default = 0,
				},
				Input188 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsRedOutputHigh",
					ControlGroup = 127,
					Default = 1,
				},
				Input189 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsGreenContrast",
					Default = 1,
				},
				Input190 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsGreenGain",
					Default = 1,
				},
				Input191 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsGreenLift",
					Default = 0,
				},
				Input192 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsGreenGamma",
					Default = 1,
				},
				Input193 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsGreenBrightness",
					Default = 0,
				},
				Input194 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsGreenLow",
					ControlGroup = 133,
					Default = 0,
				},
				Input195 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsGreenMid",
					ControlGroup = 133,
					Default = 1,
				},
				Input196 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsGreenHigh",
					ControlGroup = 133,
					Default = 1,
				},
				Input197 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsGreenOutputLow",
					ControlGroup = 134,
					Default = 0,
				},
				Input198 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsGreenOutputHigh",
					ControlGroup = 134,
					Default = 1,
				},
				Input199 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsBlueContrast",
					Default = 1,
				},
				Input200 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsBlueGain",
					Default = 1,
				},
				Input201 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsBlueLift",
					Default = 0,
				},
				Input202 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsBlueGamma",
					Default = 1,
				},
				Input203 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsBlueBrightness",
					Default = 0,
				},
				Input204 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsBlueLow",
					ControlGroup = 140,
					Default = 0,
				},
				Input205 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsBlueMid",
					ControlGroup = 140,
					Default = 1,
				},
				Input206 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsBlueHigh",
					ControlGroup = 140,
					Default = 1,
				},
				Input207 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsBlueOutputLow",
					ControlGroup = 141,
					Default = 0,
				},
				Input208 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "HighlightsBlueOutputHigh",
					ControlGroup = 141,
					Default = 1,
				},
				Input209 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ResetAllColorChanges",
				},
				Input210 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ResetAllLevels",
				},
				Input211 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Red1",
					ControlGroup = 144,
					Default = 1,
				},
				Input212 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Yellow1",
					ControlGroup = 144,
					Default = 1,
				},
				Input213 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Green1",
					ControlGroup = 144,
					Default = 1,
				},
				Input214 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Cyan1",
					ControlGroup = 144,
					Default = 1,
				},
				Input215 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Blue1",
					ControlGroup = 144,
					Default = 1,
				},
				Input216 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Magenta1",
					ControlGroup = 144,
					Default = 1,
				},
				Input217 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Red2",
					ControlGroup = 144,
					Default = 1,
				},
				Input218 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Yellow2",
					ControlGroup = 144,
					Default = 1,
				},
				Input219 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Green2",
					ControlGroup = 144,
					Default = 1,
				},
				Input220 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Cyan2",
					ControlGroup = 144,
					Default = 1,
				},
				Input221 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Blue2",
					ControlGroup = 144,
					Default = 1,
				},
				Input222 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Magenta2",
					ControlGroup = 144,
					Default = 1,
				},
				Input223 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Red3",
					ControlGroup = 144,
					Default = 1,
				},
				Input224 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Yellow3",
					ControlGroup = 144,
					Default = 1,
				},
				Input225 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Green3",
					ControlGroup = 144,
					Default = 1,
				},
				Input226 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Cyan3",
					ControlGroup = 144,
					Default = 1,
				},
				Input227 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Blue3",
					ControlGroup = 144,
					Default = 1,
				},
				Input228 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Magenta3",
					ControlGroup = 144,
					Default = 1,
				},
				Input229 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Red4",
					ControlGroup = 144,
					Default = 1,
				},
				Input230 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Yellow4",
					ControlGroup = 144,
					Default = 1,
				},
				Input231 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Green4",
					ControlGroup = 144,
					Default = 1,
				},
				Input232 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Cyan4",
					ControlGroup = 144,
					Default = 1,
				},
				Input233 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Blue4",
					ControlGroup = 144,
					Default = 1,
				},
				Input234 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Magenta4",
					ControlGroup = 144,
					Default = 1,
				},
				Input235 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "SuppressionRangeDummy",
					ControlGroup = 144,
				},
				Input236 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "SuppressionAngle1",
					MaxScale = 0.1666666666667,
					Default = 0,
				},
				Input237 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "SuppressionAngle2",
					MaxScale = 0.1666666666667,
					Default = 0,
				},
				Input238 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "SuppressionAngle3",
					MaxScale = 0.1666666666667,
					Default = 0,
				},
				Input239 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "SuppressionAngle4",
					MaxScale = 0.1666666666667,
					Default = 0,
				},
				Input240 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ResetAllSuppression",
				},
				Input241 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "RangesRange",
					Name = "Range",
				},
				Input242 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "RangesChannel",
				},
				Input243 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ColorRanges",
				},
				Input244 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "RenderOutputRange",
					Default = 0,
				},
				Input245 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "PresetSimpleRanges",
				},
				Input246 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "PresetSmoothRanges",
				},
				Input247 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "Blend",
					Default = 1,
				},
				Input248 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ProcessRed",
					Name = "Red",
					Default = 1,
				},
				Input249 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ProcessGreen",
					Name = "Green",
					Default = 1,
				},
				Input250 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1",
					Source = "ProcessBlue",
					Name = "Blue",
					Default = 1,
				}
			},
			Outputs = {
				MainOutput1 = InstanceOutput {
					SourceOp = "AlphaMultiplyMask_1",
					Source = "Output",
				}
			},
			ViewInfo = GroupInfo { Pos = { 275, 148.5 } },
			Tools = ordered() {
				AlphaMultiplyMask_1 = AlphaMultiply {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "ColorCorrectorMask_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 109.646, 72.6145 } },
				},
				ColorCorrectorMask_1 = ColorCorrector {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						WheelSaturation1 = Input { Value = 0, },
						ColorRanges = Input {
							Value = ColorCurves {
								Curves = {
									{
										Points = {
											{ 0, 1 },
											{ 0.4, 0.2 },
											{ 0.6, 0 },
											{ 1, 0 }
										}
									},
									{
										Points = {
											{ 0, 0 },
											{ 0.4, 0 },
											{ 0.6, 0.2 },
											{ 1, 1 }
										}
									}
								}
							},
						},
						HistogramIgnoreTransparent = Input { Value = 1, },
						Input = Input {
							SourceOp = "AlphaDivideMask_1",
							Source = "Output",
						},
						EffectMask = Input {
							SourceOp = "GradientMaskBackground_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0.3535, 73.3216 } },
				},
				GradientMaskBackground_1 = Background {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input { Value = 3840, },
						Height = Input { Value = 1920, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						Type = Input { Value = FuID { "Gradient" }, },
						Start = Input { Value = { 1, 0.5 }, },
						End = Input { Value = { 0.5, 0.5 }, },
						Gradient = Input {
							Value = Gradient {
								Colors = {
									[0] = { 0, 0, 0, 0 },
									[1] = { 1, 1, 1, 1 }
								}
							},
						},
					},
					ViewInfo = OperatorInfo { Pos = { 7.7325, 10.15 } },
				},
				AlphaDivideMask_1 = AlphaDivide {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Loader1_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -109.646, 74.0287 } },
				}
			},
		},
		ColorCorrectorMasked3 = GroupOperator {
			CtrlWZoom = false,
			NameSet = true,
			Inputs = ordered() {
				Input251 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "Width",
					Default = 3840,
				},
				Input252 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "Height",
					Default = 1920,
				},
				Input253 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "Depth",
					Default = 0,
				},
				Input254 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "Type",
				},
				Input255 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "TopLeftRed",
					Name = "Top Left",
					ControlGroup = 164,
					Default = 0,
				},
				Input256 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "TopLeftGreen",
					ControlGroup = 164,
					Default = 0,
				},
				Input257 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "TopLeftBlue",
					ControlGroup = 164,
					Default = 0,
				},
				Input258 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "TopLeftAlpha",
					ControlGroup = 164,
					Default = 1,
				},
				Input259 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "TopRightRed",
					Name = "Top Right",
					ControlGroup = 165,
					Default = 0,
				},
				Input260 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "TopRightGreen",
					ControlGroup = 165,
					Default = 0,
				},
				Input261 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "TopRightBlue",
					ControlGroup = 165,
					Default = 0,
				},
				Input262 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "TopRightAlpha",
					ControlGroup = 165,
					Default = 1,
				},
				Input263 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "BottomLeftRed",
					Name = "Bottom Left",
					ControlGroup = 166,
					Default = 0,
				},
				Input264 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "BottomLeftGreen",
					ControlGroup = 166,
					Default = 0,
				},
				Input265 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "BottomLeftBlue",
					ControlGroup = 166,
					Default = 0,
				},
				Input266 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "BottomLeftAlpha",
					ControlGroup = 166,
					Default = 1,
				},
				Input267 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "BottomRightRed",
					Name = "Bottom Right",
					ControlGroup = 167,
					Default = 0,
				},
				Input268 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "BottomRightGreen",
					ControlGroup = 167,
					Default = 0,
				},
				Input269 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "BottomRightBlue",
					ControlGroup = 167,
					Default = 0,
				},
				Input270 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "BottomRightAlpha",
					ControlGroup = 167,
					Default = 1,
				},
				Input271 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "GradientType",
				},
				Input272 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "Start",
					DefaultX = 0.5,
					DefaultY = 1,
				},
				Input273 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "End",
					DefaultX = 0.5,
					DefaultY = 0.5,
				},
				Input274 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "Gradient",
				},
				Input275 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "GradientInterpolationMethod",
				},
				Input276 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "Offset",
					Default = 0,
				},
				Input277 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "Repeat",
				},
				Input278 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "SubPixel",
				},
				Input279 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "MotionBlur",
					Default = 0,
				},
				Input280 = InstanceInput {
					SourceOp = "GradientMaskBackground_1_1",
					Source = "Quality",
					Default = 2,
				},
				MainInput1 = InstanceInput {
					SourceOp = "AlphaDivideMask_1_1",
					Source = "Input",
				},
				Input1 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Menu",
				},
				Input2 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "CorrectionRange",
				},
				Input3 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "WheelHue1",
					ControlGroup = 3,
				},
				Input4 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "WheelSaturation1",
					ControlGroup = 3,
					Default = 1,
				},
				Input5 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "WheelTintAngle1",
					ControlGroup = 3,
				},
				Input6 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "WheelTintLength1",
					ControlGroup = 3,
				},
				Input7 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "WheelRangeDummy1",
					ControlGroup = 3,
					Default = 0,
				},
				Input8 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "WheelHue2",
					ControlGroup = 3,
				},
				Input9 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "WheelSaturation2",
					ControlGroup = 3,
					Default = 1,
				},
				Input10 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "WheelTintAngle2",
					ControlGroup = 3,
				},
				Input11 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "WheelTintLength2",
					ControlGroup = 3,
				},
				Input12 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "WheelHue3",
					ControlGroup = 3,
				},
				Input13 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "WheelSaturation3",
					ControlGroup = 3,
					Default = 1,
				},
				Input14 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "WheelTintAngle3",
					ControlGroup = 3,
				},
				Input15 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "WheelTintLength3",
					ControlGroup = 3,
				},
				Input16 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "WheelHue4",
					ControlGroup = 3,
				},
				Input17 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "WheelSaturation4",
					ControlGroup = 3,
					Default = 1,
				},
				Input18 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "WheelTintAngle4",
					ControlGroup = 3,
				},
				Input19 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "WheelTintLength4",
					ControlGroup = 3,
				},
				Input20 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "TintMode",
					Default = 2,
				},
				Input21 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Hue1",
				},
				Input22 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Saturation1",
					Default = 1,
				},
				Input23 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Hue2",
				},
				Input24 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Saturation2",
					Default = 1,
				},
				Input25 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Hue3",
				},
				Input26 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Saturation3",
					Default = 1,
				},
				Input27 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Hue4",
				},
				Input28 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Saturation4",
					Default = 1,
				},
				Input29 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Channel",
				},
				Input30 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Histogram",
					ControlGroup = 14,
				},
				Input31 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HistogramReference",
					ControlGroup = 14,
				},
				Input32 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HistogramOutput",
					ControlGroup = 14,
				},
				Input33 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HistogramCurve",
					ControlGroup = 14,
				},
				Input34 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HistogramType",
				},
				Input35 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "EqualizeLuminance",
					Default = 0,
				},
				Input36 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "LockRedGreenBlue",
					Default = 1,
				},
				Input37 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "EqualizeRed",
					Default = 1,
				},
				Input38 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "EqualizeGreen",
					Default = 1,
				},
				Input39 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "EqualizeBlue",
					Default = 1,
				},
				Input40 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Precision",
					Default = 2,
				},
				Input41 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "SmoothOutCorrectionCurve",
					Default = 0,
				},
				Input42 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "SnapshotMatch",
				},
				Input43 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ReleaseMatch",
				},
				Input44 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MatchShow",
					Default = 0,
				},
				Input45 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MatchCenter",
					DefaultX = 0.5,
					DefaultY = 0.5,
				},
				Input46 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MatchWidth",
					Default = 1,
				},
				Input47 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MatchHeight",
					Default = 1,
				},
				Input48 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ResetAllHistogramChanges",
				},
				Input49 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRGBContrast",
					Default = 1,
				},
				Input50 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRGBGain",
					Default = 1,
				},
				Input51 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRGBLift",
					Default = 0,
				},
				Input52 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRGBGamma",
					Default = 1,
				},
				Input53 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRGBBrightness",
					Default = 0,
				},
				Input54 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRGBLow",
					ControlGroup = 35,
					Default = 0,
				},
				Input55 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRGBMid",
					ControlGroup = 35,
					Default = 1,
				},
				Input56 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRGBHigh",
					ControlGroup = 35,
					Default = 1,
				},
				Input57 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRGBOutputLow",
					ControlGroup = 36,
					Default = 0,
				},
				Input58 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRGBOutputHigh",
					ControlGroup = 36,
					Default = 1,
				},
				Input59 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRedContrast",
					Default = 1,
				},
				Input60 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRedGain",
					Default = 1,
				},
				Input61 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRedLift",
					Default = 0,
				},
				Input62 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRedGamma",
					Default = 1,
				},
				Input63 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRedBrightness",
					Default = 0,
				},
				Input64 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRedLow",
					ControlGroup = 42,
					Default = 0,
				},
				Input65 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRedMid",
					ControlGroup = 42,
					Default = 1,
				},
				Input66 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRedHigh",
					ControlGroup = 42,
					Default = 1,
				},
				Input67 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRedOutputLow",
					ControlGroup = 43,
					Default = 0,
				},
				Input68 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterRedOutputHigh",
					ControlGroup = 43,
					Default = 1,
				},
				Input69 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterGreenContrast",
					Default = 1,
				},
				Input70 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterGreenGain",
					Default = 1,
				},
				Input71 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterGreenLift",
					Default = 0,
				},
				Input72 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterGreenGamma",
					Default = 1,
				},
				Input73 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterGreenBrightness",
					Default = 0,
				},
				Input74 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterGreenLow",
					ControlGroup = 49,
					Default = 0,
				},
				Input75 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterGreenMid",
					ControlGroup = 49,
					Default = 1,
				},
				Input76 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterGreenHigh",
					ControlGroup = 49,
					Default = 1,
				},
				Input77 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterGreenOutputLow",
					ControlGroup = 50,
					Default = 0,
				},
				Input78 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterGreenOutputHigh",
					ControlGroup = 50,
					Default = 1,
				},
				Input79 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterBlueContrast",
					Default = 1,
				},
				Input80 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterBlueGain",
					Default = 1,
				},
				Input81 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterBlueLift",
					Default = 0,
				},
				Input82 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterBlueGamma",
					Default = 1,
				},
				Input83 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterBlueBrightness",
					Default = 0,
				},
				Input84 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterBlueLow",
					ControlGroup = 56,
					Default = 0,
				},
				Input85 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterBlueMid",
					ControlGroup = 56,
					Default = 1,
				},
				Input86 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterBlueHigh",
					ControlGroup = 56,
					Default = 1,
				},
				Input87 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterBlueOutputLow",
					ControlGroup = 57,
					Default = 0,
				},
				Input88 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MasterBlueOutputHigh",
					ControlGroup = 57,
					Default = 1,
				},
				Input89 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRGBContrast",
					Default = 1,
				},
				Input90 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRGBGain",
					Default = 1,
				},
				Input91 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRGBLift",
					Default = 0,
				},
				Input92 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRGBGamma",
					Default = 1,
				},
				Input93 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRGBBrightness",
					Default = 0,
				},
				Input94 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRGBLow",
					ControlGroup = 63,
					Default = 0,
				},
				Input95 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRGBMid",
					ControlGroup = 63,
					Default = 1,
				},
				Input96 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRGBHigh",
					ControlGroup = 63,
					Default = 1,
				},
				Input97 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRGBOutputLow",
					ControlGroup = 64,
					Default = 0,
				},
				Input98 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRGBOutputHigh",
					ControlGroup = 64,
					Default = 1,
				},
				Input99 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRedContrast",
					Default = 1,
				},
				Input100 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRedGain",
					Default = 1,
				},
				Input101 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRedLift",
					Default = 0,
				},
				Input102 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRedGamma",
					Default = 1,
				},
				Input103 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRedBrightness",
					Default = 0,
				},
				Input104 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRedLow",
					ControlGroup = 70,
					Default = 0,
				},
				Input105 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRedMid",
					ControlGroup = 70,
					Default = 1,
				},
				Input106 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRedHigh",
					ControlGroup = 70,
					Default = 1,
				},
				Input107 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRedOutputLow",
					ControlGroup = 71,
					Default = 0,
				},
				Input108 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsRedOutputHigh",
					ControlGroup = 71,
					Default = 1,
				},
				Input109 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsGreenContrast",
					Default = 1,
				},
				Input110 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsGreenGain",
					Default = 1,
				},
				Input111 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsGreenLift",
					Default = 0,
				},
				Input112 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsGreenGamma",
					Default = 1,
				},
				Input113 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsGreenBrightness",
					Default = 0,
				},
				Input114 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsGreenLow",
					ControlGroup = 77,
					Default = 0,
				},
				Input115 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsGreenMid",
					ControlGroup = 77,
					Default = 1,
				},
				Input116 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsGreenHigh",
					ControlGroup = 77,
					Default = 1,
				},
				Input117 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsGreenOutputLow",
					ControlGroup = 78,
					Default = 0,
				},
				Input118 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsGreenOutputHigh",
					ControlGroup = 78,
					Default = 1,
				},
				Input119 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsBlueContrast",
					Default = 1,
				},
				Input120 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsBlueGain",
					Default = 1,
				},
				Input121 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsBlueLift",
					Default = 0,
				},
				Input122 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsBlueGamma",
					Default = 1,
				},
				Input123 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsBlueBrightness",
					Default = 0,
				},
				Input124 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsBlueLow",
					ControlGroup = 84,
					Default = 0,
				},
				Input125 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsBlueMid",
					ControlGroup = 84,
					Default = 1,
				},
				Input126 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsBlueHigh",
					ControlGroup = 84,
					Default = 1,
				},
				Input127 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsBlueOutputLow",
					ControlGroup = 85,
					Default = 0,
				},
				Input128 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ShadowsBlueOutputHigh",
					ControlGroup = 85,
					Default = 1,
				},
				Input129 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRGBContrast",
					Default = 1,
				},
				Input130 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRGBGain",
					Default = 1,
				},
				Input131 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRGBLift",
					Default = 0,
				},
				Input132 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRGBGamma",
					Default = 1,
				},
				Input133 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRGBBrightness",
					Default = 0,
				},
				Input134 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRGBLow",
					ControlGroup = 91,
					Default = 0,
				},
				Input135 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRGBMid",
					ControlGroup = 91,
					Default = 1,
				},
				Input136 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRGBHigh",
					ControlGroup = 91,
					Default = 1,
				},
				Input137 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRGBOutputLow",
					ControlGroup = 92,
					Default = 0,
				},
				Input138 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRGBOutputHigh",
					ControlGroup = 92,
					Default = 1,
				},
				Input139 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRedContrast",
					Default = 1,
				},
				Input140 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRedGain",
					Default = 1,
				},
				Input141 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRedLift",
					Default = 0,
				},
				Input142 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRedGamma",
					Default = 1,
				},
				Input143 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRedBrightness",
					Default = 0,
				},
				Input144 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRedLow",
					ControlGroup = 98,
					Default = 0,
				},
				Input145 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRedMid",
					ControlGroup = 98,
					Default = 1,
				},
				Input146 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRedHigh",
					ControlGroup = 98,
					Default = 1,
				},
				Input147 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRedOutputLow",
					ControlGroup = 99,
					Default = 0,
				},
				Input148 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesRedOutputHigh",
					ControlGroup = 99,
					Default = 1,
				},
				Input149 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesGreenContrast",
					Default = 1,
				},
				Input150 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesGreenGain",
					Default = 1,
				},
				Input151 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesGreenLift",
					Default = 0,
				},
				Input152 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesGreenGamma",
					Default = 1,
				},
				Input153 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesGreenBrightness",
					Default = 0,
				},
				Input154 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesGreenLow",
					ControlGroup = 105,
					Default = 0,
				},
				Input155 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesGreenMid",
					ControlGroup = 105,
					Default = 1,
				},
				Input156 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesGreenHigh",
					ControlGroup = 105,
					Default = 1,
				},
				Input157 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesGreenOutputLow",
					ControlGroup = 106,
					Default = 0,
				},
				Input158 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesGreenOutputHigh",
					ControlGroup = 106,
					Default = 1,
				},
				Input159 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesBlueContrast",
					Default = 1,
				},
				Input160 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesBlueGain",
					Default = 1,
				},
				Input161 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesBlueLift",
					Default = 0,
				},
				Input162 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesBlueGamma",
					Default = 1,
				},
				Input163 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesBlueBrightness",
					Default = 0,
				},
				Input164 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesBlueLow",
					ControlGroup = 112,
					Default = 0,
				},
				Input165 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesBlueMid",
					ControlGroup = 112,
					Default = 1,
				},
				Input166 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesBlueHigh",
					ControlGroup = 112,
					Default = 1,
				},
				Input167 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesBlueOutputLow",
					ControlGroup = 113,
					Default = 0,
				},
				Input168 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "MidTonesBlueOutputHigh",
					ControlGroup = 113,
					Default = 1,
				},
				Input169 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRGBContrast",
					Default = 1,
				},
				Input170 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRGBGain",
					Default = 1,
				},
				Input171 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRGBLift",
					Default = 0,
				},
				Input172 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRGBGamma",
					Default = 1,
				},
				Input173 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRGBBrightness",
					Default = 0,
				},
				Input174 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRGBLow",
					ControlGroup = 119,
					Default = 0,
				},
				Input175 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRGBMid",
					ControlGroup = 119,
					Default = 1,
				},
				Input176 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRGBHigh",
					ControlGroup = 119,
					Default = 1,
				},
				Input177 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRGBOutputLow",
					ControlGroup = 120,
					Default = 0,
				},
				Input178 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRGBOutputHigh",
					ControlGroup = 120,
					Default = 1,
				},
				Input179 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRedContrast",
					Default = 1,
				},
				Input180 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRedGain",
					Default = 1,
				},
				Input181 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRedLift",
					Default = 0,
				},
				Input182 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRedGamma",
					Default = 1,
				},
				Input183 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRedBrightness",
					Default = 0,
				},
				Input184 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRedLow",
					ControlGroup = 126,
					Default = 0,
				},
				Input185 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRedMid",
					ControlGroup = 126,
					Default = 1,
				},
				Input186 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRedHigh",
					ControlGroup = 126,
					Default = 1,
				},
				Input187 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRedOutputLow",
					ControlGroup = 127,
					Default = 0,
				},
				Input188 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsRedOutputHigh",
					ControlGroup = 127,
					Default = 1,
				},
				Input189 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsGreenContrast",
					Default = 1,
				},
				Input190 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsGreenGain",
					Default = 1,
				},
				Input191 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsGreenLift",
					Default = 0,
				},
				Input192 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsGreenGamma",
					Default = 1,
				},
				Input193 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsGreenBrightness",
					Default = 0,
				},
				Input194 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsGreenLow",
					ControlGroup = 133,
					Default = 0,
				},
				Input195 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsGreenMid",
					ControlGroup = 133,
					Default = 1,
				},
				Input196 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsGreenHigh",
					ControlGroup = 133,
					Default = 1,
				},
				Input197 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsGreenOutputLow",
					ControlGroup = 134,
					Default = 0,
				},
				Input198 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsGreenOutputHigh",
					ControlGroup = 134,
					Default = 1,
				},
				Input199 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsBlueContrast",
					Default = 1,
				},
				Input200 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsBlueGain",
					Default = 1,
				},
				Input201 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsBlueLift",
					Default = 0,
				},
				Input202 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsBlueGamma",
					Default = 1,
				},
				Input203 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsBlueBrightness",
					Default = 0,
				},
				Input204 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsBlueLow",
					ControlGroup = 140,
					Default = 0,
				},
				Input205 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsBlueMid",
					ControlGroup = 140,
					Default = 1,
				},
				Input206 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsBlueHigh",
					ControlGroup = 140,
					Default = 1,
				},
				Input207 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsBlueOutputLow",
					ControlGroup = 141,
					Default = 0,
				},
				Input208 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "HighlightsBlueOutputHigh",
					ControlGroup = 141,
					Default = 1,
				},
				Input209 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ResetAllColorChanges",
				},
				Input210 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ResetAllLevels",
				},
				Input211 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Red1",
					ControlGroup = 144,
					Default = 1,
				},
				Input212 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Yellow1",
					ControlGroup = 144,
					Default = 1,
				},
				Input213 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Green1",
					ControlGroup = 144,
					Default = 1,
				},
				Input214 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Cyan1",
					ControlGroup = 144,
					Default = 1,
				},
				Input215 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Blue1",
					ControlGroup = 144,
					Default = 1,
				},
				Input216 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Magenta1",
					ControlGroup = 144,
					Default = 1,
				},
				Input217 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Red2",
					ControlGroup = 144,
					Default = 1,
				},
				Input218 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Yellow2",
					ControlGroup = 144,
					Default = 1,
				},
				Input219 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Green2",
					ControlGroup = 144,
					Default = 1,
				},
				Input220 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Cyan2",
					ControlGroup = 144,
					Default = 1,
				},
				Input221 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Blue2",
					ControlGroup = 144,
					Default = 1,
				},
				Input222 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Magenta2",
					ControlGroup = 144,
					Default = 1,
				},
				Input223 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Red3",
					ControlGroup = 144,
					Default = 1,
				},
				Input224 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Yellow3",
					ControlGroup = 144,
					Default = 1,
				},
				Input225 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Green3",
					ControlGroup = 144,
					Default = 1,
				},
				Input226 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Cyan3",
					ControlGroup = 144,
					Default = 1,
				},
				Input227 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Blue3",
					ControlGroup = 144,
					Default = 1,
				},
				Input228 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Magenta3",
					ControlGroup = 144,
					Default = 1,
				},
				Input229 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Red4",
					ControlGroup = 144,
					Default = 1,
				},
				Input230 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Yellow4",
					ControlGroup = 144,
					Default = 1,
				},
				Input231 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Green4",
					ControlGroup = 144,
					Default = 1,
				},
				Input232 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Cyan4",
					ControlGroup = 144,
					Default = 1,
				},
				Input233 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Blue4",
					ControlGroup = 144,
					Default = 1,
				},
				Input234 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Magenta4",
					ControlGroup = 144,
					Default = 1,
				},
				Input235 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "SuppressionRangeDummy",
					ControlGroup = 144,
				},
				Input236 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "SuppressionAngle1",
					MaxScale = 0.1666666666667,
					Default = 0,
				},
				Input237 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "SuppressionAngle2",
					MaxScale = 0.1666666666667,
					Default = 0,
				},
				Input238 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "SuppressionAngle3",
					MaxScale = 0.1666666666667,
					Default = 0,
				},
				Input239 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "SuppressionAngle4",
					MaxScale = 0.1666666666667,
					Default = 0,
				},
				Input240 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ResetAllSuppression",
				},
				Input241 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "RangesRange",
					Name = "Range",
				},
				Input242 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "RangesChannel",
				},
				Input243 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ColorRanges",
				},
				Input244 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "RenderOutputRange",
					Default = 0,
				},
				Input245 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "PresetSimpleRanges",
				},
				Input246 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "PresetSmoothRanges",
				},
				Input247 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "Blend",
					Default = 1,
				},
				Input248 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ProcessRed",
					Name = "Red",
					Default = 1,
				},
				Input249 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ProcessGreen",
					Name = "Green",
					Default = 1,
				},
				Input250 = InstanceInput {
					SourceOp = "ColorCorrectorMask_1_1",
					Source = "ProcessBlue",
					Name = "Blue",
					Default = 1,
				}
			},
			Outputs = {
				MainOutput1 = InstanceOutput {
					SourceOp = "AlphaMultiplyMask_1_1",
					Source = "Output",
				}
			},
			ViewInfo = GroupInfo { Pos = { 275, 247.5 } },
			Tools = ordered() {
				AlphaMultiplyMask_1_1 = AlphaMultiply {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "ColorCorrectorMask_1_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 109.646, 72.6145 } },
				},
				ColorCorrectorMask_1_1 = ColorCorrector {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						WheelSaturation1 = Input { Value = 0, },
						ColorRanges = Input {
							Value = ColorCurves {
								Curves = {
									{
										Points = {
											{ 0, 1 },
											{ 0.4, 0.2 },
											{ 0.6, 0 },
											{ 1, 0 }
										}
									},
									{
										Points = {
											{ 0, 0 },
											{ 0.4, 0 },
											{ 0.6, 0.2 },
											{ 1, 1 }
										}
									}
								}
							},
						},
						HistogramIgnoreTransparent = Input { Value = 1, },
						Input = Input {
							SourceOp = "AlphaDivideMask_1_1",
							Source = "Output",
						},
						EffectMask = Input {
							SourceOp = "GradientMaskBackground_1_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0.3535, 73.3216 } },
				},
				GradientMaskBackground_1_1 = Background {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input { Value = 3840, },
						Height = Input { Value = 1920, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						Type = Input { Value = FuID { "Gradient" }, },
						Start = Input { Value = { 1, 0.5 }, },
						End = Input { Value = { 0, 0.5 }, },
						Gradient = Input {
							Value = Gradient {
								Colors = {
									[0] = { 1, 1, 1, 0.8232044198895 },
									[0.5] = { 0, 0, 0, 0 },
									[1] = { 1, 1, 1, 1 }
								}
							},
						},
					},
					ViewInfo = OperatorInfo { Pos = { 7.7325, 10.15 } },
				},
				AlphaDivideMask_1_1 = AlphaDivide {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Loader1_1_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -109.646, 74.0287 } },
				}
			},
		},
		Note1 = Note {
			Inputs = {
				Comments = Input { Value = "This example shows a vertical gradient effect that is used to fade off the saturation on the image at a certain point. This vertical gradient effect would typically be used to fix a brightness or contrast effect in the sky or tripod zone, or to apply a graduated neutral density filter type effect.", }
			},
			ViewInfo = StickyNoteInfo {
				Pos = { 110, -16.5 },
				Flags = {
					Expanded = true
				},
				Size = { 415.85, 40.0749 }
			},
		},
		Note3 = Note {
			NameSet = true,
			Inputs = {
				Comments = Input { Value = "The third example shows a horizontal gradient effect that has three control handles added to the gradient. These controls are used to fade off the saturation on the image at a certain point. This horizontal gradient effect would typically be used to fix a contrast issue with one part of a stitched camera view in a LatLong image.", }
			},
			ViewInfo = StickyNoteInfo {
				Pos = { 110.422, 181.5 },
				Flags = {
					Expanded = true
				},
				Size = { 410.622, 40.0749 }
			},
		},
		ColorCorrectorMasked1 = GroupOperator {
			NameSet = true,
			Inputs = ordered() {
				Input251 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "Width",
					Default = 3840,
				},
				Input252 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "Height",
					Default = 1920,
				},
				Input253 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "Depth",
					Default = 0,
				},
				Input254 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "Type",
				},
				Input255 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "TopLeftRed",
					Name = "Top Left",
					ControlGroup = 164,
					Default = 0,
				},
				Input256 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "TopLeftGreen",
					ControlGroup = 164,
					Default = 0,
				},
				Input257 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "TopLeftBlue",
					ControlGroup = 164,
					Default = 0,
				},
				Input258 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "TopLeftAlpha",
					ControlGroup = 164,
					Default = 1,
				},
				Input259 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "TopRightRed",
					Name = "Top Right",
					ControlGroup = 165,
					Default = 0,
				},
				Input260 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "TopRightGreen",
					ControlGroup = 165,
					Default = 0,
				},
				Input261 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "TopRightBlue",
					ControlGroup = 165,
					Default = 0,
				},
				Input262 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "TopRightAlpha",
					ControlGroup = 165,
					Default = 1,
				},
				Input263 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "BottomLeftRed",
					Name = "Bottom Left",
					ControlGroup = 166,
					Default = 0,
				},
				Input264 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "BottomLeftGreen",
					ControlGroup = 166,
					Default = 0,
				},
				Input265 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "BottomLeftBlue",
					ControlGroup = 166,
					Default = 0,
				},
				Input266 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "BottomLeftAlpha",
					ControlGroup = 166,
					Default = 1,
				},
				Input267 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "BottomRightRed",
					Name = "Bottom Right",
					ControlGroup = 167,
					Default = 0,
				},
				Input268 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "BottomRightGreen",
					ControlGroup = 167,
					Default = 0,
				},
				Input269 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "BottomRightBlue",
					ControlGroup = 167,
					Default = 0,
				},
				Input270 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "BottomRightAlpha",
					ControlGroup = 167,
					Default = 1,
				},
				Input271 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "GradientType",
				},
				Input272 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "Start",
					DefaultX = 0.5,
					DefaultY = 1,
				},
				Input273 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "End",
					DefaultX = 0.5,
					DefaultY = 0.5,
				},
				Input274 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "Gradient",
				},
				Input275 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "GradientInterpolationMethod",
				},
				Input276 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "Offset",
					Default = 0,
				},
				Input277 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "Repeat",
				},
				Input278 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "SubPixel",
				},
				Input279 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "MotionBlur",
					Default = 0,
				},
				Input280 = InstanceInput {
					SourceOp = "GradientMaskBackground",
					Source = "Quality",
					Default = 2,
				},
				MainInput1 = InstanceInput {
					SourceOp = "AlphaDivideMask",
					Source = "Input",
				},
				Input1 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Menu",
				},
				Input2 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "CorrectionRange",
				},
				Input3 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "WheelHue1",
					ControlGroup = 3,
				},
				Input4 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "WheelSaturation1",
					ControlGroup = 3,
					Default = 1,
				},
				Input5 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "WheelTintAngle1",
					ControlGroup = 3,
				},
				Input6 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "WheelTintLength1",
					ControlGroup = 3,
				},
				Input7 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "WheelRangeDummy1",
					ControlGroup = 3,
					Default = 0,
				},
				Input8 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "WheelHue2",
					ControlGroup = 3,
				},
				Input9 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "WheelSaturation2",
					ControlGroup = 3,
					Default = 1,
				},
				Input10 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "WheelTintAngle2",
					ControlGroup = 3,
				},
				Input11 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "WheelTintLength2",
					ControlGroup = 3,
				},
				Input12 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "WheelHue3",
					ControlGroup = 3,
				},
				Input13 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "WheelSaturation3",
					ControlGroup = 3,
					Default = 1,
				},
				Input14 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "WheelTintAngle3",
					ControlGroup = 3,
				},
				Input15 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "WheelTintLength3",
					ControlGroup = 3,
				},
				Input16 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "WheelHue4",
					ControlGroup = 3,
				},
				Input17 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "WheelSaturation4",
					ControlGroup = 3,
					Default = 1,
				},
				Input18 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "WheelTintAngle4",
					ControlGroup = 3,
				},
				Input19 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "WheelTintLength4",
					ControlGroup = 3,
				},
				Input20 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "TintMode",
					Default = 2,
				},
				Input21 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Hue1",
				},
				Input22 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Saturation1",
					Default = 1,
				},
				Input23 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Hue2",
				},
				Input24 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Saturation2",
					Default = 1,
				},
				Input25 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Hue3",
				},
				Input26 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Saturation3",
					Default = 1,
				},
				Input27 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Hue4",
				},
				Input28 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Saturation4",
					Default = 1,
				},
				Input29 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Channel",
				},
				Input30 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Histogram",
					ControlGroup = 14,
				},
				Input31 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HistogramReference",
					ControlGroup = 14,
				},
				Input32 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HistogramOutput",
					ControlGroup = 14,
				},
				Input33 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HistogramCurve",
					ControlGroup = 14,
				},
				Input34 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HistogramType",
				},
				Input35 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "EqualizeLuminance",
					Default = 0,
				},
				Input36 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "LockRedGreenBlue",
					Default = 1,
				},
				Input37 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "EqualizeRed",
					Default = 1,
				},
				Input38 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "EqualizeGreen",
					Default = 1,
				},
				Input39 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "EqualizeBlue",
					Default = 1,
				},
				Input40 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Precision",
					Default = 2,
				},
				Input41 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "SmoothOutCorrectionCurve",
					Default = 0,
				},
				Input42 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "SnapshotMatch",
				},
				Input43 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ReleaseMatch",
				},
				Input44 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MatchShow",
					Default = 0,
				},
				Input45 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MatchCenter",
					DefaultX = 0.5,
					DefaultY = 0.5,
				},
				Input46 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MatchWidth",
					Default = 1,
				},
				Input47 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MatchHeight",
					Default = 1,
				},
				Input48 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ResetAllHistogramChanges",
				},
				Input49 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRGBContrast",
					Default = 1,
				},
				Input50 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRGBGain",
					Default = 1,
				},
				Input51 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRGBLift",
					Default = 0,
				},
				Input52 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRGBGamma",
					Default = 1,
				},
				Input53 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRGBBrightness",
					Default = 0,
				},
				Input54 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRGBLow",
					ControlGroup = 35,
					Default = 0,
				},
				Input55 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRGBMid",
					ControlGroup = 35,
					Default = 1,
				},
				Input56 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRGBHigh",
					ControlGroup = 35,
					Default = 1,
				},
				Input57 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRGBOutputLow",
					ControlGroup = 36,
					Default = 0,
				},
				Input58 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRGBOutputHigh",
					ControlGroup = 36,
					Default = 1,
				},
				Input59 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRedContrast",
					Default = 1,
				},
				Input60 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRedGain",
					Default = 1,
				},
				Input61 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRedLift",
					Default = 0,
				},
				Input62 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRedGamma",
					Default = 1,
				},
				Input63 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRedBrightness",
					Default = 0,
				},
				Input64 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRedLow",
					ControlGroup = 42,
					Default = 0,
				},
				Input65 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRedMid",
					ControlGroup = 42,
					Default = 1,
				},
				Input66 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRedHigh",
					ControlGroup = 42,
					Default = 1,
				},
				Input67 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRedOutputLow",
					ControlGroup = 43,
					Default = 0,
				},
				Input68 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterRedOutputHigh",
					ControlGroup = 43,
					Default = 1,
				},
				Input69 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterGreenContrast",
					Default = 1,
				},
				Input70 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterGreenGain",
					Default = 1,
				},
				Input71 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterGreenLift",
					Default = 0,
				},
				Input72 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterGreenGamma",
					Default = 1,
				},
				Input73 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterGreenBrightness",
					Default = 0,
				},
				Input74 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterGreenLow",
					ControlGroup = 49,
					Default = 0,
				},
				Input75 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterGreenMid",
					ControlGroup = 49,
					Default = 1,
				},
				Input76 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterGreenHigh",
					ControlGroup = 49,
					Default = 1,
				},
				Input77 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterGreenOutputLow",
					ControlGroup = 50,
					Default = 0,
				},
				Input78 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterGreenOutputHigh",
					ControlGroup = 50,
					Default = 1,
				},
				Input79 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterBlueContrast",
					Default = 1,
				},
				Input80 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterBlueGain",
					Default = 1,
				},
				Input81 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterBlueLift",
					Default = 0,
				},
				Input82 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterBlueGamma",
					Default = 1,
				},
				Input83 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterBlueBrightness",
					Default = 0,
				},
				Input84 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterBlueLow",
					ControlGroup = 56,
					Default = 0,
				},
				Input85 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterBlueMid",
					ControlGroup = 56,
					Default = 1,
				},
				Input86 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterBlueHigh",
					ControlGroup = 56,
					Default = 1,
				},
				Input87 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterBlueOutputLow",
					ControlGroup = 57,
					Default = 0,
				},
				Input88 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MasterBlueOutputHigh",
					ControlGroup = 57,
					Default = 1,
				},
				Input89 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRGBContrast",
					Default = 1,
				},
				Input90 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRGBGain",
					Default = 1,
				},
				Input91 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRGBLift",
					Default = 0,
				},
				Input92 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRGBGamma",
					Default = 1,
				},
				Input93 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRGBBrightness",
					Default = 0,
				},
				Input94 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRGBLow",
					ControlGroup = 63,
					Default = 0,
				},
				Input95 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRGBMid",
					ControlGroup = 63,
					Default = 1,
				},
				Input96 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRGBHigh",
					ControlGroup = 63,
					Default = 1,
				},
				Input97 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRGBOutputLow",
					ControlGroup = 64,
					Default = 0,
				},
				Input98 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRGBOutputHigh",
					ControlGroup = 64,
					Default = 1,
				},
				Input99 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRedContrast",
					Default = 1,
				},
				Input100 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRedGain",
					Default = 1,
				},
				Input101 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRedLift",
					Default = 0,
				},
				Input102 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRedGamma",
					Default = 1,
				},
				Input103 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRedBrightness",
					Default = 0,
				},
				Input104 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRedLow",
					ControlGroup = 70,
					Default = 0,
				},
				Input105 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRedMid",
					ControlGroup = 70,
					Default = 1,
				},
				Input106 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRedHigh",
					ControlGroup = 70,
					Default = 1,
				},
				Input107 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRedOutputLow",
					ControlGroup = 71,
					Default = 0,
				},
				Input108 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsRedOutputHigh",
					ControlGroup = 71,
					Default = 1,
				},
				Input109 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsGreenContrast",
					Default = 1,
				},
				Input110 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsGreenGain",
					Default = 1,
				},
				Input111 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsGreenLift",
					Default = 0,
				},
				Input112 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsGreenGamma",
					Default = 1,
				},
				Input113 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsGreenBrightness",
					Default = 0,
				},
				Input114 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsGreenLow",
					ControlGroup = 77,
					Default = 0,
				},
				Input115 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsGreenMid",
					ControlGroup = 77,
					Default = 1,
				},
				Input116 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsGreenHigh",
					ControlGroup = 77,
					Default = 1,
				},
				Input117 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsGreenOutputLow",
					ControlGroup = 78,
					Default = 0,
				},
				Input118 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsGreenOutputHigh",
					ControlGroup = 78,
					Default = 1,
				},
				Input119 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsBlueContrast",
					Default = 1,
				},
				Input120 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsBlueGain",
					Default = 1,
				},
				Input121 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsBlueLift",
					Default = 0,
				},
				Input122 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsBlueGamma",
					Default = 1,
				},
				Input123 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsBlueBrightness",
					Default = 0,
				},
				Input124 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsBlueLow",
					ControlGroup = 84,
					Default = 0,
				},
				Input125 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsBlueMid",
					ControlGroup = 84,
					Default = 1,
				},
				Input126 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsBlueHigh",
					ControlGroup = 84,
					Default = 1,
				},
				Input127 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsBlueOutputLow",
					ControlGroup = 85,
					Default = 0,
				},
				Input128 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ShadowsBlueOutputHigh",
					ControlGroup = 85,
					Default = 1,
				},
				Input129 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRGBContrast",
					Default = 1,
				},
				Input130 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRGBGain",
					Default = 1,
				},
				Input131 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRGBLift",
					Default = 0,
				},
				Input132 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRGBGamma",
					Default = 1,
				},
				Input133 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRGBBrightness",
					Default = 0,
				},
				Input134 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRGBLow",
					ControlGroup = 91,
					Default = 0,
				},
				Input135 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRGBMid",
					ControlGroup = 91,
					Default = 1,
				},
				Input136 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRGBHigh",
					ControlGroup = 91,
					Default = 1,
				},
				Input137 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRGBOutputLow",
					ControlGroup = 92,
					Default = 0,
				},
				Input138 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRGBOutputHigh",
					ControlGroup = 92,
					Default = 1,
				},
				Input139 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRedContrast",
					Default = 1,
				},
				Input140 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRedGain",
					Default = 1,
				},
				Input141 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRedLift",
					Default = 0,
				},
				Input142 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRedGamma",
					Default = 1,
				},
				Input143 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRedBrightness",
					Default = 0,
				},
				Input144 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRedLow",
					ControlGroup = 98,
					Default = 0,
				},
				Input145 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRedMid",
					ControlGroup = 98,
					Default = 1,
				},
				Input146 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRedHigh",
					ControlGroup = 98,
					Default = 1,
				},
				Input147 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRedOutputLow",
					ControlGroup = 99,
					Default = 0,
				},
				Input148 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesRedOutputHigh",
					ControlGroup = 99,
					Default = 1,
				},
				Input149 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesGreenContrast",
					Default = 1,
				},
				Input150 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesGreenGain",
					Default = 1,
				},
				Input151 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesGreenLift",
					Default = 0,
				},
				Input152 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesGreenGamma",
					Default = 1,
				},
				Input153 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesGreenBrightness",
					Default = 0,
				},
				Input154 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesGreenLow",
					ControlGroup = 105,
					Default = 0,
				},
				Input155 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesGreenMid",
					ControlGroup = 105,
					Default = 1,
				},
				Input156 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesGreenHigh",
					ControlGroup = 105,
					Default = 1,
				},
				Input157 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesGreenOutputLow",
					ControlGroup = 106,
					Default = 0,
				},
				Input158 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesGreenOutputHigh",
					ControlGroup = 106,
					Default = 1,
				},
				Input159 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesBlueContrast",
					Default = 1,
				},
				Input160 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesBlueGain",
					Default = 1,
				},
				Input161 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesBlueLift",
					Default = 0,
				},
				Input162 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesBlueGamma",
					Default = 1,
				},
				Input163 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesBlueBrightness",
					Default = 0,
				},
				Input164 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesBlueLow",
					ControlGroup = 112,
					Default = 0,
				},
				Input165 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesBlueMid",
					ControlGroup = 112,
					Default = 1,
				},
				Input166 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesBlueHigh",
					ControlGroup = 112,
					Default = 1,
				},
				Input167 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesBlueOutputLow",
					ControlGroup = 113,
					Default = 0,
				},
				Input168 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "MidTonesBlueOutputHigh",
					ControlGroup = 113,
					Default = 1,
				},
				Input169 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRGBContrast",
					Default = 1,
				},
				Input170 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRGBGain",
					Default = 1,
				},
				Input171 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRGBLift",
					Default = 0,
				},
				Input172 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRGBGamma",
					Default = 1,
				},
				Input173 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRGBBrightness",
					Default = 0,
				},
				Input174 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRGBLow",
					ControlGroup = 119,
					Default = 0,
				},
				Input175 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRGBMid",
					ControlGroup = 119,
					Default = 1,
				},
				Input176 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRGBHigh",
					ControlGroup = 119,
					Default = 1,
				},
				Input177 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRGBOutputLow",
					ControlGroup = 120,
					Default = 0,
				},
				Input178 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRGBOutputHigh",
					ControlGroup = 120,
					Default = 1,
				},
				Input179 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRedContrast",
					Default = 1,
				},
				Input180 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRedGain",
					Default = 1,
				},
				Input181 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRedLift",
					Default = 0,
				},
				Input182 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRedGamma",
					Default = 1,
				},
				Input183 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRedBrightness",
					Default = 0,
				},
				Input184 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRedLow",
					ControlGroup = 126,
					Default = 0,
				},
				Input185 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRedMid",
					ControlGroup = 126,
					Default = 1,
				},
				Input186 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRedHigh",
					ControlGroup = 126,
					Default = 1,
				},
				Input187 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRedOutputLow",
					ControlGroup = 127,
					Default = 0,
				},
				Input188 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsRedOutputHigh",
					ControlGroup = 127,
					Default = 1,
				},
				Input189 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsGreenContrast",
					Default = 1,
				},
				Input190 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsGreenGain",
					Default = 1,
				},
				Input191 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsGreenLift",
					Default = 0,
				},
				Input192 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsGreenGamma",
					Default = 1,
				},
				Input193 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsGreenBrightness",
					Default = 0,
				},
				Input194 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsGreenLow",
					ControlGroup = 133,
					Default = 0,
				},
				Input195 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsGreenMid",
					ControlGroup = 133,
					Default = 1,
				},
				Input196 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsGreenHigh",
					ControlGroup = 133,
					Default = 1,
				},
				Input197 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsGreenOutputLow",
					ControlGroup = 134,
					Default = 0,
				},
				Input198 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsGreenOutputHigh",
					ControlGroup = 134,
					Default = 1,
				},
				Input199 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsBlueContrast",
					Default = 1,
				},
				Input200 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsBlueGain",
					Default = 1,
				},
				Input201 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsBlueLift",
					Default = 0,
				},
				Input202 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsBlueGamma",
					Default = 1,
				},
				Input203 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsBlueBrightness",
					Default = 0,
				},
				Input204 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsBlueLow",
					ControlGroup = 140,
					Default = 0,
				},
				Input205 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsBlueMid",
					ControlGroup = 140,
					Default = 1,
				},
				Input206 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsBlueHigh",
					ControlGroup = 140,
					Default = 1,
				},
				Input207 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsBlueOutputLow",
					ControlGroup = 141,
					Default = 0,
				},
				Input208 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "HighlightsBlueOutputHigh",
					ControlGroup = 141,
					Default = 1,
				},
				Input209 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ResetAllColorChanges",
				},
				Input210 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ResetAllLevels",
				},
				Input211 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Red1",
					ControlGroup = 144,
					Default = 1,
				},
				Input212 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Yellow1",
					ControlGroup = 144,
					Default = 1,
				},
				Input213 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Green1",
					ControlGroup = 144,
					Default = 1,
				},
				Input214 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Cyan1",
					ControlGroup = 144,
					Default = 1,
				},
				Input215 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Blue1",
					ControlGroup = 144,
					Default = 1,
				},
				Input216 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Magenta1",
					ControlGroup = 144,
					Default = 1,
				},
				Input217 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Red2",
					ControlGroup = 144,
					Default = 1,
				},
				Input218 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Yellow2",
					ControlGroup = 144,
					Default = 1,
				},
				Input219 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Green2",
					ControlGroup = 144,
					Default = 1,
				},
				Input220 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Cyan2",
					ControlGroup = 144,
					Default = 1,
				},
				Input221 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Blue2",
					ControlGroup = 144,
					Default = 1,
				},
				Input222 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Magenta2",
					ControlGroup = 144,
					Default = 1,
				},
				Input223 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Red3",
					ControlGroup = 144,
					Default = 1,
				},
				Input224 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Yellow3",
					ControlGroup = 144,
					Default = 1,
				},
				Input225 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Green3",
					ControlGroup = 144,
					Default = 1,
				},
				Input226 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Cyan3",
					ControlGroup = 144,
					Default = 1,
				},
				Input227 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Blue3",
					ControlGroup = 144,
					Default = 1,
				},
				Input228 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Magenta3",
					ControlGroup = 144,
					Default = 1,
				},
				Input229 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Red4",
					ControlGroup = 144,
					Default = 1,
				},
				Input230 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Yellow4",
					ControlGroup = 144,
					Default = 1,
				},
				Input231 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Green4",
					ControlGroup = 144,
					Default = 1,
				},
				Input232 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Cyan4",
					ControlGroup = 144,
					Default = 1,
				},
				Input233 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Blue4",
					ControlGroup = 144,
					Default = 1,
				},
				Input234 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Magenta4",
					ControlGroup = 144,
					Default = 1,
				},
				Input235 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "SuppressionRangeDummy",
					ControlGroup = 144,
				},
				Input236 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "SuppressionAngle1",
					MaxScale = 0.1666666666667,
					Default = 0,
				},
				Input237 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "SuppressionAngle2",
					MaxScale = 0.1666666666667,
					Default = 0,
				},
				Input238 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "SuppressionAngle3",
					MaxScale = 0.1666666666667,
					Default = 0,
				},
				Input239 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "SuppressionAngle4",
					MaxScale = 0.1666666666667,
					Default = 0,
				},
				Input240 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ResetAllSuppression",
				},
				Input241 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "RangesRange",
					Name = "Range",
				},
				Input242 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "RangesChannel",
				},
				Input243 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ColorRanges",
				},
				Input244 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "RenderOutputRange",
					Default = 0,
				},
				Input245 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "PresetSimpleRanges",
				},
				Input246 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "PresetSmoothRanges",
				},
				Input247 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "Blend",
					Default = 1,
				},
				Input248 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ProcessRed",
					Name = "Red",
					Default = 1,
				},
				Input249 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ProcessGreen",
					Name = "Green",
					Default = 1,
				},
				Input250 = InstanceInput {
					SourceOp = "ColorCorrectorMask",
					Source = "ProcessBlue",
					Name = "Blue",
					Default = 1,
				}
			},
			Outputs = {
				MainOutput1 = InstanceOutput {
					SourceOp = "AlphaMultiplyMask",
					Source = "Output",
				}
			},
			ViewInfo = GroupInfo { Pos = { 275, 49.5 } },
			Tools = ordered() {
				AlphaDivideMask = AlphaDivide {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Loader1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -109.646, 74.0287 } },
				},
				GradientMaskBackground = Background {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input { Value = 3840, },
						Height = Input { Value = 1920, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						Type = Input { Value = FuID { "Gradient" }, },
						Start = Input { Value = { 0.5, 1 }, },
						End = Input { Value = { 0.5, 0.5 }, },
						Gradient = Input {
							Value = Gradient {
								Colors = {
									[0] = { 0, 0, 0, 0 },
									[1] = { 1, 1, 1, 1 }
								}
							},
						},
					},
					ViewInfo = OperatorInfo { Pos = { 7.7325, 10.15 } },
				},
				ColorCorrectorMask = ColorCorrector {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						WheelSaturation1 = Input { Value = 0, },
						ColorRanges = Input {
							Value = ColorCurves {
								Curves = {
									{
										Points = {
											{ 0, 1 },
											{ 0.4, 0.2 },
											{ 0.6, 0 },
											{ 1, 0 }
										}
									},
									{
										Points = {
											{ 0, 0 },
											{ 0.4, 0 },
											{ 0.6, 0.2 },
											{ 1, 1 }
										}
									}
								}
							},
						},
						HistogramIgnoreTransparent = Input { Value = 1, },
						Input = Input {
							SourceOp = "AlphaDivideMask",
							Source = "Output",
						},
						EffectMask = Input {
							SourceOp = "GradientMaskBackground",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0.3535, 73.3216 } },
				},
				AlphaMultiplyMask = AlphaMultiply {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "ColorCorrectorMask",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 109.646, 72.6145 } },
				}
			},
		},
		Saver1_1_1 = Saver {
			CtrlWZoom = false,
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "Temp:\\KartaVR\\latlong-color-corrected-horizontal-gradient.0000.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				CreateDir = Input { Value = 1, },
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "AlphaMultiplyMask_1_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 385, 247.5 } },
		},
		Note2 = Note {
			NameSet = true,
			Inputs = {
				Comments = Input { Value = "This example shows a horizontal gradient effect that is used to fade off the saturation on the image at a certain point. This horizontal gradient effect would typically be used to fix seam issues where the contrast might not line up on the left and right frame edge on a LatLong panorama.", }
			},
			ViewInfo = StickyNoteInfo {
				Pos = { 109.578, 82.0779 },
				Flags = {
					Expanded = true
				},
				Size = { 412.336, 40.0749 }
			},
		},
		Saver1 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "Temp:\\KartaVR\\latlong-color-corrected-vertical.0000.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				CreateDir = Input { Value = 1, },
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "AlphaMultiplyMask",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 385, 49.5 } },
		},
		Saver1_1 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "Temp:\\KartaVR\\latlong-color-corrected-horizontal.0000.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				CreateDir = Input { Value = 1, },
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "AlphaMultiplyMask_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 385, 148.5 } },
		}
	},
	Views = {
		{
			FrameTypeID = "ChildFrame",
			Mode = 3,
			LayoutPreset = 0,
			Left = 0,
			Top = 27,
			Width = 3440,
			Height = 1238,
			Views = ordered() {
				Main = MultiView {
					Active = "Flow",
					ViewList = ordered() {
						Flow = "FlowView",
						Console = "ConsoleView",
						Timeline = "TimelineView",
						Spline = "SplineEditorView",
						Info = "InfoView",
						Chat = "ChatView"
					},
					Flow = FlowView {
						Flags = {
							Navigator = true,
							AutoHideNavigator = true,
							AutoSnap = true,
							Thumbnails = false,
							RemoveRouters = true
						},
						NavigatorSize = { 200, 140 },
						Direction = "Horizontal",
						PipeStyle = "Direct",
						Scale = 2.36893,
						Offset = { -1.43861, 33.2775 }
					},
					Timeline = TimelineView {
						TreeControlState = {
						},
						DisplayMode = "All Tools",
						ShowCurrentTimeTools = false,
						Filter = "Show All",
						ShowSelectedTools = false,
						ShowAnimatedToolsOnly = false,
						ShowEditBoxes = false,
						KeyFrameView = {
							Position = { Left = 150, Bottom = 343 },
							ScaleX = 0.00214424951267057,
							OffsetX = -0.0514619883040936,
							OffsetY = 0,
							AutoScaling = "scroll",
							AutoSnapTo = "frame",
							AutoSnapToGuidelines = false,
							GuidelinesGrabEnabled = true,
							GuidelinesSnapTo = "frame"
						},
						Spreadsheet = { LeftPos = 150, Visible = false }
					},
					Spline = SplineEditorView {
						LeftPos = 256,
						ScaleX = 0.2,
						ScaleY = 0.00338983050847458,
						OffsetX = -4,
						OffsetY = 0,
						AutoScaling = "scroll",
						AutoSnapTo = "frame",
						AutoSnapToGuidelines = false,
						GuidelinesSnapTo = "frame",
						ShowKeyMarkers = false,
						IndependentHandles = false,
						ShowNonSplineModifiers = false,
						GuidelinesGrabEnabled = true,
						ShowOneToolOnly = false,
						ShowSelectedTools = false,
						ShowAllInputs = false,
						Filter = "Show All"
					},
				},
				Controls = MultiView {
					Active = "Tools",
					ViewList = ordered() {
						Tools = "ControlView",
						Modifiers = "ModifierView"
					},
				},
				Left = "PreviewContainer",
				Right = "PreviewContainer",
				Transport = "TransportView",
				Time = "TimeView"
			},
			Layout = {
				Columns = 2,
				RatioX = 1,
				RatioY = 1,
				{
					Rows = 3,
					RatioX = 0.881222707423581,
					RatioY = 90.1245954692557,
					{
						Columns = 2,
						RatioX = 1,
						RatioY = 0.449593495934959,
						{ ID = "Left", RatioX = 0.501984126984127, RatioY = 103.332730560579, Pop = true },
						{ ID = "Right", RatioX = 0.498015873015873, Pop = true },
						Pop = true
					},
					{ ID = "Main", RatioY = 0.503252032520325, Pop = true },
					{ ID = "Time", SnapY = 56, Flat = true }
				},
				{
					Rows = 2,
					PixelX = 406,
					{ ID = "Controls", RatioX = 1, RatioY = 1 },
					{ ID = "Transport", FixedY = -2 }
				}
			}
		}
	},
	Prefs = {
		Comp = {
			AutoSave = {
				OnRender = true
			},
			Memory = {
				FramesAtOnce = 8,
				Render = {
					SimultaneousBranching = true
				},
				Interactive = {
					SimultaneousBranching = true,
				}
			},
			Views = {
				Right = {
					Viewer = {
						ScaleMode = 1
					},
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "Comp.Views.Right.SideB.",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0
						}
					},
				},
				Left = {
					Viewer = {
						EnableLUTs = true,
						LUTPlugin = "OCIOFileTransformViewLUT",
						ShowControls = true,
						ScaleMode = 1,
					},
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "Comp.Views.Left.SideB.",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0
						}
					},
				},
				View1 = {
					PrevCtrlInactiveColor = 0,
					PickW = 1,
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "Comp.Views.View1.SideB.",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0
						}
					},
					PickH = 1,
					PrevCtrlActiveColor = 0,
					AlwaysOnTop = true,
					FullScreen = false
				},
			},
			FrameFormat = {
				GuideRatio = 1.77778,
			},
			LastFile = "",
			Unsorted = {
				GlobalEnd = 1,
				RenderSettings = {
					Configs = {
						Final = {
							StepRender = false,
							PriorityClasses = "local",
							SizeType = 1,
							MotionBlur = true,
							CustomAspect = true,
							CustomHeight = 160,
							ShowSlaves = false,
							CustomWidth = 200,
							StepSize = 5,
							UpdateMode = "Some",
							UseNetwork = false,
							Quality = true
						},
						Preview = {
							StepRender = false,
							PriorityClasses = "local",
							SizeType = 1,
							MotionBlur = true,
							CustomAspect = true,
							CustomHeight = 160,
							ShowSlaves = false,
							CustomWidth = 200,
							StepSize = 5,
							UpdateMode = "Some",
							UseNetwork = false,
							Quality = false
						}
					},
					PreviewConfig = "Preview",
					CurrentConfig = "Final"
				}
			},
			Paths = {
			},
			FlowView = {
				ShowThumbnails = false,
			},
			QuickTime = {
			},
		}
	}
}

 