Composition {
	CurrentTime = 1,
	RenderRange = { 1, 1 },
	GlobalRange = { 1, 2 },
	CurrentID = 1510,
	HiQ = true,
	Proxy = true,
	PlaybackUpdateMode = 0,
	Version = "Fusion Studio 9.0.2 build 15",
	SavedOutputs = 1,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	Resumable = true,
	OutputClips = {
		"Comp:/Media/altus_input/Reflection_b1.0000.exr",
		"Comp:/Media/altus_input/DiffuseFilter_b1.0000.exr",
		"Comp:/Media/altus_input/MatteShadow_b1.0000.exr",
		"Comp:/Media/altus_input/WorldNormals_b1.0000.exr",
		"Comp:/Media/altus_input/WorldPositions_b1.0000.exr",
		"Comp:/Media/altus_input/rgb_b1.0000.exr",
		"Comp:/Media/altus_input/Reflection_b0.0000.exr",
		"Comp:/Media/altus_input/DiffuseFilter_b0.0000.exr",
		"Comp:/Media/altus_input/MatteShadow_b0.0000.exr",
		"Comp:/Media/altus_input/WorldNormals_b0.0000.exr",
		"Comp:/Media/altus_input/WorldPositions_b0.0000.exr",
		"Comp:/Media/altus_input/rgb_b0.0000.exr"
	},
	Tools = {
		AltusDenoiserUltra = GroupOperator {
			NameSet = true,
			CurrentSettings = 2,
			CustomData = {
				Settings = {
					[1] = {
						Tools = ordered() {
							AltusDenoiserUltra = GroupOperator {
								Inputs = ordered() {
									AltusOutputMode = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusOutputMode"
									},
									AltusBuffer = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusBuffer"
									},
									AltusChannels = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusChannels"
									},
									AltusQuality = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusQuality"
									},
									AltusVerbose = InstanceInput {
										Default = 1,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusVerbose"
									},
									AltusRenderFrame = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusRenderFrame"
									},
									AltusFirefly = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusFirefly"
									},
									Separator1 = InstanceInput {
										SourceOp = "AltusDenoiserCore",
										Source = "Separator1"
									},
									AltusKC1 = InstanceInput {
										Default = 0.45,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusKC1"
									},
									AltusKC2 = InstanceInput {
										Default = 8,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusKC2"
									},
									AltusKC3 = InstanceInput {
										Default = 0.45,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusKC3"
									},
									AltusKC4 = InstanceInput {
										Default = 5,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusKC4"
									},
									AltusKF = InstanceInput {
										Default = 0.6,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusKF"
									},
									AltusRadius = InstanceInput {
										Default = 10,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusRadius"
									},
									Separator2 = InstanceInput {
										SourceOp = "AltusDenoiserCore",
										Source = "Separator2"
									},
									OpenCompFolder = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "OpenCompFolder"
									},
									RenderCurrentFrameButton = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "RenderCurrentFrameButton"
									},
									RenderSelectedButton = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "RenderSelectedButton"
									},
									RenderAllButton = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "RenderAllButton"
									},
									NetworkRenderAllButton = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "NetworkRenderAllButton"
									},
									DoDMode = InstanceInput {
										Page = "DoD",
										SourceOp = "RGBSetDomainB0",
										Source = "Mode"
									},
									DoDAdjustLeft = InstanceInput {
										Source = "AdjustLeft",
										Default = 0,
										SourceOp = "RGBSetDomainB0",
										Page = "DoD"
									},
									DoDAdjustBottom = InstanceInput {
										Source = "AdjustBottom",
										Default = 0,
										SourceOp = "RGBSetDomainB0",
										Page = "DoD"
									},
									DoDAdjustRight = InstanceInput {
										Source = "AdjustRight",
										Default = 0,
										SourceOp = "RGBSetDomainB0",
										Page = "DoD"
									},
									DoDAdjustTop = InstanceInput {
										Source = "AdjustTop",
										Default = 0,
										SourceOp = "RGBSetDomainB0",
										Page = "DoD"
									},
									DoDLeft = InstanceInput {
										Source = "Left",
										Default = 0,
										SourceOp = "RGBSetDomainB0",
										Page = "DoD"
									},
									DoDBottom = InstanceInput {
										Source = "Bottom",
										Default = 1,
										SourceOp = "RGBSetDomainB0",
										Page = "DoD"
									},
									DoDRight = InstanceInput {
										Source = "Right",
										Default = 1,
										SourceOp = "RGBSetDomainB0",
										Page = "DoD"
									},
									DoDTop = InstanceInput {
										Source = "Top",
										Default = 0,
										SourceOp = "RGBSetDomainB0",
										Page = "DoD"
									},
									AltusExampleComp = InstanceInput {
										Source = "ExampleComp",
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Page = "Help"
									},
									AltusHelpWindow = InstanceInput {
										Source = "HelpWindow",
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Page = "Help"
									},
									HelpWebsite = InstanceInput {
										Source = "HelpWebsite",
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Page = "Help"
									}
								},
								Tools = ordered() {
									B0WorldPositions = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "worldPositions.Y" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "worldPositions.X" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "worldPositions.Z" } }
										},
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 49.5 } }
									},
									B1Reflection = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "reflectionFilter.G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "reflectionFilter.R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "reflectionFilter.B" } }
										},
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 412.5 } }
									},
									B1DiffuseFilter = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "diffuseFilter.G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "diffuseFilter.R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "diffuseFilter.B" } }
										},
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 379.5 } }
									},
									B1MatteShadow = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "matteShadow.G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "matteShadow.R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "matteShadow.B" } }
										},
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 346.5 } }
									},
									B1WorldNormals = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "worldNormals.Y" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "worldNormals.X" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "worldNormals.Z" } }
										},
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 313.5 } }
									},
									B1WorldPositions = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "worldPositions.Y" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "worldPositions.X" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "worldPositions.Z" } }
										},
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 280.5 } }
									},
									B1RGB = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "B" } }
										},
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 247.5 } }
									},
									B0Reflection = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "reflectionFilter.G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "reflectionFilter.R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "reflectionFilter.B" } }
										},
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 181.5 } }
									},
									B0DiffuseFilter = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "diffuseFilter.G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "diffuseFilter.R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "diffuseFilter.B" } }
										},
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 148.5 } }
									},
									B0MatteShadow = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "matteShadow.G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "matteShadow.R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "matteShadow.B" } }
										},
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 115.5 } }
									},
									B0WorldNormals = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "worldNormals.Y" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "worldNormals.X" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "worldNormals.Z" } }
										},
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 82.5 } }
									},
									B0RGB = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										ViewInfo = OperatorInfo { Pos = { 110, 16.5 } },
										NameSet = true,
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "B" } }
										}
									},
									DenoisedResultLoader = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/altus_output/rgb_nr.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											EffectMask = Input {
												SourceOp = "DependencyLinkerChannelBooleans",
												Source = "Output"
											},
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "B" } }
										},
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 880, 313.5 } }
									},
									B1ReflectionSaver = Saver {
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 330, 412.5 } },
										NameSet = true,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "ReflectionSetDomainB1",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/Reflection_b1.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										}
									},
									B1DiffuseFilterSaver = Saver {
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 330, 379.5 } },
										NameSet = true,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "DiffuseFilterSetDomainB1",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/DiffuseFilter_b1.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										}
									},
									B1MatteShadowSaver = Saver {
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 330, 346.5 } },
										NameSet = true,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "MatteShadowSetDomainB1",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/MatteShadow_b1.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										}
									},
									B1WorldNormalsSaver = Saver {
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 330, 313.5 } },
										NameSet = true,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "WorldNormalsSetDomainB1",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/WorldNormals_b1.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										}
									},
									B1WorldPositionsSaver = Saver {
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 330, 280.5 } },
										NameSet = true,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "WorldPositionsSetDomainB1",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/WorldPositions_b1.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										}
									},
									B1RGBSaver = Saver {
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 330, 247.5 } },
										NameSet = true,
										Inputs = {
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["OpenEXRFormat.Channels"] = Input { Value = 1 },
											Input = Input {
												SourceOp = "RGBSetDomainB1",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/rgb_b1.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["OpenEXRFormat.Depth"] = Input { Value = 1 }
										}
									},
									ReflectionSetDomainB1 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B1Reflection",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										NameSet = true,
										SourceOp = "RGBSetDomainB1",
										ViewInfo = OperatorInfo { Pos = { 220, 412.5 } }
									},
									DiffuseFilterSetDomainB1 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B1DiffuseFilter",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										NameSet = true,
										SourceOp = "RGBSetDomainB1",
										ViewInfo = OperatorInfo { Pos = { 220, 379.5 } }
									},
									MatteShadowSetDomainB1 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B1MatteShadow",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										NameSet = true,
										SourceOp = "RGBSetDomainB1",
										ViewInfo = OperatorInfo { Pos = { 220, 346.5 } }
									},
									WorldNormalsSetDomainB1 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B1WorldNormals",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										NameSet = true,
										SourceOp = "RGBSetDomainB1",
										ViewInfo = OperatorInfo { Pos = { 220, 313.5 } }
									},
									WorldPositionsSetDomainB1 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B1WorldPositions",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										NameSet = true,
										SourceOp = "RGBSetDomainB1",
										ViewInfo = OperatorInfo { Pos = { 220, 280.5 } }
									},
									RGBSetDomainB1 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B1RGB",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										NameSet = true,
										SourceOp = "RGBSetDomainB0",
										ViewInfo = OperatorInfo { Pos = { 220, 247.5 } }
									},
									B0ReflectionSaver = Saver {
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 330, 181.5 } },
										NameSet = true,
										Inputs = {
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "ReflectionSetDomainB0",
												Source = "Output"
											},
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/Reflection_b0.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										}
									},
									ReflectionSetDomainB0 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B0Reflection",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										NameSet = true,
										SourceOp = "RGBSetDomainB0",
										ViewInfo = OperatorInfo { Pos = { 220, 181.5 } }
									},
									B0DiffuseFilterSaver = Saver {
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 330, 148.5 } },
										NameSet = true,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "DiffuseFilterSetDomainB0",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/DiffuseFilter_b0.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										}
									},
									DiffuseFilterSetDomainB0 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B0DiffuseFilter",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										NameSet = true,
										SourceOp = "RGBSetDomainB0",
										ViewInfo = OperatorInfo { Pos = { 220, 148.5 } }
									},
									MatteShadowSetDomainB0 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B0MatteShadow",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										NameSet = true,
										SourceOp = "RGBSetDomainB0",
										ViewInfo = OperatorInfo { Pos = { 220, 115.5 } }
									},
									B0MatteShadowSaver = Saver {
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 330, 115.5 } },
										NameSet = true,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "MatteShadowSetDomainB0",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/MatteShadow_b0.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										}
									},
									WorldNormalsSetDomainB0 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B0WorldNormals",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										NameSet = true,
										SourceOp = "RGBSetDomainB0",
										ViewInfo = OperatorInfo { Pos = { 220, 82.5 } }
									},
									B0WorldNormalsSaver = Saver {
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 330, 82.5 } },
										NameSet = true,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "WorldNormalsSetDomainB0",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/WorldNormals_b0.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										}
									},
									B0WorldPositionsSaver = Saver {
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 330, 49.5 } },
										NameSet = true,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "WorldPositionsSetDomainB0",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/WorldPositions_b0.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										}
									},
									WorldPositionsSetDomainB0 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B0WorldPositions",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										NameSet = true,
										SourceOp = "RGBSetDomainB0",
										ViewInfo = OperatorInfo { Pos = { 220, 49.5 } }
									},
									RGBSetDomainB0 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B0RGB",
												Source = "Output"
											},
											Mode = Input { Value = FuID { "Set" } }
										},
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 220, 16.5 } },
										CustomData = {
											Settings = {
												[1] = {
													Tools = ordered() {
														RGBSetDomainB0 = SetDomain {
															Inputs = {
																Top = Input { Value = 0.592592592592593 },
																Bottom = Input { Value = 0.0666666666666667 },
																Input = Input {
																	SourceOp = "RGBB0",
																	Source = "Output"
																},
																Mode = Input { Value = FuID { "Set" } },
																Left = Input { Value = 0.310699588477366 },
																Right = Input { Value = 0.524691358024691 }
															},
															Name = "RGBSetDomainB0",
															CtrlWZoom = false,
															NameSet = true,
															ViewInfo = OperatorInfo { Pos = { 715, 280.5 } },
															CustomData = {
															}
														}
													}
												},
												[2] = {
													Tools = ordered() {
														RGBSetDomainB0 = SetDomain {
															Inputs = {
																Input = Input {
																	SourceOp = "RGBB0",
																	Source = "Output"
																},
																Mode = Input { Value = FuID { "Set" } }
															},
															CtrlWZoom = false,
															NameSet = true,
															ViewInfo = OperatorInfo { Pos = { 220, 15.8304 } },
															CustomData = {
															}
														}
													}
												}
											}
										}
									},
									B0RGBSaver = Saver {
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 330, 16.5 } },
										NameSet = true,
										Inputs = {
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											Input = Input {
												SourceOp = "RGBSetDomainB0",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/rgb_b0.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											StartEndRenderScripts = Input { Value = 1 }
										}
									},
									AltusDenoiserCore = Fuse.AltusDenoiserCore {
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 495, 214.5 } },
										Version = 100,
										Inputs = {
											["B0 MatteShadow"] = Input {
												SourceOp = "B0MatteShadowSaver",
												Source = "Output"
											},
											B0Reflection = Input {
												SourceOp = "B0ReflectionSaver",
												Source = "Output"
											},
											B1Reflection = Input {
												SourceOp = "B1ReflectionSaver",
												Source = "Output"
											},
											AltusPreserveLayers = Input { Value = 1 },
											["B0Diffuse Filter"] = Input {
												SourceOp = "B0DiffuseFilterSaver",
												Source = "Output"
											},
											["B1Diffuse Filter"] = Input {
												SourceOp = "B1DiffuseFilterSaver",
												Source = "Output"
											},
											["B0 WorldNormal"] = Input {
												SourceOp = "B0WorldNormalsSaver",
												Source = "Output"
											},
											B1MatteShadow = Input {
												SourceOp = "B1MatteShadowSaver",
												Source = "Output"
											},
											B0MatteShadow = Input {
												SourceOp = "B0MatteShadowSaver",
												Source = "Output"
											},
											["B0 WorldPosition"] = Input {
												SourceOp = "B0WorldPositionsSaver",
												Source = "Output"
											},
											B0DiffuseFilter = Input {
												SourceOp = "B0DiffuseFilterSaver",
												Source = "Output"
											},
											AltusMode = Input { Value = 1 },
											B1WorldNormals = Input {
												SourceOp = "B1WorldNormalsSaver",
												Source = "Output"
											},
											B0RGB = Input {
												SourceOp = "B0RGBSaver",
												Source = "Output"
											},
											AltusKC4 = Input { Value = 5 },
											B1WorldPositions = Input {
												SourceOp = "B1WorldPositionsSaver",
												Source = "Output"
											},
											B0WorldPositions = Input {
												SourceOp = "B0WorldPositionsSaver",
												Source = "Output"
											},
											AltusKC2 = Input { Value = 8 },
											AltusRenderFrame = Input { Value = 1 },
											B0WorldNormals = Input {
												SourceOp = "B0WorldNormalsSaver",
												Source = "Output"
											},
											AltusOutputMode = Input { Value = 1 },
											B1RGB = Input {
												SourceOp = "B1RGBSaver",
												Source = "Output"
											},
											AltusVerbose = Input { Value = 1 }
										}
									},
									DependencyLinkerChannelBooleans = ChannelBoolean {
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 715, 313.5 } },
										NameSet = true,
										Inputs = {
											ToRed = Input { Value = 16 },
											EnableExtraChannels = Input { Value = 1 },
											ToGreen = Input { Value = 16 },
											Background = Input {
												SourceOp = "Done",
												Source = "Output"
											},
											ToBlue = Input { Value = 16 },
											ToAlpha = Input { Value = 16 }
										}
									},
									SwitchElseFuse = Fuse.SwitchElse {
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 880, 214.5 } },
										Version = 100,
										Inputs = {
											Else = Input { Value = 1 },
											Notify = Input { Value = 1 },
											Switch = Input {
												Value = 2,
												Expression = "iif(AltusDenoiserCore.AltusOutputMode == 1, 2, 1)"
											},
											Input1 = Input {
												SourceOp = "Done",
												Source = "Output"
											},
											Input2 = Input {
												SourceOp = "DenoisedResultLoader",
												Source = "Output"
											}
										}
									},
									Done = Merge {
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 605, 214.5 } },
										NameSet = true,
										Inputs = {
											Background = Input {
												SourceOp = "AltusDenoiserCore",
												Source = "Output"
											},
											Blend = Input { Value = 0 },
											PerformDepthMerge = Input { Value = 0 }
										}
									}
								},
								CtrlWZoom = false,
								NameSet = true,
								ViewInfo = GroupInfo {
									Flags = {
										RemoveRouters = true,
										AutoSnap = true,
										Expanded = true,
										AllowPan = false
									},
									Direction = "Horizontal",
									Offset = { -158.424, -0.764003 },
									PipeStyle = "Direct",
									Scale = 1,
									Size = { 927.197, 460.584, 125.731, 22 },
									Pos = { 1623.01, 584.538 }
								},
								CustomData = {
									HelpPage = "http://www.andrewhazelden.com/"
								},
								Outputs = {
									DenoisedOutput = InstanceOutput {
										SourceOp = "SwitchElseFuse",
										Source = "Output"
									}
								}
							}
						}
					},
					[2] = {
						Tools = ordered() {
							AltusDenoiserUltra = GroupOperator {
								ViewInfo = GroupInfo {
									Flags = {
										RemoveRouters = true,
										AutoSnap = true,
										Expanded = true,
										AllowPan = false
									},
									Direction = "Horizontal",
									Offset = { -158.424, -0.764003 },
									PipeStyle = "Direct",
									Scale = 1,
									Size = { 927.197, 460.584, 125.731, 22 },
									Pos = { 1623.01, 584.538 }
								},
								CtrlWZoom = false,
								NameSet = true,
								Name = "AltusDenoiserUltra",
								Tools = ordered() {
									B0WorldPositions = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "worldPositions.Y" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "worldPositions.X" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "worldPositions.Z" } }
										},
										Name = "B0WorldPositions",
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 49.5 } }
									},
									B1Reflection = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "reflectionFilter.G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "reflectionFilter.R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "reflectionFilter.B" } }
										},
										Name = "B1Reflection",
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 412.5 } }
									},
									B1DiffuseFilter = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "diffuseFilter.G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "diffuseFilter.R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "diffuseFilter.B" } }
										},
										Name = "B1DiffuseFilter",
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 379.5 } }
									},
									B1MatteShadow = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "matteShadow.G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "matteShadow.R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "matteShadow.B" } }
										},
										Name = "B1MatteShadow",
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 346.5 } }
									},
									B1WorldNormals = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "worldNormals.Y" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "worldNormals.X" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "worldNormals.Z" } }
										},
										Name = "B1WorldNormals",
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 313.5 } }
									},
									B1WorldPositions = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "worldPositions.Y" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "worldPositions.X" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "worldPositions.Z" } }
										},
										Name = "B1WorldPositions",
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 280.5 } }
									},
									B1RGB = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "B" } }
										},
										Name = "B1RGB",
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 247.5 } }
									},
									B0Reflection = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "reflectionFilter.G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "reflectionFilter.R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "reflectionFilter.B" } }
										},
										Name = "B0Reflection",
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 181.5 } }
									},
									B0DiffuseFilter = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "diffuseFilter.G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "diffuseFilter.R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "diffuseFilter.B" } }
										},
										Name = "B0DiffuseFilter",
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 148.5 } }
									},
									B0MatteShadow = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "matteShadow.G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "matteShadow.R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "matteShadow.B" } }
										},
										Name = "B0MatteShadow",
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 115.5 } }
									},
									B0WorldNormals = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "worldNormals.Y" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "worldNormals.X" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "worldNormals.Z" } }
										},
										Name = "B0WorldNormals",
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 110, 82.5 } }
									},
									B0RGB = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "B" } }
										},
										Name = "B0RGB",
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 110, 16.5 } }
									},
									DenoisedResultLoader = Loader {
										Clips = {
											Clip {
												TimeCode = 0,
												LengthSetManually = true,
												AspectMode = 0,
												TrimOut = 0,
												GlobalStart = 1,
												TrimIn = 0,
												ExtendLast = 0,
												StartFrame = 1,
												Loop = 0,
												Filename = "Comp:/Media/altus_output/rgb_nr.0001.exr",
												FormatID = "OpenEXRFormat",
												ID = "Clip1",
												Depth = 0,
												ExtendFirst = 0,
												GlobalEnd = 1
											}
										},
										Inputs = {
											["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "G" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1 },
											["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "R" } },
											["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" } },
											EffectMask = Input {
												SourceOp = "DependencyLinkerChannelBooleans",
												Source = "Output"
											},
											["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "B" } }
										},
										Name = "DenoisedResultLoader",
										NameSet = true,
										CtrlWShown = false,
										ViewInfo = OperatorInfo { Pos = { 880, 313.5 } }
									},
									B1ReflectionSaver = Saver {
										CtrlWShown = false,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "ReflectionSetDomainB1",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/Reflection_b1.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										},
										Name = "B1ReflectionSaver",
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 330, 412.5 } }
									},
									B1DiffuseFilterSaver = Saver {
										CtrlWShown = false,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "DiffuseFilterSetDomainB1",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/DiffuseFilter_b1.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										},
										Name = "B1DiffuseFilterSaver",
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 330, 379.5 } }
									},
									B1MatteShadowSaver = Saver {
										CtrlWShown = false,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "MatteShadowSetDomainB1",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/MatteShadow_b1.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										},
										Name = "B1MatteShadowSaver",
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 330, 346.5 } }
									},
									B1WorldNormalsSaver = Saver {
										CtrlWShown = false,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "WorldNormalsSetDomainB1",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/WorldNormals_b1.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										},
										Name = "B1WorldNormalsSaver",
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 330, 313.5 } }
									},
									B1WorldPositionsSaver = Saver {
										CtrlWShown = false,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "WorldPositionsSetDomainB1",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/WorldPositions_b1.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										},
										Name = "B1WorldPositionsSaver",
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 330, 280.5 } }
									},
									B1RGBSaver = Saver {
										CtrlWShown = false,
										Inputs = {
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["OpenEXRFormat.Channels"] = Input { Value = 1 },
											Input = Input {
												SourceOp = "RGBSetDomainB1",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/rgb_b1.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["OpenEXRFormat.Depth"] = Input { Value = 1 }
										},
										Name = "B1RGBSaver",
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 330, 247.5 } }
									},
									ReflectionSetDomainB1 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B1Reflection",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										Name = "ReflectionSetDomainB1",
										NameSet = true,
										SourceOp = "RGBSetDomainB1",
										ViewInfo = OperatorInfo { Pos = { 220, 412.5 } }
									},
									DiffuseFilterSetDomainB1 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B1DiffuseFilter",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										Name = "DiffuseFilterSetDomainB1",
										NameSet = true,
										SourceOp = "RGBSetDomainB1",
										ViewInfo = OperatorInfo { Pos = { 220, 379.5 } }
									},
									MatteShadowSetDomainB1 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B1MatteShadow",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										Name = "MatteShadowSetDomainB1",
										NameSet = true,
										SourceOp = "RGBSetDomainB1",
										ViewInfo = OperatorInfo { Pos = { 220, 346.5 } }
									},
									WorldNormalsSetDomainB1 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B1WorldNormals",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										Name = "WorldNormalsSetDomainB1",
										NameSet = true,
										SourceOp = "RGBSetDomainB1",
										ViewInfo = OperatorInfo { Pos = { 220, 313.5 } }
									},
									WorldPositionsSetDomainB1 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B1WorldPositions",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										Name = "WorldPositionsSetDomainB1",
										NameSet = true,
										SourceOp = "RGBSetDomainB1",
										ViewInfo = OperatorInfo { Pos = { 220, 280.5 } }
									},
									RGBSetDomainB1 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B1RGB",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										Name = "RGBSetDomainB1",
										NameSet = true,
										SourceOp = "RGBSetDomainB0",
										ViewInfo = OperatorInfo { Pos = { 220, 247.5 } }
									},
									B0ReflectionSaver = Saver {
										CtrlWShown = false,
										Inputs = {
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "ReflectionSetDomainB0",
												Source = "Output"
											},
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/Reflection_b0.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										},
										Name = "B0ReflectionSaver",
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 330, 181.5 } }
									},
									ReflectionSetDomainB0 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B0Reflection",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										Name = "ReflectionSetDomainB0",
										NameSet = true,
										SourceOp = "RGBSetDomainB0",
										ViewInfo = OperatorInfo { Pos = { 220, 181.5 } }
									},
									B0DiffuseFilterSaver = Saver {
										CtrlWShown = false,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "DiffuseFilterSetDomainB0",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/DiffuseFilter_b0.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										},
										Name = "B0DiffuseFilterSaver",
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 330, 148.5 } }
									},
									DiffuseFilterSetDomainB0 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B0DiffuseFilter",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										Name = "DiffuseFilterSetDomainB0",
										NameSet = true,
										SourceOp = "RGBSetDomainB0",
										ViewInfo = OperatorInfo { Pos = { 220, 148.5 } }
									},
									MatteShadowSetDomainB0 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B0MatteShadow",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										Name = "MatteShadowSetDomainB0",
										NameSet = true,
										SourceOp = "RGBSetDomainB0",
										ViewInfo = OperatorInfo { Pos = { 220, 115.5 } }
									},
									B0MatteShadowSaver = Saver {
										CtrlWShown = false,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "MatteShadowSetDomainB0",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/MatteShadow_b0.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										},
										Name = "B0MatteShadowSaver",
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 330, 115.5 } }
									},
									WorldNormalsSetDomainB0 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B0WorldNormals",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										Name = "WorldNormalsSetDomainB0",
										NameSet = true,
										SourceOp = "RGBSetDomainB0",
										ViewInfo = OperatorInfo { Pos = { 220, 82.5 } }
									},
									B0WorldNormalsSaver = Saver {
										CtrlWShown = false,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "WorldNormalsSetDomainB0",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/WorldNormals_b0.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										},
										Name = "B0WorldNormalsSaver",
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 330, 82.5 } }
									},
									B0WorldPositionsSaver = Saver {
										CtrlWShown = false,
										Inputs = {
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											Input = Input {
												SourceOp = "WorldPositionsSetDomainB0",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/WorldPositions_b0.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } }
										},
										Name = "B0WorldPositionsSaver",
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 330, 49.5 } }
									},
									WorldPositionsSetDomainB0 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B0WorldPositions",
												Source = "Output"
											},
											StartEndRenderScripts = Input {
											},
											Foreground = Input {
											}
										},
										Name = "WorldPositionsSetDomainB0",
										NameSet = true,
										SourceOp = "RGBSetDomainB0",
										ViewInfo = OperatorInfo { Pos = { 220, 49.5 } }
									},
									RGBSetDomainB0 = SetDomain {
										CtrlWShown = false,
										Inputs = {
											Input = Input {
												SourceOp = "B0RGB",
												Source = "Output"
											},
											Mode = Input { Value = FuID { "Set" } },
											Left = Input { Value = 0.240066225165563 },
											Right = Input { Value = 0.606788079470199 }
										},
										Name = "RGBSetDomainB0",
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 220, 16.5 } },
										CustomData = {
											Settings = {
												[1] = {
													Tools = ordered() {
														RGBSetDomainB0 = SetDomain {
															Inputs = {
																Top = Input { Value = 0.592592592592593 },
																Bottom = Input { Value = 0.0666666666666667 },
																Input = Input {
																	SourceOp = "RGBB0",
																	Source = "Output"
																},
																Mode = Input { Value = FuID { "Set" } },
																Left = Input { Value = 0.310699588477366 },
																Right = Input { Value = 0.524691358024691 }
															},
															Name = "RGBSetDomainB0",
															CtrlWZoom = false,
															NameSet = true,
															ViewInfo = OperatorInfo { Pos = { 715, 280.5 } },
															CustomData = {
															}
														}
													}
												},
												[2] = {
													Tools = ordered() {
														RGBSetDomainB0 = SetDomain {
															Inputs = {
																Input = Input {
																	SourceOp = "RGBB0",
																	Source = "Output"
																},
																Mode = Input { Value = FuID { "Set" } }
															},
															CtrlWZoom = false,
															NameSet = true,
															ViewInfo = OperatorInfo { Pos = { 220, 15.8304 } },
															CustomData = {
															}
														}
													}
												}
											}
										}
									},
									B0RGBSaver = Saver {
										CtrlWShown = false,
										Inputs = {
											ProcessWhenBlendIs00 = Input { Value = 0 },
											CreateDir = Input { Value = 1 },
											OutputFormat = Input { Value = FuID { "OpenEXRFormat" } },
											["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" } },
											["OpenEXRFormat.Depth"] = Input { Value = 1 },
											Input = Input {
												SourceOp = "RGBSetDomainB0",
												Source = "Output"
											},
											SaveFrames = Input { Value = FuID { "HiQInteractive" } },
											Clip = Input {
												Value = Clip {
													TimeCode = 0,
													Depth = 0,
													Loop = 1,
													TrimIn = 0,
													GlobalStart = -2000000000,
													ExtendFirst = 0,
													Saving = true,
													Filename = "Comp:/Media/altus_input/rgb_b0.0000.exr",
													FormatID = "OpenEXRFormat",
													ExtendLast = 0,
													Length = 0,
													AspectMode = 0,
													GlobalEnd = 0
												}
											},
											StartEndRenderScripts = Input { Value = 1 }
										},
										Name = "B0RGBSaver",
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 330, 16.5 } }
									},
									AltusDenoiserCore = Fuse.AltusDenoiserCore {
										CtrlWShown = false,
										Inputs = {
											["B0 MatteShadow"] = Input {
												SourceOp = "B0MatteShadowSaver",
												Source = "Output"
											},
											B0Reflection = Input {
												SourceOp = "B0ReflectionSaver",
												Source = "Output"
											},
											B1Reflection = Input {
												SourceOp = "B1ReflectionSaver",
												Source = "Output"
											},
											AltusPreserveLayers = Input { Value = 1 },
											["B0Diffuse Filter"] = Input {
												SourceOp = "B0DiffuseFilterSaver",
												Source = "Output"
											},
											["B1Diffuse Filter"] = Input {
												SourceOp = "B1DiffuseFilterSaver",
												Source = "Output"
											},
											["B0 WorldNormal"] = Input {
												SourceOp = "B0WorldNormalsSaver",
												Source = "Output"
											},
											B1MatteShadow = Input {
												SourceOp = "B1MatteShadowSaver",
												Source = "Output"
											},
											B0MatteShadow = Input {
												SourceOp = "B0MatteShadowSaver",
												Source = "Output"
											},
											["B0 WorldPosition"] = Input {
												SourceOp = "B0WorldPositionsSaver",
												Source = "Output"
											},
											B0DiffuseFilter = Input {
												SourceOp = "B0DiffuseFilterSaver",
												Source = "Output"
											},
											AltusMode = Input { Value = 1 },
											B1WorldNormals = Input {
												SourceOp = "B1WorldNormalsSaver",
												Source = "Output"
											},
											B0RGB = Input {
												SourceOp = "B0RGBSaver",
												Source = "Output"
											},
											AltusKC4 = Input { Value = 5 },
											B1WorldPositions = Input {
												SourceOp = "B1WorldPositionsSaver",
												Source = "Output"
											},
											B0WorldPositions = Input {
												SourceOp = "B0WorldPositionsSaver",
												Source = "Output"
											},
											AltusKC2 = Input { Value = 8 },
											AltusRenderFrame = Input { Value = 1 },
											B0WorldNormals = Input {
												SourceOp = "B0WorldNormalsSaver",
												Source = "Output"
											},
											AltusOutputMode = Input { Value = 1 },
											B1RGB = Input {
												SourceOp = "B1RGBSaver",
												Source = "Output"
											},
											AltusVerbose = Input { Value = 1 }
										},
										Version = 100,
										ViewInfo = OperatorInfo { Pos = { 495, 214.5 } },
										Name = "AltusDenoiserCore"
									},
									DependencyLinkerChannelBooleans = ChannelBoolean {
										CtrlWShown = false,
										Inputs = {
											ToRed = Input { Value = 16 },
											EnableExtraChannels = Input { Value = 1 },
											ToGreen = Input { Value = 16 },
											Background = Input {
												SourceOp = "Done",
												Source = "Output"
											},
											ToBlue = Input { Value = 16 },
											ToAlpha = Input { Value = 16 }
										},
										Name = "DependencyLinkerChannelBooleans",
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 715, 313.5 } }
									},
									SwitchElseFuse = Fuse.SwitchElse {
										CtrlWShown = false,
										Inputs = {
											Else = Input { Value = 1 },
											Notify = Input { Value = 1 },
											Switch = Input {
												Value = 2,
												Expression = "iif(AltusDenoiserCore.AltusOutputMode == 1, 2, 1)"
											},
											Input1 = Input {
												SourceOp = "Done",
												Source = "Output"
											},
											Input2 = Input {
												SourceOp = "DenoisedResultLoader",
												Source = "Output"
											}
										},
										Version = 100,
										ViewInfo = OperatorInfo { Pos = { 880, 214.5 } },
										Name = "SwitchElseFuse"
									},
									Done = Merge {
										CtrlWShown = false,
										Inputs = {
											Background = Input {
												SourceOp = "AltusDenoiserCore",
												Source = "Output"
											},
											Blend = Input { Value = 0 },
											PerformDepthMerge = Input { Value = 0 }
										},
										Name = "Done",
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 605, 214.5 } }
									}
								},
								Inputs = ordered() {
									AltusOutputMode = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusOutputMode"
									},
									AltusBuffer = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusBuffer"
									},
									AltusChannels = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusChannels"
									},
									AltusQuality = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusQuality"
									},
									AltusVerbose = InstanceInput {
										Default = 1,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusVerbose"
									},
									AltusRenderFrame = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusRenderFrame"
									},
									AltusFirefly = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusFirefly"
									},
									Separator1 = InstanceInput {
										SourceOp = "AltusDenoiserCore",
										Source = "Separator1"
									},
									AltusKC1 = InstanceInput {
										Default = 0.45,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusKC1"
									},
									AltusKC2 = InstanceInput {
										Default = 8,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusKC2"
									},
									AltusKC3 = InstanceInput {
										Default = 0.45,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusKC3"
									},
									AltusKC4 = InstanceInput {
										Default = 5,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusKC4"
									},
									AltusKF = InstanceInput {
										Default = 0.6,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusKF"
									},
									AltusRadius = InstanceInput {
										Default = 10,
										SourceOp = "AltusDenoiserCore",
										Source = "AltusRadius"
									},
									Separator2 = InstanceInput {
										SourceOp = "AltusDenoiserCore",
										Source = "Separator2"
									},
									OpenCompFolder = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "OpenCompFolder"
									},
									RenderCurrentFrameButton = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "RenderCurrentFrameButton"
									},
									RenderSelectedButton = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "RenderSelectedButton"
									},
									RenderAllButton = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "RenderAllButton"
									},
									NetworkRenderAllButton = InstanceInput {
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Source = "NetworkRenderAllButton"
									},
									DoDMode = InstanceInput {
										Page = "DoD",
										SourceOp = "RGBSetDomainB0",
										Source = "Mode"
									},
									DoDAdjustLeft = InstanceInput {
										Source = "AdjustLeft",
										Default = 0,
										SourceOp = "RGBSetDomainB0",
										Page = "DoD"
									},
									DoDAdjustBottom = InstanceInput {
										Source = "AdjustBottom",
										Default = 0,
										SourceOp = "RGBSetDomainB0",
										Page = "DoD"
									},
									DoDAdjustRight = InstanceInput {
										Source = "AdjustRight",
										Default = 0,
										SourceOp = "RGBSetDomainB0",
										Page = "DoD"
									},
									DoDAdjustTop = InstanceInput {
										Source = "AdjustTop",
										Default = 0,
										SourceOp = "RGBSetDomainB0",
										Page = "DoD"
									},
									DoDLeft = InstanceInput {
										Source = "Left",
										Default = 0,
										SourceOp = "RGBSetDomainB0",
										Page = "DoD"
									},
									DoDBottom = InstanceInput {
										Source = "Bottom",
										Default = 1,
										SourceOp = "RGBSetDomainB0",
										Page = "DoD"
									},
									DoDRight = InstanceInput {
										Source = "Right",
										Default = 1,
										SourceOp = "RGBSetDomainB0",
										Page = "DoD"
									},
									DoDTop = InstanceInput {
										Source = "Top",
										Default = 0,
										SourceOp = "RGBSetDomainB0",
										Page = "DoD"
									},
									AltusExampleComp = InstanceInput {
										Source = "ExampleComp",
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Page = "Help"
									},
									AltusHelpWindow = InstanceInput {
										Source = "HelpWindow",
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Page = "Help"
									},
									HelpWebsite = InstanceInput {
										Source = "HelpWebsite",
										Default = 0,
										SourceOp = "AltusDenoiserCore",
										Page = "Help"
									}
								},
								CustomData = {
									HelpPage = "http://www.andrewhazelden.com/"
								},
								Outputs = {
									DenoisedOutput = InstanceOutput {
										SourceOp = "SwitchElseFuse",
										Source = "Output"
									}
								}
							}
						}
					},
				},
				HelpPage = "http://www.andrewhazelden.com/"
			},
			Inputs = ordered() {
				AltusOutputMode = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "AltusOutputMode",
					Default = 0,
				},
				AltusBuffer = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "AltusBuffer",
					Default = 0,
				},
				AltusChannels = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "AltusChannels",
					Default = 0,
				},
				AltusQuality = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "AltusQuality",
					Default = 0,
				},
				AltusVerbose = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "AltusVerbose",
					Default = 1,
				},
				AltusRenderFrame = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "AltusRenderFrame",
					Default = 0,
				},
				AltusFirefly = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "AltusFirefly",
					Default = 0,
				},
				Separator1 = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "Separator1",
				},
				AltusKC1 = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "AltusKC1",
					Default = 0.45,
				},
				AltusKC2 = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "AltusKC2",
					Default = 8,
				},
				AltusKC3 = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "AltusKC3",
					Default = 0.45,
				},
				AltusKC4 = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "AltusKC4",
					Default = 5,
				},
				AltusKF = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "AltusKF",
					Default = 0.6,
				},
				AltusRadius = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "AltusRadius",
					Default = 10,
				},
				Separator2 = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "Separator2",
				},
				OpenCompFolder = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "OpenCompFolder",
					Default = 0,
				},
				RenderCurrentFrameButton = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "RenderCurrentFrameButton",
					Default = 0,
				},
				RenderSelectedButton = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "RenderSelectedButton",
					Default = 0,
				},
				RenderAllButton = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "RenderAllButton",
					Default = 0,
				},
				NetworkRenderAllButton = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "NetworkRenderAllButton",
					Default = 0,
				},
				DoDMode = InstanceInput {
					SourceOp = "RGBSetDomainB0",
					Source = "Mode",
					Page = "DoD",
				},
				DoDAdjustLeft = InstanceInput {
					SourceOp = "RGBSetDomainB0",
					Source = "AdjustLeft",
					Page = "DoD",
					Default = 0,
				},
				DoDAdjustBottom = InstanceInput {
					SourceOp = "RGBSetDomainB0",
					Source = "AdjustBottom",
					Page = "DoD",
					Default = 0,
				},
				DoDAdjustRight = InstanceInput {
					SourceOp = "RGBSetDomainB0",
					Source = "AdjustRight",
					Page = "DoD",
					Default = 0,
				},
				DoDAdjustTop = InstanceInput {
					SourceOp = "RGBSetDomainB0",
					Source = "AdjustTop",
					Page = "DoD",
					Default = 0,
				},
				DoDLeft = InstanceInput {
					SourceOp = "RGBSetDomainB0",
					Source = "Left",
					Page = "DoD",
					Default = 0,
				},
				DoDBottom = InstanceInput {
					SourceOp = "RGBSetDomainB0",
					Source = "Bottom",
					Page = "DoD",
					Default = 1,
				},
				DoDRight = InstanceInput {
					SourceOp = "RGBSetDomainB0",
					Source = "Right",
					Page = "DoD",
					Default = 1,
				},
				DoDTop = InstanceInput {
					SourceOp = "RGBSetDomainB0",
					Source = "Top",
					Page = "DoD",
					Default = 0,
				},
				AltusExampleComp = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "ExampleComp",
					Page = "Help",
					Default = 0,
				},
				AltusHelpWindow = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "HelpWindow",
					Page = "Help",
					Default = 0,
				},
				HelpWebsite = InstanceInput {
					SourceOp = "AltusDenoiserCore",
					Source = "HelpWebsite",
					Page = "Help",
					Default = 0,
				}
			},
			Outputs = {
				DenoisedOutput = InstanceOutput {
					SourceOp = "SwitchElseFuse",
					Source = "Output",
				}
			},
			ViewInfo = GroupInfo {
				Pos = { 1623.01, 584.538 },
				Flags = {
					Expanded = true,
					AllowPan = false,
					AutoSnap = true,
					RemoveRouters = true
				},
				Size = { 927.197, 460.584, 125.731, 22 },
				Direction = "Horizontal",
				PipeStyle = "Direct",
				Scale = 1,
				Offset = { -158.424, -0.764003 }
			},
			Tools = ordered() {
				B0WorldPositions = Loader {
					Clips = {
						Clip {
							ID = "Clip1",
							Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
							FormatID = "OpenEXRFormat",
							StartFrame = 1,
							LengthSetManually = true,
							TrimIn = 0,
							TrimOut = 0,
							ExtendFirst = 0,
							ExtendLast = 0,
							Loop = 0,
							AspectMode = 0,
							Depth = 0,
							TimeCode = 0,
							GlobalStart = 1,
							GlobalEnd = 1
						}
					},
					NameSet = true,
					Inputs = {
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1, },
						["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "worldPositions.X" }, },
						["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "worldPositions.Y" }, },
						["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "worldPositions.Z" }, },
						["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" }, },
					},
					ViewInfo = OperatorInfo { Pos = { 110, 49.5 } },
				},
				B1Reflection = Loader {
					Clips = {
						Clip {
							ID = "Clip1",
							Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
							FormatID = "OpenEXRFormat",
							StartFrame = 1,
							LengthSetManually = true,
							TrimIn = 0,
							TrimOut = 0,
							ExtendFirst = 0,
							ExtendLast = 0,
							Loop = 0,
							AspectMode = 0,
							Depth = 0,
							TimeCode = 0,
							GlobalStart = 1,
							GlobalEnd = 1
						}
					},
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1, },
						["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "reflectionFilter.R" }, },
						["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "reflectionFilter.G" }, },
						["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "reflectionFilter.B" }, },
						["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" }, },
					},
					ViewInfo = OperatorInfo { Pos = { 110, 412.5 } },
				},
				B1DiffuseFilter = Loader {
					Clips = {
						Clip {
							ID = "Clip1",
							Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
							FormatID = "OpenEXRFormat",
							StartFrame = 1,
							LengthSetManually = true,
							TrimIn = 0,
							TrimOut = 0,
							ExtendFirst = 0,
							ExtendLast = 0,
							Loop = 0,
							AspectMode = 0,
							Depth = 0,
							TimeCode = 0,
							GlobalStart = 1,
							GlobalEnd = 1
						}
					},
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1, },
						["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "diffuseFilter.R" }, },
						["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "diffuseFilter.G" }, },
						["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "diffuseFilter.B" }, },
						["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" }, },
					},
					ViewInfo = OperatorInfo { Pos = { 110, 379.5 } },
				},
				B1MatteShadow = Loader {
					Clips = {
						Clip {
							ID = "Clip1",
							Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
							FormatID = "OpenEXRFormat",
							StartFrame = 1,
							LengthSetManually = true,
							TrimIn = 0,
							TrimOut = 0,
							ExtendFirst = 0,
							ExtendLast = 0,
							Loop = 0,
							AspectMode = 0,
							Depth = 0,
							TimeCode = 0,
							GlobalStart = 1,
							GlobalEnd = 1
						}
					},
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1, },
						["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "matteShadow.R" }, },
						["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "matteShadow.G" }, },
						["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "matteShadow.B" }, },
						["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" }, },
					},
					ViewInfo = OperatorInfo { Pos = { 110, 346.5 } },
				},
				B1WorldNormals = Loader {
					Clips = {
						Clip {
							ID = "Clip1",
							Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
							FormatID = "OpenEXRFormat",
							StartFrame = 1,
							LengthSetManually = true,
							TrimIn = 0,
							TrimOut = 0,
							ExtendFirst = 0,
							ExtendLast = 0,
							Loop = 0,
							AspectMode = 0,
							Depth = 0,
							TimeCode = 0,
							GlobalStart = 1,
							GlobalEnd = 1
						}
					},
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1, },
						["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "worldNormals.X" }, },
						["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "worldNormals.Y" }, },
						["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "worldNormals.Z" }, },
						["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" }, },
					},
					ViewInfo = OperatorInfo { Pos = { 110, 313.5 } },
				},
				B1WorldPositions = Loader {
					Clips = {
						Clip {
							ID = "Clip1",
							Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
							FormatID = "OpenEXRFormat",
							StartFrame = 1,
							LengthSetManually = true,
							TrimIn = 0,
							TrimOut = 0,
							ExtendFirst = 0,
							ExtendLast = 0,
							Loop = 0,
							AspectMode = 0,
							Depth = 0,
							TimeCode = 0,
							GlobalStart = 1,
							GlobalEnd = 1
						}
					},
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1, },
						["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "worldPositions.X" }, },
						["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "worldPositions.Y" }, },
						["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "worldPositions.Z" }, },
						["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" }, },
					},
					ViewInfo = OperatorInfo { Pos = { 110, 280.5 } },
				},
				B1RGB = Loader {
					Clips = {
						Clip {
							ID = "Clip1",
							Filename = "Comp:/Media/satellite_lighting_b1.0001.exr",
							FormatID = "OpenEXRFormat",
							StartFrame = 1,
							LengthSetManually = true,
							TrimIn = 0,
							TrimOut = 0,
							ExtendFirst = 0,
							ExtendLast = 0,
							Loop = 0,
							AspectMode = 0,
							Depth = 0,
							TimeCode = 0,
							GlobalStart = 1,
							GlobalEnd = 1
						}
					},
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1, },
						["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "R" }, },
						["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "G" }, },
						["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "B" }, },
						["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" }, },
					},
					ViewInfo = OperatorInfo { Pos = { 110, 247.5 } },
				},
				B0Reflection = Loader {
					Clips = {
						Clip {
							ID = "Clip1",
							Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
							FormatID = "OpenEXRFormat",
							StartFrame = 1,
							LengthSetManually = true,
							TrimIn = 0,
							TrimOut = 0,
							ExtendFirst = 0,
							ExtendLast = 0,
							Loop = 0,
							AspectMode = 0,
							Depth = 0,
							TimeCode = 0,
							GlobalStart = 1,
							GlobalEnd = 1
						}
					},
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1, },
						["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "reflectionFilter.R" }, },
						["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "reflectionFilter.G" }, },
						["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "reflectionFilter.B" }, },
						["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" }, },
					},
					ViewInfo = OperatorInfo { Pos = { 110, 181.5 } },
				},
				B0DiffuseFilter = Loader {
					Clips = {
						Clip {
							ID = "Clip1",
							Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
							FormatID = "OpenEXRFormat",
							StartFrame = 1,
							LengthSetManually = true,
							TrimIn = 0,
							TrimOut = 0,
							ExtendFirst = 0,
							ExtendLast = 0,
							Loop = 0,
							AspectMode = 0,
							Depth = 0,
							TimeCode = 0,
							GlobalStart = 1,
							GlobalEnd = 1
						}
					},
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1, },
						["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "diffuseFilter.R" }, },
						["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "diffuseFilter.G" }, },
						["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "diffuseFilter.B" }, },
						["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" }, },
					},
					ViewInfo = OperatorInfo { Pos = { 110, 148.5 } },
				},
				B0MatteShadow = Loader {
					Clips = {
						Clip {
							ID = "Clip1",
							Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
							FormatID = "OpenEXRFormat",
							StartFrame = 1,
							LengthSetManually = true,
							TrimIn = 0,
							TrimOut = 0,
							ExtendFirst = 0,
							ExtendLast = 0,
							Loop = 0,
							AspectMode = 0,
							Depth = 0,
							TimeCode = 0,
							GlobalStart = 1,
							GlobalEnd = 1
						}
					},
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1, },
						["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "matteShadow.R" }, },
						["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "matteShadow.G" }, },
						["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "matteShadow.B" }, },
						["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" }, },
					},
					ViewInfo = OperatorInfo { Pos = { 110, 115.5 } },
				},
				B0WorldNormals = Loader {
					Clips = {
						Clip {
							ID = "Clip1",
							Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
							FormatID = "OpenEXRFormat",
							StartFrame = 1,
							LengthSetManually = true,
							TrimIn = 0,
							TrimOut = 0,
							ExtendFirst = 0,
							ExtendLast = 0,
							Loop = 0,
							AspectMode = 0,
							Depth = 0,
							TimeCode = 0,
							GlobalStart = 1,
							GlobalEnd = 1
						}
					},
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1, },
						["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "worldNormals.X" }, },
						["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "worldNormals.Y" }, },
						["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "worldNormals.Z" }, },
						["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" }, },
					},
					ViewInfo = OperatorInfo { Pos = { 110, 82.5 } },
				},
				B0RGB = Loader {
					Clips = {
						Clip {
							ID = "Clip1",
							Filename = "Comp:/Media/satellite_lighting_b0.0001.exr",
							FormatID = "OpenEXRFormat",
							StartFrame = 1,
							LengthSetManually = true,
							TrimIn = 0,
							TrimOut = 0,
							ExtendFirst = 0,
							ExtendLast = 0,
							Loop = 0,
							AspectMode = 0,
							Depth = 0,
							TimeCode = 0,
							GlobalStart = 1,
							GlobalEnd = 1
						}
					},
					CtrlWZoom = false,
					NameSet = true,
					Inputs = {
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1, },
						["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "R" }, },
						["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "G" }, },
						["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "B" }, },
						["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" }, },
					},
					ViewInfo = OperatorInfo { Pos = { 110, 16.5 } },
				},
				DenoisedResultLoader = Loader {
					Clips = {
						Clip {
							ID = "Clip1",
							Filename = "Comp:/Media/altus_output/rgb_nr.0001.exr",
							FormatID = "OpenEXRFormat",
							StartFrame = 1,
							LengthSetManually = true,
							TrimIn = 0,
							TrimOut = 0,
							ExtendFirst = 0,
							ExtendLast = 0,
							Loop = 0,
							AspectMode = 0,
							Depth = 0,
							TimeCode = 0,
							GlobalStart = 1,
							GlobalEnd = 1
						}
					},
					NameSet = true,
					Inputs = {
						MissingFrames = Input { Value = 2, },
						Red = Input { Value = 0.97, },
						Green = Input { Value = 0.89, },
						Blue = Input { Value = 0.16, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						["Clip1.OpenEXRFormat.Channels"] = Input { Value = 1, },
						["Clip1.OpenEXRFormat.RedName"] = Input { Value = FuID { "R" }, },
						["Clip1.OpenEXRFormat.GreenName"] = Input { Value = FuID { "G" }, },
						["Clip1.OpenEXRFormat.BlueName"] = Input { Value = FuID { "B" }, },
						["Clip1.OpenEXRFormat.AlphaName"] = Input { Value = FuID { "A" }, },
						EffectMask = Input {
							SourceOp = "DependencyLinkerChannelBooleans",
							Source = "Output",
						}
					},
					ViewInfo = OperatorInfo { Pos = { 880, 313.5 } },
				},
				B1ReflectionSaver = Saver {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ProcessWhenBlendIs00 = Input { Value = 0, },
						Clip = Input {
							Value = Clip {
								Filename = "Comp:/Media/altus_input/Reflection_b1.0000.exr",
								FormatID = "OpenEXRFormat",
								Length = 0,
								Saving = true,
								TrimIn = 0,
								ExtendFirst = 0,
								ExtendLast = 0,
								Loop = 1,
								AspectMode = 0,
								Depth = 0,
								TimeCode = 0,
								GlobalStart = -2000000000,
								GlobalEnd = 0
							},
						},
						CreateDir = Input { Value = 1, },
						OutputFormat = Input { Value = FuID { "OpenEXRFormat" }, },
						SaveFrames = Input { Value = FuID { "HiQInteractive" }, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						Input = Input {
							SourceOp = "ReflectionSetDomainB1",
							Source = "Output",
						},
						["OpenEXRFormat.Depth"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { 330, 412.5 } },
				},
				B1DiffuseFilterSaver = Saver {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ProcessWhenBlendIs00 = Input { Value = 0, },
						Clip = Input {
							Value = Clip {
								Filename = "Comp:/Media/altus_input/DiffuseFilter_b1.0000.exr",
								FormatID = "OpenEXRFormat",
								Length = 0,
								Saving = true,
								TrimIn = 0,
								ExtendFirst = 0,
								ExtendLast = 0,
								Loop = 1,
								AspectMode = 0,
								Depth = 0,
								TimeCode = 0,
								GlobalStart = -2000000000,
								GlobalEnd = 0
							},
						},
						CreateDir = Input { Value = 1, },
						OutputFormat = Input { Value = FuID { "OpenEXRFormat" }, },
						SaveFrames = Input { Value = FuID { "HiQInteractive" }, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						Input = Input {
							SourceOp = "DiffuseFilterSetDomainB1",
							Source = "Output",
						},
						["OpenEXRFormat.Depth"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { 330, 379.5 } },
				},
				B1MatteShadowSaver = Saver {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ProcessWhenBlendIs00 = Input { Value = 0, },
						Clip = Input {
							Value = Clip {
								Filename = "Comp:/Media/altus_input/MatteShadow_b1.0000.exr",
								FormatID = "OpenEXRFormat",
								Length = 0,
								Saving = true,
								TrimIn = 0,
								ExtendFirst = 0,
								ExtendLast = 0,
								Loop = 1,
								AspectMode = 0,
								Depth = 0,
								TimeCode = 0,
								GlobalStart = -2000000000,
								GlobalEnd = 0
							},
						},
						CreateDir = Input { Value = 1, },
						OutputFormat = Input { Value = FuID { "OpenEXRFormat" }, },
						SaveFrames = Input { Value = FuID { "HiQInteractive" }, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						Input = Input {
							SourceOp = "MatteShadowSetDomainB1",
							Source = "Output",
						},
						["OpenEXRFormat.Depth"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { 330, 346.5 } },
				},
				B1WorldNormalsSaver = Saver {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ProcessWhenBlendIs00 = Input { Value = 0, },
						Clip = Input {
							Value = Clip {
								Filename = "Comp:/Media/altus_input/WorldNormals_b1.0000.exr",
								FormatID = "OpenEXRFormat",
								Length = 0,
								Saving = true,
								TrimIn = 0,
								ExtendFirst = 0,
								ExtendLast = 0,
								Loop = 1,
								AspectMode = 0,
								Depth = 0,
								TimeCode = 0,
								GlobalStart = -2000000000,
								GlobalEnd = 0
							},
						},
						CreateDir = Input { Value = 1, },
						OutputFormat = Input { Value = FuID { "OpenEXRFormat" }, },
						SaveFrames = Input { Value = FuID { "HiQInteractive" }, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						Input = Input {
							SourceOp = "WorldNormalsSetDomainB1",
							Source = "Output",
						},
						["OpenEXRFormat.Depth"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { 330, 313.5 } },
				},
				B1WorldPositionsSaver = Saver {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ProcessWhenBlendIs00 = Input { Value = 0, },
						Clip = Input {
							Value = Clip {
								Filename = "Comp:/Media/altus_input/WorldPositions_b1.0000.exr",
								FormatID = "OpenEXRFormat",
								Length = 0,
								Saving = true,
								TrimIn = 0,
								ExtendFirst = 0,
								ExtendLast = 0,
								Loop = 1,
								AspectMode = 0,
								Depth = 0,
								TimeCode = 0,
								GlobalStart = -2000000000,
								GlobalEnd = 0
							},
						},
						CreateDir = Input { Value = 1, },
						OutputFormat = Input { Value = FuID { "OpenEXRFormat" }, },
						SaveFrames = Input { Value = FuID { "HiQInteractive" }, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						Input = Input {
							SourceOp = "WorldPositionsSetDomainB1",
							Source = "Output",
						},
						["OpenEXRFormat.Depth"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { 330, 280.5 } },
				},
				B1RGBSaver = Saver {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ProcessWhenBlendIs00 = Input { Value = 0, },
						Clip = Input {
							Value = Clip {
								Filename = "Comp:/Media/altus_input/rgb_b1.0000.exr",
								FormatID = "OpenEXRFormat",
								Length = 0,
								Saving = true,
								TrimIn = 0,
								ExtendFirst = 0,
								ExtendLast = 0,
								Loop = 1,
								AspectMode = 0,
								Depth = 0,
								TimeCode = 0,
								GlobalStart = -2000000000,
								GlobalEnd = 0
							},
						},
						CreateDir = Input { Value = 1, },
						OutputFormat = Input { Value = FuID { "OpenEXRFormat" }, },
						SaveFrames = Input { Value = FuID { "HiQInteractive" }, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						Input = Input {
							SourceOp = "RGBSetDomainB1",
							Source = "Output",
						},
						["OpenEXRFormat.Depth"] = Input { Value = 1, },
						["OpenEXRFormat.Channels"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { 330, 247.5 } },
				},
				ReflectionSetDomainB1 = SetDomain {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "RGBSetDomainB1",
					Inputs = {
						Input = Input {
							SourceOp = "B1Reflection",
							Source = "Output",
						},
						Foreground = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 220, 412.5 } },
				},
				DiffuseFilterSetDomainB1 = SetDomain {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "RGBSetDomainB1",
					Inputs = {
						Input = Input {
							SourceOp = "B1DiffuseFilter",
							Source = "Output",
						},
						Foreground = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 220, 379.5 } },
				},
				MatteShadowSetDomainB1 = SetDomain {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "RGBSetDomainB1",
					Inputs = {
						Input = Input {
							SourceOp = "B1MatteShadow",
							Source = "Output",
						},
						Foreground = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 220, 346.5 } },
				},
				WorldNormalsSetDomainB1 = SetDomain {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "RGBSetDomainB1",
					Inputs = {
						Input = Input {
							SourceOp = "B1WorldNormals",
							Source = "Output",
						},
						Foreground = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 220, 313.5 } },
				},
				WorldPositionsSetDomainB1 = SetDomain {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "RGBSetDomainB1",
					Inputs = {
						Input = Input {
							SourceOp = "B1WorldPositions",
							Source = "Output",
						},
						Foreground = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 220, 280.5 } },
				},
				RGBSetDomainB1 = SetDomain {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "RGBSetDomainB0",
					Inputs = {
						Input = Input {
							SourceOp = "B1RGB",
							Source = "Output",
						},
						Foreground = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 220, 247.5 } },
				},
				B0ReflectionSaver = Saver {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ProcessWhenBlendIs00 = Input { Value = 0, },
						Clip = Input {
							Value = Clip {
								Filename = "Comp:/Media/altus_input/Reflection_b0.0000.exr",
								FormatID = "OpenEXRFormat",
								Length = 0,
								Saving = true,
								TrimIn = 0,
								ExtendFirst = 0,
								ExtendLast = 0,
								Loop = 1,
								AspectMode = 0,
								Depth = 0,
								TimeCode = 0,
								GlobalStart = -2000000000,
								GlobalEnd = 0
							},
						},
						CreateDir = Input { Value = 1, },
						OutputFormat = Input { Value = FuID { "OpenEXRFormat" }, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						Input = Input {
							SourceOp = "ReflectionSetDomainB0",
							Source = "Output",
						},
						["OpenEXRFormat.Depth"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { 330, 181.5 } },
				},
				ReflectionSetDomainB0 = SetDomain {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "RGBSetDomainB0",
					Inputs = {
						Input = Input {
							SourceOp = "B0Reflection",
							Source = "Output",
						},
						Foreground = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 220, 181.5 } },
				},
				B0DiffuseFilterSaver = Saver {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ProcessWhenBlendIs00 = Input { Value = 0, },
						Clip = Input {
							Value = Clip {
								Filename = "Comp:/Media/altus_input/DiffuseFilter_b0.0000.exr",
								FormatID = "OpenEXRFormat",
								Length = 0,
								Saving = true,
								TrimIn = 0,
								ExtendFirst = 0,
								ExtendLast = 0,
								Loop = 1,
								AspectMode = 0,
								Depth = 0,
								TimeCode = 0,
								GlobalStart = -2000000000,
								GlobalEnd = 0
							},
						},
						CreateDir = Input { Value = 1, },
						OutputFormat = Input { Value = FuID { "OpenEXRFormat" }, },
						SaveFrames = Input { Value = FuID { "HiQInteractive" }, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						Input = Input {
							SourceOp = "DiffuseFilterSetDomainB0",
							Source = "Output",
						},
						["OpenEXRFormat.Depth"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { 330, 148.5 } },
				},
				DiffuseFilterSetDomainB0 = SetDomain {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "RGBSetDomainB0",
					Inputs = {
						Input = Input {
							SourceOp = "B0DiffuseFilter",
							Source = "Output",
						},
						Foreground = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 220, 148.5 } },
				},
				MatteShadowSetDomainB0 = SetDomain {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "RGBSetDomainB0",
					Inputs = {
						Input = Input {
							SourceOp = "B0MatteShadow",
							Source = "Output",
						},
						Foreground = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 220, 115.5 } },
				},
				B0MatteShadowSaver = Saver {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ProcessWhenBlendIs00 = Input { Value = 0, },
						Clip = Input {
							Value = Clip {
								Filename = "Comp:/Media/altus_input/MatteShadow_b0.0000.exr",
								FormatID = "OpenEXRFormat",
								Length = 0,
								Saving = true,
								TrimIn = 0,
								ExtendFirst = 0,
								ExtendLast = 0,
								Loop = 1,
								AspectMode = 0,
								Depth = 0,
								TimeCode = 0,
								GlobalStart = -2000000000,
								GlobalEnd = 0
							},
						},
						CreateDir = Input { Value = 1, },
						OutputFormat = Input { Value = FuID { "OpenEXRFormat" }, },
						SaveFrames = Input { Value = FuID { "HiQInteractive" }, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						Input = Input {
							SourceOp = "MatteShadowSetDomainB0",
							Source = "Output",
						},
						["OpenEXRFormat.Depth"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { 330, 115.5 } },
				},
				WorldNormalsSetDomainB0 = SetDomain {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "RGBSetDomainB0",
					Inputs = {
						Input = Input {
							SourceOp = "B0WorldNormals",
							Source = "Output",
						},
						Foreground = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 220, 82.5 } },
				},
				B0WorldNormalsSaver = Saver {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ProcessWhenBlendIs00 = Input { Value = 0, },
						Clip = Input {
							Value = Clip {
								Filename = "Comp:/Media/altus_input/WorldNormals_b0.0000.exr",
								FormatID = "OpenEXRFormat",
								Length = 0,
								Saving = true,
								TrimIn = 0,
								ExtendFirst = 0,
								ExtendLast = 0,
								Loop = 1,
								AspectMode = 0,
								Depth = 0,
								TimeCode = 0,
								GlobalStart = -2000000000,
								GlobalEnd = 0
							},
						},
						CreateDir = Input { Value = 1, },
						OutputFormat = Input { Value = FuID { "OpenEXRFormat" }, },
						SaveFrames = Input { Value = FuID { "HiQInteractive" }, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						Input = Input {
							SourceOp = "WorldNormalsSetDomainB0",
							Source = "Output",
						},
						["OpenEXRFormat.Depth"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { 330, 82.5 } },
				},
				B0WorldPositionsSaver = Saver {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ProcessWhenBlendIs00 = Input { Value = 0, },
						Clip = Input {
							Value = Clip {
								Filename = "Comp:/Media/altus_input/WorldPositions_b0.0000.exr",
								FormatID = "OpenEXRFormat",
								Length = 0,
								Saving = true,
								TrimIn = 0,
								ExtendFirst = 0,
								ExtendLast = 0,
								Loop = 1,
								AspectMode = 0,
								Depth = 0,
								TimeCode = 0,
								GlobalStart = -2000000000,
								GlobalEnd = 0
							},
						},
						CreateDir = Input { Value = 1, },
						OutputFormat = Input { Value = FuID { "OpenEXRFormat" }, },
						SaveFrames = Input { Value = FuID { "HiQInteractive" }, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						Input = Input {
							SourceOp = "WorldPositionsSetDomainB0",
							Source = "Output",
						},
						["OpenEXRFormat.Depth"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { 330, 49.5 } },
				},
				WorldPositionsSetDomainB0 = SetDomain {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "RGBSetDomainB0",
					Inputs = {
						Input = Input {
							SourceOp = "B0WorldPositions",
							Source = "Output",
						},
						Foreground = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 220, 49.5 } },
				},
				RGBSetDomainB0 = SetDomain {
					CtrlWShown = false,
					NameSet = true,
					CustomData = {
						Settings = {
							[1] = {
								Tools = ordered() {
									RGBSetDomainB0 = SetDomain {
										Inputs = {
											Top = Input { Value = 0.592592592592593 },
											Bottom = Input { Value = 0.0666666666666667 },
											Input = Input {
												SourceOp = "RGBB0",
												Source = "Output"
											},
											Mode = Input { Value = FuID { "Set" } },
											Left = Input { Value = 0.310699588477366 },
											Right = Input { Value = 0.524691358024691 }
										},
										Name = "RGBSetDomainB0",
										CtrlWZoom = false,
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 715, 280.5 } },
										CustomData = {
										}
									}
								}
							},
							[2] = {
								Tools = ordered() {
									RGBSetDomainB0 = SetDomain {
										Inputs = {
											Input = Input {
												SourceOp = "RGBB0",
												Source = "Output"
											},
											Mode = Input { Value = FuID { "Set" } }
										},
										CtrlWZoom = false,
										NameSet = true,
										ViewInfo = OperatorInfo { Pos = { 220, 15.8304 } },
										CustomData = {
										}
									}
								}
							}
						}
					},
					Inputs = {
						Mode = Input { Value = FuID { "Set" }, },
						Left = Input { Value = 0.240066225165563, },
						Right = Input { Value = 0.606788079470199, },
						Input = Input {
							SourceOp = "B0RGB",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 220, 16.5 } },
				},
				B0RGBSaver = Saver {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ProcessWhenBlendIs00 = Input { Value = 0, },
						Clip = Input {
							Value = Clip {
								Filename = "Comp:/Media/altus_input/rgb_b0.0000.exr",
								FormatID = "OpenEXRFormat",
								Length = 0,
								Saving = true,
								TrimIn = 0,
								ExtendFirst = 0,
								ExtendLast = 0,
								Loop = 1,
								AspectMode = 0,
								Depth = 0,
								TimeCode = 0,
								GlobalStart = -2000000000,
								GlobalEnd = 0
							},
						},
						CreateDir = Input { Value = 1, },
						OutputFormat = Input { Value = FuID { "OpenEXRFormat" }, },
						SaveFrames = Input { Value = FuID { "HiQInteractive" }, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						Input = Input {
							SourceOp = "RGBSetDomainB0",
							Source = "Output",
						},
						StartEndRenderScripts = Input { Value = 1, },
						["OpenEXRFormat.Depth"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { 330, 16.5 } },
				},
				AltusDenoiserCore = Fuse.AltusDenoiserCore {
					CtrlWShown = false,
					Inputs = {
						["B0 MatteShadow"] = Input {
							SourceOp = "B0MatteShadowSaver",
							Source = "Output",
						},
						AltusPreserveLayers = Input { Value = 1, },
						["B0Diffuse Filter"] = Input {
							SourceOp = "B0DiffuseFilterSaver",
							Source = "Output",
						},
						["B0 WorldNormal"] = Input {
							SourceOp = "B0WorldNormalsSaver",
							Source = "Output",
						},
						["B0 WorldPosition"] = Input {
							SourceOp = "B0WorldPositionsSaver",
							Source = "Output",
						},
						AltusMode = Input { Value = 1, },
						B0RGB = Input {
							SourceOp = "B0RGBSaver",
							Source = "Output",
						},
						B0WorldPositions = Input {
							SourceOp = "B0WorldPositionsSaver",
							Source = "Output",
						},
						B0WorldNormals = Input {
							SourceOp = "B0WorldNormalsSaver",
							Source = "Output",
						},
						B0MatteShadow = Input {
							SourceOp = "B0MatteShadowSaver",
							Source = "Output",
						},
						B0DiffuseFilter = Input {
							SourceOp = "B0DiffuseFilterSaver",
							Source = "Output",
						},
						B0Reflection = Input {
							SourceOp = "B0ReflectionSaver",
							Source = "Output",
						},
						B1RGB = Input {
							SourceOp = "B1RGBSaver",
							Source = "Output",
						},
						B1WorldPositions = Input {
							SourceOp = "B1WorldPositionsSaver",
							Source = "Output",
						},
						B1WorldNormals = Input {
							SourceOp = "B1WorldNormalsSaver",
							Source = "Output",
						},
						B1MatteShadow = Input {
							SourceOp = "B1MatteShadowSaver",
							Source = "Output",
						},
						["B1Diffuse Filter"] = Input {
							SourceOp = "B1DiffuseFilterSaver",
							Source = "Output",
						},
						B1Reflection = Input {
							SourceOp = "B1ReflectionSaver",
							Source = "Output",
						},
						AltusOutputMode = Input { Value = 1, },
						AltusVerbose = Input { Value = 1, },
						AltusRenderFrame = Input { Value = 1, },
						AltusKC2 = Input { Value = 8, },
						AltusKC4 = Input { Value = 5, },
					},
					ViewInfo = OperatorInfo { Pos = { 495, 214.5 } },
					Version = 100
				},
				DependencyLinkerChannelBooleans = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 16, },
						ToGreen = Input { Value = 16, },
						ToBlue = Input { Value = 16, },
						ToAlpha = Input { Value = 16, },
						EnableExtraChannels = Input { Value = 1, },
						Background = Input {
							SourceOp = "Done",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 715, 313.5 } },
				},
				SwitchElseFuse = Fuse.SwitchElse {
					CtrlWShown = false,
					Inputs = {
						Switch = Input {
							Value = 2,
							Expression = "iif(AltusDenoiserCore.AltusOutputMode == 1, 2, 1)",
						},
						Else = Input { Value = 1, },
						Notify = Input { Value = 1, },
						Input1 = Input {
							SourceOp = "Done",
							Source = "Output",
						},
						Input2 = Input {
							SourceOp = "DenoisedResultLoader",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 880, 214.5 } },
					Version = 100
				},
				Done = Merge {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Blend = Input { Value = 0, },
						Background = Input {
							SourceOp = "AltusDenoiserCore",
							Source = "Output",
						},
						PerformDepthMerge = Input { Value = 0, },
					},
					ViewInfo = OperatorInfo { Pos = { 605, 214.5 } },
				}
			},
		}
	},
	Views = {
		{
			FrameTypeID = "ChildFrame",
			Mode = 3,
			LayoutPreset = 0,
			Left = 0,
			Top = 27,
			Width = 1839,
			Height = 1199,
			Views = ordered() {
				Main = MultiView {
					Active = "Flow",
					ViewList = ordered() {
						Flow = "FlowView",
						Timeline = "TimelineView",
						Spline = "SplineEditorView",
						Info = "InfoView",
						Chat = "ChatView"
					},
					Flow = FlowView {
						Flags = {
							AutoHideNavigator = true,
							AutoSnap = true,
							RemoveRouters = true
						},
						NavigatorSize = { 200, 140 },
						Direction = "Horizontal",
						PipeStyle = "Direct",
						Scale = 1.2644,
						Offset = { -1454.45, -517.409 }
					},
					Timeline = TimelineView {
						TreeControlState = {
						},
						DisplayMode = "All Tools",
						ShowCurrentTimeTools = false,
						Filter = "Show All",
						ShowSelectedTools = false,
						ShowAnimatedToolsOnly = false,
						ShowEditBoxes = false,
						KeyFrameView = {
							Position = { Left = 150, Bottom = 487 },
							ScaleX = 0.00214424951267056,
							OffsetX = 0.94990253411306,
							OffsetY = 0,
							AutoScaling = "scroll",
							AutoSnapTo = "frame",
							AutoSnapToGuidelines = false,
							GuidelinesGrabEnabled = true,
							GuidelinesSnapTo = "frame"
						},
						Spreadsheet = { LeftPos = 150, Visible = false }
					},
					Spline = SplineEditorView {
						LeftPos = 256,
						ScaleX = 0.2,
						ScaleY = 0.00338983050847458,
						OffsetX = -4,
						OffsetY = 0,
						AutoScaling = "scroll",
						AutoSnapTo = "frame",
						AutoSnapToGuidelines = false,
						GuidelinesSnapTo = "frame",
						ShowKeyMarkers = false,
						IndependentHandles = false,
						ShowNonSplineModifiers = false,
						GuidelinesGrabEnabled = true,
						ShowOneToolOnly = false,
						ShowSelectedTools = false,
						ShowAllInputs = false,
						Filter = "Show All"
					},
				},
				Controls = MultiView {
					Active = "Tools",
					ViewList = ordered() {
						Tools = "ControlView",
						Modifiers = "ModifierView"
					},
				},
				Left = "PreviewContainer",
				Right = "PreviewContainer",
				Transport = "TransportView",
				Time = "TimeView",
				ConsoleView = "ConsoleView"
			},
			Layout = {
				Columns = 2,
				RatioX = 1,
				RatioY = 1,
				{
					Rows = 3,
					RatioX = 0.703380588876772,
					RatioY = 99.8330550918197,
					{
						Columns = 2,
						RatioX = 1,
						RatioY = 0.350671140939597,
						{ ID = "Left", RatioX = 0.543123543123543, RatioY = 108.799043062201, Pop = true },
						{ ID = "Right", RatioX = 0.456876456876457, Pop = true },
						Pop = true
					},
					{ ID = "Main", RatioY = 0.600671140939597, Pop = true },
					{ ID = "Time", SnapY = 56, Flat = true }
				},
				{
					Rows = 2,
					PixelX = 542,
					{
						Rows = 2,
						RatioX = 1,
						RatioY = 1,
						{ ID = "Controls", RatioX = 1, RatioY = 0.810041841004184, Pop = true },
						{ ID = "ConsoleView", RatioY = 0.189958158995816, Pop = true }
					},
					{ ID = "Transport", FixedY = -2 }
				}
			}
		}
	},
	Prefs = {
		Comp = {
			Interactive = {
				Proxy = {
					Scale = 2,
				},
			},
			Memory = {
				FramesAtOnce = 1,
			},
			Views = {
				Right = {
					Viewer = {
						EnableLUTs = true,
						LUTPlugin = "OCIOColorSpaceViewLUT",
						ScaleMode = 1,
						LUTSelected = "OCIO ColorSpace ViewLUT",
					},
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0
						}
					},
					ViewLUT = {
						{
							Tools = ordered() {
								OCIOColorSpaceViewLUT1 = ViewOperator {
									CtrlWZoom = false,
									NameSet = true,
									Inputs = {
										SourceSpace = Input { Value = FuID { "linear" }, },
										OutputSpace = Input { Value = FuID { "sRGB" }, },
										Look = Input { Value = FuID { "None" }, },
									},
								}
							},
							ID = "OCIOColorSpaceViewLUT"
						},
						Recent = {
							SelectedPlugin = "OCIOColorSpaceViewLUT",
							FusionViewLUT = {
								Tools = ordered() {
									FusionViewLUT = ViewLUTOp {
										NameSet = true,
										Inputs = {
										}
									}
								}
							},
							SelectedName = "OCIO ColorSpace ViewLUT"
						},
						SelectedName = "OCIO ColorSpace ViewLUT",
						SelectedPlugin = "OCIOColorSpaceViewLUT"
					},
				},
				Left = {
					Viewer = {
						EnableLUTs = true,
						LUTPlugin = "OCIOColorSpaceViewLUT",
						ScaleMode = 1,
						LUTSelected = "OCIO ColorSpace ViewLUT",
					},
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = true,
							LUTPlugin = "OCIOColorSpaceViewLUT",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0,
							ScaleMode = 1,
							LUTSelected = "OCIO ColorSpace ViewLUT"
						},
						ViewLUT = {
							{
								Tools = ordered() {
									OCIOColorSpaceViewLUT2 = ViewOperator {
										CtrlWZoom = false,
										NameSet = true,
										Inputs = {
											SourceSpace = Input { Value = FuID { "linear" }, },
											OutputSpace = Input { Value = FuID { "sRGB" }, },
											Look = Input { Value = FuID { "None" }, },
										},
									}
								},
								ID = "OCIOColorSpaceViewLUT"
							},
							Recent = {
								FusionViewLUT = {
									Tools = ordered() {
										FusionViewLUT = ViewLUTOp {
											NameSet = true,
											Inputs = {
											},
										}
									}
								},
								SelectedPlugin = "OCIOColorSpaceViewLUT",
								SelectedName = "OCIO ColorSpace ViewLUT"
							},
							SelectedPlugin = "OCIOColorSpaceViewLUT",
							SelectedName = "OCIO ColorSpace ViewLUT"
						}
					},
					SubView = {
						Enabled = false,
						Navigator = false,
						Magnifier = false,
						ID = "GLMetadataViewer",
						GLMetadataViewer = {
							AutoBounds = true
						}
					},
					ViewLUT = {
						{
							Tools = ordered() {
								OCIOColorSpaceViewLUT = ViewOperator {
									CtrlWZoom = false,
									NameSet = true,
									Inputs = {
										SourceSpace = Input { Value = FuID { "linear" }, },
										OutputSpace = Input { Value = FuID { "sRGB" }, },
										Look = Input { Value = FuID { "None" }, },
									},
								}
							},
							ID = "OCIOColorSpaceViewLUT"
						},
						Recent = {
							SelectedPlugin = "OCIOColorSpaceViewLUT",
							FusionViewLUT = {
								Tools = ordered() {
									FusionViewLUT = ViewLUTOp {
										NameSet = true,
										Inputs = {
										}
									}
								}
							},
							SelectedName = "OCIO ColorSpace ViewLUT"
						},
						SelectedName = "OCIO ColorSpace ViewLUT",
						SelectedPlugin = "OCIOColorSpaceViewLUT"
					},
				},
				View1 = {
					PrevCtrlInactiveColor = 0,
					FullScreen = false,
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0
						}
					},
					PickH = 1,
					PrevCtrlActiveColor = 0,
					AlwaysOnTop = true,
					PickW = 1
				},
				View2 = {
					PickH = 1,
					AlwaysOnTop = true,
					FullScreen = false,
					PickW = 1
				},
				View5 = {
					PickH = 1,
					AlwaysOnTop = true,
					FullScreen = false,
					PickW = 1
				},
				View3 = {
					PickH = 1,
					AlwaysOnTop = true,
					FullScreen = false,
					PickW = 1
				},
				View4 = {
					PickH = 1,
					AlwaysOnTop = true,
					FullScreen = false,
					PickW = 1
				}
			},
			FrameFormat = {
				Name = "DSI",
				Height = 800,
				Rate = 24,
				GuideRatio = 1,
				DepthFull = 3,
				DepthPreview = 3,
				DepthInteractive = 3,
			},
			Unsorted = {
				GlobalStart = 1,
				GlobalEnd = 2,
				RenderSettings = {
					Configs = {
						Preview = {
							StepRender = false,
							PriorityClasses = "all",
							CustomAspect = true,
							StepSize = 5,
							SizeType = 1,
							CustomHeight = 160,
							ShowSlaves = false,
							CustomWidth = 200,
							MotionBlur = true,
							UpdateMode = "Some",
							UseNetwork = false,
							Quality = false
						},
						Final = {
							StepRender = false,
							PriorityClasses = "all",
							CustomAspect = true,
							StepSize = 5,
							SizeType = 1,
							CustomHeight = 160,
							ShowSlaves = false,
							CustomWidth = 200,
							MotionBlur = true,
							UpdateMode = "Some",
							UseNetwork = false,
							Quality = true
						}
					},
					PreviewConfig = "Preview",
					CurrentConfig = "Final"
				}
			},
			Tweaks = {
				OpenCL = {
					Enable = 0,
					Caching = 0
				}
			},
			Paths = {
				EnableReverseMapping = true,
			},
			QuickTime = {
			},
		}
	}
}

 