fusion:SetPrefs("Comp.LastFile", "")
fusion:SetPrefs("Comp.LastLUTFile", "")
fusion:SetPrefs("Global.FileReq.History", {})
fusion:SetPrefs("Global.LastCompFile", "")
fusion:SetPrefs("Global.RecentComps", {})
fusion:SetPrefs("Global.LastQueueFile", "")
fusion:SetPrefs("Global.Alembic.Import.LastFile", "Comps:")
fusion:SetPrefs("Global.LastFilterFile", "Filters:")
fusion:SetPrefs("Global.LensDistort.Import.LastFile", "Comps:")
fusion:SetPrefs("Global.FBX.Import.LastFile", "Comps:")
fusion:SetPrefs("Global.LastSettingFile", "Settings:")
comp:SetPrefs("Comp.Memory.FramesAtOnce", 1)
fusion:SetPrefs("Comp.Memory.FramesAtOnce", 1)
fusion:SavePrefs()