Composition {
	CurrentTime = 0,
	RenderRange = { 0, 144 },
	GlobalRange = { 0, 144 },
	CurrentID = 3708,
	HiQ = true,
	PlaybackUpdateMode = 0,
	Version = "Fusion 8.2.1 build 6",
	SavedOutputs = 1,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	Resumable = true,
	OutputClips = {
		"Temp:\\KartaVR\\DomemasterRenderer3DAdvanced_snapshot.0000.exr"
	},
	Tools = {
		SkyMerge3D = Merge3D {
			NameSet = true,
			Inputs = {
				["Transform3DOp.Translate.X"] = Input { Value = 8.63457423928764, },
				["Transform3DOp.Translate.Y"] = Input { Value = 32.5640361436439, },
				["Transform3DOp.Translate.Z"] = Input { Value = -18.7989914433103, },
				PassThroughLights = Input { Value = 1, },
				SceneInput1 = Input {
					SourceOp = "LightMerge3D",
					Source = "Output",
				},
				SceneInput2 = Input {
					SourceOp = "SkyEnvrionment",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 220, 148.5 } },
		},
		PointLight1 = LightPoint {
			Inputs = {
				["Transform3DOp.Translate.X"] = Input { Value = -161.856563476427, },
				["Transform3DOp.Translate.Y"] = Input { Value = 347.254927143773, },
				["Transform3DOp.Translate.Z"] = Input { Value = -32.0346642872779, },
				Intensity = Input { Value = 0.243373493975904, },
				DecayRate = Input { Value = 25000, },
			},
			ViewInfo = OperatorInfo { Pos = { -55, 181.5 } },
		},
		CookTorrance1 = MtlCookTorrance {
			Inputs = {
				MaterialIDNest = Input { Value = 1, },
				MaterialID = Input { Value = 6, },
			},
			ViewInfo = OperatorInfo { Pos = { -165, 82.5 } },
		},
		CoolDirectionalLight = LightDirectional {
			NameSet = true,
			Inputs = {
				["Transform3DOp.Translate.X"] = Input { Value = 58.3879784519737, },
				["Transform3DOp.Translate.Y"] = Input { Value = 95.1104338268553, },
				["Transform3DOp.Translate.Z"] = Input { Value = -26.3166398889364, },
				["Transform3DOp.Rotate.X"] = Input { Value = 137.656114007812, },
				["Transform3DOp.Rotate.Y"] = Input { Value = 31.7768835327588, },
				["Transform3DOp.Rotate.Z"] = Input { Value = 130.256588513497, },
				Red = Input { Value = 0.811764705882353, },
				Green = Input { Value = 0.917647058823529, },
				Intensity = Input { Value = 0.8, },
			},
			ViewInfo = OperatorInfo { Pos = { -55, 148.5 } },
		},
		Transform3D1YRotation = BezierSpline {
			SplineColor = { Red = 128, Green = 255, Blue = 128 },
			NameSet = true,
			KeyFrames = {
				[0] = { 180, RH = { 21.3333333333333, 180 }, Flags = { Linear = true } },
				[64] = { 180, LH = { 42.6666666666667, 180 }, Flags = { Linear = true } }
			}
		},
		Transform3D1YOffset = BezierSpline {
			SplineColor = { Red = 252, Green = 131, Blue = 47 },
			NameSet = true,
			KeyFrames = {
				[0] = { 54, RH = { 21.3333333333333, 54 }, Flags = { Linear = true } },
				[64] = { 54, LH = { 42.6666666666667, 54 }, Flags = { Linear = true } }
			}
		},
		FBXMesh3D1 = SurfaceFBXMesh {
			Inputs = {
				ImportFile = Input { Value = "Macros:\\KartaVR\\Images\\boxworld.fbx", },
				TransformToWorld = Input { Value = 0, },
				["ObjectID.Nest"] = Input { Value = 1, },
				["ObjectID.ObjectID"] = Input { Value = 4, },
				MaterialInput = Input {
					SourceOp = "CookTorrance1",
					Source = "MaterialOutput",
				},
				["MtlStdInputs.MaterialID"] = Input { Value = 5, },
			},
			ViewInfo = OperatorInfo { Pos = { -55, 82.5 } },
		},
		WarmDirectionalLight = LightDirectional {
			NameSet = true,
			Inputs = {
				["Transform3DOp.Translate.X"] = Input { Value = -37, },
				["Transform3DOp.Translate.Y"] = Input { Value = 96, },
				["Transform3DOp.Translate.Z"] = Input { Value = -27, },
				["Transform3DOp.Rotate.X"] = Input { Value = 58.1650225943886, },
				["Transform3DOp.Rotate.Y"] = Input { Value = -64.8353715026751, },
				["Transform3DOp.Rotate.Z"] = Input { Value = -91.4079946666025, },
				Green = Input { Value = 0.925490196078431, },
				Blue = Input { Value = 0.776470588235294, },
				Intensity = Input { Value = 0.8, },
			},
			ViewInfo = OperatorInfo { Pos = { -55, 115.5 } },
		},
		Transform3D1ZOffset = BezierSpline {
			SplineColor = { Red = 254, Green = 207, Blue = 46 },
			NameSet = true,
			KeyFrames = {
				[0] = { -44, RH = { 21.3333333333333, -68.2239185666667 }, Flags = { Linear = true } },
				[64] = { -116.6717557, LH = { 42.6666666666667, -92.4478371333333 }, Flags = { Linear = true } }
			}
		},
		DomemasterRenderer3DAdvanced = GroupOperator {
			CtrlWZoom = false,
			CustomData = {
				HelpPage = "http://www.andrewhazelden.com/projects/kartavr/docs/macros-guide.html#DomemasterRenderer3DAdvanced",
			},
			Inputs = ordered() {
				MainInput1 = InstanceInput {
					SourceOp = "CameraViewInput",
					Source = "SceneInput1",
				},
				Input1 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "Height",
					MaxScale = 8192,
					Default = 512,
				},
				Input2 = InstanceInput {
					SourceOp = "ChangeDepthOutput",
					Source = "Depth",
					Default = 0,
				},
				Input3 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "RendererSoftware.Channels.RGBA",
					Default = 1,
				},
				Input4 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "RendererSoftware.Channels.Z",
					Default = 1,
				},
				Input5 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "RendererSoftware.Channels.Coverage",
					Default = 1,
				},
				Input6 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "RendererSoftware.Channels.BgColor",
					Default = 1,
				},
				Input7 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "RendererSoftware.Channels.TexCoord0",
					Default = 1,
				},
				Input8 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "RendererSoftware.Channels.ObjectID",
					Default = 1,
				},
				Input9 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "RendererSoftware.Channels.MaterialID",
					Default = 1,
				},
				Input10 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "RendererSoftware.Channels.WorldCoord",
					Default = 1,
				},
				Input11 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "RendererSoftware.LightingEnabled",
					Default = 1,
				},
				Input12 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "RendererSoftware.ShadowsEnabled",
					Default = 1,
				},
				Input22 = InstanceInput {
					SourceOp = "Camera3DFront",
					Source = "Transform3DOp.Translate.X",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input23 = InstanceInput {
					SourceOp = "Camera3DFront",
					Source = "Transform3DOp.Translate.Y",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input24 = InstanceInput {
					SourceOp = "Camera3DFront",
					Source = "Transform3DOp.Translate.Z",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input25 = InstanceInput {
					SourceOp = "CubeMapColor",
					Source = "Rotate.RotOrder",
				},
				Input26 = InstanceInput {
					SourceOp = "CubeMapColor",
					Source = "Rotate.X",
					MinScale = -360,
					MaxScale = 360,
					Default = -90,
				},
				Input27 = InstanceInput {
					SourceOp = "CubeMapColor",
					Source = "Rotate.Y",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				Input28 = InstanceInput {
					SourceOp = "CubeMapColor",
					Source = "Rotate.Z",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				}
			},
			Outputs = {
				MainOutput1 = InstanceOutput {
					SourceOp = "ChangeDepthOutput",
					Source = "Output",
				}
			},
			ViewInfo = GroupInfo { Pos = { 605, 148.5 } },
			Tools = ordered() {
				Camera3DBack = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = 180,
							Expression = "Camera3DFront.Transform3DOp.Rotate.Z+180.0",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -857.7, 439.6 } },
				},
				Camera3DLeft = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = -90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.Z-90.0",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -857.7, 472.6 } },
				},
				Camera3DTop = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.X+90", },
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Z", },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -857.7, 505.6 } },
				},
				Camera3DFront = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Rotate.X"] = Input { Value = -90, },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -857.7, 373.6 } },
				},
				Camera3DRight = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = 90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.Z+90",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -857.7, 406.6 } },
				},
				Camera3DBottom = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -180,
							Expression = "Camera3DFront.Transform3DOp.Rotate.X-90",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Z", },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -857.7, 538.6 } },
				},
				CameraViewInput = Merge3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						PassThroughLights = Input { Value = 1, },
						SceneInput1 = Input {
							SourceOp = "Transform3D1",
							Source = "Output",
						},
						SceneInput2 = Input {
							SourceOp = "Camera3DFront",
							Source = "Output",
						},
						SceneInput3 = Input {
							SourceOp = "Camera3DRight",
							Source = "Output",
						},
						SceneInput5 = Input {
							SourceOp = "Camera3DLeft",
							Source = "Output",
						},
						SceneInput6 = Input {
							SourceOp = "Camera3DTop",
							Source = "Output",
						},
						SceneInput7 = Input {
							SourceOp = "Camera3DBottom",
							Source = "Output",
						},
						SceneInput4 = Input {
							SourceOp = "Camera3DBack",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -692.7, 637.6 } },
				},
				Renderer3DBack = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["RendererOpenGL.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Vector", },
						["RendererOpenGL.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.ObjectID", },
						["RendererOpenGL.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.BackVector", },
						["RendererOpenGL.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.TexCoord0", },
						["RendererOpenGL.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Z", },
						["RendererOpenGL.Channels.Nest"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Nest", },
						["RendererOpenGL.LightingEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.LightingEnabled", },
						["RendererOpenGL.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Normal", },
						["RendererOpenGL.ShadowsEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.ShadowsEnabled", },
						["RendererOpenGL.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.WorldCoord", },
						["RendererOpenGL.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.MaterialID", },
						["RendererOpenGL.Supersampling"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Supersampling", },
						GlobalOut = Input { Value = 144, },
						Width = Input {
							Value = 512,
							Expression = "Renderer3DFront.Height",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront.Height",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DBack" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.Z",
						},
						["RendererSoftware.Channels.Coverage"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage",
						},
						["RendererSoftware.Channels.BgColor"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.BgColor",
						},
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0",
						},
						["RendererSoftware.Channels.ObjectID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID",
						},
						["RendererSoftware.Channels.MaterialID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID",
						},
						["RendererSoftware.Channels.WorldCoord"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord",
						},
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -472.7, 703.6 } },
				},
				Renderer3DTop = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["RendererOpenGL.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Vector", },
						["RendererOpenGL.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.ObjectID", },
						["RendererOpenGL.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.BackVector", },
						["RendererOpenGL.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.TexCoord0", },
						["RendererOpenGL.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Z", },
						["RendererOpenGL.Channels.Nest"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Nest", },
						["RendererOpenGL.LightingEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.LightingEnabled", },
						["RendererOpenGL.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Normal", },
						["RendererOpenGL.ShadowsEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.ShadowsEnabled", },
						["RendererOpenGL.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.WorldCoord", },
						["RendererOpenGL.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.MaterialID", },
						["RendererOpenGL.Supersampling"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Supersampling", },
						GlobalOut = Input { Value = 144, },
						Width = Input {
							Value = 512,
							Expression = "Renderer3DFront.Height",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront.Height",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DTop" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.Z",
						},
						["RendererSoftware.Channels.Coverage"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage",
						},
						["RendererSoftware.Channels.BgColor"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.BgColor",
						},
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0",
						},
						["RendererSoftware.Channels.ObjectID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID",
						},
						["RendererSoftware.Channels.MaterialID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID",
						},
						["RendererSoftware.Channels.WorldCoord"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord",
						},
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -472.7, 769.6 } },
				},
				Renderer3DRight = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["RendererOpenGL.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Vector", },
						["RendererOpenGL.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.ObjectID", },
						["RendererOpenGL.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.BackVector", },
						["RendererOpenGL.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.TexCoord0", },
						["RendererOpenGL.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Z", },
						["RendererOpenGL.Channels.Nest"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Nest", },
						["RendererOpenGL.LightingEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.LightingEnabled", },
						["RendererOpenGL.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Normal", },
						["RendererOpenGL.ShadowsEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.ShadowsEnabled", },
						["RendererOpenGL.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.WorldCoord", },
						["RendererOpenGL.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.MaterialID", },
						["RendererOpenGL.Supersampling"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Supersampling", },
						GlobalOut = Input { Value = 144, },
						Width = Input {
							Value = 512,
							Expression = "Renderer3DFront.Height",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront.Height",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DRight" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.Z",
						},
						["RendererSoftware.Channels.Coverage"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage",
						},
						["RendererSoftware.Channels.BgColor"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.BgColor",
						},
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0",
						},
						["RendererSoftware.Channels.ObjectID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID",
						},
						["RendererSoftware.Channels.MaterialID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID",
						},
						["RendererSoftware.Channels.WorldCoord"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord",
						},
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -472.7, 670.6 } },
				},
				Renderer3DBottom = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["RendererOpenGL.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Vector", },
						["RendererOpenGL.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.ObjectID", },
						["RendererOpenGL.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.BackVector", },
						["RendererOpenGL.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.TexCoord0", },
						["RendererOpenGL.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Z", },
						["RendererOpenGL.Channels.Nest"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Nest", },
						["RendererOpenGL.LightingEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.LightingEnabled", },
						["RendererOpenGL.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Normal", },
						["RendererOpenGL.ShadowsEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.ShadowsEnabled", },
						["RendererOpenGL.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.WorldCoord", },
						["RendererOpenGL.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.MaterialID", },
						["RendererOpenGL.Supersampling"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Supersampling", },
						GlobalOut = Input { Value = 144, },
						Width = Input {
							Value = 512,
							Expression = "Renderer3DFront.Height",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront.Height",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DBottom" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.Z",
						},
						["RendererSoftware.Channels.Coverage"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage",
						},
						["RendererSoftware.Channels.BgColor"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.BgColor",
						},
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0",
						},
						["RendererSoftware.Channels.ObjectID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID",
						},
						["RendererSoftware.Channels.MaterialID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID",
						},
						["RendererSoftware.Channels.WorldCoord"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord",
						},
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -471.988, 802.6 } },
				},
				Renderer3DLeft = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["RendererOpenGL.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Vector", },
						["RendererOpenGL.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.ObjectID", },
						["RendererOpenGL.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.BackVector", },
						["RendererOpenGL.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.TexCoord0", },
						["RendererOpenGL.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Z", },
						["RendererOpenGL.Channels.Nest"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Nest", },
						["RendererOpenGL.LightingEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.LightingEnabled", },
						["RendererOpenGL.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.Normal", },
						["RendererOpenGL.ShadowsEnabled"] = Input { Expression = "Renderer3DFront.RendererOpenGL.ShadowsEnabled", },
						["RendererOpenGL.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.WorldCoord", },
						["RendererOpenGL.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Channels.MaterialID", },
						["RendererOpenGL.Supersampling"] = Input { Expression = "Renderer3DFront.RendererOpenGL.Supersampling", },
						GlobalOut = Input { Value = 144, },
						Width = Input {
							Value = 512,
							Expression = "Renderer3DFront.Height",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront.Height",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DLeft" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.Z",
						},
						["RendererSoftware.Channels.Coverage"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage",
						},
						["RendererSoftware.Channels.BgColor"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.BgColor",
						},
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0",
						},
						["RendererSoftware.Channels.ObjectID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID",
						},
						["RendererSoftware.Channels.MaterialID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID",
						},
						["RendererSoftware.Channels.WorldCoord"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord",
						},
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -472.7, 736.6 } },
				},
				Renderer3DFront = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 144, },
						Width = Input {
							Value = 512,
							Expression = "Height",
						},
						Height = Input { Value = 512, },
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						["Gamut.PreDividePostMultiply"] = Input { Value = 1, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DFront" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.Z"] = Input { Value = 1, },
						["RendererSoftware.Channels.Coverage"] = Input { Value = 1, },
						["RendererSoftware.Channels.BgColor"] = Input { Value = 1, },
						["RendererSoftware.Channels.TexCoord0"] = Input { Value = 1, },
						["RendererSoftware.Channels.ObjectID"] = Input { Value = 1, },
						["RendererSoftware.Channels.MaterialID"] = Input { Value = 1, },
						["RendererSoftware.Channels.WorldCoord"] = Input { Value = 1, },
						["RendererSoftware.LightingEnabled"] = Input { Value = 1, },
						["RendererSoftware.ShadowsEnabled"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -472.7, 637.6 } },
				},
				PipeRouterBottom = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DBottom",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -362.7, 802.6 } },
				},
				PipeRouterLeft = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DLeft",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -362.7, 736.6 } },
				},
				PipeRouterRight = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DRight",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -362.7, 670.6 } },
				},
				PipeRouterTop = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DTop",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -362.7, 769.6 } },
				},
				PipeRouterBack = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DBack",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -362.7, 703.6 } },
				},
				PipeRouterFront = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DFront",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -362.7, 637.6 } },
				},
				ChangeDepthLeft5 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterLeft",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 109.6 } },
				},
				ChangeDepthBack5 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBack",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 76.6 } },
				},
				ChangeDepthTop4 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterTop",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 406.6 } },
				},
				ChangeDepthRight = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterRight",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 1066.6 } },
				},
				ChangeDepthBack3 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBack",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 604.6 } },
				},
				ChangeDepthTop2 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterTop",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 934.6 } },
				},
				ChangeDepthTop = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterTop",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 1165.6 } },
				},
				ChangeDepthBottom2 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBottom",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 967.6 } },
				},
				ChangeDepthBottom3 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBottom",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 703.6 } },
				},
				ChangeDepthFront2 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterFront",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 802.6 } },
				},
				ChangeDepthLeft4 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterLeft",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 373.6 } },
				},
				ChangeDepthFront = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterFront",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 1033.6 } },
				},
				ChangeDepthLeft3 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterLeft",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 637.6 } },
				},
				ChangeDepthTop5 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterTop",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 142.6 } },
				},
				ChangeDepthFront4 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterFront",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 274.6 } },
				},
				ChangeDepthRight4 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterRight",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 307.6 } },
				},
				ChangeDepthFront5 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterFront",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 10.6 } },
				},
				ChangeDepthBack2 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBack",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 868.6 } },
				},
				ChangeDepthBack = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBack",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 1099.6 } },
				},
				ChangeDepthFront3 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterFront",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 538.6 } },
				},
				ChangeDepthBottom = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBottom",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 1198.6 } },
				},
				ChangeDepthTop3 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterTop",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 670.6 } },
				},
				ChangeDepthRight2 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterRight",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 835.6 } },
				},
				ChangeDepthRight3 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterRight",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 571.6 } },
				},
				ChangeDepthLeft2 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterLeft",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 901.6 } },
				},
				ChangeDepthLeft = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterLeft",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 1132.6 } },
				},
				ChangeDepthBottom4 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBottom",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 439.6 } },
				},
				ChangeDepthBack4 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBack",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 340.6 } },
				},
				ChangeDepthBottom5 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBottom",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 175.6 } },
				},
				ChangeDepthRight5 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterRight",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -87.7, 43.6 } },
				},
				ChannelBooleansFront5 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 27, },
						ToGreen = Input { Value = 28, },
						ToBlue = Input { Value = 29, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthFront5",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 10.6 } },
				},
				ChannelBooleansFront4 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 35, },
						ToGreen = Input { Value = 36, },
						ToBlue = Input { Value = 37, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthFront4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 274.6 } },
				},
				ChannelBooleansLeft5 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 27, },
						ToGreen = Input { Value = 28, },
						ToBlue = Input { Value = 29, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthLeft5",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 109.6 } },
				},
				ChannelBooleansRight = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 18, },
						ToGreen = Input { Value = 19, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthRight",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 1066.6 } },
				},
				ChannelBooleansFront = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 18, },
						ToGreen = Input { Value = 19, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthFront",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 1033.6 } },
				},
				ChannelBooleansBack5 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 27, },
						ToGreen = Input { Value = 28, },
						ToBlue = Input { Value = 29, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBack5",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 76.6 } },
				},
				ChannelBooleansRight2 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 21, },
						ToGreen = Input { Value = 20, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthRight2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 835.6 } },
				},
				ChannelBooleansBottom5 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 27, },
						ToGreen = Input { Value = 28, },
						ToBlue = Input { Value = 29, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBottom5",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 175.6 } },
				},
				ChannelBooleansRight5 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 27, },
						ToGreen = Input { Value = 28, },
						ToBlue = Input { Value = 29, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthRight5",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 43.6 } },
				},
				ChannelBooleansLeft4 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 35, },
						ToGreen = Input { Value = 36, },
						ToBlue = Input { Value = 37, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthLeft4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 373.6 } },
				},
				ChannelBooleansTop = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 18, },
						ToGreen = Input { Value = 19, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthTop",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 1165.6 } },
				},
				ChannelBooleansLeft3 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 22, },
						ToGreen = Input { Value = 23, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthLeft3",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 637.6 } },
				},
				ChannelBooleansTop4 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 35, },
						ToGreen = Input { Value = 36, },
						ToBlue = Input { Value = 37, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthTop4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 406.6 } },
				},
				ChannelBooleansLeft = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 18, },
						ToGreen = Input { Value = 19, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthLeft",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 1132.6 } },
				},
				ChannelBooleansRight4 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 35, },
						ToGreen = Input { Value = 36, },
						ToBlue = Input { Value = 37, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthRight4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 307.6 } },
				},
				ChannelBooleansBottom = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 18, },
						ToGreen = Input { Value = 19, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBottom",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 1198.6 } },
				},
				ChannelBooleansBottom3 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 22, },
						ToGreen = Input { Value = 23, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBottom3",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 703.6 } },
				},
				ChannelBooleansFront3 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 22, },
						ToGreen = Input { Value = 23, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthFront3",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 538.6 } },
				},
				ChannelBooleansBack3 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 22, },
						ToGreen = Input { Value = 23, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBack3",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 604.6 } },
				},
				ChannelBooleansTop3 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 22, },
						ToGreen = Input { Value = 23, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthTop3",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 670.6 } },
				},
				ChannelBooleansBack2 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 21, },
						ToGreen = Input { Value = 20, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBack2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 868.6 } },
				},
				ChannelBooleansBottom2 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 21, },
						ToGreen = Input { Value = 20, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBottom2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 967.6 } },
				},
				ChannelBooleansRight3 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 22, },
						ToGreen = Input { Value = 23, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthRight3",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 571.6 } },
				},
				ChannelBooleansTop5 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 27, },
						ToGreen = Input { Value = 28, },
						ToBlue = Input { Value = 29, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthTop5",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 142.6 } },
				},
				ChannelBooleansBack4 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 35, },
						ToGreen = Input { Value = 36, },
						ToBlue = Input { Value = 37, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBack4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 340.6 } },
				},
				ChannelBooleansBottom4 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 35, },
						ToGreen = Input { Value = 36, },
						ToBlue = Input { Value = 37, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBottom4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 439.6 } },
				},
				ChannelBooleansFront2 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 21, },
						ToGreen = Input { Value = 20, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthFront2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 802.6 } },
				},
				ChannelBooleansTop2 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 21, },
						ToGreen = Input { Value = 20, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthTop2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 934.6 } },
				},
				ChannelBooleansLeft2 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 21, },
						ToGreen = Input { Value = 20, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthLeft2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 901.6 } },
				},
				ChannelBooleansBack = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 18, },
						ToGreen = Input { Value = 19, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBack",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 22.3, 1099.6 } },
				},
				CubeMapColor = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Orientation = Input { Value = 0, },
						Rotation = Input { Value = 1, },
						["Rotate.X"] = Input { Value = 180, },
						["Rotate.Z"] = Input { Value = 180, },
						["FilterMode.Nest"] = Input { Value = 1, },
						["FilterMode.SW.LowQ"] = Input { Value = FuID { "Bilinear" }, },
						Left = Input {
							SourceOp = "PipeRouterLeft",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "PipeRouterRight",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "PipeRouterTop",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "PipeRouterBottom",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "PipeRouterFront",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "PipeRouterBack",
							Source = "Output",
						},
						MaterialID = Input { Value = 3, },
					},
					ViewInfo = OperatorInfo { Pos = { 187.3, 1429.6 } },
				},
				CubeMapDepth = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CubeMapColor",
					Inputs = {
						Rotation = Input { Value = 1, },
						["FilterMode.Nest"] = Input { Value = 1, },
						CrossImage = Input { },
						Left = Input {
							SourceOp = "ChannelBooleansLeft",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "ChannelBooleansRight",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "ChannelBooleansTop",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "ChannelBooleansBottom",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "ChannelBooleansFront",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "ChannelBooleansBack",
							Source = "Output",
						},
						MaterialIDNest = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 187.3, 1198.6 } },
				},
				CubeMapWorld = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CubeMapColor",
					Inputs = {
						Rotation = Input { Value = 1, },
						["FilterMode.Nest"] = Input { Value = 1, },
						CrossImage = Input { },
						Left = Input {
							SourceOp = "ChannelBooleansLeft4",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "ChannelBooleansRight4",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "ChannelBooleansTop4",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "ChannelBooleansBottom4",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "ChannelBooleansFront4",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "ChannelBooleansBack4",
							Source = "Output",
						},
						MaterialIDNest = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 187.3, 439.6 } },
				},
				CubeMapTex = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CubeMapColor",
					Inputs = {
						Rotation = Input { Value = 1, },
						["FilterMode.Nest"] = Input { Value = 1, },
						CrossImage = Input { },
						Left = Input {
							SourceOp = "ChannelBooleansLeft3",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "ChannelBooleansRight3",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "ChannelBooleansTop3",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "ChannelBooleansBottom3",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "ChannelBooleansFront3",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "ChannelBooleansBack3",
							Source = "Output",
						},
						MaterialIDNest = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 187.3, 703.6 } },
				},
				CubeMapID = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CubeMapColor",
					Inputs = {
						Rotation = Input { Value = 1, },
						["FilterMode.Nest"] = Input { Value = 1, },
						CrossImage = Input { },
						Left = Input {
							SourceOp = "ChannelBooleansLeft2",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "ChannelBooleansRight2",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "ChannelBooleansTop2",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "ChannelBooleansBottom2",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "ChannelBooleansFront2",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "ChannelBooleansBack2",
							Source = "Output",
						},
						MaterialIDNest = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 187.3, 967.6 } },
				},
				CubeMapBGColor = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CubeMapColor",
					Inputs = {
						Rotation = Input { Value = 1, },
						["FilterMode.Nest"] = Input { Value = 1, },
						CrossImage = Input { },
						Left = Input {
							SourceOp = "ChannelBooleansLeft5",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "ChannelBooleansRight5",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "ChannelBooleansTop5",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "ChannelBooleansBottom5",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "ChannelBooleansFront5",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "ChannelBooleansBack5",
							Source = "Output",
						},
						MaterialIDNest = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 187.3, 175.6 } },
				},
				Shape3DWorld = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Shape3DColor",
					Inputs = {
						SceneInput = Input { },
						["Transform3DOp.Translation"] = Input { },
						["Transform3DOp.Rotation"] = Input { },
						["Transform3DOp.PivotNest"] = Input { },
						["Transform3DOp.ScaleNest"] = Input { },
						["Transform3DOp.TargetNest"] = Input { },
						["Transform3DOp.Import"] = Input { },
						MaterialInput = Input {
							SourceOp = "CubeMapWorld",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.Diffuse.Nest"] = Input { },
						["MtlStdInputs.Specular.Nest"] = Input { },
						["MtlStdInputs.Transmittance.Nest"] = Input { },
						["MtlStdInputs.MaterialIDNest"] = Input { Value = 1, },
						StartEndRenderScripts = Input { },
						["SurfacePlaneInputs.Nest"] = Input { },
						["SurfacePlaneInputs.SizeLock"] = Input { },
						["SurfacePlaneInputs.Width"] = Input { },
						["SurfacePlaneInputs.Height"] = Input { },
						["SurfacePlaneInputs.SubdivisionWidth"] = Input { },
						["SurfacePlaneInputs.SubdivisionHeight"] = Input { },
						["SurfacePlaneInputs.Wireframe"] = Input { },
						["SurfacePlaneInputs.IsWireframeAntialiased"] = Input { },
						["SurfacePlaneInputs.Visibility.Nest"] = Input { },
						["SurfacePlaneInputs.Visibility.IsVisible"] = Input { },
						["SurfacePlaneInputs.Visibility.IsUnseenByCameras"] = Input { },
						["SurfacePlaneInputs.Visibility.CullFrontFace"] = Input { },
						["SurfacePlaneInputs.Visibility.CullBackFace"] = Input { },
						["SurfacePlaneInputs.Visibility.IgnoreTransparentPixelsInAuxChannels"] = Input { },
						["SurfacePlaneInputs.Lighting.Nest"] = Input { },
						["SurfacePlaneInputs.Lighting.IsAffectedByLights"] = Input { },
						["SurfacePlaneInputs.Lighting.IsShadowCaster"] = Input { },
						["SurfacePlaneInputs.Lighting.IsShadowReceiver"] = Input { },
						["SurfacePlaneInputs.Matte.Nest"] = Input { },
						["SurfacePlaneInputs.Matte.IsMatte"] = Input { },
						["SurfacePlaneInputs.Matte.OpaqueAlpha"] = Input { },
						["SurfacePlaneInputs.Matte.InfiniteZ"] = Input { },
						["SurfacePlaneInputs.BlendMode.Nest"] = Input { },
						["SurfacePlaneInputs.BlendMode.GL.Nest"] = Input { },
						["SurfacePlaneInputs.BlendMode.GL.BlendMode"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.Nest"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.BlendMode"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.Operator"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.SubtractiveAdditive"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.Gain"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.BurnIn"] = Input { },
						["SurfacePlaneInputs.Controls.Nest"] = Input { },
						["SurfacePlaneInputs.Controls.Normals.Scale"] = Input { },
						["SurfacePlaneInputs.Controls.Normals.Show"] = Input { },
						["SurfacePlaneInputs.Controls.Tangents.Show"] = Input { },
						["SurfacePlaneInputs.ObjectID.Nest"] = Input { },
						["SurfaceSphereInputs.Visibility.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.Lighting.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.Matte.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.BlendMode.Nest"] = Input { },
						["SurfaceSphereInputs.Controls.Nest"] = Input { },
						["SurfaceSphereInputs.ObjectID.Nest"] = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 297.3, 439.6 } },
				},
				Shape3DColor = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 2, },
						["SurfaceTorusInputs.ObjectID.ObjectID"] = Input { Value = 6, },
						["SurfaceIcoInputs.ObjectID.ObjectID"] = Input { Value = 7, },
						["SurfaceCubeInputs.ObjectID.ObjectID"] = Input { Value = 4, },
						["SurfaceCylinderInputs.ObjectID.ObjectID"] = Input { Value = 5, },
						Shape = Input { Value = FuID { "SurfaceSphereInputs" }, },
						MaterialInput = Input {
							SourceOp = "CubeMapColor",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.Diffuse.Color.Red"] = Input { Value = 0.5968992248062, },
						["MtlStdInputs.Diffuse.Color.Green"] = Input { Value = 0.3643410852713, },
						["MtlStdInputs.Diffuse.Color.Blue"] = Input { Value = 0.6589147286822, },
						["MtlStdInputs.ReceivesLighting"] = Input { Value = 0, },
						["MtlStdInputs.ReceivesShadows"] = Input { Value = 0, },
						["MtlStdInputs.MaterialIDNest"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 2, },
						["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 72, },
						["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 36, },
						["SurfaceSphereInputs.Visibility.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.Visibility.CullFrontFace"] = Input { Value = 1, },
						["SurfaceSphereInputs.Lighting.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.Lighting.IsAffectedByLights"] = Input { Value = 0, },
						["SurfaceSphereInputs.Matte.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.Controls.Normals.Scale"] = Input { Value = 6.93, },
						["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 3, }
					},
					ViewInfo = OperatorInfo { Pos = { 297.3, 1429.6 } },
				},
				Shape3DDepth = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Shape3DColor",
					Inputs = {
						SceneInput = Input { },
						["Transform3DOp.Translation"] = Input { },
						["Transform3DOp.Rotation"] = Input { },
						["Transform3DOp.PivotNest"] = Input { },
						["Transform3DOp.ScaleNest"] = Input { },
						["Transform3DOp.TargetNest"] = Input { },
						["Transform3DOp.Import"] = Input { },
						MaterialInput = Input {
							SourceOp = "CubeMapDepth",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.Diffuse.Nest"] = Input { },
						["MtlStdInputs.Specular.Nest"] = Input { },
						["MtlStdInputs.Transmittance.Nest"] = Input { },
						["MtlStdInputs.MaterialIDNest"] = Input { Value = 1, },
						StartEndRenderScripts = Input { },
						["SurfacePlaneInputs.Nest"] = Input { },
						["SurfacePlaneInputs.SizeLock"] = Input { },
						["SurfacePlaneInputs.Width"] = Input { },
						["SurfacePlaneInputs.Height"] = Input { },
						["SurfacePlaneInputs.SubdivisionWidth"] = Input { },
						["SurfacePlaneInputs.SubdivisionHeight"] = Input { },
						["SurfacePlaneInputs.Wireframe"] = Input { },
						["SurfacePlaneInputs.IsWireframeAntialiased"] = Input { },
						["SurfacePlaneInputs.Visibility.Nest"] = Input { },
						["SurfacePlaneInputs.Visibility.IsVisible"] = Input { },
						["SurfacePlaneInputs.Visibility.IsUnseenByCameras"] = Input { },
						["SurfacePlaneInputs.Visibility.CullFrontFace"] = Input { },
						["SurfacePlaneInputs.Visibility.CullBackFace"] = Input { },
						["SurfacePlaneInputs.Visibility.IgnoreTransparentPixelsInAuxChannels"] = Input { },
						["SurfacePlaneInputs.Lighting.Nest"] = Input { },
						["SurfacePlaneInputs.Lighting.IsAffectedByLights"] = Input { },
						["SurfacePlaneInputs.Lighting.IsShadowCaster"] = Input { },
						["SurfacePlaneInputs.Lighting.IsShadowReceiver"] = Input { },
						["SurfacePlaneInputs.Matte.Nest"] = Input { },
						["SurfacePlaneInputs.Matte.IsMatte"] = Input { },
						["SurfacePlaneInputs.Matte.OpaqueAlpha"] = Input { },
						["SurfacePlaneInputs.Matte.InfiniteZ"] = Input { },
						["SurfacePlaneInputs.BlendMode.Nest"] = Input { },
						["SurfacePlaneInputs.BlendMode.GL.Nest"] = Input { },
						["SurfacePlaneInputs.BlendMode.GL.BlendMode"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.Nest"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.BlendMode"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.Operator"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.SubtractiveAdditive"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.Gain"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.BurnIn"] = Input { },
						["SurfacePlaneInputs.Controls.Nest"] = Input { },
						["SurfacePlaneInputs.Controls.Normals.Scale"] = Input { },
						["SurfacePlaneInputs.Controls.Normals.Show"] = Input { },
						["SurfacePlaneInputs.Controls.Tangents.Show"] = Input { },
						["SurfacePlaneInputs.ObjectID.Nest"] = Input { },
						["SurfaceSphereInputs.Visibility.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.Lighting.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.Matte.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.BlendMode.Nest"] = Input { },
						["SurfaceSphereInputs.Controls.Nest"] = Input { },
						["SurfaceSphereInputs.ObjectID.Nest"] = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 297.3, 1198.6 } },
				},
				Shape3DTex = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Shape3DColor",
					Inputs = {
						SceneInput = Input { },
						["Transform3DOp.Translation"] = Input { },
						["Transform3DOp.Rotation"] = Input { },
						["Transform3DOp.PivotNest"] = Input { },
						["Transform3DOp.ScaleNest"] = Input { },
						["Transform3DOp.TargetNest"] = Input { },
						["Transform3DOp.Import"] = Input { },
						MaterialInput = Input {
							SourceOp = "CubeMapTex",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.Diffuse.Nest"] = Input { },
						["MtlStdInputs.Specular.Nest"] = Input { },
						["MtlStdInputs.Transmittance.Nest"] = Input { },
						["MtlStdInputs.MaterialIDNest"] = Input { Value = 1, },
						StartEndRenderScripts = Input { },
						["SurfacePlaneInputs.Nest"] = Input { },
						["SurfacePlaneInputs.SizeLock"] = Input { },
						["SurfacePlaneInputs.Width"] = Input { },
						["SurfacePlaneInputs.Height"] = Input { },
						["SurfacePlaneInputs.SubdivisionWidth"] = Input { },
						["SurfacePlaneInputs.SubdivisionHeight"] = Input { },
						["SurfacePlaneInputs.Wireframe"] = Input { },
						["SurfacePlaneInputs.IsWireframeAntialiased"] = Input { },
						["SurfacePlaneInputs.Visibility.Nest"] = Input { },
						["SurfacePlaneInputs.Visibility.IsVisible"] = Input { },
						["SurfacePlaneInputs.Visibility.IsUnseenByCameras"] = Input { },
						["SurfacePlaneInputs.Visibility.CullFrontFace"] = Input { },
						["SurfacePlaneInputs.Visibility.CullBackFace"] = Input { },
						["SurfacePlaneInputs.Visibility.IgnoreTransparentPixelsInAuxChannels"] = Input { },
						["SurfacePlaneInputs.Lighting.Nest"] = Input { },
						["SurfacePlaneInputs.Lighting.IsAffectedByLights"] = Input { },
						["SurfacePlaneInputs.Lighting.IsShadowCaster"] = Input { },
						["SurfacePlaneInputs.Lighting.IsShadowReceiver"] = Input { },
						["SurfacePlaneInputs.Matte.Nest"] = Input { },
						["SurfacePlaneInputs.Matte.IsMatte"] = Input { },
						["SurfacePlaneInputs.Matte.OpaqueAlpha"] = Input { },
						["SurfacePlaneInputs.Matte.InfiniteZ"] = Input { },
						["SurfacePlaneInputs.BlendMode.Nest"] = Input { },
						["SurfacePlaneInputs.BlendMode.GL.Nest"] = Input { },
						["SurfacePlaneInputs.BlendMode.GL.BlendMode"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.Nest"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.BlendMode"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.Operator"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.SubtractiveAdditive"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.Gain"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.BurnIn"] = Input { },
						["SurfacePlaneInputs.Controls.Nest"] = Input { },
						["SurfacePlaneInputs.Controls.Normals.Scale"] = Input { },
						["SurfacePlaneInputs.Controls.Normals.Show"] = Input { },
						["SurfacePlaneInputs.Controls.Tangents.Show"] = Input { },
						["SurfacePlaneInputs.ObjectID.Nest"] = Input { },
						["SurfaceSphereInputs.Visibility.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.Lighting.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.Matte.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.BlendMode.Nest"] = Input { },
						["SurfaceSphereInputs.Controls.Nest"] = Input { },
						["SurfaceSphereInputs.ObjectID.Nest"] = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 297.3, 703.6 } },
				},
				Shape3DBGColor = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Shape3DColor",
					Inputs = {
						SceneInput = Input { },
						["Transform3DOp.Translation"] = Input { },
						["Transform3DOp.Rotation"] = Input { },
						["Transform3DOp.PivotNest"] = Input { },
						["Transform3DOp.ScaleNest"] = Input { },
						["Transform3DOp.TargetNest"] = Input { },
						["Transform3DOp.Import"] = Input { },
						MaterialInput = Input {
							SourceOp = "CubeMapBGColor",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.Diffuse.Nest"] = Input { },
						["MtlStdInputs.Specular.Nest"] = Input { },
						["MtlStdInputs.Transmittance.Nest"] = Input { },
						["MtlStdInputs.MaterialIDNest"] = Input { Value = 1, },
						StartEndRenderScripts = Input { },
						["SurfacePlaneInputs.Nest"] = Input { },
						["SurfacePlaneInputs.SizeLock"] = Input { },
						["SurfacePlaneInputs.Width"] = Input { },
						["SurfacePlaneInputs.Height"] = Input { },
						["SurfacePlaneInputs.SubdivisionWidth"] = Input { },
						["SurfacePlaneInputs.SubdivisionHeight"] = Input { },
						["SurfacePlaneInputs.Wireframe"] = Input { },
						["SurfacePlaneInputs.IsWireframeAntialiased"] = Input { },
						["SurfacePlaneInputs.Visibility.Nest"] = Input { },
						["SurfacePlaneInputs.Visibility.IsVisible"] = Input { },
						["SurfacePlaneInputs.Visibility.IsUnseenByCameras"] = Input { },
						["SurfacePlaneInputs.Visibility.CullFrontFace"] = Input { },
						["SurfacePlaneInputs.Visibility.CullBackFace"] = Input { },
						["SurfacePlaneInputs.Visibility.IgnoreTransparentPixelsInAuxChannels"] = Input { },
						["SurfacePlaneInputs.Lighting.Nest"] = Input { },
						["SurfacePlaneInputs.Lighting.IsAffectedByLights"] = Input { },
						["SurfacePlaneInputs.Lighting.IsShadowCaster"] = Input { },
						["SurfacePlaneInputs.Lighting.IsShadowReceiver"] = Input { },
						["SurfacePlaneInputs.Matte.Nest"] = Input { },
						["SurfacePlaneInputs.Matte.IsMatte"] = Input { },
						["SurfacePlaneInputs.Matte.OpaqueAlpha"] = Input { },
						["SurfacePlaneInputs.Matte.InfiniteZ"] = Input { },
						["SurfacePlaneInputs.BlendMode.Nest"] = Input { },
						["SurfacePlaneInputs.BlendMode.GL.Nest"] = Input { },
						["SurfacePlaneInputs.BlendMode.GL.BlendMode"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.Nest"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.BlendMode"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.Operator"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.SubtractiveAdditive"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.Gain"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.BurnIn"] = Input { },
						["SurfacePlaneInputs.Controls.Nest"] = Input { },
						["SurfacePlaneInputs.Controls.Normals.Scale"] = Input { },
						["SurfacePlaneInputs.Controls.Normals.Show"] = Input { },
						["SurfacePlaneInputs.Controls.Tangents.Show"] = Input { },
						["SurfacePlaneInputs.ObjectID.Nest"] = Input { },
						["SurfaceSphereInputs.Visibility.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.Lighting.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.Matte.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.BlendMode.Nest"] = Input { },
						["SurfaceSphereInputs.Controls.Nest"] = Input { },
						["SurfaceSphereInputs.ObjectID.Nest"] = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 297.3, 175.6 } },
				},
				Shape3DID = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Shape3DColor",
					Inputs = {
						SceneInput = Input { },
						["Transform3DOp.Translation"] = Input { },
						["Transform3DOp.Rotation"] = Input { },
						["Transform3DOp.PivotNest"] = Input { },
						["Transform3DOp.ScaleNest"] = Input { },
						["Transform3DOp.TargetNest"] = Input { },
						["Transform3DOp.Import"] = Input { },
						MaterialInput = Input {
							SourceOp = "CubeMapID",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.Diffuse.Nest"] = Input { },
						["MtlStdInputs.Specular.Nest"] = Input { },
						["MtlStdInputs.Transmittance.Nest"] = Input { },
						["MtlStdInputs.MaterialIDNest"] = Input { Value = 1, },
						StartEndRenderScripts = Input { },
						["SurfacePlaneInputs.Nest"] = Input { },
						["SurfacePlaneInputs.SizeLock"] = Input { },
						["SurfacePlaneInputs.Width"] = Input { },
						["SurfacePlaneInputs.Height"] = Input { },
						["SurfacePlaneInputs.SubdivisionWidth"] = Input { },
						["SurfacePlaneInputs.SubdivisionHeight"] = Input { },
						["SurfacePlaneInputs.Wireframe"] = Input { },
						["SurfacePlaneInputs.IsWireframeAntialiased"] = Input { },
						["SurfacePlaneInputs.Visibility.Nest"] = Input { },
						["SurfacePlaneInputs.Visibility.IsVisible"] = Input { },
						["SurfacePlaneInputs.Visibility.IsUnseenByCameras"] = Input { },
						["SurfacePlaneInputs.Visibility.CullFrontFace"] = Input { },
						["SurfacePlaneInputs.Visibility.CullBackFace"] = Input { },
						["SurfacePlaneInputs.Visibility.IgnoreTransparentPixelsInAuxChannels"] = Input { },
						["SurfacePlaneInputs.Lighting.Nest"] = Input { },
						["SurfacePlaneInputs.Lighting.IsAffectedByLights"] = Input { },
						["SurfacePlaneInputs.Lighting.IsShadowCaster"] = Input { },
						["SurfacePlaneInputs.Lighting.IsShadowReceiver"] = Input { },
						["SurfacePlaneInputs.Matte.Nest"] = Input { },
						["SurfacePlaneInputs.Matte.IsMatte"] = Input { },
						["SurfacePlaneInputs.Matte.OpaqueAlpha"] = Input { },
						["SurfacePlaneInputs.Matte.InfiniteZ"] = Input { },
						["SurfacePlaneInputs.BlendMode.Nest"] = Input { },
						["SurfacePlaneInputs.BlendMode.GL.Nest"] = Input { },
						["SurfacePlaneInputs.BlendMode.GL.BlendMode"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.Nest"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.BlendMode"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.Operator"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.SubtractiveAdditive"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.Gain"] = Input { },
						["SurfacePlaneInputs.BlendMode.SW.BurnIn"] = Input { },
						["SurfacePlaneInputs.Controls.Nest"] = Input { },
						["SurfacePlaneInputs.Controls.Normals.Scale"] = Input { },
						["SurfacePlaneInputs.Controls.Normals.Show"] = Input { },
						["SurfacePlaneInputs.Controls.Tangents.Show"] = Input { },
						["SurfacePlaneInputs.ObjectID.Nest"] = Input { },
						["SurfaceSphereInputs.Visibility.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.Lighting.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.Matte.Nest"] = Input { Value = 1, },
						["SurfaceSphereInputs.BlendMode.Nest"] = Input { },
						["SurfaceSphereInputs.Controls.Nest"] = Input { },
						["SurfaceSphereInputs.ObjectID.Nest"] = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 297.3, 967.6 } },
				},
				Dome220Renderer3DColor = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 144, },
						Width = Input {
							Value = 589,
							Expression = "Height",
						},
						Height = Input {
							Value = 589,
							Expression = "Renderer3DFront.Width*1.15",
						},
						Overscan = Input { Value = 1.4, },
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "Shape3DColor",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 407.3, 1429.6 } },
				},
				Dome220Renderer3DID = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Dome220Renderer3DColor",
					Inputs = {
						Width = Input {
							Value = 589,
							Expression = "Height"
						},
						Height = Input {
							Value = 589,
							Expression = "Renderer3DFront.Width*1.15"
						},
						["Gamut.ColorSpaceNest"] = Input { },
						["Gamut.GammaSpaceNest"] = Input { },
						SceneInput = Input {
							SourceOp = "Shape3DID",
							Source = "Output",
						},
						Reporting = Input { },
						StartEndRenderScripts = Input { },
						["RendererSoftware.Channels.Nest"] = Input { },
						["RendererSoftware.Lighting"] = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { 407.3, 967.6 } },
				},
				Dome220Renderer3DWorld = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Dome220Renderer3DColor",
					Inputs = {
						Width = Input {
							Value = 589,
							Expression = "Height"
						},
						Height = Input {
							Value = 589,
							Expression = "Renderer3DFront.Width*1.15"
						},
						["Gamut.ColorSpaceNest"] = Input { },
						["Gamut.GammaSpaceNest"] = Input { },
						SceneInput = Input {
							SourceOp = "Shape3DWorld",
							Source = "Output",
						},
						Reporting = Input { },
						StartEndRenderScripts = Input { },
						["RendererSoftware.Channels.Nest"] = Input { },
						["RendererSoftware.Lighting"] = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { 407.3, 439.6 } },
				},
				Dome220Renderer3DTex = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Dome220Renderer3DColor",
					Inputs = {
						Width = Input {
							Value = 589,
							Expression = "Height"
						},
						Height = Input {
							Value = 589,
							Expression = "Renderer3DFront.Width*1.15"
						},
						["Gamut.ColorSpaceNest"] = Input { },
						["Gamut.GammaSpaceNest"] = Input { },
						SceneInput = Input {
							SourceOp = "Shape3DTex",
							Source = "Output",
						},
						Reporting = Input { },
						StartEndRenderScripts = Input { },
						["RendererSoftware.Channels.Nest"] = Input { },
						["RendererSoftware.Lighting"] = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { 407.3, 703.6 } },
				},
				Dome220Renderer3DDepth = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Dome220Renderer3DColor",
					Inputs = {
						Width = Input {
							Value = 589,
							Expression = "Height"
						},
						Height = Input {
							Value = 589,
							Expression = "Renderer3DFront.Width*1.15"
						},
						["Gamut.ColorSpaceNest"] = Input { },
						["Gamut.GammaSpaceNest"] = Input { },
						SceneInput = Input {
							SourceOp = "Shape3DDepth",
							Source = "Output",
						},
						Reporting = Input { },
						StartEndRenderScripts = Input { },
						["RendererSoftware.Channels.Nest"] = Input { },
						["RendererSoftware.Lighting"] = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { 407.3, 1198.6 } },
				},
				Dome220Renderer3DBGColor = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "Dome220Renderer3DColor",
					Inputs = {
						Width = Input {
							Value = 589,
							Expression = "Height"
						},
						Height = Input {
							Value = 589,
							Expression = "Renderer3DFront.Width*1.15"
						},
						["Gamut.ColorSpaceNest"] = Input { },
						["Gamut.GammaSpaceNest"] = Input { },
						SceneInput = Input {
							SourceOp = "Shape3DBGColor",
							Source = "Output",
						},
						Reporting = Input { },
						StartEndRenderScripts = Input { },
						["RendererSoftware.Channels.Nest"] = Input { },
						["RendererSoftware.Lighting"] = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { 407.3, 175.6 } },
				},
				CropColor = Crop {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						XOffset = Input { Value = 38, },
						YOffset = Input { Value = 38, },
						XSize = Input {
							Value = 512,
							Expression = "YSize",
						},
						YSize = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width",
						},
						KeepCentered = Input { Value = 1, },
						Input = Input {
							SourceOp = "Dome220Renderer3DColor",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 517.3, 1429.6 } },
				},
				CropBGColor = Crop {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CropColor",
					Inputs = {
						XSize = Input {
							Value = 512,
							Expression = "YSize"
						},
						YSize = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width"
						},
						ResetSize = Input { },
						ResetOffset = Input { },
						Input = Input {
							SourceOp = "Dome220Renderer3DBGColor",
							Source = "Output",
						},
						AutoCrop = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 517.3, 175.6 } },
				},
				CropWorld = Crop {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CropColor",
					Inputs = {
						XSize = Input {
							Value = 512,
							Expression = "YSize"
						},
						YSize = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width"
						},
						ResetSize = Input { },
						ResetOffset = Input { },
						Input = Input {
							SourceOp = "Dome220Renderer3DWorld",
							Source = "Output",
						},
						AutoCrop = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 517.3, 439.6 } },
				},
				CropDepth = Crop {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CropColor",
					Inputs = {
						XSize = Input {
							Value = 512,
							Expression = "YSize"
						},
						YSize = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width"
						},
						ResetSize = Input { },
						ResetOffset = Input { },
						Input = Input {
							SourceOp = "Dome220Renderer3DDepth",
							Source = "Output",
						},
						AutoCrop = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 517.3, 1198.6 } },
				},
				CropTex = Crop {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CropColor",
					Inputs = {
						XSize = Input {
							Value = 512,
							Expression = "YSize"
						},
						YSize = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width"
						},
						ResetSize = Input { },
						ResetOffset = Input { },
						Input = Input {
							SourceOp = "Dome220Renderer3DTex",
							Source = "Output",
						},
						AutoCrop = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 517.3, 703.6 } },
				},
				CropID = Crop {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CropColor",
					Inputs = {
						XSize = Input {
							Value = 512,
							Expression = "YSize"
						},
						YSize = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width"
						},
						ResetSize = Input { },
						ResetOffset = Input { },
						Input = Input {
							SourceOp = "Dome220Renderer3DID",
							Source = "Output",
						},
						AutoCrop = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 517.3, 967.6 } },
				},
				FisheyeMergeColor = Merge {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ApplyMaskInverted = Input { Value = 1, },
						MultiplyByMask = Input { Value = 1, },
						Background = Input {
							SourceOp = "CropColor",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "FisheyeMaskColor",
							Source = "Mask",
						},
						Operator = Input { Value = FuID { "XOr" }, },
						PerformDepthMerge = Input { Value = 0, },
						EffectMask = Input {
							SourceOp = "FisheyeMaskColor",
							Source = "Mask",
						}
					},
					ViewInfo = OperatorInfo { Pos = { 627.3, 1429.6 } },
				},
				FisheyeMaskColor = EllipseMask {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Invert = Input { Value = 1, },
						OutputSize = Input { Value = FuID { "Custom" }, },
						MaskWidth = Input {
							Value = 512,
							Expression = "MaskHeight",
						},
						MaskHeight = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width",
						},
						PixelAspect = Input { Value = { 1, 1 }, },
						ClippingMode = Input { Value = FuID { "None" }, },
						Width = Input { Value = 1, },
						Height = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { 627.3, 1363.6 } },
				},
				FisheyeMergeWorld = Merge {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "FisheyeMergeColor",
					Inputs = {
						Background = Input {
							SourceOp = "CropWorld",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "FisheyeMaskWorld",
							Source = "Mask",
						},
						ReferenceSize = Input { },
						StartEndRenderScripts = Input { },
						EffectMask = Input {
							SourceOp = "FisheyeMaskWorld",
							Source = "Mask",
						}
					},
					ViewInfo = OperatorInfo { Pos = { 627.3, 439.6 } },
				},
				FisheyeMaskID = EllipseMask {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "FisheyeMaskColor",
					Inputs = {
						MaskWidth = Input {
							Value = 512,
							Expression = "MaskHeight"
						},
						MaskHeight = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width"
						},
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { 627.3, 901.6 } },
				},
				FisheyeMaskBGColor = EllipseMask {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "FisheyeMaskColor",
					Inputs = {
						MaskWidth = Input {
							Value = 512,
							Expression = "MaskHeight"
						},
						MaskHeight = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width"
						},
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { 627.3, 109.6 } },
				},
				FisheyeMergeTex = Merge {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "FisheyeMergeColor",
					Inputs = {
						Background = Input {
							SourceOp = "CropTex",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "FisheyeMaskTex",
							Source = "Mask",
						},
						ReferenceSize = Input { },
						StartEndRenderScripts = Input { },
						EffectMask = Input {
							SourceOp = "FisheyeMaskTex",
							Source = "Mask",
						}
					},
					ViewInfo = OperatorInfo { Pos = { 627.3, 703.6 } },
				},
				FisheyeMaskDepth = EllipseMask {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "FisheyeMaskColor",
					Inputs = {
						MaskWidth = Input {
							Value = 512,
							Expression = "MaskHeight"
						},
						MaskHeight = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width"
						},
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { 627.3, 1132.6 } },
				},
				FisheyeMaskTex = EllipseMask {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "FisheyeMaskColor",
					Inputs = {
						MaskWidth = Input {
							Value = 512,
							Expression = "MaskHeight"
						},
						MaskHeight = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width"
						},
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { 627.3, 637.6 } },
				},
				FisheyeMaskWorld = EllipseMask {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "FisheyeMaskColor",
					Inputs = {
						MaskWidth = Input {
							Value = 512,
							Expression = "MaskHeight"
						},
						MaskHeight = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width"
						},
						StartEndRenderScripts = Input { },
						EffectMask = Input { }
					},
					ViewInfo = OperatorInfo { Pos = { 627.3, 373.6 } },
				},
				FisheyeMergeBGColor = Merge {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "FisheyeMergeColor",
					Inputs = {
						Background = Input {
							SourceOp = "CropBGColor",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "FisheyeMaskBGColor",
							Source = "Mask",
						},
						ReferenceSize = Input { },
						StartEndRenderScripts = Input { },
						EffectMask = Input {
							SourceOp = "FisheyeMaskBGColor",
							Source = "Mask",
						}
					},
					ViewInfo = OperatorInfo { Pos = { 627.3, 175.6 } },
				},
				FisheyeMergeID = Merge {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "FisheyeMergeColor",
					Inputs = {
						Background = Input {
							SourceOp = "CropID",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "FisheyeMaskID",
							Source = "Mask",
						},
						ReferenceSize = Input { },
						StartEndRenderScripts = Input { },
						EffectMask = Input {
							SourceOp = "FisheyeMaskID",
							Source = "Mask",
						}
					},
					ViewInfo = OperatorInfo { Pos = { 627.3, 967.6 } },
				},
				FisheyeMergeDepth = Merge {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "FisheyeMergeColor",
					Inputs = {
						Background = Input {
							SourceOp = "CropDepth",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "FisheyeMaskDepth",
							Source = "Mask",
						},
						ReferenceSize = Input { },
						StartEndRenderScripts = Input { },
						EffectMask = Input {
							SourceOp = "FisheyeMaskDepth",
							Source = "Mask",
						}
					},
					ViewInfo = OperatorInfo { Pos = { 627.3, 1198.6 } },
				},
				PipeRouterBGColor = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "FisheyeMergeBGColor",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 737.3, 175.6 } },
				},
				PipeRouterID = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "FisheyeMergeID",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 737.3, 967.6 } },
				},
				PipeRouterTex = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "FisheyeMergeTex",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 737.3, 703.6 } },
				},
				PipeRouterDepth = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "FisheyeMergeDepth",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 737.3, 1198.6 } },
				},
				PipeRouterWorld = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "FisheyeMergeWorld",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 737.3, 439.6 } },
				},
				ChannelBooleansBGColorMerge = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 5, },
						ToGreen = Input { Value = 6, },
						ToBlue = Input { Value = 7, },
						ToAlpha = Input { Value = 8, },
						EnableExtraChannels = Input { Value = 1, },
						ToBGRed = Input { Value = 0, },
						ToBGGreen = Input { Value = 1, },
						ToBGBlue = Input { Value = 2, },
						Background = Input {
							SourceOp = "ChannelBooleansWorldMerge",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "PipeRouterBGColor",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 847.3, 175.6 } },
				},
				ChannelBooleansDepthMerge = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 5, },
						ToGreen = Input { Value = 6, },
						ToBlue = Input { Value = 7, },
						ToAlpha = Input { Value = 8, },
						EnableExtraChannels = Input { Value = 1, },
						ToZBuffer = Input { Value = 0, },
						ToZCoverage = Input { Value = 1, },
						Background = Input {
							SourceOp = "PipeRouterColor",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "PipeRouterDepth",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 847.3, 1198.6 } },
				},
				ChannelBooleansIDMerge = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 5, },
						ToGreen = Input { Value = 6, },
						ToBlue = Input { Value = 7, },
						ToAlpha = Input { Value = 8, },
						EnableExtraChannels = Input { Value = 1, },
						ToObjectID = Input { Value = 1, },
						ToMaterialID = Input { Value = 0, },
						Background = Input {
							SourceOp = "ChannelBooleansDepthMerge",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "PipeRouterID",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 847.3, 967.6 } },
				},
				ChannelBooleansTexMerge = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 5, },
						ToGreen = Input { Value = 6, },
						ToBlue = Input { Value = 7, },
						ToAlpha = Input { Value = 8, },
						EnableExtraChannels = Input { Value = 1, },
						ToUTexture = Input { Value = 0, },
						ToVTexture = Input { Value = 1, },
						Background = Input {
							SourceOp = "ChannelBooleansIDMerge",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "PipeRouterTex",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 847.3, 703.6 } },
				},
				ChannelBooleansWorldMerge = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 5, },
						ToGreen = Input { Value = 6, },
						ToBlue = Input { Value = 7, },
						ToAlpha = Input { Value = 8, },
						EnableExtraChannels = Input { Value = 1, },
						ToXPosition = Input { Value = 0, },
						ToYPosition = Input { Value = 1, },
						ToZPosition = Input { Value = 2, },
						Background = Input {
							SourceOp = "ChannelBooleansTexMerge",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "PipeRouterWorld",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 847.3, 439.6 } },
				},
				ChangeDepthOutput = ChangeDepth {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 1, },
						Input = Input {
							SourceOp = "ChannelBooleansBGColorMerge",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 857.7, 42.235 } },
				},
				PipeRouterColor = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "FisheyeMergeColor",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 847.3, 1429.6 } },
				}
			},
		},
		SkyMirrorTransform = Transform {
			NameSet = true,
			Inputs = {
				Center = Input { Value = { 0.5, 0.9 }, },
				Pivot = Input { Value = { 0.5, 0 }, },
				UseSizeAndAspect = Input { Value = 0, },
				YSize = Input { Value = 0.6, },
				Edges = Input { Value = 3, },
				Input = Input {
					SourceOp = "SkyGradient",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -55, 16.5 } },
		},
		Note1 = Note {
			Inputs = {
				Comments = Input { Value = "This example shows how to render multi-channel elements from Fusion's 3D animation system to an Equirectangular/LatLong/spherical format output.", }
			},
			ViewInfo = StickyNoteInfo {
				Pos = { 385, 16.5 },
				Flags = {
					Expanded = true
				},
				Size = { 537.731, 71.6937 }
			},
		},
		LightMerge3D = Merge3D {
			NameSet = true,
			Inputs = {
				PassThroughLights = Input { Value = 1, },
				SceneInput1 = Input {
					SourceOp = "FBXMesh3D1",
					Source = "Output",
				},
				SceneInput2 = Input {
					SourceOp = "WarmDirectionalLight",
					Source = "Output",
				},
				SceneInput3 = Input {
					SourceOp = "CoolDirectionalLight",
					Source = "Output",
				},
				SceneInput4 = Input {
					SourceOp = "PointLight1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 55, 148.5 } },
		},
		SkyEnvrionment = Shape3D {
			NameSet = true,
			Inputs = {
				["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 2, },
				Shape = Input { Value = FuID { "SurfaceSphereInputs" }, },
				MaterialInput = Input {
					SourceOp = "SkyWard",
					Source = "MaterialOutput",
				},
				["MtlStdInputs.Diffuse.Color.Red"] = Input { Value = 0.141728395061728, },
				["MtlStdInputs.Diffuse.Color.Green"] = Input { Value = 0.262716049382716, },
				["MtlStdInputs.Diffuse.Color.Blue"] = Input { Value = 0.373333333333333, },
				["MtlStdInputs.MaterialID"] = Input { Value = 4, },
				["SurfaceSphereInputs.Radius"] = Input { Value = 400, },
				["SurfaceSphereInputs.Lighting.Nest"] = Input { Value = 1, },
				["SurfaceSphereInputs.Lighting.IsAffectedByLights"] = Input { Value = 0, },
				["SurfaceSphereInputs.ObjectID.Nest"] = Input { Value = 1, },
				["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 5, }
			},
			ViewInfo = OperatorInfo { Pos = { 220, 16.5 } },
		},
		Transform3D1XRotation = BezierSpline {
			SplineColor = { Red = 255, Green = 128, Blue = 128 },
			NameSet = true,
			KeyFrames = {
				[0] = { 90, RH = { 21.3333333333333, 90 }, Flags = { Linear = true } },
				[64] = { 90, LH = { 42.6666666666667, 90 }, Flags = { Linear = true } }
			}
		},
		SkyWard = MtlWard {
			NameSet = true,
			Inputs = {
				["Diffuse.Color.Material"] = Input {
					SourceOp = "SkyMirrorTransform",
					Source = "Output",
				},
				["Specular.Nest"] = Input { Value = 1, },
				["Specular.Intensity"] = Input { Value = 0, },
				["Transmittance.Nest"] = Input { Value = 1, },
				ReceivesLighting = Input { Value = 0, },
				ReceivesShadows = Input { Value = 0, },
				MaterialIDNest = Input { Value = 1, },
				MaterialID = Input { Value = 7, },
			},
			ViewInfo = OperatorInfo { Pos = { 55, 16.5 } },
		},
		PipeRouter2 = PipeRouter {
			Inputs = {
				Input = Input {
					SourceOp = "SkyMerge3D",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 330, 148.5 } },
		},
		SkyGradient = Background {
			NameSet = true,
			Inputs = {
				GlobalOut = Input { Value = 144, },
				Width = Input { Value = 640, },
				Height = Input { Value = 640, },
				Depth = Input { Value = 4, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Type = Input { Value = FuID { "Vertical" }, },
				TopLeftRed = Input { Value = 0.16078431372549, },
				TopLeftGreen = Input { Value = 0.294117647058824, },
				TopLeftBlue = Input { Value = 0.423529411764706, },
				BottomLeftRed = Input { Value = 0.858823529411765, },
				BottomLeftGreen = Input { Value = 0.882352941176471, },
				BottomLeftBlue = Input { Value = 0.898039215686275, },
				Gradient = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { -165, 16.5 } },
		},
		Transform3D1XOffset = BezierSpline {
			SplineColor = { Red = 250, Green = 59, Blue = 49 },
			NameSet = true,
			KeyFrames = {
				[0] = { 0, RH = { 21.3333333333333, 0 }, Flags = { Linear = true } },
				[64] = { 0, LH = { 42.6666666666667, 0 }, Flags = { Linear = true } }
			}
		},
		Saver1 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "Temp:\\KartaVR\\DomemasterRenderer3DAdvanced_snapshot.0000.exr",
						FormatID = "OpenEXRFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				CreateDir = Input { Value = 1, },
				OutputFormat = Input { Value = FuID { "OpenEXRFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "ChangeDepthOutput",
					Source = "Output",
				},
				["OpenEXRFormat.Channels"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 825, 148.5 } },
		},
		ChannelBooleans1 = ChannelBoolean {
			Inputs = {
				ToRed = Input { Value = 18, },
				ToGreen = Input { Value = 18, },
				ToBlue = Input { Value = 18, },
				Background = Input {
					SourceOp = "ChangeDepthOutput",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 825.963, 215.463 } },
		},
		Transform3D1 = Transform3D {
			Inputs = {
				SceneInput = Input {
					SourceOp = "PipeRouter2",
					Source = "Output",
				},
				["Transform3DOp.Translate.X"] = Input {
					SourceOp = "Transform3D1XOffset",
					Source = "Value",
				},
				["Transform3DOp.Translate.Y"] = Input {
					SourceOp = "Transform3D1YOffset",
					Source = "Value",
				},
				["Transform3DOp.Translate.Z"] = Input {
					SourceOp = "Transform3D1ZOffset",
					Source = "Value",
				},
				["Transform3DOp.Rotate.X"] = Input {
					SourceOp = "Transform3D1XRotation",
					Source = "Value",
				},
				["Transform3DOp.Rotate.Y"] = Input {
					SourceOp = "Transform3D1YRotation",
					Source = "Value",
				},
				["Transform3DOp.InvertTransform"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 440, 148.5 } },
		}
	},
	Views = {
		{
			FrameTypeID = "ChildFrame",
			Mode = 3,
			LayoutPreset = 0,
			Left = 0,
			Top = 27,
			Width = 3440,
			Height = 1238,
			Views = ordered() {
				Main = MultiView {
					Active = "Flow",
					ViewList = ordered() {
						Flow = "FlowView",
						Console = "ConsoleView",
						Timeline = "TimelineView",
						Spline = "SplineEditorView",
						Info = "InfoView",
						Chat = "ChatView"
					},
					Flow = FlowView {
						Flags = {
							AutoHideNavigator = true,
							AutoSnap = true,
							RemoveRouters = true
						},
						NavigatorSize = { 200, 140 },
						Direction = "Horizontal",
						PipeStyle = "Direct",
						Scale = 1.03822,
						Offset = { 286.593, 55.6832 }
					},
					Timeline = TimelineView {
						TreeControlState = {
						},
						DisplayMode = "All Tools",
						ShowCurrentTimeTools = false,
						Filter = "Show All",
						ShowSelectedTools = false,
						ShowAnimatedToolsOnly = false,
						ShowEditBoxes = false,
						KeyFrameView = {
							Position = { Left = 150, Bottom = 343 },
							ScaleX = 0.308771929824561,
							OffsetX = -7.10175438596491,
							OffsetY = 0,
							AutoScaling = "scroll",
							AutoSnapTo = "frame",
							AutoSnapToGuidelines = false,
							GuidelinesGrabEnabled = true,
							GuidelinesSnapTo = "frame"
						},
						Spreadsheet = { LeftPos = 150, Visible = false }
					},
					Spline = SplineEditorView {
						LeftPos = 256,
						ScaleX = 0.2,
						ScaleY = 0.00338983050847458,
						OffsetX = -3.8,
						OffsetY = 0,
						AutoScaling = "scroll",
						AutoSnapTo = "frame",
						AutoSnapToGuidelines = false,
						GuidelinesSnapTo = "frame",
						ShowKeyMarkers = false,
						IndependentHandles = false,
						ShowNonSplineModifiers = false,
						GuidelinesGrabEnabled = true,
						ShowOneToolOnly = false,
						ShowSelectedTools = false,
						ShowAllInputs = false,
						Filter = "Show All"
					},
				},
				Controls = MultiView {
					Active = "Tools",
					ViewList = ordered() {
						Tools = "ControlView",
						Modifiers = "ModifierView"
					},
				},
				Left = "PreviewContainer",
				Right = "PreviewContainer",
				Transport = "TransportView",
				Time = "TimeView"
			},
			Layout = {
				Columns = 2,
				RatioX = 1,
				RatioY = 1,
				{
					Rows = 3,
					RatioX = 0.899854439592431,
					RatioY = 0.00970873786407767,
					{
						Columns = 2,
						RatioX = 1,
						RatioY = 0.542276422764228,
						{ ID = "Left", RatioX = 1, RatioY = 125, Pop = true },
						{ ID = "Right", RatioX = -2, Pop = true },
						Pop = true
					},
					{ ID = "Main", RatioY = 0.410569105691057, Pop = true },
					{ ID = "Time", SnapY = 56, Flat = true }
				},
				{
					Rows = 2,
					PixelX = 342,
					{ ID = "Controls", RatioX = 1, RatioY = 1 },
					{ ID = "Transport", FixedY = -2 }
				}
			}
		}
	},
	Prefs = {
		Comp = {
			Views = {
				Right = {
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "Comp.Views.Right.SideB.",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0
						}
					},
				},
				Left = {
					Viewer = {
						Channel = 4294967295,
						One2One = false,
						Normalise = true,
						ScaleMode = 1,
						Smooth = true,
					},
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "Comp.Views.Left.SideB.",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0
						}
					},
				},
				View1 = {
					PrevCtrlInactiveColor = 0,
					PickW = 0,
					PickH = 0,
					PrevCtrlActiveColor = 0,
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "Comp.Views.View1.SideB.",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0
						}
					}
				},
			},
			FrameFormat = {
				GuideRatio = 1.77777777777778,
			},
			LastFile = "",
			Unsorted = {
				GlobalEnd = 144
			},
			Paths = {
			},
			QuickTime = {
			},
		}
	}
}

 