Composition {
	CurrentTime = 0,
	RenderRange = { 0, 0 },
	GlobalRange = { 0, 1 },
	CurrentID = 954,
	PlaybackUpdateMode = 0,
	Version = "Fusion Studio 8.2.1 build 6",
	SavedOutputs = 0,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	Resumable = true,
	OutputClips = {
		"Temp:\\KartaVR\\domemaster_snapshot.0000.png",
		"Temp:\\KartaVR\\domemaster_snapshot.0000.png"
	},
	Tools = {
		Loader1_1_1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "Macros:\\KartaVR\\Images\\latlong_wide_ar.jpg",
					FormatID = "JpegFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 165, 214.5 } },
		},
		Loader1_1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "Macros:\\KartaVR\\Images\\latlong_wide_ar.jpg",
					FormatID = "JpegFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 165, 148.5 } },
		},
		CylindricalRenderer3DAdvanced = GroupOperator {
			CtrlWZoom = false,
			CustomData = {
				HelpPage = "http://www.andrewhazelden.com/projects/kartavr/docs/macros-guide.html#CylindricalRenderer3DAdvanced",
			},
			Inputs = ordered() {
				MainInput1 = InstanceInput {
					SourceOp = "CameraViewInput_1",
					Source = "SceneInput1",
				},
				Input1 = InstanceInput {
					SourceOp = "Renderer3DFront_1",
					Source = "Height",
					MaxScale = 8192,
					Default = 512,
				},
				Input2 = InstanceInput {
					SourceOp = "UVRenderer3DColor",
					Source = "Depth",
					Default = 4,
				},
				Input3 = InstanceInput {
					SourceOp = "Renderer3DFront_1",
					Source = "RendererSoftware.Channels.RGBA",
					Default = 1,
				},
				Input4 = InstanceInput {
					SourceOp = "Renderer3DFront_1",
					Source = "RendererSoftware.Channels.Z",
					Default = 1,
				},
				Input5 = InstanceInput {
					SourceOp = "Renderer3DFront_1",
					Source = "RendererSoftware.Channels.Coverage",
					Default = 1,
				},
				Input6 = InstanceInput {
					SourceOp = "Renderer3DFront_1",
					Source = "RendererSoftware.Channels.BgColor",
					Default = 1,
				},
				Input7 = InstanceInput {
					SourceOp = "Renderer3DFront_1",
					Source = "RendererSoftware.Channels.TexCoord0",
					Default = 1,
				},
				Input8 = InstanceInput {
					SourceOp = "Renderer3DFront_1",
					Source = "RendererSoftware.Channels.ObjectID",
					Default = 1,
				},
				Input9 = InstanceInput {
					SourceOp = "Renderer3DFront_1",
					Source = "RendererSoftware.Channels.MaterialID",
					Default = 1,
				},
				Input10 = InstanceInput {
					SourceOp = "Renderer3DFront_1",
					Source = "RendererSoftware.Channels.WorldCoord",
					Default = 1,
				},
				Input11 = InstanceInput {
					SourceOp = "Renderer3DFront_1",
					Source = "RendererSoftware.LightingEnabled",
					Default = 1,
				},
				Input12 = InstanceInput {
					SourceOp = "Renderer3DFront_1",
					Source = "RendererSoftware.ShadowsEnabled",
					Default = 1,
				},
				Input13 = InstanceInput {
					SourceOp = "Camera3DFront_1",
					Source = "Transform3DOp.Translate.X",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input14 = InstanceInput {
					SourceOp = "Camera3DFront_1",
					Source = "Transform3DOp.Translate.Y",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input15 = InstanceInput {
					SourceOp = "Camera3DFront_1",
					Source = "Transform3DOp.Translate.Z",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input16 = InstanceInput {
					SourceOp = "CubeMapColor",
					Source = "Rotate.RotOrder",
				},
				Input17 = InstanceInput {
					SourceOp = "CubeMapColor",
					Source = "Rotate.X",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				Input18 = InstanceInput {
					SourceOp = "CubeMapColor",
					Source = "Rotate.Y",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				Input19 = InstanceInput {
					SourceOp = "CubeMapColor",
					Source = "Rotate.Z",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				}
			},
			Outputs = {
				MainOutput1 = InstanceOutput {
					SourceOp = "ChannelBooleansBGColorMerge",
					Source = "Output",
				}
			},
			ViewInfo = GroupInfo {
				Pos = { 495, 214.5 },
				Flags = {
					AllowPan = false,
					AutoSnap = true,
					RemoveRouters = true
				},
				Size = { 1685.5, 1484.2, 842.75, 22 },
				Direction = "Horizontal",
				PipeStyle = "Direct",
				Scale = 1,
				Offset = { 0, 0 }
			},
			Tools = ordered() {
				Camera3DFront_1 = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Rotate.X"] = Input { Value = -90, },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -797.5, 373.6 } },
				},
				Camera3DLeft_1 = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront_1.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = -90,
							Expression = "Camera3DFront_1.Transform3DOp.Rotate.Z-90.0",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -797.5, 472.6 } },
				},
				Camera3DTop_1 = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Rotate.X+90", },
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Rotate.Z", },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -797.5, 505.6 } },
				},
				Camera3DBack_1 = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront_1.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = 180,
							Expression = "Camera3DFront_1.Transform3DOp.Rotate.Z+180.0",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -797.5, 439.6 } },
				},
				Camera3DRight_1 = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront_1.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = 90,
							Expression = "Camera3DFront_1.Transform3DOp.Rotate.Z+90",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -797.5, 406.6 } },
				},
				Camera3DBottom_1 = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -180,
							Expression = "Camera3DFront_1.Transform3DOp.Rotate.X-90",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input { Expression = "Camera3DFront_1.Transform3DOp.Rotate.Z", },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -797.5, 538.6 } },
				},
				CameraViewInput_1 = Merge3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						PassThroughLights = Input { Value = 1, },
						SceneInput1 = Input {
							SourceOp = "Shape3D_1",
							Source = "Output",
						},
						SceneInput2 = Input {
							SourceOp = "Camera3DFront_1",
							Source = "Output",
						},
						SceneInput3 = Input {
							SourceOp = "Camera3DRight_1",
							Source = "Output",
						},
						SceneInput5 = Input {
							SourceOp = "Camera3DLeft_1",
							Source = "Output",
						},
						SceneInput4 = Input {
							SourceOp = "Camera3DBack_1",
							Source = "Output",
						},
						SceneInput7 = Input {
							SourceOp = "Camera3DBottom_1",
							Source = "Output",
						},
						SceneInput6 = Input {
							SourceOp = "Camera3DTop_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -632.5, 637.6 } },
				},
				Renderer3DFront_1 = Renderer3D {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 512,
							Expression = "Height",
						},
						Height = Input { Value = 512, },
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_1",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DFront_1" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.Z"] = Input { Value = 1, },
						["RendererSoftware.Channels.Coverage"] = Input { Value = 1, },
						["RendererSoftware.Channels.BgColor"] = Input { Value = 1, },
						["RendererSoftware.Channels.TexCoord0"] = Input { Value = 1, },
						["RendererSoftware.Channels.ObjectID"] = Input { Value = 1, },
						["RendererSoftware.Channels.MaterialID"] = Input { Value = 1, },
						["RendererSoftware.Channels.WorldCoord"] = Input { Value = 1, },
						["RendererSoftware.LightingEnabled"] = Input { Value = 1, },
						["RendererSoftware.ShadowsEnabled"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -412.5, 637.6 } },
				},
				Renderer3DRight_1 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["RendererOpenGL.Channels.Vector"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Vector", },
						["RendererOpenGL.Channels.ObjectID"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.ObjectID", },
						["RendererOpenGL.Channels.BackVector"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.BackVector", },
						["RendererOpenGL.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.TexCoord0", },
						["RendererOpenGL.Channels.Z"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Z", },
						["RendererOpenGL.Channels.Nest"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Nest", },
						["RendererOpenGL.LightingEnabled"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.LightingEnabled", },
						["RendererOpenGL.Channels.Normal"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Normal", },
						["RendererOpenGL.ShadowsEnabled"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.ShadowsEnabled", },
						["RendererOpenGL.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.WorldCoord", },
						["RendererOpenGL.Channels.MaterialID"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.MaterialID", },
						["RendererOpenGL.Supersampling"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Supersampling", },
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 512,
							Expression = "Renderer3DFront_1.Height",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront_1.Height",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_1",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DRight_1" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.Z",
						},
						["RendererSoftware.Channels.Coverage"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.Coverage",
						},
						["RendererSoftware.Channels.BgColor"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.BgColor",
						},
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.TexCoord0",
						},
						["RendererSoftware.Channels.ObjectID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.ObjectID",
						},
						["RendererSoftware.Channels.MaterialID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.MaterialID",
						},
						["RendererSoftware.Channels.WorldCoord"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.WorldCoord",
						},
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -412.5, 670.6 } },
				},
				Renderer3DBack_1 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["RendererOpenGL.Channels.Vector"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Vector", },
						["RendererOpenGL.Channels.ObjectID"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.ObjectID", },
						["RendererOpenGL.Channels.BackVector"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.BackVector", },
						["RendererOpenGL.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.TexCoord0", },
						["RendererOpenGL.Channels.Z"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Z", },
						["RendererOpenGL.Channels.Nest"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Nest", },
						["RendererOpenGL.LightingEnabled"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.LightingEnabled", },
						["RendererOpenGL.Channels.Normal"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Normal", },
						["RendererOpenGL.ShadowsEnabled"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.ShadowsEnabled", },
						["RendererOpenGL.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.WorldCoord", },
						["RendererOpenGL.Channels.MaterialID"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.MaterialID", },
						["RendererOpenGL.Supersampling"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Supersampling", },
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 512,
							Expression = "Renderer3DFront_1.Height",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront_1.Height",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_1",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DBack_1" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.Z",
						},
						["RendererSoftware.Channels.Coverage"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.Coverage",
						},
						["RendererSoftware.Channels.BgColor"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.BgColor",
						},
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.TexCoord0",
						},
						["RendererSoftware.Channels.ObjectID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.ObjectID",
						},
						["RendererSoftware.Channels.MaterialID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.MaterialID",
						},
						["RendererSoftware.Channels.WorldCoord"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.WorldCoord",
						},
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -412.5, 703.6 } },
				},
				Renderer3DTop_1 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["RendererOpenGL.Channels.Vector"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Vector", },
						["RendererOpenGL.Channels.ObjectID"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.ObjectID", },
						["RendererOpenGL.Channels.BackVector"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.BackVector", },
						["RendererOpenGL.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.TexCoord0", },
						["RendererOpenGL.Channels.Z"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Z", },
						["RendererOpenGL.Channels.Nest"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Nest", },
						["RendererOpenGL.LightingEnabled"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.LightingEnabled", },
						["RendererOpenGL.Channels.Normal"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Normal", },
						["RendererOpenGL.ShadowsEnabled"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.ShadowsEnabled", },
						["RendererOpenGL.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.WorldCoord", },
						["RendererOpenGL.Channels.MaterialID"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.MaterialID", },
						["RendererOpenGL.Supersampling"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Supersampling", },
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 512,
							Expression = "Renderer3DFront_1.Height",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront_1.Height",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_1",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DTop_1" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.Z",
						},
						["RendererSoftware.Channels.Coverage"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.Coverage",
						},
						["RendererSoftware.Channels.BgColor"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.BgColor",
						},
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.TexCoord0",
						},
						["RendererSoftware.Channels.ObjectID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.ObjectID",
						},
						["RendererSoftware.Channels.MaterialID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.MaterialID",
						},
						["RendererSoftware.Channels.WorldCoord"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.WorldCoord",
						},
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -412.5, 769.6 } },
				},
				Renderer3DLeft_1 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["RendererOpenGL.Channels.Vector"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Vector", },
						["RendererOpenGL.Channels.ObjectID"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.ObjectID", },
						["RendererOpenGL.Channels.BackVector"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.BackVector", },
						["RendererOpenGL.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.TexCoord0", },
						["RendererOpenGL.Channels.Z"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Z", },
						["RendererOpenGL.Channels.Nest"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Nest", },
						["RendererOpenGL.LightingEnabled"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.LightingEnabled", },
						["RendererOpenGL.Channels.Normal"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Normal", },
						["RendererOpenGL.ShadowsEnabled"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.ShadowsEnabled", },
						["RendererOpenGL.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.WorldCoord", },
						["RendererOpenGL.Channels.MaterialID"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.MaterialID", },
						["RendererOpenGL.Supersampling"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Supersampling", },
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 512,
							Expression = "Renderer3DFront_1.Height",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront_1.Height",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_1",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DLeft_1" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.Z",
						},
						["RendererSoftware.Channels.Coverage"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.Coverage",
						},
						["RendererSoftware.Channels.BgColor"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.BgColor",
						},
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.TexCoord0",
						},
						["RendererSoftware.Channels.ObjectID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.ObjectID",
						},
						["RendererSoftware.Channels.MaterialID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.MaterialID",
						},
						["RendererSoftware.Channels.WorldCoord"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.WorldCoord",
						},
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -412.5, 737.55 } },
				},
				Renderer3DBottom_1 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["RendererOpenGL.Channels.Vector"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Vector", },
						["RendererOpenGL.Channels.ObjectID"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.ObjectID", },
						["RendererOpenGL.Channels.BackVector"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.BackVector", },
						["RendererOpenGL.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.TexCoord0", },
						["RendererOpenGL.Channels.Z"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Z", },
						["RendererOpenGL.Channels.Nest"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Nest", },
						["RendererOpenGL.LightingEnabled"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.LightingEnabled", },
						["RendererOpenGL.Channels.Normal"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.Normal", },
						["RendererOpenGL.ShadowsEnabled"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.ShadowsEnabled", },
						["RendererOpenGL.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.WorldCoord", },
						["RendererOpenGL.Channels.MaterialID"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Channels.MaterialID", },
						["RendererOpenGL.Supersampling"] = Input { Expression = "Renderer3DFront_1.RendererOpenGL.Supersampling", },
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 512,
							Expression = "Renderer3DFront_1.Height",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront_1.Height",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_1",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DBottom_1" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.Z",
						},
						["RendererSoftware.Channels.Coverage"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.Coverage",
						},
						["RendererSoftware.Channels.BgColor"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.BgColor",
						},
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.TexCoord0",
						},
						["RendererSoftware.Channels.ObjectID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.ObjectID",
						},
						["RendererSoftware.Channels.MaterialID"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.MaterialID",
						},
						["RendererSoftware.Channels.WorldCoord"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.Channels.WorldCoord",
						},
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront_1.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_1.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -412.5, 803.836 } },
				},
				PipeRouterLeft = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DLeft_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -302.5, 736.6 } },
				},
				PipeRouterBack = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DBack_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -302.5, 703.6 } },
				},
				PipeRouterBottom = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DBottom_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -302.5, 802.6 } },
				},
				PipeRouterTop = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DTop_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -302.5, 769.6 } },
				},
				PipeRouterRight = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DRight_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -302.5, 670.6 } },
				},
				PipeRouterFront = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "Renderer3DFront_1",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { -302.5, 637.6 } },
				},
				ChangeDepthBottom3 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 2, },
						Input = Input {
							SourceOp = "PipeRouterBottom",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 703.6 } },
				},
				ChangeDepthTop4 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterTop",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 406.6 } },
				},
				ChangeDepthFront5 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterFront",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 10.6 } },
				},
				ChangeDepthBottom5 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBottom",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 175.6 } },
				},
				ChangeDepthBottom2 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBottom",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 967.6 } },
				},
				ChangeDepthTop2 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterTop",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 934.6 } },
				},
				ChangeDepthTop = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterTop",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 1165.6 } },
				},
				ChangeDepthTop5 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterTop",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 142.6 } },
				},
				ChangeDepthRight5 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterRight",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 43.6 } },
				},
				ChangeDepthBack3 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 2, },
						Input = Input {
							SourceOp = "PipeRouterBack",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 604.6 } },
				},
				ChangeDepthBack2 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBack",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 868.6 } },
				},
				ChangeDepthBack = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBack",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 1099.6 } },
				},
				ChangeDepthRight3 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 2, },
						Input = Input {
							SourceOp = "PipeRouterRight",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 571.6 } },
				},
				ChangeDepthFront3 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 2, },
						Input = Input {
							SourceOp = "PipeRouterFront",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 538.6 } },
				},
				ChangeDepthBottom = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBottom",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 1198.6 } },
				},
				ChangeDepthTop3 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 2, },
						Input = Input {
							SourceOp = "PipeRouterTop",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 670.6 } },
				},
				ChangeDepthFront2 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterFront",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 802.6 } },
				},
				ChangeDepthRight2 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterRight",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 835.6 } },
				},
				ChangeDepthFront = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterFront",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 1033.6 } },
				},
				ChangeDepthLeft4 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterLeft",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 373.6 } },
				},
				ChangeDepthRight = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterRight",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 1066.6 } },
				},
				ChangeDepthLeft2 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterLeft",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 901.6 } },
				},
				ChangeDepthBack5 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBack",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 76.6 } },
				},
				ChangeDepthLeft = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterLeft",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 1132.6 } },
				},
				ChangeDepthBottom4 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBottom",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 439.6 } },
				},
				ChangeDepthBack4 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterBack",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 340.6 } },
				},
				ChangeDepthRight4 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterRight",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 307.6 } },
				},
				ChangeDepthLeft3 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 2, },
						Input = Input {
							SourceOp = "PipeRouterLeft",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 637.6 } },
				},
				ChangeDepthFront4 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterFront",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 274.6 } },
				},
				ChangeDepthLeft5 = ChangeDepth {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Depth = Input { Value = 4, },
						Input = Input {
							SourceOp = "PipeRouterLeft",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -27.5, 109.6 } },
				},
				ChannelBooleansFront3 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 22, },
						ToGreen = Input { Value = 23, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthFront3",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 538.6 } },
				},
				ChannelBooleansLeft3 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 22, },
						ToGreen = Input { Value = 23, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthLeft3",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 637.6 } },
				},
				ChannelBooleansBack3 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 22, },
						ToGreen = Input { Value = 23, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBack3",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 604.6 } },
				},
				ChannelBooleansRight3 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 22, },
						ToGreen = Input { Value = 23, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthRight3",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 571.6 } },
				},
				ChannelBooleansLeft5 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 27, },
						ToGreen = Input { Value = 28, },
						ToBlue = Input { Value = 29, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthLeft5",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 109.6 } },
				},
				ChannelBooleansBack5 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 27, },
						ToGreen = Input { Value = 28, },
						ToBlue = Input { Value = 29, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBack5",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 76.6 } },
				},
				ChannelBooleansRight5 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 27, },
						ToGreen = Input { Value = 28, },
						ToBlue = Input { Value = 29, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthRight5",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 43.6 } },
				},
				ChannelBooleansRight2 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 21, },
						ToGreen = Input { Value = 20, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthRight2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 835.6 } },
				},
				ChannelBooleansTop5 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 27, },
						ToGreen = Input { Value = 28, },
						ToBlue = Input { Value = 29, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthTop5",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 142.6 } },
				},
				ChannelBooleansBack4 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 35, },
						ToGreen = Input { Value = 36, },
						ToBlue = Input { Value = 37, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBack4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 340.6 } },
				},
				ChannelBooleansTop = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 18, },
						ToGreen = Input { Value = 19, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthTop",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 1165.6 } },
				},
				ChannelBooleansLeft2 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 21, },
						ToGreen = Input { Value = 20, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthLeft2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 901.6 } },
				},
				ChannelBooleansFront5 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 27, },
						ToGreen = Input { Value = 28, },
						ToBlue = Input { Value = 29, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthFront5",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 10.6 } },
				},
				ChannelBooleansBottom4 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 35, },
						ToGreen = Input { Value = 36, },
						ToBlue = Input { Value = 37, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBottom4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 439.6 } },
				},
				ChannelBooleansLeft4 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 35, },
						ToGreen = Input { Value = 36, },
						ToBlue = Input { Value = 37, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthLeft4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 373.6 } },
				},
				ChannelBooleansRight = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 18, },
						ToGreen = Input { Value = 19, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthRight",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 1066.6 } },
				},
				ChannelBooleansFront2 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 21, },
						ToGreen = Input { Value = 20, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthFront2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 802.6 } },
				},
				ChannelBooleansTop4 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 35, },
						ToGreen = Input { Value = 36, },
						ToBlue = Input { Value = 37, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthTop4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 406.6 } },
				},
				ChannelBooleansRight4 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 35, },
						ToGreen = Input { Value = 36, },
						ToBlue = Input { Value = 37, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthRight4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 307.6 } },
				},
				ChannelBooleansBottom = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 18, },
						ToGreen = Input { Value = 19, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBottom",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 1198.6 } },
				},
				ChannelBooleansTop2 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 21, },
						ToGreen = Input { Value = 20, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthTop2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 934.6 } },
				},
				ChannelBooleansLeft = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 18, },
						ToGreen = Input { Value = 19, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthLeft",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 1132.6 } },
				},
				ChannelBooleansBottom3 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 22, },
						ToGreen = Input { Value = 23, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBottom3",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 703.6 } },
				},
				ChannelBooleansFront4 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 35, },
						ToGreen = Input { Value = 36, },
						ToBlue = Input { Value = 37, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthFront4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 274.6 } },
				},
				ChannelBooleansFront = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 18, },
						ToGreen = Input { Value = 19, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthFront",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 1033.6 } },
				},
				ChannelBooleansBottom5 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 27, },
						ToGreen = Input { Value = 28, },
						ToBlue = Input { Value = 29, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBottom5",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 80.792, 175.6 } },
				},
				ChannelBooleansTop3 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 22, },
						ToGreen = Input { Value = 23, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthTop3",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 670.6 } },
				},
				ChannelBooleansBack2 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 21, },
						ToGreen = Input { Value = 20, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBack2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 868.6 } },
				},
				ChannelBooleansBottom2 = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 21, },
						ToGreen = Input { Value = 20, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBottom2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 967.6 } },
				},
				ChannelBooleansBack = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 18, },
						ToGreen = Input { Value = 19, },
						ToBlue = Input { Value = 15, },
						ToAlpha = Input { Value = 4, },
						Background = Input {
							SourceOp = "ChangeDepthBack",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 82.5, 1099.6 } },
				},
				CubeMapBGColor = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CubeMapColor",
					Inputs = {
						Rotation = Input { Value = 1, },
						["FilterMode.Nest"] = Input { Value = 1, },
						CrossImage = Input { },
						Left = Input {
							SourceOp = "ChannelBooleansLeft5",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "ChannelBooleansRight5",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "ChannelBooleansTop5",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "ChannelBooleansBottom5",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "ChannelBooleansFront5",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "ChannelBooleansBack5",
							Source = "Output",
						},
						MaterialIDNest = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 247.5, 175.6 } },
				},
				CubeMapDepth = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CubeMapColor",
					Inputs = {
						Rotation = Input { Value = 1, },
						["FilterMode.Nest"] = Input { Value = 1, },
						CrossImage = Input { },
						Left = Input {
							SourceOp = "ChannelBooleansLeft",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "ChannelBooleansRight",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "ChannelBooleansTop",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "ChannelBooleansBottom",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "ChannelBooleansFront",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "ChannelBooleansBack",
							Source = "Output",
						},
						MaterialIDNest = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 247.5, 1198.6 } },
				},
				CubeMapID = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CubeMapColor",
					Inputs = {
						Rotation = Input { Value = 1, },
						["FilterMode.Nest"] = Input { Value = 1, },
						CrossImage = Input { },
						Left = Input {
							SourceOp = "ChannelBooleansLeft2",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "ChannelBooleansRight2",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "ChannelBooleansTop2",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "ChannelBooleansBottom2",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "ChannelBooleansFront2",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "ChannelBooleansBack2",
							Source = "Output",
						},
						MaterialIDNest = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 247.5, 967.6 } },
				},
				CubeMapColor = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Orientation = Input { Value = 0, },
						Rotation = Input { Value = 1, },
						["FilterMode.Nest"] = Input { Value = 1, },
						["FilterMode.SW.LowQ"] = Input { Value = FuID { "Bilinear" }, },
						Left = Input {
							SourceOp = "PipeRouterLeft",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "PipeRouterRight",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "PipeRouterTop",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "PipeRouterBottom",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "PipeRouterFront",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "PipeRouterBack",
							Source = "Output",
						},
						MaterialID = Input { Value = 3, },
					},
					ViewInfo = OperatorInfo { Pos = { 247.5, 1429.6 } },
				},
				CubeMapWorld = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CubeMapColor",
					Inputs = {
						Rotation = Input { Value = 1, },
						["FilterMode.Nest"] = Input { Value = 1, },
						CrossImage = Input { },
						Left = Input {
							SourceOp = "ChannelBooleansLeft4",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "ChannelBooleansRight4",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "ChannelBooleansTop4",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "ChannelBooleansBottom4",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "ChannelBooleansFront4",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "ChannelBooleansBack4",
							Source = "Output",
						},
						MaterialIDNest = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 247.5, 439.6 } },
				},
				CubeMapTex = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					SourceOp = "CubeMapColor",
					Inputs = {
						Rotation = Input { Value = 1, },
						["FilterMode.Nest"] = Input { Value = 1, },
						CrossImage = Input { },
						Left = Input {
							SourceOp = "ChannelBooleansLeft3",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "ChannelBooleansRight3",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "ChannelBooleansTop3",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "ChannelBooleansBottom3",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "ChannelBooleansFront3",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "ChannelBooleansBack3",
							Source = "Output",
						},
						MaterialIDNest = Input { },
						StartEndRenderScripts = Input { },
					},
					ViewInfo = OperatorInfo { Pos = { 247.5, 703.6 } },
				},
				Shape3DCylinderDepth = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 7, },
						["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 8, },
						["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceSphereInputs.Radius"] = Input { Value = 500, },
						["Transform3DOp.Rotate.Y"] = Input { Value = 270, },
						["Transform3DOp.ScaleLock"] = Input { Value = 0, },
						["Transform3DOp.Scale.X"] = Input { Value = -1, },
						Shape = Input { Value = FuID { "SurfaceCylinderInputs" }, },
						MaterialInput = Input {
							SourceOp = "CubeMapDepth",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.MaterialID"] = Input { Value = 6, },
						["SurfaceCylinderInputs.Radius"] = Input { Value = 500, },
						["SurfaceCylinderInputs.Height"] = Input { Value = 1000, },
						["SurfaceCylinderInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceCylinderInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceCylinderInputs.ObjectID.ObjectID"] = Input { Value = 2, }
					},
					ViewInfo = OperatorInfo { Pos = { 357.5, 1198.6 } },
				},
				Shape3DCylinderWorld = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 7, },
						["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 8, },
						["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceSphereInputs.Radius"] = Input { Value = 500, },
						["Transform3DOp.Rotate.Y"] = Input { Value = 270, },
						["Transform3DOp.ScaleLock"] = Input { Value = 0, },
						["Transform3DOp.Scale.X"] = Input { Value = -1, },
						Shape = Input { Value = FuID { "SurfaceCylinderInputs" }, },
						MaterialInput = Input {
							SourceOp = "CubeMapWorld",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.MaterialID"] = Input { Value = 6, },
						["SurfaceCylinderInputs.Radius"] = Input { Value = 500, },
						["SurfaceCylinderInputs.Height"] = Input { Value = 1000, },
						["SurfaceCylinderInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceCylinderInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceCylinderInputs.ObjectID.ObjectID"] = Input { Value = 2, }
					},
					ViewInfo = OperatorInfo { Pos = { 357.5, 439.6 } },
				},
				Shape3DCylinderTex = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 7, },
						["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 8, },
						["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceSphereInputs.Radius"] = Input { Value = 500, },
						["Transform3DOp.Rotate.Y"] = Input { Value = 270, },
						["Transform3DOp.ScaleLock"] = Input { Value = 0, },
						["Transform3DOp.Scale.X"] = Input { Value = -1, },
						Shape = Input { Value = FuID { "SurfaceCylinderInputs" }, },
						MaterialInput = Input {
							SourceOp = "CubeMapTex",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.MaterialID"] = Input { Value = 6, },
						["SurfaceCylinderInputs.Radius"] = Input { Value = 500, },
						["SurfaceCylinderInputs.Height"] = Input { Value = 1000, },
						["SurfaceCylinderInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceCylinderInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceCylinderInputs.ObjectID.ObjectID"] = Input { Value = 2, }
					},
					ViewInfo = OperatorInfo { Pos = { 357.5, 703.6 } },
				},
				Shape3DCylinderColor = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 7, },
						["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 8, },
						["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceSphereInputs.Radius"] = Input { Value = 500, },
						["Transform3DOp.Rotate.Y"] = Input { Value = 270, },
						["Transform3DOp.ScaleLock"] = Input { Value = 0, },
						["Transform3DOp.Scale.X"] = Input { Value = -1, },
						Shape = Input { Value = FuID { "SurfaceCylinderInputs" }, },
						MaterialInput = Input {
							SourceOp = "CubeMapColor",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.MaterialID"] = Input { Value = 6, },
						["SurfaceCylinderInputs.Radius"] = Input { Value = 500, },
						["SurfaceCylinderInputs.Height"] = Input { Value = 1000, },
						["SurfaceCylinderInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceCylinderInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceCylinderInputs.ObjectID.ObjectID"] = Input { Value = 2, }
					},
					ViewInfo = OperatorInfo { Pos = { 357.5, 1429.6 } },
				},
				Shape3DCylinderID = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 7, },
						["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 8, },
						["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceSphereInputs.Radius"] = Input { Value = 500, },
						["Transform3DOp.Rotate.Y"] = Input { Value = 270, },
						["Transform3DOp.ScaleLock"] = Input { Value = 0, },
						["Transform3DOp.Scale.X"] = Input { Value = -1, },
						Shape = Input { Value = FuID { "SurfaceCylinderInputs" }, },
						MaterialInput = Input {
							SourceOp = "CubeMapID",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.MaterialID"] = Input { Value = 6, },
						["SurfaceCylinderInputs.Radius"] = Input { Value = 500, },
						["SurfaceCylinderInputs.Height"] = Input { Value = 1000, },
						["SurfaceCylinderInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceCylinderInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceCylinderInputs.ObjectID.ObjectID"] = Input { Value = 2, }
					},
					ViewInfo = OperatorInfo { Pos = { 357.5, 967.6 } },
				},
				Shape3DCylinderBGColor = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 7, },
						["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 8, },
						["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceSphereInputs.Radius"] = Input { Value = 500, },
						["Transform3DOp.Rotate.Y"] = Input { Value = 270, },
						["Transform3DOp.ScaleLock"] = Input { Value = 0, },
						["Transform3DOp.Scale.X"] = Input { Value = -1, },
						Shape = Input { Value = FuID { "SurfaceCylinderInputs" }, },
						MaterialInput = Input {
							SourceOp = "CubeMapBGColor",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.MaterialID"] = Input { Value = 6, },
						["SurfaceCylinderInputs.Radius"] = Input { Value = 500, },
						["SurfaceCylinderInputs.Height"] = Input { Value = 1000, },
						["SurfaceCylinderInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceCylinderInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceCylinderInputs.ObjectID.ObjectID"] = Input { Value = 2, }
					},
					ViewInfo = OperatorInfo { Pos = { 361.347, 175.124 } },
				},
				UVRenderer3DColor = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 2048,
							Expression = "Renderer3DFront_1.Width*4",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront_1.Width",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "Shape3DCylinderColor",
							Source = "Output",
						},
						RendererType = Input { Value = FuID { "RendererOpenGLUV" }, },
						["RendererOpenGLUV.UVGutterSize"] = Input { Value = 0, },
						["RendererOpenGLUV.Texturing"] = Input { Value = 1, },
						["RendererOpenGLUV.TextureDepth"] = Input { Value = 0, },
					},
					ViewInfo = OperatorInfo { Pos = { 467.5, 1429.6 } },
				},
				UVRenderer3DBGColor = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 2048,
							Expression = "Renderer3DFront_1.Width*4",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront_1.Width",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "Shape3DCylinderBGColor",
							Source = "Output",
						},
						RendererType = Input { Value = FuID { "RendererOpenGLUV" }, },
						["RendererOpenGLUV.UVGutterSize"] = Input { Value = 0, },
						["RendererOpenGLUV.Texturing"] = Input { Value = 1, },
						["RendererOpenGLUV.TextureDepth"] = Input { Value = 0, },
					},
					ViewInfo = OperatorInfo { Pos = { 471.347, 175.124 } },
				},
				UVRenderer3DWorld = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 2048,
							Expression = "Renderer3DFront_1.Width*4",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront_1.Width",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "Shape3DCylinderWorld",
							Source = "Output",
						},
						RendererType = Input { Value = FuID { "RendererOpenGLUV" }, },
						["RendererOpenGLUV.UVGutterSize"] = Input { Value = 0, },
						["RendererOpenGLUV.Texturing"] = Input { Value = 1, },
						["RendererOpenGLUV.TextureDepth"] = Input { Value = 0, },
					},
					ViewInfo = OperatorInfo { Pos = { 467.5, 439.6 } },
				},
				UVRenderer3DTex = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 2048,
							Expression = "Renderer3DFront_1.Width*4",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront_1.Width",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "Shape3DCylinderTex",
							Source = "Output",
						},
						RendererType = Input { Value = FuID { "RendererOpenGLUV" }, },
						["RendererOpenGLUV.UVGutterSize"] = Input { Value = 0, },
						["RendererOpenGLUV.Texturing"] = Input { Value = 1, },
						["RendererOpenGLUV.TextureDepth"] = Input { Value = 2, },
					},
					ViewInfo = OperatorInfo { Pos = { 466.55, 702.65 } },
				},
				UVRenderer3DDepth = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 2048,
							Expression = "Renderer3DFront_1.Width*4",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront_1.Width",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "Shape3DCylinderDepth",
							Source = "Output",
						},
						RendererType = Input { Value = FuID { "RendererOpenGLUV" }, },
						["RendererOpenGLUV.UVGutterSize"] = Input { Value = 0, },
						["RendererOpenGLUV.Texturing"] = Input { Value = 1, },
						["RendererOpenGLUV.TextureDepth"] = Input { Value = 0, },
					},
					ViewInfo = OperatorInfo { Pos = { 467.5, 1198.6 } },
				},
				UVRenderer3DID = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 2048,
							Expression = "Renderer3DFront_1.Width*4",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront_1.Width",
						},
						Depth = Input { Value = 4, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "Shape3DCylinderID",
							Source = "Output",
						},
						RendererType = Input { Value = FuID { "RendererOpenGLUV" }, },
						["RendererOpenGLUV.UVGutterSize"] = Input { Value = 0, },
						["RendererOpenGLUV.Texturing"] = Input { Value = 1, },
						["RendererOpenGLUV.TextureDepth"] = Input { Value = 0, },
					},
					ViewInfo = OperatorInfo { Pos = { 467.5, 967.6 } },
				},
				PipeRouterID = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "UVRenderer3DID",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 577.5, 967.6 } },
				},
				PipeRouterTex = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "UVRenderer3DTex",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 577.5, 703.6 } },
				},
				PipeRouterBGColor = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "UVRenderer3DBGColor",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 577.5, 175.6 } },
				},
				PipeRouterDepth = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "UVRenderer3DDepth",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 577.5, 1198.6 } },
				},
				PipeRouterWorld = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "UVRenderer3DWorld",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 577.5, 439.6 } },
				},
				ChannelBooleansBGColorMerge = ChannelBoolean {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 5, },
						ToGreen = Input { Value = 6, },
						ToBlue = Input { Value = 7, },
						ToAlpha = Input { Value = 8, },
						EnableExtraChannels = Input { Value = 1, },
						ToBGRed = Input { Value = 0, },
						ToBGGreen = Input { Value = 1, },
						ToBGBlue = Input { Value = 2, },
						Background = Input {
							SourceOp = "ChannelBooleansWorldMerge",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "PipeRouterBGColor",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 742.5, 175.6 } },
				},
				ChannelBooleansDepthMerge = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 5, },
						ToGreen = Input { Value = 6, },
						ToBlue = Input { Value = 7, },
						ToAlpha = Input { Value = 8, },
						EnableExtraChannels = Input { Value = 1, },
						ToZBuffer = Input { Value = 0, },
						ToZCoverage = Input { Value = 1, },
						Background = Input {
							SourceOp = "PipeRouterColor",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "PipeRouterDepth",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 742.5, 1198.6 } },
				},
				ChannelBooleansWorldMerge = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 5, },
						ToGreen = Input { Value = 6, },
						ToBlue = Input { Value = 7, },
						ToAlpha = Input { Value = 8, },
						EnableExtraChannels = Input { Value = 1, },
						ToXPosition = Input { Value = 0, },
						ToYPosition = Input { Value = 1, },
						ToZPosition = Input { Value = 2, },
						Background = Input {
							SourceOp = "ChannelBooleansTexMerge",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "PipeRouterWorld",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 742.5, 439.6 } },
				},
				ChannelBooleansIDMerge = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 5, },
						ToGreen = Input { Value = 6, },
						ToBlue = Input { Value = 7, },
						ToAlpha = Input { Value = 8, },
						EnableExtraChannels = Input { Value = 1, },
						ToObjectID = Input { Value = 1, },
						ToMaterialID = Input { Value = 0, },
						Background = Input {
							SourceOp = "ChannelBooleansDepthMerge",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "PipeRouterID",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 742.5, 967.6 } },
				},
				ChannelBooleansTexMerge = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToRed = Input { Value = 5, },
						ToGreen = Input { Value = 6, },
						ToBlue = Input { Value = 7, },
						ToAlpha = Input { Value = 8, },
						EnableExtraChannels = Input { Value = 1, },
						ToUTexture = Input { Value = 0, },
						ToVTexture = Input { Value = 1, },
						Background = Input {
							SourceOp = "ChannelBooleansIDMerge",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "PipeRouterTex",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 742.5, 703.6 } },
				},
				PipeRouterColor = PipeRouter {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "UVRenderer3DColor",
							Source = "Output",
						},
					},
					ViewInfo = PipeRouterInfo { Pos = { 797.5, 1429.6 } },
				}
			},
		},
		Note1 = Note {
			Inputs = {
				Comments = Input { Value = "This example shows how to render elements from Fusion's 3D animation system to a cylindrical format output.", }
			},
			ViewInfo = StickyNoteInfo {
				Pos = { 220, 49.5 },
				Flags = {
					Expanded = true
				},
				Size = { 438.495, 64.52 }
			},
		},
		CylindricalRenderer3D = GroupOperator {
			CustomData = {
				HelpPage = "http://www.andrewhazelden.com/projects/kartavr/docs/macros-guide.html#CylindricalRenderer3D",
			},
			Inputs = ordered() {
				MainInput1 = InstanceInput {
					SourceOp = "CameraViewInput",
					Source = "SceneInput1",
				},
				Input1 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "Width",
					Name = "Height",
					MaxScale = 8192,
					Default = 512,
				},
				Input2 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "Depth",
					Default = 3,
				},
				Input3 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "RendererSoftware.LightingEnabled",
					Default = 1,
				},
				Input4 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "RendererSoftware.ShadowsEnabled",
					Default = 1,
				},
				Input5 = InstanceInput {
					SourceOp = "Camera3DFront",
					Source = "Transform3DOp.Translate.X",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input6 = InstanceInput {
					SourceOp = "Camera3DFront",
					Source = "Transform3DOp.Translate.Y",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input7 = InstanceInput {
					SourceOp = "Camera3DFront",
					Source = "Transform3DOp.Translate.Z",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input8 = InstanceInput {
					SourceOp = "CubeMap",
					Source = "Rotate.RotOrder",
				},
				Input9 = InstanceInput {
					SourceOp = "CubeMap",
					Source = "Rotate.X",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				Input10 = InstanceInput {
					SourceOp = "CubeMap",
					Source = "Rotate.Y",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				Input11 = InstanceInput {
					SourceOp = "CubeMap",
					Source = "Rotate.Z",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				}
			},
			Outputs = {
				MainOutput1 = InstanceOutput {
					SourceOp = "UVRenderer3D",
					Source = "Output",
				}
			},
			ViewInfo = GroupInfo {
				Pos = { 495, 148.5 },
				Flags = {
					AllowPan = false,
					AutoSnap = true,
					RemoveRouters = true
				},
				Size = { 896, 493.3, 448, 22 },
				Direction = "Horizontal",
				PipeStyle = "Direct",
				Scale = 1,
				Offset = { 0, 0 }
			},
			Tools = ordered() {
				UVRenderer3D = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 2048,
							Expression = "Renderer3DFront.Width*4",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width",
						},
						Depth = Input {
							Value = 3,
							Expression = "Renderer3DFront.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "Shape3DCylinder",
							Source = "Output",
						},
						RendererType = Input { Value = FuID { "RendererOpenGLUV" }, },
						["RendererOpenGLUV.UVGutterSize"] = Input { Value = 0, },
						["RendererOpenGLUV.Texturing"] = Input { Value = 1, },
						["RendererOpenGLUV.TextureDepth"] = Input { Value = 0, },
					},
					ViewInfo = OperatorInfo { Pos = { 385, 340.15 } },
				},
				Shape3DCylinder = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 7, },
						["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 8, },
						["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceSphereInputs.Radius"] = Input { Value = 500, },
						["Transform3DOp.Rotate.Y"] = Input { Value = 270, },
						["Transform3DOp.ScaleLock"] = Input { Value = 0, },
						["Transform3DOp.Scale.X"] = Input { Value = -1, },
						Shape = Input { Value = FuID { "SurfaceCylinderInputs" }, },
						MaterialInput = Input {
							SourceOp = "CubeMap",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.MaterialID"] = Input { Value = 6, },
						["SurfaceCylinderInputs.Radius"] = Input { Value = 500, },
						["SurfaceCylinderInputs.Height"] = Input { Value = 1000, },
						["SurfaceCylinderInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceCylinderInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceCylinderInputs.ObjectID.ObjectID"] = Input { Value = 2, }
					},
					ViewInfo = OperatorInfo { Pos = { 275, 340.15 } },
				},
				CubeMap = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Orientation = Input { Value = 0, },
						Rotation = Input { Value = 1, },
						["FilterMode.Nest"] = Input { Value = 1, },
						["FilterMode.SW.LowQ"] = Input { Value = FuID { "Bilinear" }, },
						Left = Input {
							SourceOp = "Renderer3DLeft",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "Renderer3DRight",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "Renderer3DTop",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "Renderer3DBottom",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "Renderer3DFront",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "Renderer3DBack",
							Source = "Output",
						},
						MaterialID = Input { Value = 3, },
					},
					ViewInfo = OperatorInfo { Pos = { 165, 340.15 } },
				},
				Renderer3DTop = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width",
						},
						Depth = Input {
							Value = 3,
							Expression = "Renderer3DFront.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DTop" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 406.15 } },
				},
				Renderer3DRight = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width",
						},
						Depth = Input {
							Value = 3,
							Expression = "Renderer3DFront.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DRight" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 307.15 } },
				},
				Renderer3DBack = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width",
						},
						Depth = Input {
							Value = 3,
							Expression = "Renderer3DFront.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DBack" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 340.15 } },
				},
				Renderer3DBottom = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width",
						},
						Depth = Input {
							Value = 3,
							Expression = "Renderer3DFront.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DBottom" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 439.15 } },
				},
				Renderer3DLeft = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width",
						},
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width",
						},
						Depth = Input {
							Value = 3,
							Expression = "Renderer3DFront.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DLeft" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 373.15 } },
				},
				Renderer3DFront = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input { Value = 512, },
						Height = Input {
							Value = 512,
							Expression = "Renderer3DFront.Width",
						},
						Depth = Input { Value = 3, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DFront" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.LightingEnabled"] = Input { Value = 1, },
						["RendererSoftware.ShadowsEnabled"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { 0, 274.15 } },
				},
				CameraViewInput = Merge3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						PassThroughLights = Input { Value = 1, },
						SceneInput1 = Input {
							SourceOp = "Shape3D",
							Source = "Output",
						},
						SceneInput2 = Input {
							SourceOp = "Camera3DFront",
							Source = "Output",
						},
						SceneInput3 = Input {
							SourceOp = "Camera3DRight",
							Source = "Output",
						},
						SceneInput5 = Input {
							SourceOp = "Camera3DLeft",
							Source = "Output",
						},
						SceneInput6 = Input {
							SourceOp = "Camera3DTop",
							Source = "Output",
						},
						SceneInput7 = Input {
							SourceOp = "Camera3DBottom",
							Source = "Output",
						},
						SceneInput4 = Input {
							SourceOp = "Camera3DBack",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -220, 274.15 } },
				},
				Camera3DBottom = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -180,
							Expression = "Camera3DFront.Transform3DOp.Rotate.X-90",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Z", },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 175.15 } },
				},
				Camera3DRight = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = 90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.Z+90",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 43.15 } },
				},
				Camera3DTop = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.X+90", },
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Z", },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 142.15 } },
				},
				Camera3DLeft = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = -90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.Z-90.0",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 109.15 } },
				},
				Camera3DBack = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = 180,
							Expression = "Camera3DFront.Transform3DOp.Rotate.Z+180.0",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 76.15 } },
				},
				Camera3DFront = Camera3D {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Rotate.X"] = Input { Value = -90, },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 10.15 } },
				}
			},
		},
		Saver1_1 = Saver {
			CtrlWZoom = false,
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "Temp:\\KartaVR\\domemaster_snapshot.0000.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				CreateDir = Input { Value = 1, },
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "ChannelBooleansBGColorMerge",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 605, 214.5 } },
		},
		Shape3D_1 = Shape3D {
			NameSet = true,
			Inputs = {
				["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 2, },
				["SurfaceTorusInputs.ObjectID.ObjectID"] = Input { Value = 6, },
				["SurfaceIcoInputs.ObjectID.ObjectID"] = Input { Value = 7, },
				["SurfaceCylinderInputs.ObjectID.ObjectID"] = Input { Value = 5, },
				["SurfaceCubeInputs.ObjectID.ObjectID"] = Input { Value = 4, },
				Shape = Input { Value = FuID { "SurfaceSphereInputs" }, },
				MaterialInput = Input {
					SourceOp = "SphereMap_1",
					Source = "MaterialOutput",
				},
				["MtlStdInputs.Diffuse.Color.Red"] = Input { Value = 0.596899224806202, },
				["MtlStdInputs.Diffuse.Color.Green"] = Input { Value = 0.364341085271318, },
				["MtlStdInputs.Diffuse.Color.Blue"] = Input { Value = 0.65891472868217, },
				["MtlStdInputs.ReceivesLighting"] = Input { Value = 0, },
				["MtlStdInputs.ReceivesShadows"] = Input { Value = 0, },
				["MtlStdInputs.MaterialIDNest"] = Input { Value = 1, },
				["MtlStdInputs.MaterialID"] = Input { Value = 2, },
				["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 72, },
				["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 36, },
				["SurfaceSphereInputs.Visibility.Nest"] = Input { Value = 1, },
				["SurfaceSphereInputs.Visibility.CullFrontFace"] = Input { Value = 1, },
				["SurfaceSphereInputs.Lighting.Nest"] = Input { Value = 1, },
				["SurfaceSphereInputs.Lighting.IsAffectedByLights"] = Input { Value = 0, },
				["SurfaceSphereInputs.Matte.Nest"] = Input { Value = 1, },
				["SurfaceSphereInputs.Controls.Normals.Scale"] = Input { Value = 6.93, },
				["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 3, }
			},
			ViewInfo = OperatorInfo { Pos = { 385, 214.5 } },
		},
		Shape3D = Shape3D {
			NameSet = true,
			Inputs = {
				["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 2, },
				["SurfaceTorusInputs.ObjectID.ObjectID"] = Input { Value = 6, },
				["SurfaceIcoInputs.ObjectID.ObjectID"] = Input { Value = 7, },
				["SurfaceCylinderInputs.ObjectID.ObjectID"] = Input { Value = 5, },
				["SurfaceCubeInputs.ObjectID.ObjectID"] = Input { Value = 4, },
				Shape = Input { Value = FuID { "SurfaceSphereInputs" }, },
				MaterialInput = Input {
					SourceOp = "SphereMap",
					Source = "MaterialOutput",
				},
				["MtlStdInputs.Diffuse.Color.Red"] = Input { Value = 0.596899224806202, },
				["MtlStdInputs.Diffuse.Color.Green"] = Input { Value = 0.364341085271318, },
				["MtlStdInputs.Diffuse.Color.Blue"] = Input { Value = 0.65891472868217, },
				["MtlStdInputs.ReceivesLighting"] = Input { Value = 0, },
				["MtlStdInputs.ReceivesShadows"] = Input { Value = 0, },
				["MtlStdInputs.MaterialIDNest"] = Input { Value = 1, },
				["MtlStdInputs.MaterialID"] = Input { Value = 2, },
				["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 72, },
				["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 36, },
				["SurfaceSphereInputs.Visibility.Nest"] = Input { Value = 1, },
				["SurfaceSphereInputs.Visibility.CullFrontFace"] = Input { Value = 1, },
				["SurfaceSphereInputs.Lighting.Nest"] = Input { Value = 1, },
				["SurfaceSphereInputs.Lighting.IsAffectedByLights"] = Input { Value = 0, },
				["SurfaceSphereInputs.Matte.Nest"] = Input { Value = 1, },
				["SurfaceSphereInputs.Controls.Normals.Scale"] = Input { Value = 6.93, },
				["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 3, }
			},
			ViewInfo = OperatorInfo { Pos = { 385, 148.5 } },
		},
		Saver1 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "Temp:\\KartaVR\\domemaster_snapshot.0000.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				CreateDir = Input { Value = 1, },
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "UVRenderer3D",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 605, 148.5 } },
		},
		SphereMap = SphereMap {
			CtrlWZoom = false,
			NameSet = true,
			Inputs = {
				Rotation = Input { Value = 1, },
				["Rotate.RotOrder"] = Input { Value = FuID { "YXZ" }, },
				["Rotate.X"] = Input { Value = -90, },
				["Rotate.Y"] = Input { Value = -90, },
				["FilterMode.Nest"] = Input { Value = 1, },
				Image = Input {
					SourceOp = "Loader1_1",
					Source = "Output",
				},
				MaterialID = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 275, 148.5 } },
		},
		SphereMap_1 = SphereMap {
			NameSet = true,
			Inputs = {
				Rotation = Input { Value = 1, },
				["Rotate.RotOrder"] = Input { Value = FuID { "YXZ" }, },
				["Rotate.X"] = Input { Value = -90, },
				["Rotate.Y"] = Input { Value = -90, },
				["FilterMode.Nest"] = Input { Value = 1, },
				Image = Input {
					SourceOp = "Loader1_1_1",
					Source = "Output",
				},
				MaterialID = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 275, 214.5 } },
		}
	},
	Views = {
		{
			FrameTypeID = "ChildFrame",
			Mode = 3,
			LayoutPreset = 0,
			Left = 0,
			Top = 27,
			Width = 3440,
			Height = 1197,
			Views = ordered() {
				Main = MultiView {
					Active = "Flow",
					ViewList = ordered() {
						Flow = "FlowView",
						Console = "ConsoleView",
						Timeline = "TimelineView",
						Spline = "SplineEditorView",
						Info = "InfoView",
						Chat = "ChatView"
					},
					Flow = FlowView {
						Flags = {
							AutoHideNavigator = true,
							AutoSnap = true,
							RemoveRouters = true
						},
						NavigatorSize = { 200, 140 },
						Direction = "Horizontal",
						PipeStyle = "Direct",
						Scale = 2.58207,
						Offset = { -68.5178, -19.7931 }
					},
					Timeline = TimelineView {
						TreeControlState = {
						},
						DisplayMode = "All Tools",
						ShowCurrentTimeTools = false,
						Filter = "Show All",
						ShowSelectedTools = false,
						ShowAnimatedToolsOnly = false,
						ShowEditBoxes = false,
						KeyFrameView = {
							Position = { Left = 150, Bottom = 423 },
							ScaleX = 0.00214424951267057,
							OffsetX = -0.0514619883040936,
							OffsetY = 0,
							AutoScaling = "scroll",
							AutoSnapTo = "frame",
							AutoSnapToGuidelines = false,
							GuidelinesGrabEnabled = true,
							GuidelinesSnapTo = "frame"
						},
						Spreadsheet = { LeftPos = 130, Visible = false }
					},
					Spline = SplineEditorView {
						LeftPos = 256,
						ScaleX = 0.2,
						ScaleY = 0.00338983050847458,
						OffsetX = -4,
						OffsetY = 0,
						AutoScaling = "scroll",
						AutoSnapTo = "frame",
						AutoSnapToGuidelines = false,
						GuidelinesSnapTo = "frame",
						ShowKeyMarkers = false,
						IndependentHandles = false,
						ShowNonSplineModifiers = false,
						GuidelinesGrabEnabled = true,
						ShowOneToolOnly = false,
						ShowSelectedTools = false,
						ShowAllInputs = false,
						Filter = "Show All"
					},
				},
				Controls = MultiView {
					Active = "Tools",
					ViewList = ordered() {
						Tools = "ControlView",
						Modifiers = "ModifierView"
					},
				},
				Left = "PreviewContainer",
				Right = "PreviewContainer",
				Transport = "TransportView",
				Time = "TimeView"
			},
			Layout = {
				Columns = 2,
				RatioX = 1,
				RatioY = 1,
				{
					Rows = 3,
					RatioX = 0.84745269286754,
					RatioY = 0.0100418410041841,
					{
						Columns = 2,
						RatioX = 1,
						RatioY = 0.399495374264087,
						{ ID = "Left", RatioX = 1, RatioY = 82, Pop = true },
						{ ID = "Right", RatioX = -2, Pop = true },
						Pop = true
					},
					{ ID = "Main", RatioY = 0.551724137931034, Pop = true },
					{ ID = "Time", SnapY = 56, Flat = true }
				},
				{
					Rows = 2,
					PixelX = 522,
					{ ID = "Controls", RatioX = 1, RatioY = 1 },
					{ ID = "Transport", FixedY = -2 }
				}
			}
		}
	},
	Prefs = {
		Comp = {
			Interactive = {
				Proxy = {
					Auto = false
				},
			},
			Views = {
				Right = {
				},
				Left = {
					Viewer = {
						ScaleMode = 1,
					},
					View3D = {
						CamFront = {
							Rotation = {
								Y = 0,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamLeft = {
							Rotation = {
								Y = 90,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamPersp = {
							Rotation = {
								Y = 0,
								X = 30,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamTop = {
							Rotation = {
								Y = 0,
								X = 90,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamRight = {
							Rotation = {
								Y = -90,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CameraName = "Perspective"
					},
				},
				View1 = {
				},
			},
			FrameFormat = {
				Name = "2K Full Aperture (Super 35)",
				Width = 2048,
				Height = 1556,
				Rate = 24,
				PerFeet = 16,
				GuideRatio = 1.77778,
			},
			LastFile = "",
			Unsorted = {
				GlobalEnd = 1,
				RenderSettings = {
					Configs = {
						Preview = {
							StepRender = false,
							PriorityClasses = "all",
							CustomAspect = true,
							StepSize = 5,
							SizeType = 1,
							CustomHeight = 160,
							ShowSlaves = false,
							CustomWidth = 200,
							MotionBlur = true,
							UpdateMode = "Some",
							UseNetwork = false,
							Quality = false
						},
						Final = {
							StepRender = false,
							PriorityClasses = "all",
							CustomAspect = true,
							StepSize = 5,
							SizeType = 1,
							CustomHeight = 160,
							ShowSlaves = false,
							CustomWidth = 200,
							MotionBlur = true,
							UpdateMode = "Some",
							UseNetwork = false,
							Quality = true
						}
					},
					PreviewConfig = "Preview",
					CurrentConfig = "Final"
				}
			},
			Paths = {
			},
			QuickTime = {
			},
		}
	}
}

 