Composition {
	CurrentTime = 0,
	RenderRange = { 0, 0 },
	GlobalRange = { 0, 1 },
	CurrentID = 581,
	PlaybackUpdateMode = 0,
	Version = "Fusion Studio 8.2 build 2",
	SavedOutputs = 1,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	Resumable = true,
	OutputClips = {
		"Temp:\\KartaVR\\text.0000.png",
		"Temp:\\KartaVR\\stereo_text.0000.png"
	},
	Tools = {
		Loader1_1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "Macros:\\KartaVR\\Images\\latlong_wide_ar.jpg",
					FormatID = "JpegFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 330, 214.5 } },
		},
		EquirectangularRenderer3D_1 = GroupOperator {
			CustomData = {
				HelpPage = "http://www.andrewhazelden.com/projects/kartavr/docs/macros-guide.html#EquirectangularRenderer3D",
			},
			Inputs = ordered() {
				MainInput1 = InstanceInput {
					SourceOp = "CameraViewInput_3",
					Source = "SceneInput1",
				},
				Input1 = InstanceInput {
					SourceOp = "UVRenderer3D_3",
					Source = "Height",
					MaxScale = 8192,
					Default = 1920,
				},
				Input2 = InstanceInput {
					SourceOp = "UVRenderer3D_3",
					Source = "Depth",
					Default = 3,
				},
				Input3 = InstanceInput {
					SourceOp = "Renderer3DFront_3",
					Source = "RendererSoftware.LightingEnabled",
					Default = 1,
				},
				Input4 = InstanceInput {
					SourceOp = "Renderer3DFront_3",
					Source = "RendererSoftware.ShadowsEnabled",
					Default = 1,
				},
				Input5 = InstanceInput {
					SourceOp = "Camera3DFront_3",
					Source = "Transform3DOp.Translate.X",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input6 = InstanceInput {
					SourceOp = "Camera3DFront_3",
					Source = "Transform3DOp.Translate.Y",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input7 = InstanceInput {
					SourceOp = "Camera3DFront_3",
					Source = "Transform3DOp.Translate.Z",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input8 = InstanceInput {
					SourceOp = "CubeMap_3",
					Source = "Rotate.RotOrder",
				},
				Input9 = InstanceInput {
					SourceOp = "CubeMap_3",
					Source = "Rotate.X",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				Input10 = InstanceInput {
					SourceOp = "CubeMap_3",
					Source = "Rotate.Y",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				Input11 = InstanceInput {
					SourceOp = "CubeMap_3",
					Source = "Rotate.Z",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				}
			},
			Outputs = {
				MainOutput1 = InstanceOutput {
					SourceOp = "UVRenderer3D_3",
					Source = "Output",
				}
			},
			ViewInfo = GroupInfo { Pos = { 1156.15, 213.106 } },
			Tools = ordered() {
				UVRenderer3D_3 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 3840,
							Expression = "Height*2",
						},
						Height = Input { Value = 1920, },
						Depth = Input { Value = 1, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "Shape3DSphere_3",
							Source = "Output",
						},
						RendererType = Input { Value = FuID { "RendererOpenGLUV" }, },
						["RendererOpenGLUV.UVGutterSize"] = Input { Value = 0, },
						["RendererOpenGLUV.Texturing"] = Input { Value = 1, },
						["RendererOpenGLUV.TextureDepth"] = Input { Value = 0, },
					},
					ViewInfo = OperatorInfo { Pos = { 385, 340.15 } },
				},
				Shape3DSphere_3 = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 7, },
						["Transform3DOp.Rotate.Y"] = Input { Value = 270, },
						["Transform3DOp.ScaleLock"] = Input { Value = 0, },
						["Transform3DOp.Scale.X"] = Input { Value = -1000, },
						["Transform3DOp.Scale.Y"] = Input { Value = 1000, },
						["Transform3DOp.Scale.Z"] = Input { Value = 1000, },
						Shape = Input { Value = FuID { "SurfaceSphereInputs" }, },
						MaterialInput = Input {
							SourceOp = "CubeMap_3",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.MaterialID"] = Input { Value = 6, },
						["SurfaceSphereInputs.Radius"] = Input { Value = 500, },
						["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 8, }
					},
					ViewInfo = OperatorInfo { Pos = { 275, 340.15 } },
				},
				CubeMap_3 = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Orientation = Input { Value = 0, },
						Rotation = Input { Value = 1, },
						["Rotate.X"] = Input { Value = 90, },
						["FilterMode.Nest"] = Input { Value = 1, },
						["FilterMode.SW.LowQ"] = Input { Value = FuID { "Bilinear" }, },
						Left = Input {
							SourceOp = "Renderer3DLeft_3",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "Renderer3DRight_3",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "Renderer3DTop_3",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "Renderer3DBottom_3",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "Renderer3DFront_3",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "Renderer3DBack_3",
							Source = "Output",
						},
						MaterialID = Input { Value = 3, },
					},
					ViewInfo = OperatorInfo { Pos = { 165, 340.15 } },
				},
				Renderer3DBottom_3 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D_3.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D_3.Height*0.5",
						},
						Depth = Input {
							Value = 1,
							Expression = "UVRenderer3D_3.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_3",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DBottom_3" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_3.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_3.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 439.15 } },
				},
				Renderer3DTop_3 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D_3.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D_3.Height*0.5",
						},
						Depth = Input {
							Value = 1,
							Expression = "UVRenderer3D_3.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_3",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DTop_3" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_3.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_3.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 406.15 } },
				},
				Renderer3DRight_3 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D_3.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D_3.Height*0.5",
						},
						Depth = Input {
							Value = 1,
							Expression = "UVRenderer3D_3.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_3",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DRight_3" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_3.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_3.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 307.15 } },
				},
				Renderer3DFront_3 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D_3.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D_3.Height*0.5",
						},
						Depth = Input {
							Value = 1,
							Expression = "UVRenderer3D_3.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_3",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DFront_3" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.LightingEnabled"] = Input { Value = 1, },
						["RendererSoftware.ShadowsEnabled"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { 0, 274.15 } },
				},
				Renderer3DLeft_3 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D_3.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D_3.Height*0.5",
						},
						Depth = Input {
							Value = 1,
							Expression = "UVRenderer3D_3.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_3",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DLeft_3" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_3.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_3.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 373.15 } },
				},
				Renderer3DBack_3 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D_3.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D_3.Height*0.5",
						},
						Depth = Input {
							Value = 1,
							Expression = "UVRenderer3D_3.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_3",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DBack_3" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront_3.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_3.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_3.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 340.15 } },
				},
				CameraViewInput_3 = Merge3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						PassThroughLights = Input { Value = 1, },
						SceneInput1 = Input {
							SourceOp = "RightViewTransform3D",
							Source = "Output",
						},
						SceneInput2 = Input {
							SourceOp = "Camera3DFront_3",
							Source = "Output",
						},
						SceneInput3 = Input {
							SourceOp = "Camera3DRight_3",
							Source = "Output",
						},
						SceneInput5 = Input {
							SourceOp = "Camera3DLeft_3",
							Source = "Output",
						},
						SceneInput6 = Input {
							SourceOp = "Camera3DTop_3",
							Source = "Output",
						},
						SceneInput7 = Input {
							SourceOp = "Camera3DBottom_3",
							Source = "Output",
						},
						SceneInput4 = Input {
							SourceOp = "Camera3DBack_3",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -220, 274.15 } },
				},
				Camera3DRight_3 = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront_3.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = 90,
							Expression = "Camera3DFront_3.Transform3DOp.Rotate.Z+90",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 43.15 } },
				},
				Camera3DLeft_3 = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront_3.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = -90,
							Expression = "Camera3DFront_3.Transform3DOp.Rotate.Z-90.0",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 109.15 } },
				},
				Camera3DTop_3 = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Rotate.X+90", },
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Rotate.Z", },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 142.15 } },
				},
				Camera3DBottom_3 = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -180,
							Expression = "Camera3DFront_3.Transform3DOp.Rotate.X-90",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Rotate.Z", },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 175.15 } },
				},
				Camera3DBack_3 = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront_3.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront_3.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = 180,
							Expression = "Camera3DFront_3.Transform3DOp.Rotate.Z+180.0",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 76.15 } },
				},
				Camera3DFront_3 = Camera3D {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Rotate.X"] = Input { Value = -90, },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 10.15 } },
				}
			},
		},
		StereoSideBySideMerge = GroupOperator {
			CustomData = {
				HelpPage = "http://www.andrewhazelden.com/projects/kartavr/docs/macros-guide.html#StereoSideBySideMerge"
			},
			Inputs = ordered() {
				MainInput1 = InstanceInput {
					SourceOp = "InputScalingLeft_2",
					Source = "Input",
					Name = "Left",
				},
				MainInput2 = InstanceInput {
					SourceOp = "InputScalingRight_2",
					Source = "Input",
					Name = "Right",
				},
				Input1 = InstanceInput {
					SourceOp = "InputScalingLeft_2",
					Source = "Width",
					Name = "Input Width",
					MaxScale = 8192,
					Default = 2048,
				},
				Input2 = InstanceInput {
					SourceOp = "InputScalingLeft_2",
					Source = "Height",
					Name = "Input Height",
					MaxScale = 8192,
					Default = 1024,
				}
			},
			Outputs = {
				MainOutput1 = InstanceOutput {
					SourceOp = "OverUnderCrop_1",
					Source = "Output",
				}
			},
			ViewInfo = GroupInfo { Pos = { 1320, 280.5 } },
			Tools = ordered() {
				OverUnderCrop_1 = Crop {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						XSize = Input {
							Value = 2048,
							Expression = "InputScalingLeft_2.Width",
						},
						YSize = Input {
							Value = 1024,
							Expression = "InputScalingLeft_2.Height",
						},
						Input = Input {
							SourceOp = "ViewMerge_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 220, 109.15 } },
				},
				ViewMerge_1 = Merge {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Background = Input {
							SourceOp = "ViewTransformRight_1",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "ViewTransformLeft_1",
							Source = "Output",
						},
						PerformDepthMerge = Input { Value = 0, },
					},
					ViewInfo = OperatorInfo { Pos = { 110, 109.15 } },
				},
				ViewTransformRight_1 = Transform {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Center = Input { Value = { 1.5, 0.5 }, },
						Input = Input {
							SourceOp = "ScaleHalfHeightRight_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 109.15 } },
				},
				ViewTransformLeft_1 = Transform {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Input = Input {
							SourceOp = "ScaleHalfHeightLeft_1",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -1, 10.15 } },
				},
				ScaleHalfHeightLeft_1 = Scale {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						LockXY = Input { Value = 0, },
						XSize = Input { Value = 0.5, },
						PixelAspect = Input { Value = { 1, 1 }, },
						Input = Input {
							SourceOp = "InputScalingLeft_2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -109, 10.15 } },
				},
				ScaleHalfHeightRight_1 = Scale {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						LockXY = Input { Value = 0, },
						XSize = Input { Value = 0.5, },
						PixelAspect = Input { Value = { 1, 1 }, },
						Input = Input {
							SourceOp = "InputScalingRight_2",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -110, 109.15 } },
				},
				InputScalingLeft_2 = BetterResize {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Width = Input { Value = 2048, },
						Height = Input { Value = 1024, },
						PixelAspect = Input { Value = { 1, 1 }, },
						FilterMethod = Input { Value = 6, },
						Input = Input {
							SourceOp = "UVRenderer3D_4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -220, 10.15 } },
				},
				InputScalingRight_2 = BetterResize {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Width = Input {
							Value = 2048,
							Expression = "InputScalingLeft_2.Width",
						},
						Height = Input {
							Value = 1024,
							Expression = "InputScalingLeft_2.Height",
						},
						PixelAspect = Input { Value = { 1, 1 }, },
						FilterMethod = Input { Value = 6, },
						Input = Input {
							SourceOp = "UVRenderer3D_3",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -220, 109.15 } },
				}
			},
		},
		LeftViewTransform3D = Transform3D {
			NameSet = true,
			Inputs = {
				SceneInput = Input {
					SourceOp = "PipeRouter1",
					Source = "Output",
				},
				["Transform3DOp.Translate.Z"] = Input {
					Value = 0.3,
					Expression = "RightViewTransform3D.Transform3DOp.Translate.Z*-1",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 1045, 280.5 } },
		},
		RightViewTransform3D = Transform3D {
			NameSet = true,
			Inputs = {
				SceneInput = Input {
					SourceOp = "PipeRouter1",
					Source = "Output",
				},
				["Transform3DOp.Translate.Z"] = Input { Value = -0.3, },
			},
			ViewInfo = OperatorInfo { Pos = { 1045, 214.5 } },
		},
		Text1 = TextPlus {
			Inputs = {
				GlobalOut = Input { Value = 1, },
				Width = Input { Value = 3840, },
				Height = Input { Value = 3840, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Size = Input { Value = 0.191489361702128, },
				Font = Input { Value = "Open Sans", },
				StyledText = Input { Value = "Hello", },
				Style = Input { Value = "Bold", },
				ManualFontKerningPlacement = Input {
					Value = StyledText {
						Array = {
						},
						Value = ""
					},
				},
				ShadingGradient1 = Input {
					Value = Gradient {
						Colors = {
							[0] = { 0, 0, 0, 1 },
							[1] = { 1, 1, 1, 1 }
						}
					},
				},
			},
			ViewInfo = OperatorInfo { Pos = { 440, 148.5 } },
		},
		StereoAnaglyphHalfColorMerge1 = GroupOperator {
			Inputs = ordered() {
				MainInput1 = InstanceInput {
					SourceOp = "InputScalingLeft",
					Source = "Input",
					Name = "Left",
				},
				MainInput2 = InstanceInput {
					SourceOp = "InputScalingRight",
					Source = "Input",
					Name = "Right",
				},
				Input1 = InstanceInput {
					SourceOp = "InputScalingLeft",
					Source = "Width",
					Name = "Input Width",
					MaxScale = 8192,
					Default = 2048,
				},
				Input2 = InstanceInput {
					SourceOp = "InputScalingLeft",
					Source = "Height",
					Name = "Input Height",
					MaxScale = 8192,
					Default = 1024,
				},
				Input3 = InstanceInput {
					SourceOp = "HalfColorLeft",
					Source = "Saturation1",
					Name = "Saturation",
					Default = 0.5,
				},
				Input4 = InstanceInput {
					SourceOp = "SlideTransform",
					Source = "Edges",
					Default = 1,
				},
				Input5 = InstanceInput {
					SourceOp = "SlideTransform",
					Source = "Center",
					Name = "Convergence",
				},
				Input6 = InstanceInput {
					SourceOp = "SlideTransform",
					Source = "Size",
					Default = 1,
				},
				Input7 = InstanceInput {
					SourceOp = "SlideTransform",
					Source = "Angle",
					Default = 0,
				}
			},
			Outputs = {
				MainOutput1 = InstanceOutput {
					SourceOp = "AnaglyphHalfColorMerge",
					Source = "Output",
				}
			},
			ViewInfo = GroupInfo { Pos = { 1320, 214.5 } },
			Tools = ordered() {
				AnaglyphHalfColorMerge = ChannelBoolean {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						ToGreen = Input { Value = 6, },
						ToBlue = Input { Value = 7, },
						ToAlpha = Input { Value = 16, },
						Background = Input {
							SourceOp = "HalfColorRight",
							Source = "Output",
						},
						Foreground = Input {
							SourceOp = "HalfColorLeft",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 165, 109.15 } },
				},
				HalfColorRight = ColorCorrector {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						WheelSaturation1 = Input {
							Value = 0,
							Expression = "HalfColorLeft.Saturation1",
						},
						Saturation1 = Input { Expression = "HalfColorLeft.Saturation1", },
						ColorRanges = Input {
							Value = ColorCurves {
								Curves = {
									{
										Points = {
											{ 0, 1 },
											{ 0.4, 0.2 },
											{ 0.6, 0 },
											{ 1, 0 }
										}
									},
									{
										Points = {
											{ 0, 0 },
											{ 0.4, 0 },
											{ 0.6, 0.2 },
											{ 1, 1 }
										}
									}
								}
							},
						},
						HistogramIgnoreTransparent = Input { Value = 1, },
						Input = Input {
							SourceOp = "SlideTransform",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 55, 109.15 } },
				},
				SlideTransform = Transform {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Edges = Input { Value = 1, },
						FilterMethod = Input { Value = 6, },
						Input = Input {
							SourceOp = "InputScalingRight",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -55.707, 109.15 } },
				},
				HalfColorLeft = ColorCorrector {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						WheelSaturation1 = Input { Value = 0, },
						ColorRanges = Input {
							Value = ColorCurves {
								Curves = {
									{
										Points = {
											{ 0, 1 },
											{ 0.4, 0.2 },
											{ 0.6, 0 },
											{ 1, 0 }
										}
									},
									{
										Points = {
											{ 0, 0 },
											{ 0.4, 0 },
											{ 0.6, 0.2 },
											{ 1, 1 }
										}
									}
								}
							},
						},
						HistogramIgnoreTransparent = Input { Value = 1, },
						Input = Input {
							SourceOp = "InputScalingLeft",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -55, 10.15 } },
				},
				InputScalingLeft = BetterResize {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Width = Input { Value = 2048, },
						Height = Input { Value = 1024, },
						PixelAspect = Input { Value = { 1, 1 }, },
						FilterMethod = Input { Value = 6, },
						Input = Input {
							SourceOp = "UVRenderer3D_4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -165, 10.15 } },
				},
				InputScalingRight = BetterResize {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Width = Input {
							Value = 2048,
							Expression = "InputScalingLeft.Width",
						},
						Height = Input {
							Value = 1024,
							Expression = "InputScalingLeft.Height",
						},
						PixelAspect = Input { Value = { 1, 1 }, },
						FilterMethod = Input { Value = 6, },
						Input = Input {
							SourceOp = "UVRenderer3D_3",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -165, 109.15 } },
				}
			},
		},
		EquirectangularRenderer3D = GroupOperator {
			CustomData = {
				HelpPage = "http://www.andrewhazelden.com/projects/kartavr/docs/macros-guide.html#EquirectangularRenderer3D",
			},
			Inputs = ordered() {
				MainInput1 = InstanceInput {
					SourceOp = "CameraViewInput",
					Source = "SceneInput1",
				},
				Input1 = InstanceInput {
					SourceOp = "UVRenderer3D",
					Source = "Height",
					MaxScale = 8192,
					Default = 1920,
				},
				Input2 = InstanceInput {
					SourceOp = "UVRenderer3D",
					Source = "Depth",
					Default = 3,
				},
				Input3 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "RendererSoftware.LightingEnabled",
					Default = 1,
				},
				Input4 = InstanceInput {
					SourceOp = "Renderer3DFront",
					Source = "RendererSoftware.ShadowsEnabled",
					Default = 1,
				},
				Input5 = InstanceInput {
					SourceOp = "Camera3DFront",
					Source = "Transform3DOp.Translate.X",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input6 = InstanceInput {
					SourceOp = "Camera3DFront",
					Source = "Transform3DOp.Translate.Y",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input7 = InstanceInput {
					SourceOp = "Camera3DFront",
					Source = "Transform3DOp.Translate.Z",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input8 = InstanceInput {
					SourceOp = "CubeMap_2",
					Source = "Rotate.RotOrder",
				},
				Input9 = InstanceInput {
					SourceOp = "CubeMap_2",
					Source = "Rotate.X",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				Input10 = InstanceInput {
					SourceOp = "CubeMap_2",
					Source = "Rotate.Y",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				Input11 = InstanceInput {
					SourceOp = "CubeMap_2",
					Source = "Rotate.Z",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				}
			},
			Outputs = {
				MainOutput1 = InstanceOutput {
					SourceOp = "UVRenderer3D",
					Source = "Output",
				}
			},
			ViewInfo = GroupInfo { Pos = { 1320, 147.759 } },
			Tools = ordered() {
				UVRenderer3D = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 3840,
							Expression = "Height*2",
						},
						Height = Input { Value = 1920, },
						Depth = Input { Value = 1, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "Shape3DSphere_2",
							Source = "Output",
						},
						RendererType = Input { Value = FuID { "RendererOpenGLUV" }, },
						["RendererOpenGLUV.UVGutterSize"] = Input { Value = 0, },
						["RendererOpenGLUV.Texturing"] = Input { Value = 1, },
						["RendererOpenGLUV.TextureDepth"] = Input { Value = 0, },
					},
					ViewInfo = OperatorInfo { Pos = { 385, 340.15 } },
				},
				Shape3DSphere_2 = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 7, },
						["Transform3DOp.Rotate.Y"] = Input { Value = 270, },
						["Transform3DOp.ScaleLock"] = Input { Value = 0, },
						["Transform3DOp.Scale.X"] = Input { Value = -1000, },
						["Transform3DOp.Scale.Y"] = Input { Value = 1000, },
						["Transform3DOp.Scale.Z"] = Input { Value = 1000, },
						Shape = Input { Value = FuID { "SurfaceSphereInputs" }, },
						MaterialInput = Input {
							SourceOp = "CubeMap_2",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.MaterialID"] = Input { Value = 6, },
						["SurfaceSphereInputs.Radius"] = Input { Value = 500, },
						["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 8, }
					},
					ViewInfo = OperatorInfo { Pos = { 275, 340.15 } },
				},
				CubeMap_2 = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Orientation = Input { Value = 0, },
						Rotation = Input { Value = 1, },
						["Rotate.X"] = Input { Value = 90, },
						["FilterMode.Nest"] = Input { Value = 1, },
						["FilterMode.SW.LowQ"] = Input { Value = FuID { "Bilinear" }, },
						Left = Input {
							SourceOp = "Renderer3DLeft",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "Renderer3DRight",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "Renderer3DTop",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "Renderer3DBottom",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "Renderer3DFront",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "Renderer3DBack",
							Source = "Output",
						},
						MaterialID = Input { Value = 3, },
					},
					ViewInfo = OperatorInfo { Pos = { 165, 340.15 } },
				},
				Renderer3DBottom = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D.Height*0.5",
						},
						Depth = Input {
							Value = 1,
							Expression = "UVRenderer3D.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DBottom" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 439.15 } },
				},
				Renderer3DTop = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D.Height*0.5",
						},
						Depth = Input {
							Value = 1,
							Expression = "UVRenderer3D.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DTop" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 406.15 } },
				},
				Renderer3DRight = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D.Height*0.5",
						},
						Depth = Input {
							Value = 1,
							Expression = "UVRenderer3D.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DRight" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 307.15 } },
				},
				Renderer3DFront = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D.Height*0.5",
						},
						Depth = Input {
							Value = 1,
							Expression = "UVRenderer3D.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DFront" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.LightingEnabled"] = Input { Value = 1, },
						["RendererSoftware.ShadowsEnabled"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { 0, 274.15 } },
				},
				Renderer3DLeft = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D.Height*0.5",
						},
						Depth = Input {
							Value = 1,
							Expression = "UVRenderer3D.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DLeft" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 373.15 } },
				},
				Renderer3DBack = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D.Height*0.5",
						},
						Depth = Input {
							Value = 1,
							Expression = "UVRenderer3D.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DBack" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 340.15 } },
				},
				CameraViewInput = Merge3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						PassThroughLights = Input { Value = 1, },
						SceneInput1 = Input {
							SourceOp = "PipeRouter2",
							Source = "Output",
						},
						SceneInput2 = Input {
							SourceOp = "Camera3DFront",
							Source = "Output",
						},
						SceneInput3 = Input {
							SourceOp = "Camera3DRight",
							Source = "Output",
						},
						SceneInput5 = Input {
							SourceOp = "Camera3DLeft",
							Source = "Output",
						},
						SceneInput6 = Input {
							SourceOp = "Camera3DTop",
							Source = "Output",
						},
						SceneInput7 = Input {
							SourceOp = "Camera3DBottom",
							Source = "Output",
						},
						SceneInput4 = Input {
							SourceOp = "Camera3DBack",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -220, 274.15 } },
				},
				Camera3DRight = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = 90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.Z+90",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 43.15 } },
				},
				Camera3DLeft = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = -90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.Z-90.0",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 109.15 } },
				},
				Camera3DTop = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.X+90", },
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Z", },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 142.15 } },
				},
				Camera3DBottom = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -180,
							Expression = "Camera3DFront.Transform3DOp.Rotate.X-90",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Z", },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 175.15 } },
				},
				Camera3DBack = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = 180,
							Expression = "Camera3DFront.Transform3DOp.Rotate.Z+180.0",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 76.15 } },
				},
				Camera3DFront = Camera3D {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Rotate.X"] = Input { Value = -90, },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 10.15 } },
				}
			},
		},
		Saver1_1_1 = Saver {
			Inputs = {
				["QuickTimeMovies.Compression"] = Input { Value = FuID { "H.264_avc1" }, },
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "Temp:\\KartaVR\\text.0000.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				CreateDir = Input { Value = 1, },
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "UVRenderer3D",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 1485, 148.5 } },
		},
		Note1 = Note {
			Inputs = {
				Comments = Input { Value = "This example shows how to create text in Fusion that can be mapped onto a polygon image plane using Fusion's 3D system.\n\nAs a bonus a parallel stereo camera rig is created that allows you to render out equirectangular stereo imagery that can be viewed using the stereo side by side merge node, or the stereo anaglyph nodes in the composite.", }
			},
			ViewInfo = StickyNoteInfo {
				Pos = { 880, 49.5 },
				Flags = {
					Expanded = true
				},
				Size = { 560.498, 87.3662 }
			},
		},
		Saver1_1 = Saver {
			Inputs = {
				["QuickTimeMovies.Compression"] = Input { Value = FuID { "H.264_avc1" }, },
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "Temp:\\KartaVR\\stereo_text.0000.png",
						FormatID = "PNGFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				CreateDir = Input { Value = 1, },
				OutputFormat = Input { Value = FuID { "PNGFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "AnaglyphHalfColorMerge",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 1485, 214.5 } },
		},
		EquirectangularRenderer3D_2 = GroupOperator {
			CtrlWZoom = false,
			CustomData = {
				HelpPage = "http://www.andrewhazelden.com/projects/kartavr/docs/macros-guide.html#EquirectangularRenderer3D",
			},
			Inputs = ordered() {
				MainInput1 = InstanceInput {
					SourceOp = "CameraViewInput_4",
					Source = "SceneInput1",
				},
				Input1 = InstanceInput {
					SourceOp = "UVRenderer3D_4",
					Source = "Height",
					MaxScale = 8192,
					Default = 1920,
				},
				Input2 = InstanceInput {
					SourceOp = "UVRenderer3D_4",
					Source = "Depth",
					Default = 3,
				},
				Input3 = InstanceInput {
					SourceOp = "Renderer3DFront_4",
					Source = "RendererSoftware.LightingEnabled",
					Default = 1,
				},
				Input4 = InstanceInput {
					SourceOp = "Renderer3DFront_4",
					Source = "RendererSoftware.ShadowsEnabled",
					Default = 1,
				},
				Input5 = InstanceInput {
					SourceOp = "Camera3DFront_4",
					Source = "Transform3DOp.Translate.X",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input6 = InstanceInput {
					SourceOp = "Camera3DFront_4",
					Source = "Transform3DOp.Translate.Y",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input7 = InstanceInput {
					SourceOp = "Camera3DFront_4",
					Source = "Transform3DOp.Translate.Z",
					MinScale = -1000,
					MaxScale = 1000,
					Default = 0,
				},
				Input8 = InstanceInput {
					SourceOp = "CubeMap",
					Source = "Rotate.RotOrder",
				},
				Input9 = InstanceInput {
					SourceOp = "CubeMap",
					Source = "Rotate.X",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				Input10 = InstanceInput {
					SourceOp = "CubeMap",
					Source = "Rotate.Y",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				},
				Input11 = InstanceInput {
					SourceOp = "CubeMap",
					Source = "Rotate.Z",
					MinScale = -360,
					MaxScale = 360,
					Default = 0,
				}
			},
			Outputs = {
				MainOutput1 = InstanceOutput {
					SourceOp = "UVRenderer3D_4",
					Source = "Output",
				}
			},
			ViewInfo = GroupInfo { Pos = { 1155.41, 282.759 } },
			Tools = ordered() {
				UVRenderer3D_4 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 3840,
							Expression = "Height*2",
						},
						Height = Input { Value = 1920, },
						Depth = Input { Value = 1, },
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "Shape3DSphere",
							Source = "Output",
						},
						RendererType = Input { Value = FuID { "RendererOpenGLUV" }, },
						["RendererOpenGLUV.UVGutterSize"] = Input { Value = 0, },
						["RendererOpenGLUV.Texturing"] = Input { Value = 1, },
						["RendererOpenGLUV.TextureDepth"] = Input { Value = 0, },
					},
					ViewInfo = OperatorInfo { Pos = { 385, 340.15 } },
				},
				Shape3DSphere = Shape3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 7, },
						["Transform3DOp.Rotate.Y"] = Input { Value = 270, },
						["Transform3DOp.ScaleLock"] = Input { Value = 0, },
						["Transform3DOp.Scale.X"] = Input { Value = -1000, },
						["Transform3DOp.Scale.Y"] = Input { Value = 1000, },
						["Transform3DOp.Scale.Z"] = Input { Value = 1000, },
						Shape = Input { Value = FuID { "SurfaceSphereInputs" }, },
						MaterialInput = Input {
							SourceOp = "CubeMap",
							Source = "MaterialOutput",
						},
						["MtlStdInputs.MaterialID"] = Input { Value = 6, },
						["SurfaceSphereInputs.Radius"] = Input { Value = 500, },
						["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 256, },
						["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 256, },
						["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 8, }
					},
					ViewInfo = OperatorInfo { Pos = { 275, 340.15 } },
				},
				CubeMap = CubeMap {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						Orientation = Input { Value = 0, },
						Rotation = Input { Value = 1, },
						["Rotate.X"] = Input { Value = 90, },
						["FilterMode.Nest"] = Input { Value = 1, },
						["FilterMode.SW.LowQ"] = Input { Value = FuID { "Bilinear" }, },
						Left = Input {
							SourceOp = "Renderer3DLeft_4",
							Source = "Output",
						},
						Right = Input {
							SourceOp = "Renderer3DRight_4",
							Source = "Output",
						},
						Up = Input {
							SourceOp = "Renderer3DTop_4",
							Source = "Output",
						},
						Down = Input {
							SourceOp = "Renderer3DBottom_4",
							Source = "Output",
						},
						Front = Input {
							SourceOp = "Renderer3DFront_4",
							Source = "Output",
						},
						Back = Input {
							SourceOp = "Renderer3DBack_4",
							Source = "Output",
						},
						MaterialID = Input { Value = 3, },
					},
					ViewInfo = OperatorInfo { Pos = { 165, 340.15 } },
				},
				Renderer3DBottom_4 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D_4.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D_4.Height*0.5",
						},
						Depth = Input {
							Value = 3,
							Expression = "UVRenderer3D_4.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_4",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DBottom_4" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_4.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_4.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 439.15 } },
				},
				Renderer3DTop_4 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D_4.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D_4.Height*0.5",
						},
						Depth = Input {
							Value = 3,
							Expression = "UVRenderer3D_4.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_4",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DTop_4" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_4.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_4.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 406.15 } },
				},
				Renderer3DRight_4 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D_4.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D_4.Height*0.5",
						},
						Depth = Input {
							Value = 3,
							Expression = "UVRenderer3D_4.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_4",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DRight_4" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_4.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_4.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 307.15 } },
				},
				Renderer3DFront_4 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D_4.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D_4.Height*0.5",
						},
						Depth = Input {
							Value = 3,
							Expression = "UVRenderer3D_4.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_4",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DFront_4" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.LightingEnabled"] = Input { Value = 1, },
						["RendererSoftware.ShadowsEnabled"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { 0, 274.15 } },
				},
				Renderer3DLeft_4 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D_4.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D_4.Height*0.5",
						},
						Depth = Input {
							Value = 3,
							Expression = "UVRenderer3D_4.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_4",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DLeft_4" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_4.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_4.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 373.15 } },
				},
				Renderer3DBack_4 = Renderer3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						GlobalOut = Input { Value = 1, },
						Width = Input {
							Value = 960,
							Expression = "UVRenderer3D_4.Height*0.5",
						},
						Height = Input {
							Value = 960,
							Expression = "UVRenderer3D_4.Height*0.5",
						},
						Depth = Input {
							Value = 3,
							Expression = "UVRenderer3D_4.Depth",
						},
						["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
						SceneInput = Input {
							SourceOp = "CameraViewInput_4",
							Source = "Output",
						},
						CameraSelector = Input { Value = FuID { "Camera3DBack_4" }, },
						["RendererSoftware.Channels.Nest"] = Input { Value = 1, },
						["RendererSoftware.Channels.RGBA"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.RGBA", },
						["RendererSoftware.Channels.Z"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Z", },
						["RendererSoftware.Channels.Coverage"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Coverage", },
						["RendererSoftware.Channels.Normal"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Normal", },
						["RendererSoftware.Channels.TexCoord0"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.TexCoord0", },
						["RendererSoftware.Channels.ObjectID"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.ObjectID", },
						["RendererSoftware.Channels.MaterialID"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.MaterialID", },
						["RendererSoftware.Channels.WorldCoord"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.WorldCoord", },
						["RendererSoftware.Channels.Vector"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.Vector", },
						["RendererSoftware.Channels.BackVector"] = Input { Expression = "Renderer3DFront_4.RendererSoftware.Channels.BackVector", },
						["RendererSoftware.Lighting"] = Input { Value = 0, },
						["RendererSoftware.LightingEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_4.RendererSoftware.LightingEnabled",
						},
						["RendererSoftware.ShadowsEnabled"] = Input {
							Value = 1,
							Expression = "Renderer3DFront_4.RendererSoftware.ShadowsEnabled",
						},
					},
					ViewInfo = OperatorInfo { Pos = { 0, 340.15 } },
				},
				CameraViewInput_4 = Merge3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						PassThroughLights = Input { Value = 1, },
						SceneInput1 = Input {
							SourceOp = "LeftViewTransform3D",
							Source = "Output",
						},
						SceneInput2 = Input {
							SourceOp = "Camera3DFront_4",
							Source = "Output",
						},
						SceneInput3 = Input {
							SourceOp = "Camera3DRight_4",
							Source = "Output",
						},
						SceneInput5 = Input {
							SourceOp = "Camera3DLeft_4",
							Source = "Output",
						},
						SceneInput6 = Input {
							SourceOp = "Camera3DTop_4",
							Source = "Output",
						},
						SceneInput7 = Input {
							SourceOp = "Camera3DBottom_4",
							Source = "Output",
						},
						SceneInput4 = Input {
							SourceOp = "Camera3DBack_4",
							Source = "Output",
						},
					},
					ViewInfo = OperatorInfo { Pos = { -220, 274.15 } },
				},
				Camera3DRight_4 = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront_4.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = 90,
							Expression = "Camera3DFront_4.Transform3DOp.Rotate.Z+90",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 43.15 } },
				},
				Camera3DLeft_4 = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront_4.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = -90,
							Expression = "Camera3DFront_4.Transform3DOp.Rotate.Z-90.0",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 109.15 } },
				},
				Camera3DTop_4 = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Rotate.X+90", },
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Rotate.Z", },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 142.15 } },
				},
				Camera3DBottom_4 = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -180,
							Expression = "Camera3DFront_4.Transform3DOp.Rotate.X-90",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Rotate.Z", },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 175.15 } },
				},
				Camera3DBack_4 = Camera3D {
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Translate.X"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Translate.X", },
						["Transform3DOp.Translate.Y"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Translate.Y", },
						["Transform3DOp.Translate.Z"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Translate.Z", },
						["Transform3DOp.Rotate.X"] = Input {
							Value = -90,
							Expression = "Camera3DFront_4.Transform3DOp.Rotate.X",
						},
						["Transform3DOp.Rotate.Y"] = Input { Expression = "Camera3DFront_4.Transform3DOp.Rotate.Y", },
						["Transform3DOp.Rotate.Z"] = Input {
							Value = 180,
							Expression = "Camera3DFront_4.Transform3DOp.Rotate.Z+180.0",
						},
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 76.15 } },
				},
				Camera3DFront_4 = Camera3D {
					CtrlWZoom = false,
					CtrlWShown = false,
					NameSet = true,
					Inputs = {
						["Transform3DOp.Rotate.X"] = Input { Value = -90, },
						AoV = Input { Value = 90, },
						FLength = Input { Value = 12.7, },
						["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
						FilmBack = Input { Value = 1, },
						FilmGate = Input { Value = FuID { "User" }, },
						ApertureW = Input { Value = 1, },
						ApertureH = Input { Value = 1, },
						["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 1, },
						["MtlStdInputs.MaterialID"] = Input { Value = 1, },
					},
					ViewInfo = OperatorInfo { Pos = { -385, 10.15 } },
				}
			},
		},
		PipeRouter1 = PipeRouter {
			Inputs = {
				Input = Input {
					SourceOp = "Merge3D1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 935, 214.5 } },
		},
		ImagePlane = Shape3D {
			NameSet = true,
			Inputs = {
				["SurfaceSphereInputs.Lighting.Nest"] = Input { Value = 1, },
				["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 60, },
				["SurfaceSphereInputs.Radius"] = Input { Value = 800, },
				["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 5, },
				["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 60, },
				["Transform3DOp.Translate.X"] = Input { Value = 15, },
				["Transform3DOp.Rotate.Y"] = Input { Value = -90, },
				["Transform3DOp.ScaleLock"] = Input { Value = 0, },
				["Transform3DOp.Scale.X"] = Input { Value = 40, },
				["Transform3DOp.Scale.Y"] = Input { Value = 40, },
				["Transform3DOp.Scale.Z"] = Input { Value = 40, },
				MaterialInput = Input {
					SourceOp = "WhiteMatteCookTorrance_1",
					Source = "MaterialOutput",
				},
				["MtlStdInputs.Diffuse.Color.Red"] = Input { Value = 0.141728395061728, },
				["MtlStdInputs.Diffuse.Color.Green"] = Input { Value = 0.262716049382716, },
				["MtlStdInputs.Diffuse.Color.Blue"] = Input { Value = 0.373333333333333, },
				["MtlStdInputs.MaterialID"] = Input { Value = 4, },
				["SurfacePlaneInputs.Width"] = Input { Value = 2, },
				["SurfacePlaneInputs.Visibility.Nest"] = Input { Value = 1, },
				["SurfacePlaneInputs.Lighting.Nest"] = Input { Value = 1, },
				["SurfacePlaneInputs.Lighting.IsAffectedByLights"] = Input { Value = 0, },
				["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 2, }
			},
			ViewInfo = OperatorInfo { Pos = { 660, 148.5 } },
		},
		Merge3D1 = Merge3D {
			Inputs = {
				SceneInput1 = Input {
					SourceOp = "Transform3D1",
					Source = "Output",
				},
				SceneInput2 = Input {
					SourceOp = "Shape3D",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 770, 214.5 } },
		},
		Shape3D = Shape3D {
			NameSet = true,
			Inputs = {
				["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 2, },
				["SurfaceTorusInputs.ObjectID.ObjectID"] = Input { Value = 6, },
				["SurfaceIcoInputs.ObjectID.ObjectID"] = Input { Value = 7, },
				["SurfaceCylinderInputs.ObjectID.ObjectID"] = Input { Value = 5, },
				["SurfaceCubeInputs.ObjectID.ObjectID"] = Input { Value = 4, },
				["Transform3DOp.Scale.X"] = Input { Value = 100, },
				Shape = Input { Value = FuID { "SurfaceSphereInputs" }, },
				MaterialInput = Input {
					SourceOp = "SphereMap",
					Source = "MaterialOutput",
				},
				["MtlStdInputs.Diffuse.Color.Red"] = Input { Value = 0.596899224806202, },
				["MtlStdInputs.Diffuse.Color.Green"] = Input { Value = 0.364341085271318, },
				["MtlStdInputs.Diffuse.Color.Blue"] = Input { Value = 0.65891472868217, },
				["MtlStdInputs.ReceivesLighting"] = Input { Value = 0, },
				["MtlStdInputs.ReceivesShadows"] = Input { Value = 0, },
				["MtlStdInputs.MaterialIDNest"] = Input { Value = 1, },
				["MtlStdInputs.MaterialID"] = Input { Value = 2, },
				["SurfaceSphereInputs.SubdivisionLevelBase"] = Input { Value = 72, },
				["SurfaceSphereInputs.SubdivisionLevelHeight"] = Input { Value = 36, },
				["SurfaceSphereInputs.Visibility.Nest"] = Input { Value = 1, },
				["SurfaceSphereInputs.Visibility.CullFrontFace"] = Input { Value = 1, },
				["SurfaceSphereInputs.Lighting.Nest"] = Input { Value = 1, },
				["SurfaceSphereInputs.Lighting.IsAffectedByLights"] = Input { Value = 0, },
				["SurfaceSphereInputs.Matte.Nest"] = Input { Value = 1, },
				["SurfaceSphereInputs.Controls.Normals.Scale"] = Input { Value = 6.93, },
				["SurfaceSphereInputs.ObjectID.ObjectID"] = Input { Value = 3, }
			},
			ViewInfo = OperatorInfo { Pos = { 660, 214.5 } },
		},
		SphereMap = SphereMap {
			NameSet = true,
			Inputs = {
				Rotation = Input { Value = 1, },
				["Rotate.RotOrder"] = Input { Value = FuID { "YXZ" }, },
				["Rotate.Y"] = Input { Value = -90, },
				["FilterMode.Nest"] = Input { Value = 1, },
				Image = Input {
					SourceOp = "ColorCorrector1",
					Source = "Output",
				},
				MaterialID = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 550, 214.5 } },
		},
		ColorCorrector1 = ColorCorrector {
			Inputs = {
				WheelSaturation1 = Input { Value = 0.280851063829787, },
				WheelTintAngle1 = Input { Value = -0.381362805673996, },
				WheelTintLength1 = Input { Value = 1, },
				ColorRanges = Input {
					Value = ColorCurves {
						Curves = {
							{
								Points = {
									{ 0, 1 },
									{ 0.4, 0.2 },
									{ 0.6, 0 },
									{ 1, 0 }
								}
							},
							{
								Points = {
									{ 0, 0 },
									{ 0.4, 0 },
									{ 0.6, 0.2 },
									{ 1, 1 }
								}
							}
						}
					},
				},
				HistogramIgnoreTransparent = Input { Value = 1, },
				Input = Input {
					SourceOp = "Loader1_1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 440, 214.5 } },
		},
		PipeRouter2 = PipeRouter {
			Inputs = {
				Input = Input {
					SourceOp = "PipeRouter1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 990, 148.5 } },
		},
		WhiteMatteCookTorrance_1 = MtlCookTorrance {
			NameSet = true,
			Inputs = {
				["Diffuse.Color.Material"] = Input {
					SourceOp = "Text1",
					Source = "Output",
				},
				["Specular.Nest"] = Input { Value = 1, },
				["Specular.Intensity"] = Input { Value = 0, },
				["Specular.DoFresnel"] = Input { Value = 0, },
				ReceivesLighting = Input { Value = 0, },
				ReceivesShadows = Input { Value = 0, },
				MaterialID = Input { Value = 11, },
			},
			ViewInfo = OperatorInfo { Pos = { 550, 148.5 } },
		},
		Transform3D1 = Transform3D {
			Inputs = {
				SceneInput = Input {
					SourceOp = "ImagePlane",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 770, 148.5 } },
		}
	},
	Views = {
		{
			FrameTypeID = "ChildFrame",
			Mode = 3,
			LayoutPreset = 0,
			Left = 0,
			Top = 27,
			Width = 2785,
			Height = 1282,
			Views = ordered() {
				Main = MultiView {
					Active = "Flow",
					ViewList = ordered() {
						Flow = "FlowView",
						Console = "ConsoleView",
						Timeline = "TimelineView",
						Spline = "SplineEditorView",
						Info = "InfoView",
						Chat = "ChatView"
					},
					Flow = FlowView {
						Flags = {
							AutoHideNavigator = true,
							AutoSnap = true,
							RemoveRouters = true
						},
						NavigatorSize = { 200, 140 },
						Direction = "Horizontal",
						PipeStyle = "Direct",
						Scale = 1.34954,
						Offset = { 36.1106, 104.039 }
					},
					Timeline = TimelineView {
						TreeControlState = {
						},
						DisplayMode = "All Tools",
						ShowCurrentTimeTools = false,
						Filter = "Show All",
						ShowSelectedTools = false,
						ShowAnimatedToolsOnly = false,
						ShowEditBoxes = false,
						KeyFrameView = {
							Position = { Left = 150, Bottom = 343 },
							ScaleX = 0.00214424951267057,
							OffsetX = -0.0514619883040936,
							OffsetY = 0,
							AutoScaling = "scroll",
							AutoSnapTo = "frame",
							AutoSnapToGuidelines = false,
							GuidelinesGrabEnabled = true,
							GuidelinesSnapTo = "frame"
						},
						Spreadsheet = { LeftPos = 150, Visible = false }
					},
					Spline = SplineEditorView {
						LeftPos = 256,
						ScaleX = 0.2,
						ScaleY = 0.00338983050847458,
						OffsetX = -4,
						OffsetY = 0,
						AutoScaling = "scroll",
						AutoSnapTo = "frame",
						AutoSnapToGuidelines = false,
						GuidelinesSnapTo = "frame",
						ShowKeyMarkers = false,
						IndependentHandles = false,
						ShowNonSplineModifiers = false,
						GuidelinesGrabEnabled = true,
						ShowOneToolOnly = false,
						ShowSelectedTools = false,
						ShowAllInputs = false,
						Filter = "Show All"
					},
				},
				Controls = MultiView {
					Active = "Tools",
					ViewList = ordered() {
						Tools = "ControlView",
						Modifiers = "ModifierView"
					},
				},
				Left = "PreviewContainer",
				Right = "PreviewContainer",
				Transport = "TransportView",
				Time = "TimeView"
			},
			Layout = {
				Columns = 2,
				RatioX = 1,
				RatioY = 1,
				{
					Rows = 3,
					RatioX = 0.876258992805755,
					RatioY = 0.01015625,
					{
						Columns = 2,
						RatioX = 1,
						RatioY = 0.444270015698587,
						{ ID = "Left", RatioX = 1, RatioY = 94.3339222614841, Pop = true },
						{ ID = "Right", RatioX = -2, Pop = true },
						Pop = true
					},
					{ ID = "Main", RatioY = 0.510204081632653, Pop = true },
					{ ID = "Time", SnapY = 56, Flat = true }
				},
				{
					Rows = 2,
					PixelX = 342,
					{ ID = "Controls", RatioX = 1, RatioY = 1 },
					{ ID = "Transport", FixedY = -2 }
				}
			}
		}
	},
	Prefs = {
		Comp = {
			Interactive = {
				Proxy = {
					Scale = 5,
				},
			},
			Memory = {
				FramesAtOnce = 1,
			},
			Views = {
				Right = {
					Viewer = {
						ScaleMode = 1
					},
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0
						}
					},
				},
				Left = {
					Viewer = {
						ScaleMode = 1
					},
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0
						}
					},
					MaterialViewer = {
						Camera = {
							Rotation = {
								Y = -20,
								X = 15,
								Z = 0
							}
						}
					},
					View3D = {
						Options = {
							Lighting = false
						},
						CamFront = {
							Rotation = {
								Y = 0,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamLeft = {
							Rotation = {
								Y = 90,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamRight = {
							Rotation = {
								Y = -90,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamTop = {
							Rotation = {
								Y = 0,
								X = 90,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamPersp = {
							Rotation = {
								Y = 451.200012207031,
								X = 27.1999988555908,
								Z = 0
							},
							Scale = 0.0843968614935875,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CameraName = "Perspective"
					},
				},
				View1 = {
					PrevCtrlInactiveColor = 0,
					PickW = 0,
					PickH = 0,
					PrevCtrlActiveColor = 0,
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							NearZ = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							FitMarginY = 0
						}
					}
				},
			},
			FrameFormat = {
				Name = "4K Pano",
				Width = 3840,
				Height = 1920,
				Rate = 23.98,
				GuideRatio = 1,
			},
			LastFile = "",
			Unsorted = {
				GlobalEnd = 1
			},
			Paths = {
			},
			QuickTime = {
			},
		}
	}
}

 