Composition {
	CurrentTime = 0,
	RenderRange = { 0, 1000 },
	GlobalRange = { 0, 1000 },
	CurrentID = 2038,
	PlaybackUpdateMode = 0,
	Version = "Fusion 10 Beta 1 build 13",
	SavedOutputs = 1,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	AutoRenderRange = true,
	Resumable = true,
	OutputClips = {
		"Previews:/VCS/Cowgrammetry-Fusion.0000.exr",
		"Previews:/VCS/Spherical-Cowgrammetry-Fusion.0000.exr"
	},
	Tools = {
		Loader1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "Comp:/Media/BarnObj/barn.jpg",
					FormatID = "JpegFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { -935, -478.5 } },
		},
		Loader2 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "Comp:/Media/TobiasFullCharacterOBJ/tobias_character.jpg",
					FormatID = "JpegFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			CtrlWZoom = false,
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { -935, 181.5 } },
		},
		Loader1_1 = Loader {
			Clips = {
				Clip {
					ID = "Clip1",
					Filename = "Comp:/Media/CowOBJ/cow.jpg",
					FormatID = "JpegFormat",
					StartFrame = -1,
					LengthSetManually = true,
					TrimIn = 0,
					TrimOut = 0,
					ExtendFirst = 0,
					ExtendLast = 0,
					Loop = 0,
					AspectMode = 0,
					Depth = 0,
					TimeCode = 0,
					GlobalStart = 0,
					GlobalEnd = 0
				}
			},
			Inputs = {
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
			},
			ViewInfo = OperatorInfo { Pos = { -935, -115.5 } },
		},
		pixel_147_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_82_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1430, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_2 = PipeRouter {
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { -330, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_353_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_341_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1265, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_342 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_396",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1595, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_19 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_66",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1650, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_353 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_341",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -605, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_282 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_311",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 110, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_81 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_430",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -55, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_302 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_258",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1045, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_81_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_430_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 275, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_82 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_37",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -440, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_322 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_359",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -55, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_349 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_302",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1045, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_10 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_47",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -715, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_253_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_217_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 495, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_147 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_82",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -440, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		CowMerge3D = Merge3D {
			CtrlWZoom = false,
			NameSet = true,
			Inputs = {
				SceneInput1 = Input {
					SourceOp = "PipeRouter1",
					Source = "Output",
				},
				SceneInput2 = Input {
					SourceOp = "CowShiftTransform3D",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 220, -115.5 } },
		},
		LinearOCIOColorspace = OCIOColorSpace {
			NameSet = true,
			Inputs = {
				SourceSpace = Input { Value = FuID { "sRGB" }, },
				OutputSpace = Input { Value = FuID { "linear" }, },
				Look = Input { Value = FuID { "None" }, },
				Input = Input {
					SourceOp = "Loader1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -825, -478.5 } },
		},
		pixel_20 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_126",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1265, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_93 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_152",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1705, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_283 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_317",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1265, -1369.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_310_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_253_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 495, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_50 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_427",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 165, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_413 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_356",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -495, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_269 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_225",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -165, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_182 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_257",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1925, -1402.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_385 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_41",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -330, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_417 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_43",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1375, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_46 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_423",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1925, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_419 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_411",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -165, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_289 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_244",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -935, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_141 = PipeRouter {
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { -330, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_46_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_423_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1595, -1237.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_121 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_75",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1045, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_279 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_327",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1375, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_396 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_19",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1650, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		CowCameraMerge3D = Merge3D {
			NameSet = true,
			Inputs = {
				SceneInput1 = Input {
					SourceOp = "CowCamera3D",
					Source = "Output",
				},
				SceneInput2 = Input {
					SourceOp = "CowTransform3D",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -275, -115.5 } },
		},
		TobiasMerge3D = Merge3D {
			NameSet = true,
			Inputs = {
				SceneInput1 = Input {
					SourceOp = "CowMerge3D",
					Source = "Output",
				},
				SceneInput2 = Input {
					SourceOp = "TobiasShiftTransform3D",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 220, 181.5 } },
		},
		pixel_53 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_101",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1045, -1237.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_275 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_187",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1595, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_392 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_310",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 165, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_181 = PipeRouter {
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { -1045, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_188 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_189",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1485, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		TobiasShiftTransform3D = Transform3D {
			NameSet = true,
			Inputs = {
				SceneInput = Input {
					SourceOp = "TobiasCameraMerge3D",
					Source = "Output",
				},
				["Transform3DOp.Translate.X"] = Input { Value = 39.5656026272347, },
				["Transform3DOp.Translate.Z"] = Input { Value = 2.99038984352434, },
				["Transform3DOp.Rotate.Y"] = Input { Value = -136.6, },
			},
			ViewInfo = OperatorInfo { Pos = { 55, 181.5 } },
		},
		pixel_167 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_96",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 605, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_89 = PipeRouter {
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { -1265, -1204.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		SphericalCowgrammetryRenderer3D = Renderer3D {
			CtrlWZoom = false,
			NameSet = true,
			CustomData = {
				ToolVersion = 2
			},
			Inputs = {
				Width = Input { Value = 1920, },
				Height = Input { Value = 1920, },
				Depth = Input { Value = 3, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				SceneInput = Input {
					SourceOp = "PipeRouter2",
					Source = "Output",
				},
				CameraSelector = Input { Value = FuID { "CowgrammetrySphericalCamera" }, },
				RendererType = Input { Value = FuID { "RendererOpenGL" }, },
				["RendererOpenGL.Channels.Nest"] = Input { Value = 1, },
				["RendererOpenGL.Channels.Z"] = Input { Value = 1, },
				["RendererOpenGL.Channels.Normal"] = Input { Value = 1, },
				["RendererOpenGL.Channels.TexCoord0"] = Input { Value = 1, },
				["RendererOpenGL.Channels.WorldCoord"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 605, 82.5 } },
		},
		pixel_157_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_97_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 495, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_204 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_283",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1210, -1402.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		CowCamera3D = Camera3D {
			NameSet = true,
			Inputs = {
				["Transform3DOp.Translate.X"] = Input { Value = -16.909740359585, },
				["Transform3DOp.Translate.Y"] = Input { Value = 4.56141967949451, },
				["Transform3DOp.Translate.Z"] = Input { Value = -11.7521461803209, },
				["Transform3DOp.Rotate.X"] = Input { Value = 172.288662638515, },
				["Transform3DOp.Rotate.Y"] = Input { Value = -51.1444093747996, },
				["Transform3DOp.Rotate.Z"] = Input { Value = 179.53416986065, },
				FLength = Input { Value = 14.3404285604962, },
				["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
				FilmGate = Input { Value = FuID { "BMD_URSA_4K_16x9" }, },
				ApertureW = Input { Value = 0.831496062992126, },
				ApertureH = Input { Value = 0.467716535433071, },
				["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 2, },
				["MtlStdInputs.MaterialID"] = Input { Value = 3, },
			},
			ViewInfo = OperatorInfo { Pos = { -275, -49.5 } },
		},
		pixel_192_1 = PipeRouter {
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { 1265, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_39 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_379",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -165, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		BarnShiftTransform3D1 = Transform3D {
			NameSet = true,
			Inputs = {
				SceneInput = Input {
					SourceOp = "BarnCameraMerge3D",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 55, -478.5 } },
		},
		pixel_356_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_353_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1320, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		BarnTex2D = Texture2DOperator {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "LinearOCIOColorspace",
					Source = "Output",
				},
				WrapMode = Input { Value = FuID { "Wrap" }, },
				MaterialID = Input { Value = 2, },
			},
			ViewInfo = OperatorInfo { Pos = { -715, -478.5 } },
		},
		pixel_150 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_98",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1870, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_4 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_412",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -825, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_431_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_76_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1265, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_416 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_53",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1100, -1270.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		PipeRouter1 = PipeRouter {
			Inputs = {
				Input = Input {
					SourceOp = "BarnShiftTransform3D1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 220, -478.5 } },
		},
		CowgrammetryRenderer3D_1 = Renderer3D {
			NameSet = true,
			CustomData = {
				ToolVersion = 2
			},
			Inputs = {
				Width = Input { Value = 3840, },
				Height = Input { Value = 2160, },
				Depth = Input { Value = 3, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				SceneInput = Input {
					SourceOp = "PipeRouter2",
					Source = "Output",
				},
				CameraSelector = Input { Value = FuID { "CowgrammetryCamera3D" }, },
				RendererType = Input { Value = FuID { "RendererOpenGL" }, },
				["RendererOpenGL.Channels.Nest"] = Input { Value = 1, },
				["RendererOpenGL.Channels.Z"] = Input { Value = 1, },
				["RendererOpenGL.Channels.Normal"] = Input { Value = 1, },
				["RendererOpenGL.Channels.TexCoord0"] = Input { Value = 1, },
				["RendererOpenGL.Channels.WorldCoord"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 605, 280.5 } },
		},
		pixel_76 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_56",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -605, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_375 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_417",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1375, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_411 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_415",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -220, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_240_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_185_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1375, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_126 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_25",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1210, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_435 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_150",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1815, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_433 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_153",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 715, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_331 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_271",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1045, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_211_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_214_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1485, -1402.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_207 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_245",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1100, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_268 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_328",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -330, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_8 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_364",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 605, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_350 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_402",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1265, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_14 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_390",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1045, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_298 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_342",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1540, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_101 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_118",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1045, -1204.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		BarnReplaceNormals3D = ReplaceNormals3D {
			NameSet = true,
			Inputs = {
				SceneInput = Input {
					SourceOp = "BarnMesh3D",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -495, -478.5 } },
		},
		pixel_97_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_50_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 495, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_373 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_383",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 770, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		TobiasTransform3D = Transform3D {
			NameSet = true,
			Inputs = {
				SceneInput = Input {
					SourceOp = "TobiasReplaceNormals3D",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -385, 181.5 } },
		},
		pixel_73 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_129",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1375, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_189 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_279",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1430, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_403 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_26",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1925, -1270.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_301 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_347",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1760, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		Saver1_1 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "Previews:/VCS/Cowgrammetry-Fusion.0000.exr",
						FormatID = "OpenEXRFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				CreateDir = Input { Value = 1, },
				OutputFormat = Input { Value = FuID { "OpenEXRFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "CowgrammetryRenderer3D_1",
					Source = "Output",
				},
				["OpenEXRFormat.Depth"] = Input { Value = 1, },
				["OpenEXRFormat.Compression"] = Input { Value = 8, },
				["OpenEXRFormat.Channels"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 825, 280.5 } },
		},
		pixel_359 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_12",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -55, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_273 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_246",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1045, -1369.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_48 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_8",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 605, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_21 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_401",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1045, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_328 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_385",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -330, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_12_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_55_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 275, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_85 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_39",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -165, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_75 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_51",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1045, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_245 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_208",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 990, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_354_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_316_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1375, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_431 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_76",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -605, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_50_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_427_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 495, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		CowgrammetryCamera3D = Camera3D {
			NameSet = true,
			Inputs = {
				["Transform3DOp.Translate.X"] = Input { Value = -16.1289077278427, },
				["Transform3DOp.Translate.Y"] = Input { Value = 9.8667243549161, },
				["Transform3DOp.Translate.Z"] = Input { Value = 25.0917686477079, },
				["Transform3DOp.Rotate.X"] = Input { Value = -6.43709264602512, },
				["Transform3DOp.Rotate.Y"] = Input { Value = -52.7886756644584, },
				["Transform3DOp.Rotate.Z"] = Input { Value = 1.06001100130379, },
				FLength = Input { Value = 14.3404285604962, },
				["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
				FilmGate = Input { Value = FuID { "BMD_URSA_4K_16x9" }, },
				ApertureW = Input { Value = 0.831496062992126, },
				ApertureH = Input { Value = 0.467716535433071, },
				["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 2, },
				["MtlStdInputs.MaterialID"] = Input { Value = 3, },
			},
			ViewInfo = OperatorInfo { Pos = { 385, 280.5 } },
		},
		pixel_429 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_135",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -825, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_56_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_421_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1265, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_118 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_117",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1100, -1171.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_169 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_255",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1540, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_254 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_301",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1760, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_191 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_207",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1155, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_70 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_24",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1760, -1204.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		TobiasMesh3D = SurfaceFBXMesh {
			NameSet = true,
			CustomData = {
				NumMtlSlots = 1
			},
			Inputs = {
				["Transform3DOp.Scale.X"] = Input { Value = 0.1, },
				ImportFile = Input { Value = "Comp:/Media/TobiasFullCharacterOBJ/tobias_character.obj", },
				ObjName = Input { Value = "tobias_character", },
				TransformToWorld = Input { Value = 0, },
				EnableAxisConversion = Input { Value = 1, },
				EnableUnitConversion = Input { Value = 1, },
				["Lighting.Nest"] = Input { Value = 1, },
				["Lighting.IsAffectedByLights"] = Input { Value = 0, },
				["Lighting.IsShadowReceiver"] = Input { Value = 0, },
				["ObjectID.ObjectID"] = Input { Value = 2, },
				["Materials.tobias_characterSG_mat0"] = Input {
					SourceOp = "TobiasTex2D",
					Source = "MaterialOutput",
					CustomData = {
						MtlSlotIndex = 0
					},
				},
				["MtlStdInputs.ReceivesLighting"] = Input { Value = 0, },
				["MtlStdInputs.ReceivesShadows"] = Input { Value = 0, },
				["MtlStdInputs.MaterialID"] = Input { Value = 4, },
				MultiMaterial = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { -605, 181.5 } },
		},
		pixel_436 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_131",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1485, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		TobiasRenderer3D = Renderer3D {
			NameSet = true,
			CustomData = {
				ToolVersion = 2
			},
			Inputs = {
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				Depth = Input { Value = 3, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				SceneInput = Input {
					SourceOp = "TobiasCameraMerge3D",
					Source = "Output",
				},
				CameraSelector = Input { Value = FuID { "TobiasCamera3D" }, },
				RendererType = Input { Value = FuID { "RendererOpenGL" }, },
				["RendererOpenGL.Channels.Z"] = Input { Value = 1, },
				["RendererOpenGL.Channels.Normal"] = Input { Value = 1, },
				["RendererOpenGL.Channels.TexCoord0"] = Input { Value = 1, },
				["RendererOpenGL.Channels.WorldCoord"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { -275, 115.5 } },
		},
		pixel_223 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_196",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 770, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_402 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_20",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1265, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_25 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_125",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1155, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_215_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_280_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 275, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_423 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_391",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1925, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_82_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_37_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1430, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		CowShiftTransform3D = Transform3D {
			NameSet = true,
			Inputs = {
				SceneInput = Input {
					SourceOp = "CowCameraMerge3D",
					Source = "Output",
				},
				["Transform3DOp.Translate.X"] = Input { Value = 3.55786877927001, },
				["Transform3DOp.Translate.Z"] = Input { Value = -3.08364485296873, },
				["Transform3DOp.Rotate.Y"] = Input { Value = 21.7, },
			},
			ViewInfo = OperatorInfo { Pos = { 55, -115.5 } },
		},
		pixel_198 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_237",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -825, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		CowTex2D = Texture2DOperator {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "Instance_LinearOCIOColorspace",
					Source = "Output",
				},
				WrapMode = Input { Value = FuID { "Wrap" }, },
				MaterialID = Input { Value = 2, },
			},
			ViewInfo = OperatorInfo { Pos = { -715, -115.5 } },
		},
		pixel_215 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_280",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -55, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_88 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_160",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -715, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_257 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_307",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1925, -1369.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_152_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_435_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1430, -1171.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_324 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_289",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -935, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_237 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_290",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -770, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_157 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_97",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 165, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_341 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_265",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -605, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_421 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_353",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -605, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_427 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_392",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 165, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_84 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_141",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -330, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_98 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_46",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1925, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		ReplaceNormals3D1 = ReplaceNormals3D {
			Inputs = {
				SceneInput = Input {
					SourceOp = "CowMesh3D",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -495, -115.5 } },
		},
		pixel_69 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_127",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1870, -1204.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_391_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_320_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1595, -1303.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_200 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_242",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 660, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_367 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_314",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1595, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_214_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_277_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1430, -1402.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_415 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_2",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -275, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_265_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_192_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1265, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		BarnMesh3D = SurfaceFBXMesh {
			NameSet = true,
			CustomData = {
				NumMtlSlots = 1
			},
			Inputs = {
				["Transform3DOp.Scale.X"] = Input { Value = 10, },
				ImportFile = Input { Value = "Comp:/Media/BarnObj/barn.obj", },
				ObjName = Input { Value = "default", },
				TransformToWorld = Input { Value = 0, },
				EnableAxisConversion = Input { Value = 1, },
				EnableUnitConversion = Input { Value = 1, },
				["ObjectID.ObjectID"] = Input { Value = 1, },
				["Materials.Barn_Material_mat0"] = Input {
					SourceOp = "BarnTex2D",
					Source = "MaterialOutput",
					CustomData = {
						MtlSlotIndex = 0
					},
				},
				["MtlStdInputs.MaterialID"] = Input { Value = 1, },
				MultiMaterial = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { -605, -478.5 } },
		},
		pixel_24 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_398",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1705, -1237.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_311 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_281",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 55, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_7 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_388",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -935, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_125 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_21",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1100, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_278 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_241",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1925, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		CowMesh3D = SurfaceFBXMesh {
			NameSet = true,
			CustomData = {
				NumMtlSlots = 1
			},
			Inputs = {
				["Transform3DOp.Translate.X"] = Input { Value = -4.80369595135364, },
				["Transform3DOp.Translate.Y"] = Input { Value = -5.502, },
				["Transform3DOp.Translate.Z"] = Input { Value = -10.2910958514818, },
				["Transform3DOp.Rotate.X"] = Input { Value = -90, },
				["Transform3DOp.Rotate.Y"] = Input { Value = 50.3, },
				["Transform3DOp.Scale.X"] = Input { Value = 2.8, },
				ImportFile = Input { Value = "Comp:/Media/CowOBJ/cow.obj", },
				ObjName = Input { Value = "Mesh", },
				TransformToWorld = Input { Value = 0, },
				EnableAxisConversion = Input { Value = 1, },
				EnableUnitConversion = Input { Value = 1, },
				["Lighting.Nest"] = Input { Value = 1, },
				["Lighting.IsAffectedByLights"] = Input { Value = 0, },
				["ObjectID.ObjectID"] = Input { Value = 1, },
				["Materials.mesh_Material_u1_v1_mat0"] = Input {
					SourceOp = "CowTex2D",
					Source = "MaterialOutput",
					CustomData = {
						MtlSlotIndex = 0
					},
				},
				["MtlStdInputs.ReceivesLighting"] = Input { Value = 0, },
				["MtlStdInputs.ReceivesShadows"] = Input { Value = 0, },
				["MtlStdInputs.MaterialID"] = Input { Value = 1, },
				MultiMaterial = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { -605, -115.5 } },
		},
		BarnCameraMerge3D = Merge3D {
			NameSet = true,
			Inputs = {
				SceneInput1 = Input {
					SourceOp = "BarnCamera3D",
					Source = "Output",
				},
				SceneInput2 = Input {
					SourceOp = "BarnTransform3D",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -275, -478.5 } },
		},
		pixel_183 = PipeRouter {
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { -1705, -1402.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_388 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_324",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -935, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_423_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_391_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1595, -1270.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_176 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_254",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1760, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_430 = PipeRouter {
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { -55, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_37_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_413_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1430, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_367",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1595, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		CowTransform3D = Transform3D {
			NameSet = true,
			Inputs = {
				SceneInput = Input {
					SourceOp = "ReplaceNormals3D1",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -385, -115.5 } },
		},
		CowgrammetryMerge3D = Merge3D {
			NameSet = true,
			Inputs = {
				SceneInput1 = Input {
					SourceOp = "TobiasMerge3D",
					Source = "Output",
				},
				SceneInput2 = Input {
					SourceOp = "CowgrammetryCamera3D",
					Source = "Output",
				},
				SceneInput3 = Input {
					SourceOp = "CowgrammetrySphericalCamera",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { 385, 181.5 } },
		},
		pixel_392_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_310_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 495, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_180 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_259",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1265, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_102 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_45",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1595, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_115 = PipeRouter {
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { 1650, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_55 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_81",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -55, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_37 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_413",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -440, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_285 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_240",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -440, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_359_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_12_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 275, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_96 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_48",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 605, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_156 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_89",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1210, -1171.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		TobiasCamera3D = Camera3D {
			NameSet = true,
			Inputs = {
				["Transform3DOp.Translate.X"] = Input { Value = 42.0627251013494, },
				["Transform3DOp.Translate.Y"] = Input { Value = 15.2984731784159, },
				["Transform3DOp.Translate.Z"] = Input { Value = 27.4050520806224, },
				["Transform3DOp.Rotate.X"] = Input { Value = -3.63903797743842, },
				["Transform3DOp.Rotate.Y"] = Input { Value = 56.6841215784661, },
				["Transform3DOp.Rotate.Z"] = Input { Value = 0.0896385055966675, },
				FLength = Input { Value = 14.3404285604962, },
				["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
				FilmGate = Input { Value = FuID { "BMD_URSA_4K_16x9" }, },
				ApertureW = Input { Value = 0.831496062992126, },
				ApertureH = Input { Value = 0.467716535433071, },
				["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 2, },
				["MtlStdInputs.MaterialID"] = Input { Value = 3, },
			},
			ViewInfo = OperatorInfo { Pos = { -275, 247.5 } },
		},
		pixel_242 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_223",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 715, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_160 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_429",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -770, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_98_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_46_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1595, -1204.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		OutputNote = Note {
			NameSet = true,
			Inputs = {
				Comments = Input { Value = "This is the linear workflow 16-bit half float output from the comp. DWAA compression is enabled. The RGBA, Z-Depth, UV Pass, Normals, and World Space Position channels are enabled for the render.", }
			},
			ViewInfo = StickyNoteInfo {
				Pos = { 605, 115.5 },
				Flags = {
					Expanded = true
				},
				Size = { 823.693, 134.796 }
			},
		},
		pixel_246 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_205",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1100, -1402.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		BarnTransform3D = Transform3D {
			NameSet = true,
			Inputs = {
				SceneInput = Input {
					SourceOp = "BarnReplaceNormals3D",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -385, -478.5 } },
		},
		pixel_356 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_353",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -550, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		Instance_LinearOCIOColorspace = OCIOColorSpace {
			NameSet = true,
			SourceOp = "LinearOCIOColorspace",
			Inputs = {
				Input = Input {
					SourceOp = "Loader1_1",
					Source = "Output",
				},
				StartEndRenderScripts = Input { },
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { -825, -115.5 } },
		},
		pixel_192 = PipeRouter {
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { -605, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		TobiasCameraMerge3D = Merge3D {
			NameSet = true,
			Inputs = {
				SceneInput1 = Input {
					SourceOp = "TobiasCamera3D",
					Source = "Output",
				},
				SceneInput2 = Input {
					SourceOp = "TobiasTransform3D",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -275, 181.5 } },
		},
		pixel_160_2 = PipeRouter {
			CtrlWZoom = false,
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { -1925, 940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_56 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_421",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -605, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_413_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_356_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1375, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		CowRenderer3D = Renderer3D {
			NameSet = true,
			CustomData = {
				ToolVersion = 2
			},
			Inputs = {
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				Depth = Input { Value = 3, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				SceneInput = Input {
					SourceOp = "CowCameraMerge3D",
					Source = "Output",
				},
				CameraSelector = Input { Value = FuID { "CowCamera3D" }, },
				RendererType = Input { Value = FuID { "RendererOpenGL" }, },
				["RendererOpenGL.Channels.Z"] = Input { Value = 1, },
				["RendererOpenGL.Channels.Normal"] = Input { Value = 1, },
				["RendererOpenGL.Channels.TexCoord0"] = Input { Value = 1, },
				["RendererOpenGL.Channels.WorldCoord"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { -275, -181.5 } },
		},
		TobiasReplaceNormals3D = ReplaceNormals3D {
			NameSet = true,
			Inputs = {
				SceneInput = Input {
					SourceOp = "TobiasMesh3D",
					Source = "Output",
				},
			},
			ViewInfo = OperatorInfo { Pos = { -495, 181.5 } },
		},
		pixel_241 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_211",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1870, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_351 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_306",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1705, -1303.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_253 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_217",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 165, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_217_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_282_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 495, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_26 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_69",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1925, -1237.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_421_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_353_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1265, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_12 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_55",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -55, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_320_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_278_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1595, -1336.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_345 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_403",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1925, -1303.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_214 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_277",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1760, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_97 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_50",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 165, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_135 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_87",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -880, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_277_1 = PipeRouter {
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { -1375, -1369.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_42 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_7",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -935, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_76_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_56_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1265, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_401 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_349",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1045, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_43 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_73",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1375, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_383 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_366",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 715, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_430_1 = PipeRouter {
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { 275, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_152 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_435",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1760, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_142 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_85",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -165, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		BarnCamera3D = Camera3D {
			NameSet = true,
			Inputs = {
				["Transform3DOp.Translate.X"] = Input { Value = -24.1961719259526, },
				["Transform3DOp.Translate.Y"] = Input { Value = 14.6938505762865, },
				["Transform3DOp.Translate.Z"] = Input { Value = 29.3416523842311, },
				["Transform3DOp.Rotate.Y"] = Input { Value = -43.5649373899214, },
				FLength = Input { Value = 14.3404285604962, },
				["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
				FilmGate = Input { Value = FuID { "BMD_URSA_4K_16x9" }, },
				ApertureW = Input { Value = 0.831496062992126, },
				ApertureH = Input { Value = 0.467716535433071, },
				["SurfacePlaneInputs.ObjectID.ObjectID"] = Input { Value = 2, },
				["MtlStdInputs.MaterialID"] = Input { Value = 3, },
			},
			ViewInfo = OperatorInfo { Pos = { -275, -412.5 } },
		},
		pixel_354 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_316",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -495, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_305 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_350",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1265, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_390 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_331",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1045, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_127 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_70",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1815, -1171.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_427_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_392_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 495, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_208 = PipeRouter {
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { 935, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_66 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_115",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1650, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		VCSNote_1 = Note {
			NameSet = true,
			Inputs = {
				Comments = Input { Value = "This is Lima (Lee ma) the cow. She was captured by VolumetricCameraSystems live-action portable videogrammetry scanning system on Aug 2018. You can get 30 FPS mesh sequences and point clouds from the VCS \"Multi Planar Grid Array\" and \"Planar Dome Grid Array\" Volumetric Camera Rigs.\n\n3D Model License Terms:\nAttribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)\n\nFor more information:\nhttp://www.VolumetricCameraSystems.com\n(Volumetric Camera Hardware) by Tobias Chen <me@TobiasChen.com>\n(Volumetric Software Pipeline) by Andrew Hazelden <andrew@AndrewHazelden.com>", }
			},
			ViewInfo = StickyNoteInfo {
				Pos = { -1925, -247.5 },
				Flags = {
					Expanded = true
				},
				Size = { 935.154, 262.158 }
			},
		},
		BarnRenderer3D = Renderer3D {
			NameSet = true,
			CustomData = {
				ToolVersion = 2
			},
			Inputs = {
				Width = Input { Value = 1920, },
				Height = Input { Value = 1080, },
				Depth = Input { Value = 3, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				SceneInput = Input {
					SourceOp = "BarnCameraMerge3D",
					Source = "Output",
				},
				CameraSelector = Input { Value = FuID { "BarnCamera3D" }, },
				RendererType = Input { Value = FuID { "RendererOpenGL" }, },
				["RendererOpenGL.Channels.Z"] = Input { Value = 1, },
				["RendererOpenGL.Channels.Normal"] = Input { Value = 1, },
				["RendererOpenGL.Channels.TexCoord0"] = Input { Value = 1, },
				["RendererOpenGL.Channels.WorldCoord"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { -275, -544.5 } },
		},
		pixel_55_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_81_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 275, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_131 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_102",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1540, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		CowgrammetrySphericalCamera = SphericalCamera3D {
			NameSet = true,
			Inputs = {
				["Transform3DOp.Translate.X"] = Input { Value = -1.57263495561975, },
				["Transform3DOp.Translate.Y"] = Input { Value = 13.7535223340511, },
				["Transform3DOp.Translate.Z"] = Input { Value = 12.2510472438366, },
				["Transform3DOp.Rotate.Y"] = Input { Value = -50.4709332985803, },
				["Stereo.Mode"] = Input { Value = FuID { "Mono" }, },
			},
			ViewInfo = OperatorInfo { Pos = { 385, 82.5 } },
		},
		pixel_45 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1595, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_314 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_275",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1595, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_347 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_396",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1705, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_379 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_315",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -165, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_258 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_181",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1045, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_278_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_241_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1595, -1369.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_290 = PipeRouter {
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { -715, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_87 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_42",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -935, -874.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_265 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_192",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -605, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_216 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_245",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1045, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_240 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_185",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -495, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_47 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_88",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -715, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_185_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_192_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1320, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_282_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_311_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 440, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		VCSNote_2 = Note {
			NameSet = true,
			Inputs = {
				Comments = Input { Value = "This is Digital Tobias. He was captured by VolumetricCameraSystems live-action portable videogrammetry scanning system. You can get 30 FPS mesh sequences and point clouds from the VCS \"Multi Planar Grid Array\" and \"Planar Dome Grid Array\" Volumetric Camera Rigs.\n\n3D Model License Terms:\nAttribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)\n\nFor more information:\nhttp://www.VolumetricCameraSystems.com\n(Volumetric Camera Hardware) by Tobias Chen <me@TobiasChen.com>\n(Volumetric Software Pipeline) by Andrew Hazelden <andrew@AndrewHazelden.com>", }
			},
			ViewInfo = StickyNoteInfo {
				Pos = { -1925, 49.5 },
				Flags = {
					Expanded = true
				},
				Size = { 925.719, 491.249 }
			},
		},
		pixel_196 = PipeRouter {
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { 825, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_259 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_305",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1265, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_51 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_14",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1045, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_333 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_296",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 605, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_366 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_364",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 660, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_211 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_214",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1815, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_129 = PipeRouter {
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { -1430, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_311_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_281_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 385, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_93_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_152_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1375, -1204.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_210 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_200",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 605, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_327 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_375",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1375, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_230 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_268",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -275, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		PipeRouter2 = PipeRouter {
			Inputs = {
				Input = Input {
					SourceOp = "CowgrammetryMerge3D",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 495, 181.5 } },
		},
		Instance_LinearOCIOColorspace_1 = OCIOColorSpace {
			NameSet = true,
			SourceOp = "LinearOCIOColorspace",
			Inputs = {
				Input = Input {
					SourceOp = "Loader2",
					Source = "Output",
				},
				StartEndRenderScripts = Input { },
				EffectMask = Input { }
			},
			ViewInfo = OperatorInfo { Pos = { -825, 181.5 } },
		},
		pixel_155 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_132",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 825, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_310 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_253",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 165, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_341_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_265_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1265, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_315 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_269",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -165, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_225 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_230",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -220, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_132 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_433",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 770, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_398 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_351",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1705, -1270.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_281_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_215_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 330, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_285_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_240_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1430, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_322_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_359_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 275, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_280 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_322",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -55, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_281 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_215",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 0, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_217 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_282",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 165, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_244 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_198",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -880, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_255 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_298",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1540, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_271 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_216",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1045, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_117 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_156",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1155, -1171.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_435_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_150_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1485, -1171.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_150_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_98_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1540, -1171.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_153 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_167",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 660, -841.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_364 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_333",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 605, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_307 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_345",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1925, -1336.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_420 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_416",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1155, -1270.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_422 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_420",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1210, -1270.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_280_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_322_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 275, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_41 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_84",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -330, -907.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_296 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_210",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 605, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_360 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_422",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1265, -1303.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_277 = PipeRouter {
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { -1705, -1039.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_260 = PipeRouter {
			NameSet = true,
			ViewInfo = PipeRouterInfo { Pos = { -1705, -1369.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_205 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_204",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1155, -1402.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_317 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_360",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1265, -1336.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_185 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_192",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -550, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_241_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_211_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1540, -1402.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_187 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_188",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1540, -1072.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_316 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_285",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -440, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_316_1 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_285_1",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { 1430, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		VCSNote = Note {
			NameSet = true,
			Inputs = {
				Comments = Input { Value = "This is a scan of a old barn at a family run hobby farm located 30 minutes outside of Burnaby, B.C. Canada. This barn is home to Lima (Lee ma) the cow. The barn was captured by Volumetric Camera Systems using a Leica LIDAR Scanner on Aug 2018.\n\n3D Model License Terms:\nAttribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0)\n\nFor more information:\nhttp://www.VolumetricCameraSystems.com\n(Volumetric Camera Hardware) by Tobias Chen <me@TobiasChen.com>\n(Volumetric Software Pipeline) by Andrew Hazelden <andrew@AndrewHazelden.com>", }
			},
			ViewInfo = StickyNoteInfo {
				Pos = { -1925, -742.5 },
				Flags = {
					Expanded = true
				},
				Size = { 927.985, 426.932 }
			},
		},
		TobiasTex2D = Texture2DOperator {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "Instance_LinearOCIOColorspace_1",
					Source = "Output",
				},
				WrapMode = Input { Value = FuID { "Wrap" }, },
				MaterialID = Input { Value = 2, },
			},
			ViewInfo = OperatorInfo { Pos = { -715, 181.5 } },
		},
		pixel_412 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_10",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -770, -940.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_306 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_260",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1705, -1336.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		Saver1 = Saver {
			Inputs = {
				ProcessWhenBlendIs00 = Input { Value = 0, },
				Clip = Input {
					Value = Clip {
						Filename = "Previews:/VCS/Spherical-Cowgrammetry-Fusion.0000.exr",
						FormatID = "OpenEXRFormat",
						Length = 0,
						Saving = true,
						TrimIn = 0,
						ExtendFirst = 0,
						ExtendLast = 0,
						Loop = 1,
						AspectMode = 0,
						Depth = 0,
						TimeCode = 0,
						GlobalStart = -2000000000,
						GlobalEnd = 0
					},
				},
				CreateDir = Input { Value = 1, },
				OutputFormat = Input { Value = FuID { "OpenEXRFormat" }, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				Input = Input {
					SourceOp = "SphericalCowgrammetryRenderer3D",
					Source = "Output",
				},
				["OpenEXRFormat.Depth"] = Input { Value = 1, },
				["OpenEXRFormat.Compression"] = Input { Value = 8, },
				["OpenEXRFormat.Channels"] = Input { Value = 1, },
			},
			ViewInfo = OperatorInfo { Pos = { 825, 82.5 } },
		},
		pixel_320 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_278",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1925, -1006.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		},
		pixel_391 = PipeRouter {
			NameSet = true,
			Inputs = {
				Input = Input {
					SourceOp = "pixel_320",
					Source = "Output",
				},
			},
			ViewInfo = PipeRouterInfo { Pos = { -1925, -973.5 } },
			Colors = {
				TileColor = { R = 0.423529411764706, G = 0.423529411764706, B = 0.423529411764706 },
				TextColor = { R = 0.984313725490196, G = 1, B = 1 },
			}
		}
	},
	Views = {
		{
			FrameTypeID = "ChildFrame",
			Mode = 3,
			LayoutPreset = 0,
			Left = 0,
			Top = 27,
			Width = 1680,
			Height = 872,
			Views = ordered() {
				Main = MultiView {
					Active = "Flow",
					ViewList = ordered() {
						Flow = "FlowView",
						Timeline = "TimelineView",
						Spline = "SplineEditorView",
						Info = "InfoView",
						Chat = "ChatView"
					},
					Flow = FlowView {
						Flags = {
							Navigator = true,
							AutoHideNavigator = true,
							AutoSnap = true
						},
						NavigatorSize = { 200, 140 },
						Direction = "Horizontal",
						PipeStyle = "Direct",
						Scale = 0.249688,
						Offset = { 2351.12, 1555.15 }
					},
					Timeline = TimelineView {
						TreeControlState = {
						},
						DisplayMode = "All Tools",
						ShowCurrentTimeTools = false,
						Filter = "Show All",
						ShowSelectedTools = false,
						ShowAnimatedToolsOnly = false,
						ShowEditBoxes = false,
						KeyFrameView = {
							Position = { Left = 150, Bottom = 343 },
							ScaleX = 2.14424951267057,
							OffsetX = -51.4619883040936,
							OffsetY = 0,
							AutoScaling = "scroll",
							AutoSnapTo = "frame",
							AutoSnapToGuidelines = false,
							GuidelinesGrabEnabled = true,
							GuidelinesSnapTo = "frame"
						},
						Spreadsheet = { LeftPos = 150, Visible = false }
					},
					Spline = SplineEditorView {
						LeftPos = 256,
						ScaleX = 0.2,
						ScaleY = 0.00338983050847458,
						OffsetX = -3.8,
						OffsetY = 0,
						AutoScaling = "scroll",
						AutoSnapTo = "frame",
						AutoSnapToGuidelines = false,
						GuidelinesSnapTo = "frame",
						ShowKeyMarkers = false,
						IndependentHandles = false,
						ShowNonSplineModifiers = false,
						GuidelinesGrabEnabled = true,
						ShowOneToolOnly = false,
						ShowSelectedTools = false,
						ShowAllInputs = false,
						Filter = "Show All"
					},
				},
				Controls = MultiView {
					Active = "Tools",
					ViewList = ordered() {
						Tools = "ControlView",
						Modifiers = "ModifierView"
					},
				},
				Left = "PreviewContainer",
				Right = "PreviewContainer",
				Transport = "TransportView",
				Time = "TimeView",
				ConsoleView = "ConsoleView"
			},
			Layout = {
				Columns = 2,
				RatioX = 1,
				RatioY = 1,
				{
					Rows = 3,
					RatioX = 0.785671641791045,
					RatioY = 1,
					{
						Columns = 2,
						RatioX = 1,
						RatioY = 0.386127167630058,
						{ ID = "Left", RatioX = 0.5003808073115, RatioY = 101.667664670659, Pop = true },
						{ ID = "Right", RatioX = 0.4996191926885, Pop = true },
						Pop = true
					},
					{ ID = "Main", RatioY = 0.546820809248555, Pop = true },
					{ ID = "Time", SnapY = 56, Flat = true }
				},
				{
					Rows = 2,
					PixelX = 357,
					{
						Rows = 2,
						RatioX = 1,
						RatioY = 1,
						{ ID = "Controls", RatioX = 1, RatioY = 0.77073732718894, Pop = true },
						{ ID = "ConsoleView", RatioY = 0.22926267281106, Pop = true }
					},
					{ ID = "Transport", FixedY = -2 }
				}
			}
		}
	},
	Prefs = {
		Comp = {
			Views = {
				Right = {
					Viewer = {
						EnableLUTs = true,
						LUTPlugin = "Fuse.rec709_VSFuse",
						ScaleMode = 1,
						LUTSelected = "rec709"
					},
					ViewLUT = {
						{
							Tools = ordered() {
								rec7093 = ViewOperator {
									NameSet = true,
									CtrlWZoom = false
								}
							},
							ID = "Fuse.rec709_VSFuse"
						},
						Recent = {
							SelectedPlugin = "Fuse.rec709_VSFuse",
							FusionViewLUT = {
								Tools = ordered() {
									FusionViewLUT = ViewLUTOp {
										NameSet = true,
										Inputs = {
										}
									}
								}
							},
							SelectedName = "rec709"
						},
						SelectedName = "rec709",
						SelectedPlugin = "Fuse.rec709_VSFuse"
					},
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							FitMarginY = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							NearZ = 0
						}
					},
					BufferLUT = {
						Plugin = "Fuse.rec709_VSFuse",
						Selected = "rec709",
					},
					View3D = {
						CamFront = {
							Rotation = {
								Y = 0,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamLeft = {
							Rotation = {
								Y = 90,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamPersp = {
							Rotation = {
								Y = 16.4000034332275,
								X = 14.8000020980835,
								Z = 0
							},
							Scale = 0.0390152297914028,
							Position = {
								Y = -2.02569651603699,
								X = -23.1823577880859,
								Z = 5.12836503982544
							}
						},
						CamRight = {
							Rotation = {
								Y = -90,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamTop = {
							Rotation = {
								Y = 0,
								X = 90,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						}
					},
				},
				Left = {
					Viewer = {
						EnableLUTs = true,
						LUTPlugin = "Fuse.rec709_VSFuse",
						ScaleMode = 1,
						LUTSelected = "rec709"
					},
					MaterialViewer = {
						Camera = {
							Rotation = {
								Y = -20,
								X = 15,
								Z = 0
							}
						}
					},
					ViewLUT = {
						{
							Tools = ordered() {
								rec7092 = ViewOperator {
									NameSet = true
								}
							},
							ID = "Fuse.rec709_VSFuse"
						},
						SelectedPlugin = "Fuse.rec709_VSFuse",
						SelectedName = "rec709",
						Recent = {
							SelectedPlugin = "Fuse.rec709_VSFuse",
							FusionViewLUT = {
								Tools = ordered() {
									FusionViewLUT = ViewLUTOp {
										NameSet = true,
										Inputs = {
										}
									}
								}
							},
							SelectedName = "rec709"
						}
					},
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							FitMarginY = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							NearZ = 0
						}
					},
					BufferLUT = {
						Plugin = "Fuse.rec709_VSFuse",
						Selected = "rec709",
					},
					View3D = {
						CamLeft = {
							Rotation = {
								Y = 90,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						Options = {
							Lighting = false,
							Shadows = false
						},
						SortMethod = "ZBuffer",
						CamRight = {
							Rotation = {
								Y = -90,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamPersp = {
							Rotation = {
								Y = 48.799991607666,
								X = 10.8000020980835,
								Z = 0
							},
							Scale = 0.0463825948536396,
							Position = {
								Y = -4.99560928344727,
								X = 1.28033971786499,
								Z = 5.84276056289673
							}
						},
						CamTop = {
							Rotation = {
								Y = 0,
								X = 90,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						},
						CamFront = {
							Rotation = {
								Y = 0,
								X = 0,
								Z = 0
							},
							Scale = 1,
							Position = {
								Y = 0,
								X = 0,
								Z = 0
							}
						}
					},
				},
				View1 = {
					PrevCtrlInactiveColor = 0,
					FullScreen = false,
					PickH = 1,
					SideB = {
						PrevCtrlInactiveColor = 4278255360,
						PickW = 1,
						PickH = 1,
						PrevCtrlActiveColor = 4278190335,
						Viewer = {
							EnableLUTs = false,
							LUTPlugin = "FusionViewLUT",
							FitMarginY = 0,
							FitMarginX = 0,
							FitMarginType = 0,
							FarZ = -1000,
							NearZ = 0
						}
					},
					PrevCtrlActiveColor = 0,
					AlwaysOnTop = true,
					PickW = 1
				},
			},
			FrameFormat = {
				GuideRatio = 1.77777777777778,
			},
			LastFile = "/Users/andrew/Desktop/Volumemtric-Camera-Systems-Cowgrammetry-Fusion/Comps/VolumemtricCameraSystems-Cowgrammetry/Media/CowOBJ/cow.jpg",
			Tweaks = {
				OpenCL = {
					Enable = 0,
					Caching = 0
				}
			},
			Paths = {
				EnableReverseMapping = true,
			},
			FlowView = {
				RemoveRouters = false
			},
			QuickTime = {
			},
		}
	}
}

 